- changelog/fixed-rv32-reset-halt-timout.md
- probe-rs/src/architecture/riscv/mod.rs
Timeout in reset-and-halt is necessary for some MCUs(in my case: CH32V003).
- Add the missing timeout handling
- The original logic is not changed, so this won't break any old targets.
- The default timeout value is set to 500ms(in `fn reset`), which is enough for almost all targets
> Add missing reset-and-halt timeout for rv32

- changelog/added-support-for-CH32V003.md
- probe-rs/targets/CH32V0_Series.yaml
Add support(flash algorithm) for [CH32V003](https://www.wch-ic.com/products/CH32V003.html).
It's an RV32EC target.
`riscv32ec-unknown-none-elf` is not supported by official Rust yet.
ch32-rs has a patched version of Rust with rv32ec support: https://github.com/ch32-rs/rust
- Require #1874 to be merged. CH32V003 needs additional idle wait after a reset req.
- Require #1875 to be merged. CH32V003 needs additional idle wait after a resume req. (`resumeack` is reported, but hart is still not available)
Repo for the flash algorithm: https://github.com/ch32-rs/flash-algorithms/tree/main/ch32v003
> Add support for CH32V003

- changelog/added-riscv-semihostring.md
- probe-rs/src/architecture/arm/core/cortex_m.rs
- probe-rs/src/architecture/riscv/mod.rs
- probe-rs/src/architecture/riscv/registers.rs
- probe-rs/src/rtt.rs
- probe-rs/src/rtt/syscall.rs
I've implemented SYS_EXIT semihosting support for riscv, similar on how its done for the cortex-m.
Works with a simple test program on my esp32c6:
```
riscv32-esp-elf-objdump  -d target/riscv32imac-unknown-none-elf/debug/riscv_semihosting_example --section=.text | grep ebreak -C1
42001150:	01f01013          	slli	zero,zero,0x1f
42001154:	00100073          	ebreak
42001158:	40705013          	srai	zero,zero,0x7
```
```
probe-rs run --chip esp32c6 --format idf target/riscv32imac-unknown-none-elf/debug/riscv_semihosting_example
```
Please advise on:
* the todo regarding renabling breakpoints:  https://github.com/probe-rs/probe-rs/compare/master...t-moe:probe-rs:features/riscv_semihosting?expand=1#diff-30133d43f1cf396fea0c96eaf00b38660fa961edf89b716da104dc0288c4ae36R327
> Add semihosting sys_exit support to riscv

- probe-rs/src/debug/debug_info.rs
- probe-rs/src/debug/debug_step.rs
- probe-rs/src/debug/function_die.rs
- probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__print_stacktrace.snap
- probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__unwinding_in_exception_handler.snap
- probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__unwinding_in_exception_trampoline.snap
- probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__unwinding_inlined.snap
- probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__unwinding_inlined_debug.snap
- probe-rs/src/debug/stack_frame.rs
- probe-rs/src/debug/unit_info.rs
- Print stack frame in unwind tests
- Don't use memory access to get function information
> debugger: Refactor function lookup

- changelog/fixed-mark-arm-memory-requests-cacheable.md
- probe-rs/src/architecture/arm/ap/memory_ap/mod.rs
- probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs
Fixes #1517
Patch is from that issue, thanks to @bcantrill.
> Mark all ARM memory accesses as cacheable

- changelog/changed-vector-catch-output.md
- probe-rs/src/bin/probe-rs/cmd/run.rs
On RISCV you get a confusing message which might make users think it's not working, when in reality it is. This hides the vector catch error in that case.
> [run]: don't output the vector catch error if it hasn't been implemented

- changelog/fixed-stm32g4-target-yaml.md
- probe-rs/targets/STM32G4_Series.yaml
This yaml file was generated using target-gen on version 1.5.0 of https://www.keil.arm.com/packs/stm32g4xx_dfp-keil/versions/
This change fixes the stm32g4xx_256 flash algorithm, which was broken in the previous checked-in version.
Thanks to adamgreig, dirbaio, and James Munns for some very timely help in the Matrix chat to get this figured out!
> Update the STM32G4 target yaml to latest release.

- changelog/fixed-esp32c3-memory-map.md
- probe-rs/targets/esp32c3.yaml
Update from DM discussion:
The Flash range in this PR represents max addressable space, and not necessarily physical flash memory available, since the latter is external to the chip. This is deemed OK, since the flash loader will error if we try and flash (write) past the size of the fitted flash, and reads will return 0's beyond the physically available flash memory.
> Fix the address mapping for esp32c3 RAM regions

- changelog/fixed-vscode-error-response.md
- probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/protocol.rs
- probe-rs/src/bin/probe-rs/cmd/dap_server/server/debugger.rs
The error response had the wrong type, and was ignored by vscode. The additional show_message call before the
error response is removed, because that led to duplicate message popups.
Calls to `show_message` and `log_to_console` are also removed from the `send_event` function, to prevent endless recursion.
> dap-adapter: Fix type for error response

- Cargo.lock
- changelog/added-reset-flag-to-rtthost.md
- rtthost/Cargo.toml
- rtthost/src/main.rs
I've needed a simple RTT logger of an (non-rust) application, which just prints the RTT log into stdout. rtthost is perfect for that, but sadly I can't connect to the target and reset it afterwards as the probe is in use. 
I've added a simple `--reset` flag similar to `--reset` flags of `cargo-flash` etc.
Additionally, I've moved `rtthost` to use anyhow instead of exit codes.
> rtthost: Add reset flag

- changelog/changed-stack-refresh-on-halt.md
- probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
- probe-rs/src/bin/probe-rs/cmd/dap_server/server/session_data.rs
Hi,
Currently if a DAP client sends multiple `stackTrace` requests per suspend state, (in my case [nvim-dap](https://github.com/mfussenegger/nvim-dap)), the stack trace is refreshed for every request.
This results in the variable references also being refreshed; for `nvim-dap` this means it is unable to do anything with local variables. 
From my reading these references should stay valid for the entire suspend state:
https://pub.dev/documentation/dap/latest/dap/SetVariableResponseBody/variablesReference.html
This PR moves the stack refresh functionality to `poll_cores`, and triggers a refresh when the state changes from 'running' to 'halted'.
I have tested with both `nvim-dap` and `vscode` and had no issues.
Thanks :)
> dap-adapter: Refresh stack trace when core halts, instead of on StackTrace request.

- changelog/changed-config-done-threads.md
- probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
This should have been submitted with #1902, apologies.
Currently if the core stops before configuraiton is complete, a `stopped` event is not generated until a `threads` request is sent. 
In my use case (again using `nvim-dap`), a `threads` request is only sent after seeing a `stopped` event; thus the DAP client hangs.
This PR moves the initial check of the core state (and thus the generation of a `stopped` event), to the `configuration_done` request handler.
This means `threads` requests received before the `configuration_done` request will be sent an error response; imo that is a valid response, but happy to hear your thoughts and implement a different response if required.
> dap-adapter: Move initial core state check from threads request to configuration_done 

- changelog/added-cli-flags-for-vector-catch.md
- probe-rs/src/bin/probe-rs/cmd/run.rs
- probe-rs/src/core/core_state.rs
I have an interesting boot process where the chip (arm) bootloader will reset at least once during the process; having the vector catch enabled during this process will cause `probe-rs run` to halt and stop the boot process. 
We make this a negative flag, i.e `--no-vector-catch`.
> Add `--catch-reset` & `--catch-hardfault` flags

- changelog/changed-scan-memory-behavior.md
- probe-rs/src/bin/probe-rs/cmd/run.rs
This changes the default of scanning to not scanning. This should hopefully not impact many users since most tools define a `_SEGGER_RTT` symbol in the ELF, in which case only that particular address is checked.
Fixes #1865
> Gate scanning memory for RTT control block behind a flag

- changelog/changed-refactor-espusbjtag.md
- probe-rs/src/probe/espusbjtag/mod.rs
- probe-rs/src/probe/espusbjtag/protocol.rs
This is an exploratory refactor in esp-usbjtag, clarifying some details I found hard to read, as well as correcting percieved inaccuracies.
cc @MabezDev as you made some of the modifications previously that this PR undoes (specifically to `OUT_BUFFER_SIZE`).
> Refactor esp-usbjtag

- changelog/fixed-espusbjtag-reset-levels.md
- probe-rs/src/probe/espusbjtag/mod.rs
According to the ESP32-S3 technical reference manual, SRST is high-active. This PR will
- trigger a JTAG reset when asserting reset (instead of while deasserting)
- correct the SRST levels so deasserting now pulls the MCU out of reset instead of triggering it
> SRST is connected to the reset logic of the digital circuitry in the SoC and a high level on this line
will cause a digital system reset. Note that the USB Serial/JTAG Controller itself is not affected by SRST.
I'm not sure if attach under reset was used for ESP32-Cx devices or if it worked, but the current esp-usbjtag implementation doesn't seem to be correct in this regard.
> esp-usbjtag: correct reset assert/deassert levels

- changelog/changed-espusbjtag-avoid-por-on-attach.md
- probe-rs/src/probe/espusbjtag/mod.rs
There isn't currently a generic way to handle attach under reset, so in this case I'm changing the behavior of the espusbjtag driver to _not_ attach under reset by default.
> espusbjtag: don't reset the chip on attach

- changelog/changed-coredump-auto-calculate-memory.md
- probe-rs-target/src/memory.rs
- probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/repl_commands.rs
- probe-rs/src/bin/probe-rs/cmd/dap_server/server/core_data.rs
- probe-rs/src/core.rs
- probe-rs/src/debug/debug_info.rs
- probe-rs/src/debug/registers.rs
- probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__RP2040__full_unwind.snap
- probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__nRF52833_xxAA__full_unwind.snap
- probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__print_stacktrace.snap
- probe-rs/src/debug/unit_info.rs
- probe-rs/src/debug/variable.rs
- probe-rs/src/debug/variable_cache.rs
- As part of the journey to complete high quality unwind testing in the debugger (see #1916), this PR updates the debugger's REPL `dump` command, to auto calculate the memory ranges required in the `CoreDump`.  e.g.:
- Previously required something like `dump 0x20000000 0x4000 0x4cf0 0x1070 target/NRF52833_xxAA.coredump`
- Now the user can use `dump target/NRF52833_xxAA.coredump` to automatically dump all "in-scope" memory ranges, i.e. memory ranges required to reproduce the full stack unwind at the current target halt point (program counter).
- For the test case in `debug::debug_info::test::full_unwind::armv7_m_using_nrf52833_xxaa`, this reduced the coredump file from ~24Kb to ~10Kb. Note: The updated coredump for these tests are not included in this PR, because I wanted to isolate …
> debugger: REPL 'dump' command, auto calculate required memory ranges for `CoreDump`

- changelog/changed-espusbjtag-capture-less.md
- probe-rs/src/architecture/riscv/communication_interface.rs
- probe-rs/src/architecture/riscv/dtm.rs
- probe-rs/src/probe.rs
- probe-rs/src/probe/espusbjtag/mod.rs
- probe-rs/src/probe/espusbjtag/protocol.rs
- probe-rs/src/probe/ftdi/mod.rs
This PR implements a bunch of changes designed to transfer as few bits as possible. For one, a JTAG state machine should skip generating a few state transitions in some cases. Additionally, the batch command execution can now follow which results will definitely not be read, and the espusbjtag driver can now skip capturing data bits for those commands.
> JTAG command batching / espusbjtag: Transfer fewer bits

- changelog/changed-rp2040-flatten.md
- probe-rs/targets/RP2040.yaml
There is absolutely no issue writing from 0x2003FFFF to 0x20040000, so there's no need to arbitrarily divide up the memory and block the use of ELF regions that span across 'blocks'.
> Flatten the RP2040 memory map.

- changelog/changed-esp-target-update.md
- probe-rs/targets/esp32c2.yaml
- probe-rs/targets/esp32c3.yaml
- probe-rs/targets/esp32c6.yaml
- probe-rs/targets/esp32h2.yaml
Tune flashing algos to use faster block erase and increase the write page size for some gains.
[flash loader changes](https://github.com/esp-rs/esp-flash-loader/pull/7) and [flash size changes](https://github.com/esp-rs/esp-flash-loader/pull/10)
> Update esp targets

- Cargo.lock
- changelog/changed-log-to-file-opt-in.md
- probe-rs/Cargo.toml
- probe-rs/src/architecture/riscv/mod.rs
- probe-rs/src/bin/probe-rs/main.rs
This PR turns of file logging by default. It is slow, generates extreme amounts of data and apparently rarely used. Logging to file can now be enabled by two ways:
- by providing the `--log-file <some path>` switch
- or by setting `--log-to-folder` (name pending, feel free to suggest a better one!) in which case the logs are generated into the previously default folder.
If logging to file is used, probe-rs now uses [`tracing_appender::non_blocking`](https://docs.rs/tracing-appender/latest/tracing_appender/non_blocking/struct.NonBlocking.html) to avoid waiting on file IO if possible.
> Make logging to file opt-in

- changelog/fixed-single-buffer-transfer-speed.md
- probe-rs/src/flashing/flasher.rs
This change has a pretty sizeable effect (3-4KB/s -> 20+ KB/s) while flashing an ESP32-C6 with `--disable-double-buffering`
> Transfer words while single-buffer flashing

- .vscode/launch.json
- changelog/added-initial-xtensa-support.md
- probe-rs/examples/xtensa.rs
- probe-rs/src/architecture/mod.rs
- probe-rs/src/architecture/xtensa/arch/instruction/format.rs
- probe-rs/src/architecture/xtensa/arch/instruction/mod.rs
- probe-rs/src/architecture/xtensa/arch/mod.rs
- probe-rs/src/architecture/xtensa/communication_interface.rs
- probe-rs/src/architecture/xtensa/mod.rs
- probe-rs/src/architecture/xtensa/xdm.rs
- probe-rs/src/error.rs
- probe-rs/src/probe.rs
- probe-rs/src/probe/espusbjtag/mod.rs
- probe-rs/src/probe/ftdi/mod.rs
- probe-rs/src/probe/jlink/mod.rs
I'm opening this up early, to get initial feedback, but also to ensure that this PR and subsequent PRs are reviewable.
With much help from @bugadani, this PR implements the following:
* Support for communicating with the Xtensa Debug Module (Xdm)
* Support for powering up the xdm, and reading back the status
* Support for entering and exiting debug mode
* Support for halt & resume
* Support for random access memory reads, write is not yet implemented
* Adds `try_get_xtensa_interface` & `has_xtensa_interface` to probes, and implements it for espusbjtag
* Finally, an example which can be ran on the esp32s3 to read back a timestamp register. If you have an esp32s3 board, you can run it with `RUST_LOG="info" cargo run --example xtensa`
> Initial Xtensa support

- probe-rs/src/architecture/riscv/communication_interface.rs
- probe-rs/src/architecture/riscv/dtm.rs
- probe-rs/src/probe.rs
This PR:
- only saves the S0 and S1 registers if necessary, saving 2-4 unqueued operations
- results of JTAG command batches are now stored in the DTM struct instead of passed around by a reference. The results are "compacted" during each new execution to avoid leaking memory. This enables the following changes.
- changes read_dm_register_untyped to schedule its read and execute the queue. This means if a sequence ends with a DM register read, the read will still be part of the command queue.
- cleans up code based on the above change
> More JTAG batching changes

- changelog/fixed-flash-loader-not-loading-last-word.md
- probe-rs/src/flashing/flasher.rs
This isn't a bug... yet, but the miniz encoder introduced in #1947 does not pad it's output. Instead of requiring this for each future algorithm, I thought we might simply pad the last word right before download if we need to.
> Fill last word with empty bytes

- probe-rs/src/architecture/xtensa/xdm.rs
- probe-rs/src/probe.rs
The current interface is very slow as it doesn't use any batching. This probably won't change until we actually have something working, but this change at least does the register reads/writes in one step. I see a more than 2x speedup which is helpful even in this early stage.
> Xtensa: Batch up some transfers

- probe-rs/src/bin/probe-rs/cmd/dap_server/server/debugger.rs
- probe-rs/src/bin/probe-rs/cmd/download.rs
- probe-rs/src/bin/probe-rs/cmd/profile.rs
- probe-rs/src/bin/probe-rs/cmd/run.rs
- probe-rs/src/bin/probe-rs/util/flash.rs
- probe-rs/src/flashing/download.rs
This PR cleans up a bunch of duplicate flash data loading. Not everything - cargo-embed and libraries using `download_file_with_options` aren't affected because `FlashOptions` is internal to the probe-rs binary crate.
> Deduplicate FlashLoader data loading

- changelog/added-opentitan-target.md
- probe-rs/targets/OpenTitan.yaml
OpenTitan is an open source root of trust project. The discrete chip (Earl Grey) is now frozen and has a RISC-V debug module. 
This commit does not include a flash algorithm which will need writing from scratch.
The memory map addresses and sizes of the four memory regions can be found [this design doc](https://opentitan.org/book/hw/top_earlgrey/doc/design/index.html#memory-map) and [in the datasheet](https://opentitan.org/book/hw/top_earlgrey/doc/specification.html) respectively:
|                   memory | size    | start        |
|-------------------------:|---------|--------------|
|                      ROM | 32kiB   | `0x00008000` |
|                    Flash | 1024kiB | `0x20000000` |
|                Main SRAM | 128kiB  | `0x10000000` |
| Always-on retention SRAM | 4kiB    | …
> Add target file for OpenTitan Earl Grey

- probe-rs/src/architecture/xtensa/communication_interface.rs
- Make sure the core is halted when accessing memory. Trying to execute instructions while running means the instructions get ignored.
- Fix the bitfields of PS.
> Xtensa: fixes

- probe-rs-target/src/chip.rs
- probe-rs-target/src/flash_algorithm.rs
- probe-rs/src/flashing/flash_algorithm.rs
This PR removed `transfer_encoding: raw` from newly generated yamls
> Don't serialize the default transfer encoding

- changelog/changed-vendored-ftdi.md
- probe-rs/Cargo.toml
Previously enabling `ftdi-vendored` still did not include the ftdi probe driver, which honestly made no sense to me.
> Enable ftdi when using ftdi-vendored

- changelog/added-esp32s3-support.md
Somewhere along the line it started to make sense to advertise esp32-s3 support, but I forgot to do so :)
> ESP32-S3: Add missing changelog entry

- probe-rs/src/probe/espusbjtag/mod.rs
A proper BYPASS is IR = all 1. This doesn't currently cause problems because the S3 doesn't implement  the all-0 command, but with multicore RISC-V MCUs coming in this might turn into a problem.
> espusbjtag: send proper BYPASS bits

- changelog/added-specifying-a-chip-via-environment-variable.md
- probe-rs/Cargo.toml
- probe-rs/src/bin/probe-rs/util/common_options.rs
Pretty minor change, but this solves a problem for me when using in conjunction with `embedded-test` :)
Wasn't totally sure on the env var naming, considered `PROBERS_CHIP` as well, or maybe something else would be better. Regardless, happy to change it.
Also wasn't sure whether or not any other options would benefit from this, but I'm happy to add more if requested.
> Allow specifying a chip via environment variable

- changelog/fixed-jtag-measurement.md
- probe-rs/src/probe/cmsisdap/mod.rs
- probe-rs/src/probe/common.rs
- probe-rs/src/probe/espusbjtag/mod.rs
- probe-rs/src/probe/ftdi/mod.rs
This PR removes the custom IR length measurement from FTDI, and implements (as it turns out, CMSIS-DAP's) a new strategy to measure IR length: first, shift out ones, then a sequence of zeroes-then-ones, and find the common sequence.
> espusbjtag, ftdi: Fix JTAG IR measurement

- changelog/added-xtensa-info.md
- probe-rs/src/architecture/xtensa/communication_interface.rs
- probe-rs/src/architecture/xtensa/xdm.rs
- probe-rs/src/bin/probe-rs/cmd/info.rs
WIP, as automatic IR detection reports ambiguous on xtensa, i.e. the algorithm likely treats trailing ones incorrectly.
> Make probe-rs info work with Xtensa

- changelog/changed-debug-probe-traits.md
- changelog/removed-debugprobetype.md
- probe-rs/src/bin/probe-rs/cmd/dap_server/server/debugger.rs
- probe-rs/src/lib.rs
- probe-rs/src/probe.rs
- probe-rs/src/probe/arm_jtag.rs
- probe-rs/src/probe/cmsisdap/mod.rs
- probe-rs/src/probe/cmsisdap/tools.rs
- probe-rs/src/probe/espusbjtag/mod.rs
- probe-rs/src/probe/espusbjtag/protocol.rs
- probe-rs/src/probe/fake_probe.rs
- probe-rs/src/probe/ftdi/mod.rs
- probe-rs/src/probe/jlink/mod.rs
- probe-rs/src/probe/list.rs
- probe-rs/src/probe/stlink/mod.rs
- probe-rs/src/probe/stlink/tools.rs
- probe-rs/src/probe/stlink/usb_interface.rs
- probe-rs/src/probe/wlink/mod.rs
- probe-rs/src/probe/wlink/usb_interface.rs
This PR makes some slight cleanups in espusbjtag, and separates ProbeDriver from DebugProbe. This change allows reducing hard coding or probe types, cleaning up the probe driver lists, streamlining the open and probe lister code.
This PR also removes the `DebugProbeType` enum, which is only used to print the probe type internally, and requires the set of probe types to be hard coded into probe-rs.
> Split out `ProbeDriver`

- Cargo.lock
This removes a warning regarding a yanked version when installing with 'cargo install --locked'.
> Update ahash from 0.7.6 to 0.7.7 in Cargo.lock

- .github/workflows/start-release.yml
- xtask/src/main.rs
Github tools seem to tolerate both GH_TOKEN and GITHUB_TOKEN, but the release workflow gets mad at me if I try to change it to GITHUB_TOKEN, so let's go the other direction.
> Fix GITHUB_TOKEN env var name

- smoke-tester/src/dut_definition.rs
Before:
```console
$ /target/release/smoke_tester --chip RP2040
For tests, chip definition must be exact. Chip name RP2040 matches multiple chips:
RP2040
RP2040_SELFDEBUG
Error: Chip definition does not match exactly.
```
After:
```console
$ ./target/release/smoke_tester --chip not_a_chip
Error: Unable to find any chip matching not_a_chip
$ ./target/release/smoke_tester --chip rp204
For tests, chip definition must be exact. Chip name rp204 matches multiple chips:
RP2040
RP2040_SELFDEBUG
Error: Chip definition does not match exactly.
$ ./target/release/smoke_tester --chip rp2040
[1/1](RP2040) - Starting Test
[1/1](RP2040) - Error message: No probes detected!
[1/1](RP2040) - Tests Failed
[DONE] - Some DUTs failed some tests.
Test summary:
[RP2040] failed
1 out of 1 tests failed.
$ …
```
> Fix smoke-tester being unable to target rp2040

- probe-rs/src/probe.rs
- probe-rs/src/probe/cmsisdap/mod.rs
- probe-rs/src/probe/common.rs
- probe-rs/src/probe/espusbjtag/mod.rs
- probe-rs/src/probe/ftdi/mod.rs
This PR extends `extract_idcode` to stop and not die at 0xFFFF_FFFF, and replaces the manual reimplementations with calls to `extract_idcode`. The PR includes related changes to JtagChainItem, and also FTDI driver error types because one place complained and this is here that particular rabbit hole led.
> Use `extract_idcode` more

- Cargo.lock
- changelog/changed-nusb.md
- probe-rs/Cargo.toml
- probe-rs/src/probe.rs
- probe-rs/src/probe/cmsisdap/commands/mod.rs
- probe-rs/src/probe/cmsisdap/tools.rs
- probe-rs/src/probe/espusbjtag/protocol.rs
- probe-rs/src/probe/ftdi/mod.rs
- probe-rs/src/probe/jlink/jaylink/bits.rs
- probe-rs/src/probe/jlink/jaylink/capabilities.rs
- probe-rs/src/probe/jlink/jaylink/error.rs
- probe-rs/src/probe/jlink/jaylink/interface.rs
- probe-rs/src/probe/jlink/jaylink/macros.rs
- probe-rs/src/probe/jlink/jaylink/mod.rs
- probe-rs/src/probe/jlink/mod.rs
- probe-rs/src/probe/stlink/mod.rs
- probe-rs/src/probe/stlink/tools.rs
- probe-rs/src/probe/stlink/usb_interface.rs
- probe-rs/src/probe/usb_util.rs
- probe-rs/src/probe/wlink/mod.rs
- probe-rs/src/probe/wlink/usb_interface.rs
[nusb](https://github.com/kevinmehall/nusb) is a pure-Rust libusb replacement. It can help a lot with the issues we're having with libusb (cross compiling pain, segfaults).
~~I'm not sure what strategy we should follow. Either port probe drivers one-by-one, or port them all. Also, nusb doesn't support macos yet...~~
> Port to nusb

- probe-rs/src/probe/cmsisdap/tools.rs
Do not ignore devices without product string, still try to check whether they have an
interface with "CMSIS-DAP" in the name.
It seems the root cause is a `nusb` issue (https://github.com/kevinmehall/nusb/issues/24), which makes
`product_string()` always return None on Windows. Even when that's fixed, I
still think it's good to not bail out if there's no product string, it can help with compatibility
with weird probes.
> cmsisdap: fix probes not being found on windows.

- .github/workflows/smoketest.yml
- changelog/changed-jlink-multiple-taps.md
- probe-rs/src/architecture/riscv/dtm.rs
- probe-rs/src/architecture/xtensa/xdm.rs
- probe-rs/src/probe/cmsisdap/mod.rs
- probe-rs/src/probe/common.rs
- probe-rs/src/probe/espusbjtag/mod.rs
- probe-rs/src/probe/espusbjtag/protocol.rs
- probe-rs/src/probe/jlink/mod.rs
This PR adds some bits from espusbjtag to jlink, enables support for multiple TAPs, and adds Xtensa interface. In the end, the goal will be to try and unify the JTAG probes, and while this isn't exactly there, the added capabilities might be useful for someone else, too.
> Align jlink and espusbjtag impls, clean up

- probe-rs/src/probe/cmsisdap/tools.rs
I hadn't noticed nusb had an API to do this before! :)
> cmsisdap: use `get_string_descriptor` instead of doing a control request manually.

- probe-rs/src/probe/espusbjtag/protocol.rs
- probe-rs/src/probe/usb_util.rs
**WARNING**: I haven't tested it on real hardware, please test before merge! :pray:
> espusbjtag: use nusb `get_descriptor()` instead of doing a manual control request.

- probe-rs/src/architecture/arm/core/armv6m.rs
- probe-rs/src/architecture/arm/core/armv7m.rs
- probe-rs/src/architecture/arm/core/armv8m.rs
This change makes it possible to attach to running cores using `probe-rs attach`.
Before, I got an error trying to attach to a running app, because `read_core_reg()` requires the core to be *halted*, but the core might not be *halted*.
With the changes in this PR, `read_core_reg()` is only executed in case core stopped at a breakpoint.
This is fine, because `pc_before_step` is only used if core stopped at a breakpoint.
I decided to use a dummy register in the *else* branch, because it won't be accessed anyways.
**Note:** I only tested this on *armv7m*, but *armv6m* and *armv8m* should behave similar.
> fix: only read pc if breakpoint was reached for armvXm

- probe-rs/src/probe/ftdi/mod.rs
Looks like windows might have some trouble reading the product string (nusb tries to read DEVPKEY_Device_FriendlyName which may be missing) for whatever reason. Probe-rs discarded previously working FTDI chips due to this.
cc @Dirbaio in case you know something better, and since this is likely a nusb regression
> Ftdi: do not discard devices without product string

- changelog/added-16bit.md
- probe-rs/src/architecture/arm/core/armv6m.rs
- probe-rs/src/architecture/arm/core/armv7a.rs
- probe-rs/src/architecture/arm/core/armv7m.rs
- probe-rs/src/architecture/arm/core/armv8a.rs
- probe-rs/src/architecture/arm/core/armv8m.rs
- probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs
- probe-rs/src/architecture/riscv/communication_interface.rs
- probe-rs/src/architecture/riscv/mod.rs
- probe-rs/src/architecture/xtensa/communication_interface.rs
- probe-rs/src/architecture/xtensa/mod.rs
- probe-rs/src/bin/probe-rs/cmd/debug.rs
- probe-rs/src/core.rs
- probe-rs/src/memory/mod.rs
- probe-rs/src/probe/fake_probe.rs
- probe-rs/src/probe/stlink/mod.rs
- probe-rs/src/test.rs
- arch/arm: simplify removing aligned_range.
- arch/arm: simplify block transfer chunking.
- Add support for 16bit reads/writes.
Tested working with STLink and cmsisdap.
TODO:
> Add support for 16bit reads/writes.

- probe-rs/src/probe/common.rs
- probe-rs/src/probe/espusbjtag/mod.rs
- Fix JTAG state tracking (exit from Reset was previously incorrectly detected)
- Fix JTAG state traversal (Idle -> Reset is TMS = 0, not TMS = 1)
- Reset, just in case
> JTAG state machine fixes

- Cargo.lock
- probe-rs/Cargo.toml
- probe-rs/src/probe/cmsisdap/tools.rs
nusb added an API to list basic interface info from DeviceInfo which does no
actual USB I/O to the device (info is cached by the OS when plugging in the device).
This includes the interface string, which we use to detect CMSIS-DAP interfaces.
This takes `probe-rs list` in the Embassy CI machine (52 USB devices, 32 probes) from 900ms to 60ms.
see https://github.com/kevinmehall/nusb/issues/28
> cmsisdap: don't do i/o for the iface string when listing devices.

- probe-rs/src/probe/jlink/jaylink/mod.rs
- probe-rs/src/probe/jlink/mod.rs
This PR does fewer IO operations, speeding up JTAG considerably. Not quite up to the levels of FTDI/espusbjtag, but usable - I had a ~~36-37~~ 53-54 KiB/s flashing run while testing.
> Speed up J-Link JTAG

- probe-rs/src/probe.rs
- probe-rs/src/probe/espusbjtag/mod.rs
Similar pattern was added and then fixed in #2016 - it should be a tiny free perf increase.
Previously, `write_ir` immediately flushed the internal buffers, causing an IO operation. This was followed by another IO operation for the DR scan shortly after. This change allows batching these.
> Don't eagerly send out IR scan, clean up register access

- changelog/fixed-stm32g431-flash-algorithm.md
- probe-rs/targets/STM32G4_Series.yaml
The latest STM32G4 target pack from upstream was adopted in https://github.com/probe-rs/probe-rs/pull/1896.
Unfortunately, it was reported that this broke flashing for STM32G431CBU and STM32G431KBU.
This change re-introduces the previous flash algorithm for those two parts in order to un-break flashing.
See the discussion in https://github.com/probe-rs/probe-rs/pull/1896 for further context.
> Bring back the stm32g4xx_128 flash algorithm for STM32G431xB

- changelog/fixed-info-ir.md
- probe-rs/src/probe.rs
- probe-rs/src/probe/arm_jtag.rs
- probe-rs/src/probe/espusbjtag/mod.rs
- probe-rs/src/probe/ftdi/mod.rs
- probe-rs/src/probe/jlink/mod.rs
- probe-rs/src/probe/wlink/mod.rs
Closes #2067
Xtensas and some other MCUs use 5 IR bits. `swj_sequence` overwriting this causes problems in `probe-rs info` where the code forces 4 bits, no matter the detected length. In general, we either measure the IR lengths on attach, or use the value configured by target descriptions, so forcing 4 bits in code should not be necessary. Similarly, we configure IR lengths by setting the scan chain, so a method that sets the length after attach *should* not be necessary.
> Do not overwrite detected IR length

- changelog/fixed-no-rtt-no-error.md
- probe-rs/src/bin/probe-rs/cmd/run.rs
- probe-rs/src/bin/probe-rs/util/rtt.rs
At least partially addresses #2072 at least in theory
If the .elf has no `_SEGGER_RTT` symbol defined and no scan regions are set, probe-rs should not print an error.
> Don't error if there is no candidate region for the RTT control block

- probe-rs/src/probe.rs
- probe-rs/src/probe/arm_jtag.rs
- probe-rs/src/probe/common.rs
- probe-rs/src/probe/espusbjtag/mod.rs
- probe-rs/src/probe/espusbjtag/protocol.rs
- probe-rs/src/probe/ftdi/mod.rs
- probe-rs/src/probe/jlink/mod.rs
- probe-rs/src/probe/wlink/mod.rs
FTDI, JLink and espusbjtag are essentially the same high level JTAG code. This PR removes the duplication from them, getting rid of a considerable amount of code.
This PR also skips IR detection if the configuration contains a scan chain specification. This is now consistent with the CMSIS-DAP implementation. On the other hand, there exists #1796 ... This PR is big enough and blocks enough others so that I would vote for resolving 1796 later.
I'm willing to say this closes #1181
> Delete duplicate JTAG logic

- changelog/added-jlink-multidrop.md
- probe-rs/src/probe/arm_jtag.rs
Closes #1272
Closes #1157 
Closes #997
The original PR was pretty close, but missed a few tricky parts:
- A line reset in `raw_read_register` could immediately deselect the target. This was the root cause of incorrect DPIDR values.
- IHI0074D contains the following line: `If overrun detection is enabled, then the line reset sets CTRL/STAT.STICKYORUN to 0b1.`. This means we need to clear the sticky overflow bit after target selection, because the selection process starts with a line reset.
Note that I only tested that probe-rs can reset a Raspberry Pico W, I haven't done anything more extensive. Also, `line_reset` is similarly broken but at least RP2040 has now a chance to work.
Based on top of #2066
> J-Link multidrop support

- probe-rs/src/bin/probe-rs/cmd/cargo_embed/mod.rs
- probe-rs/src/bin/probe-rs/util/common_options.rs
- probe-rs/src/probe.rs
And display probe list in probe-rs error outputs, because why not :)
This refactor is pretty helpful in adding a default probe speed to targets, because I'll need to swap order of operations a bit for that.
> Reuse ProbeOptions in cargo-embed

- probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs
- arch/arm: unify build_csw_register and write_csw_register.
- arch/arm: add 64bit block transfers, to make it consistent with smaller ones.
> arch/arm: add 64bit block transfers, to make it consistent with smaller ones.

- changelog/added-ftdi-speed.md
- probe-rs/src/probe/ftdi/ftdi_impl.rs
- probe-rs/src/probe/ftdi/mod.rs
If not set, this PR falls back to 1MHz which feels like a safe default. Previously, the speed was I think dependent on the FTDI chip, or maybe 2-3MHz, not sure.
Blocked on #2066
> FTDI: Implement probe speed configuration

- changelog/changed-jtag-description.md
- changelog/changed-scan-chain.md
- probe-rs-target/src/chip.rs
- probe-rs-target/src/lib.rs
- probe-rs/src/config/registry.rs
- probe-rs/src/config/target.rs
- probe-rs/src/probe/cmsisdap/mod.rs
- probe-rs/src/probe/common.rs
- probe-rs/src/session.rs
- probe-rs/targets/esp32c2.yaml
- probe-rs/targets/esp32c3.yaml
- probe-rs/targets/esp32c6.yaml
- probe-rs/targets/esp32h2.yaml
- probe-rs/targets/esp32s2.yaml
- probe-rs/targets/esp32s3.yaml
- probe-rs/tests/scan_chain_test.yaml
- target-gen/src/commands/elf.rs
- target-gen/src/generate.rs
- scan chain info in target yamls are now for validation only
- scan_chain is now located under jtag
This is done to prepare for introducing more configuration, like default TAP index, default probe speed, etc.
Closes #1796
> Move scan_chain under jtag, use for validation only

- changelog/added-ftdi-arm.md
- probe-rs/src/probe/arm_jtag.rs
- probe-rs/src/probe/ftdi/mod.rs
- probe-rs/src/probe/jlink/mod.rs
Closes #1716
Not a lot was missing in theory but all I get at this moment is an IR scan, an IDCODE and a timeout.
I'm not entirely sure what I have to see for `probe-rs info` but the current output is the following, matching my J-Link over JTAG:
```
❯ probe-rs  info
Probing target via JTAG
ARM Chip:
Debug Port: Version 0, DP Designer: <unknown>
└── 0 MemoryAP
└── Generic
```
> Add ARM interface to FTDI

- changelog/removed-flash-algorithm-begin-data.md
- probe-rs/src/flashing/flash_algorithm.rs
- probe-rs/src/flashing/flasher.rs
This is a breaking change but it's very simple to migrate and I don't see the need to maintain the redundancy
> Remove `FlashAlgorithm::begin_data`

- changelog/fixed-jlink-speed.md
- probe-rs/src/probe/jlink/mod.rs
- probe-rs/src/probe/jlink/speed.rs
J-Links like to reset speed when their interface changes. This PR a) reduces the number of interface changes and b) restores speed on interface change.
> Fix j-link speed config

- Cargo.lock
- changelog/fixed-cargo-embed.md
- changelog/fixed-logging-with-progress-bars.md
- probe-rs/Cargo.toml
- probe-rs/src/bin/probe-rs/cmd/cargo_embed/config/mod.rs
- probe-rs/src/bin/probe-rs/cmd/cargo_embed/mod.rs
- probe-rs/src/bin/probe-rs/cmd/cargo_embed/rttui/app.rs
- probe-rs/src/bin/probe-rs/cmd/cargo_embed/rttui/channel.rs
- probe-rs/src/bin/probe-rs/cmd/cargo_flash/diagnostics.rs
- probe-rs/src/bin/probe-rs/cmd/cargo_flash/mod.rs
- probe-rs/src/bin/probe-rs/cmd/info.rs
- probe-rs/src/bin/probe-rs/cmd/run.rs
- probe-rs/src/bin/probe-rs/main.rs
- probe-rs/src/bin/probe-rs/util/common_options.rs
- probe-rs/src/bin/probe-rs/util/flash.rs
- probe-rs/src/bin/probe-rs/util/logging.rs
- probe-rs/src/bin/probe-rs/util/mod.rs
- probe-rs/src/bin/probe-rs/util/rtt.rs
This PR also fixes a regression introduced in #2083 that ignored the chip in `Embed.toml`
> Remove `log`, integrate tracing and progress bars better, make cargo-embed smarter

- probe-rs/src/bin/probe-rs/util/logging.rs
I hope this time `cargo flash` really does default to WARN. `None`-ing missing clap arguments has its downsides...
I'm still not happy with it. `cargo embed` defines its default in `default.toml` even though the config type is `Option<LevelFilter>`. If we would remove the option, however, it would hurt discoverability as I believe that file is the template for the documentation.
> Use WARN as the default log level

- probe-rs/src/architecture/arm/dp/mod.rs
- probe-rs/src/probe.rs
- probe-rs/src/probe/arm_debug_interface.rs
- probe-rs/src/probe/ftdi/mod.rs
- probe-rs/src/probe/jlink/mod.rs
The module is not JTAG specific, it also contains SWD related functions.
The log is really confusing when it always talks about arm_jtag, even though you're using SWD...
> Rename the arm_jtag module to arm_debug_interface

- changelog/fixed-chipname-when-substring.md
- probe-rs/src/config/registry.rs
#1671 removed checking if we had an exact match for chip name before looking for partial chip names.
This broke all chips that are a substring of another chip.
It also removed a check for multiple exact matches, but I think that case is probably impossible as long as the registry doesn't have any duplicates.
Example:
```system
$ probe-rs read b32 0x0 1 --chip Cortex-M3
Error: The chip 'Cortex-M3' was not found in the database.
Caused by:
Found multiple chips matching 'Cortex-M3', unable to select a single chip. (Cortex-M33, Cortex-M35P)
```
This doesn't need a changelog entry IMO.
> Don't match partial chipname if we have an exact one

- probe-rs/src/bin/probe-rs/cmd/cargo_embed/mod.rs
- probe-rs/src/bin/probe-rs/main.rs
Just ran into `probe-rs run` panicking for some reason. I don't think we should consider timestamp issues critical.
I've also extracted the same code from cargo embed, and removed the - ineffectual - logging. If we really need to notify the user, we should maybe pass around an `Option` and handle the `None` case where we need to use the timestamp. I consider this out of scope for this PR.
> Don't panic if `current_local_offset` fails

- Cargo.lock
- probe-rs/src/probe/ftdi/ftdaye/mod.rs
Closes #2096
Implemented as https://github.com/kevinmehall/nusb/pull/35
nusb 0.1.6 is released so this probably fixes #2122, too
> update nusb, attempt to detach ftdi drivers

- changelog/added-cargo-embed-rtt-channel-socket.md
- probe-rs/src/bin/probe-rs/cmd/cargo_embed/config/default.toml
- probe-rs/src/bin/probe-rs/cmd/cargo_embed/rttui/app.rs
- probe-rs/src/bin/probe-rs/cmd/cargo_embed/rttui/channel.rs
- probe-rs/src/bin/probe-rs/cmd/cargo_embed/rttui/mod.rs
- probe-rs/src/bin/probe-rs/cmd/cargo_embed/rttui/tcp.rs
This PR adds the option to send raw RTT data over a TCP Socket. This enables you to receive the data in some external frontend for e.g. plotting or specific processing.
This can be configured via a new 'socket' option in the `ChannelConfig` of Cargo Embed. 
The socket automatically connects if a listener (server) is available on the configured address. It also tries to reconnect automatically after an error. This means the transmission can be lossy.
Let me know if I put everything in the right location / use the correct naming.
> Cargo Embed: publish channel data over optional tcp socket

- changelog/added-support-for-CH32V307.md
- probe-rs/src/flashing/flash_algorithm.rs
- probe-rs/targets/CH32V3_Series.yaml
This patch adds support for CH32V307, including the flashing algorithm. Adding support for CH32V3xx and CH32V2xx should be trivial, but I don't have them, so I can't test it.
target-gen only allows a single byte for "erased state", half word is needed at least for this target.
The flashing is also very slow, at about 3.2 KiB/s. I suspect it is due to no batching with WCHLink.
> RISC-V: CH32V307 support

- probe-rs/src/flashing/error.rs
- probe-rs/src/flashing/flash_algorithm.rs
This PR - step-by-step - gets rid of the very cryptic loop in `assemble_from_raw`. This code was very confusing so I've included every single step I made in a different commit so you can catch any mistakes I made.
This PR also fixes a suspected issue where the stack may overlap with the data pages
> Simplify `FlashAlgorithm::assemble_from_raw`

- changelog/added-cfa.md
- probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
- probe-rs/src/bin/probe-rs/cmd/dap_server/server/core_data.rs
- probe-rs/src/bin/probe-rs/cmd/debug.rs
- probe-rs/src/debug/debug_info.rs
- probe-rs/src/debug/function_die.rs
- probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__RP2040__full_unwind.snap
- probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__nRF52833_xxAA__full_unwind.snap
- probe-rs/src/debug/stack_frame.rs
- probe-rs/src/debug/unit_info.rs
- probe-rs/src/debug/variable.rs
- probe-rs/src/debug/variable_cache.rs
- We need to set `frame_section.set_address_size` as gimli defaults to host (8) which is just incorrect
- This PR propagates (some?) CFA information to the evaluation as required by my elf
- This PR moves CFA calculation to before determining frame base. In my case, the reverse failed due to CFA being None.
With this, I now have a decent call stack, but variable values are still not filly implemented (enums!). Also, struct fields are always read with the same byte count as the struct itself, it looks like.
> Try to improve C debugging experience

- CONTRIBUTING.md
Currently the `probe-rs` binary needs `cli` which is not a default feature.
> Fix cargo subcommand build instructions

- changelog/fixed-debug-dw-at-accessibility.md
- probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/protocol.rs
- probe-rs/src/debug/unit_info.rs
Fixes probe-rs/probe-rs#2140
It turns out that silently ignoring this attribute (for now) fixes the unwind of variables that failed when Rust codegen for LLVM introduced the use of the `DW_AT_accessibility` attribute.
Our current debug capabilities has no use case for using the 'public/private/protected' variants of this attribute.
The DAP Specification allows these as [presentation hints](https://microsoft.github.io/debug-adapter-protocol/specification#Types_VariablePresentationHint), so that is one possible use case for future consideration.
> Fix: Debug cannot resolve variables with DW_AT_accessibility attribute

- probe-rs/src/debug/language.rs
- probe-rs/src/debug/language/c.rs
- probe-rs/src/debug/language/rust.rs
- probe-rs/src/debug/mod.rs
- probe-rs/src/debug/unit_info.rs
Continuation of #2150
GCC seems to encode enum variants as `data1` (or wider), while LLVM used `udata` for Rust. In this PR I'm adding code to handle all the constant values (that I found). `dataN` can be any data format, but right now I've went with the path of least resistance and am handling them as unsigned integers.
> Unwind C enum variants, handle all C versions known by gimli, fix struct members

- changelog/fixed-jlink-swd-transfer-size.md
- probe-rs/src/probe/jlink/mod.rs
For the swdio command, it seems that the `max_mem_block_size` is actually useful.
This should probably be coordinated with the JTAG I/O, so it's still marked as draft.
@bugadani I think you looked into the mem block size for JTAG, what exactly was the problem there?
> Fix SWDIO for J-Link

- probe-rs/src/architecture/riscv/communication_interface.rs
- probe-rs/src/probe/common.rs
- probe-rs/src/probe/espusbjtag/mod.rs
- probe-rs/src/probe/ftdi/mod.rs
- probe-rs/src/probe/jlink/mod.rs
Some newer nightly started complaining and these are really unused. I'm surprised about `flush` but I guess we're always reading back something currently.
> Remove unused code

- changelog/changed-ensure-core-halted-during-setup.md
- probe-rs/src/bin/probe-rs/util/common_options.rs
- probe-rs/src/flashing/loader.rs
- probe-rs/src/probe/fake_probe.rs
- probe-rs/src/session.rs
- probe-rs/tests/flash_dry_run.rs
This PR adds a new method on Session, which currently isn't public which allows blocks of code to be run when all cores are halted. This is useful for running sequences, especially in the case of the esps, as some sequences poke flash. Doing so during operation of the chip can cause all manner of issues, related to cache pulls.
Closes #2023
> Halt the core after attaching so sequences can run freely

- probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
- probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/request_helpers.rs
- probe-rs/src/bin/probe-rs/cmd/dap_server/peripherals.rs
- probe-rs/src/bin/probe-rs/cmd/dap_server/peripherals/svd_cache.rs
- probe-rs/src/bin/probe-rs/cmd/dap_server/peripherals/svd_variables.rs
- probe-rs/src/debug/variable.rs
- probe-rs/src/debug/variable_cache.rs
The SVD handling is not related to debug information at all, so I think it's cleaner to have it separate. It introduces some small duplication in the cache handling.
> Split SVD variable cache into a separate struct

- changelog/fixed-espusbjtag-cold-start.md
- probe-rs/src/probe/espusbjtag/protocol.rs
This solves the
```rust
thread 'main' panicked at probe-rs/src/probe/espusbjtag/protocol.rs:152:38:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
errors.
It's likely a regression by switching to nusb, but simple enough to work around.
> Ensure we have valid descriptor data when initially accessing espusbjtag

- probe-rs/src/architecture/arm/ap/memory_ap/mock.rs
- probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs
`write` has a number of mistakes, some of which are obvious at a glance, others got uncovered while trying #2171
- `start_extra_count` can be 4 if aligned and should be `<= len`
- `end_extra_count` and `inbetween_count` could underflow for short buffers
- `write_32` can return an error even if it gets an empty buffer (i.e. its data is too short and written entirely by the above `write_8`, and address ends up unaligned)
- branch handling `end_extra_count` tried to write `start_extra_count` number of bytes
> ADIv5: Fix a bunch of mistakes in `ArmProbe::write`

- probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
- probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/repl_commands_helpers.rs
I find `"Base(unsigned int)"` a very unfriendly type if I hover over a variable. This PR tries to avoid debug-printing the type name. I'm not sure I found all of them :)
> Do not debug-print VariableType variant when hovering over a variable

- README.md
somewhat counterintuitively, `cargo install` command by default doesn't respect the `Cargo.lock` file (see https://github.com/rust-lang/cargo/issues/7169 ), leading to situations when the command offered in the README may fail if one of the dependencies has an incompatible update and isn't pinned in the Cargo.toml
This just happened because defmt-decoder 0.3.10 made some changes to their unstable APIs which broke `cargo install probe-rs`, because defmt-decode requirement was `0.3` and Cargo.lock wasn't respected.
> Update cargo install command in the readme to use Cargo.lock

- probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__RP2040__full_unwind.snap
- probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__nRF52833_xxAA__full_unwind.snap
- probe-rs/src/debug/unit_info.rs
The only difference should be the name of the namespace variables in the variable cache.
I think not having the parent included in the child namespace makes more sense, since the structure of the already shows what the hierarchy looks like.
> debug: Simplify namespace processing

- probe-rs/src/debug/language/c.rs
- probe-rs/src/debug/language/rust.rs
- probe-rs/src/debug/language/value.rs
A bit subjective, but this PR will print "1.0" for float values instead of "1", which is much less surprising to me.
> Print at least one fractional digit for floats

- probe-rs/src/debug/unit_info.rs
@noppej do you have a better idea maybe? I think failing if we encounter something we haven't seen before is a bit harsh as strategies go, especially considering that DWARF allows vendor-specific extensions.
Should fix #2188 (or at least fail less loudly)
> Do not error if we encounter unknown attributes

- .vscode/launch.json
I didn't notice this when I removed the xtensa example.
> Remove xtensa example launch config

- probe-rs/Cargo.toml
we use `detach_and_claim_interface` which is only present in 0.1.6+.
> fix nusb dep version.

- probe-rs/targets/STM32H5_Series.yaml
For some reason some RAMs are marked as Generic. The flash loader will refuse
to "fake-flash" data to RAM to "generic" memories. This breaks
teleprobe running from RAM.
Fix is marking all RAMs as RAM.
> targets: fix generic RAM in STM32H5

- changelog/fixed-debugger-exception-unwind-abort.md
- probe-rs/src/debug/debug_info.rs
This doesn't solve the unwind problem I'm seeing, but at least it doesn't completely abort everything when the problem occurs.
> dap-server: Don't stop when unwinding an exception fails

- probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
- probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/repl_commands_helpers.rs
- probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/request_helpers.rs
- probe-rs/src/bin/probe-rs/cmd/debug.rs
- probe-rs/src/debug/debug_info.rs
- probe-rs/src/debug/language/value.rs
- probe-rs/src/debug/unit_info.rs
- probe-rs/src/debug/variable.rs
- probe-rs/src/debug/variable_cache.rs
The `get_children` function always returned `Ok`, so there is no point in it returning a `Result`. It should also be a bit more efficient to just return an iterator, instead of creating a `Vec` with cloned variables.
> Remove unnecessary Result return value

- probe-rs/src/gdb_server/target/desc/data.rs
Fix panics caused by the wrong other_name when connecting AArch64 devices.
I tested with a Raspberry Pi 5.
> AArch64: Fix FPCR other name

- probe-rs/targets/BCM2712.yaml
This PR adds BCM2712 targets.
This target file is based on BCM2711.yaml
1. Append `enable_jtag_gpio=1` to `/boot/config.txt`
2. Connect Raspberry Pi Debug Probe's Debug connector to Raspberry Pi 5's UART connector.
3. Run following command
```
cargo run --bin probe-rs --features=cli -- \
gdb --chip RaspberryPi5B --speed 1000 --protocol swd  \
--gdb-connection-string 127.0.0.1:3333
```
> targets: Add BCM2712(Raspberry Pi 5)

- probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
- probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/repl_commands_helpers.rs
- probe-rs/src/bin/probe-rs/cmd/dap_server/peripherals/svd_cache.rs
- probe-rs/src/bin/probe-rs/cmd/debug.rs
- probe-rs/src/debug/debug_info.rs
- probe-rs/src/debug/language.rs
- probe-rs/src/debug/language/c.rs
- probe-rs/src/debug/language/rust.rs
- probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__RP2040__full_unwind.snap
- probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__nRF52833_xxAA__full_unwind.snap
- probe-rs/src/debug/unit_info.rs
- probe-rs/src/debug/variable.rs
- probe-rs/src/debug/variable_cache.rs
Continuation of #2171
This PR aims at reducing the number of `<unnamed>` variables while debugging C code. We're doing this by passing the type name from upper tree nodes if they are `typedef`, (or `const` or `volatile`, so this is possibly not only hacky, but wrong). While not perfect (we still ignore modifiers, pointer constness, etc) this now allows showing more type names to the user.
> Improve variable typing: follow typedefs, resolve pointer types better

- probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__RP2040__full_unwind.snap
- probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__RP2040__static_variables.snap
- probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__atsamd51p19a__full_unwind.snap
- probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__atsamd51p19a__static_variables.snap
- probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__nRF52833_xxAA__full_unwind.snap
- probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__nRF52833_xxAA__static_variables.snap
- probe-rs/src/debug/variable.rs
- probe-rs/src/debug/variable_cache.rs
- Display a few children for big arrays, too
- Do not include invisible spaces
- Reduce the number of allocations around variable printing and cache
> Improve printing big arrays & a collection of small assorted improvements

- changelog/added-expose-all-probe-options-as-env.md
- probe-rs/src/bin/probe-rs/util/common_options.rs
This helps when running multi probe system and you need to point the same commands to a lot of different probes
> Expose all probe settings via environment variables

- README.md
This was a leftover from when we needed libftdi, I believe.
> Remove vcpkg meantion from the readme

- changelog/fixed-riscv-dm-disabled.md
- probe-rs/src/architecture/riscv/communication_interface.rs
- probe-rs/src/architecture/riscv/mod.rs
Introduced in #2080
cc @bjoernQ can you tell me please if this (not using the already read `dmcontrol`, instead writing a new one with `dmactive=0`) is indeed a mistake or just an oversight?
> Don't accidentally disable the Risc-V debug module

- probe-rs/src/bin/probe-rs/cmd/cargo_embed/mod.rs
- probe-rs/src/bin/probe-rs/cmd/dap_server/server/debugger.rs
- probe-rs/src/bin/probe-rs/cmd/list.rs
- probe-rs/src/bin/probe-rs/util/common_options.rs
- probe-rs/src/probe.rs
- probe-rs/src/probe/cmsisdap/mod.rs
- probe-rs/src/probe/cmsisdap/tools.rs
- probe-rs/src/probe/espusbjtag/mod.rs
- probe-rs/src/probe/ftdi/mod.rs
- probe-rs/src/probe/jlink/mod.rs
- probe-rs/src/probe/stlink/mod.rs
- probe-rs/src/probe/wlink/mod.rs
Somewhat opinionated, but `Debug` should be for debugging output, and `Display` should be used for user-facing output.
> Don't use debug for end user output of probe types

- changelog/fixed-debug-breakpoint-step.md
- probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
- probe-rs/src/debug/debug_info.rs
- probe-rs/src/debug/debug_step.rs
- probe-rs/src/debug/language/c.rs
- probe-rs/src/debug/language/parsing.rs
- probe-rs/src/debug/language/rust.rs
- probe-rs/src/debug/language/value.rs
- probe-rs/src/debug/mod.rs
- probe-rs/src/debug/source_instructions.rs
- probe-rs/src/debug/unit_info.rs
- probe-rs/src/debug/variable.rs
This is a continuation of #2181 , to fix known issues and add new tests.
> Debug: Improve breakpoints and debug stepping behavior

- probe-rs/examples/tcp_itm.rs
- probe-rs/src/core/dump.rs
examples/tcp_itm: unused_io_amount
src/core/dump: suspicious_open_options
> clippy: Address some lints from nightly’s clippy

- changelog/fixed-windows-crossterm-double-press.md
- probe-rs/src/bin/probe-rs/cmd/cargo_embed/rttui/app.rs
On Windows, Crossterm emits both `Press` and `Release` events for each keypress (see the related discussion at https://github.com/ratatui-org/ratatui/issues/347)
This change ensures that only `Press` events are processed by the input system.
> Prevent cargo-embed from receiving duplicated inputs on windows

- changelog/changed-function-die-struct.md
- changelog/fixed-unitinfo-function-ranges.md
- probe-rs/src/debug/debug_info.rs
- probe-rs/src/debug/debug_step.rs
- probe-rs/src/debug/function_die.rs
- probe-rs/src/debug/unit_info.rs
This PR fixes two issues (encountered while wip on a breakpoint PR) related to handling of `FunctionDie` address ranges.
1. `UnitInfo::get_function_dies` assigned the `low_pc` and `high_pc` values based on only the last processed `gimli::Range` for the funciton DIE. 
2. Attempting to coalesce ranges into a `low_pc` and `high_pc` implies that the ranges are contiguous, which are not necessarily the case.
> Fixes to `FunctionDie`: Handling of valid address ranges.

- probe-rs/src/bin/probe-rs/main.rs
#2240 introduces a change that negatively impacts  the DAP clients like the VSCode extension. This PR introduces a temporary fix to ensure those clients can continue to work without requiring an immediate release.
Once we have released the current master branch, we can release https://github.com/probe-rs/vscode/pull/86, and then remove this alias.
> Add serde alias for `FormatOptions::binary_format`

- changelog/fixed-defmt-timestamp-detection.md
- probe-rs/src/bin/probe-rs/util/rtt.rs
Recently I noticed the following message while running a binary with a defmt rtt channel that was supposed to have a `defmt_timestamp!` implementation:
```
WARN defmt_decoder::log::format: logger format contains timestamp but no timestamp implementation was provided; consider removing the timestamp (`{t}` or `{T}`) from the logger format or provide a `defmt::timestamp!` implementation
```
After looking into this issue, I realized that the `FormatterConfig` used for defmt did not have the correct timestamp configuration, so it was causing this message to trigger even if the ELF actually had a timestamp configuration in its debug symbol table.
This change simply fixes it by setting the `is_timestamp_available` of the `FormatterConfig` to the configuration read from the symbol table of the …
> Fix detection of defmt timestamp

- changelog/fixed-wlink-detection.md
- probe-rs/src/probe/wlink/mod.rs
Fix wlink detection after the nusb refactor #1842 .
The nusb driver seems to report a different product string.
Verified on:
- Probe: WCH-Link v2.10(v30) (WCH-LinkE-CH32V305)
- OS: macOS
- Board: CH32V307VCT6 (YD-CH32V307VCT6)
- Code: https://github.com/ch32-rs/ch32-hal
CC @Dirbaio
> Fix wlink detection

- changelog/changed-probe-selector.md
- probe-rs/src/bin/probe-rs/cmd/cargo_embed/mod.rs
- probe-rs/src/bin/probe-rs/cmd/dap_server/server/configuration.rs
- probe-rs/src/bin/probe-rs/util/common_options.rs
@Tiwalun as `--probe` is consistent across the other tools I'm assuming the rename in #1769 was not intended.
Fixes #2261 by re-renaming the option.
> Restore `--probe` in cargo embed

- changelog/fixed-probe-rs-attach-timeout.md
- probe-rs/src/bin/probe-rs/cmd/run.rs
Try fix 
- #2183.
This error could be introduced by
- #1899.
ps.
Actually I don't understand why this happened, or why move the line can fix it, XD. I just find the PR that breaks "attach" cmd, and compare the changes and move this line back into the if block.
> fix probe-rs attach timeout error

- changelog/changed-embed-toml.md
- probe-rs/src/bin/probe-rs/cmd/cargo_embed/config/default.toml
- probe-rs/src/bin/probe-rs/cmd/cargo_embed/config/mod.rs
- probe-rs/src/bin/probe-rs/cmd/cargo_embed/mod.rs
- probe-rs/src/bin/probe-rs/cmd/cargo_embed/rttui/app.rs
- probe-rs/src/bin/probe-rs/cmd/cargo_embed/rttui/channel.rs
- probe-rs/src/bin/probe-rs/cmd/cargo_embed/rttui/mod.rs
- probe-rs/src/bin/probe-rs/cmd/cargo_embed/rttui/tab.rs
- probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
- probe-rs/src/bin/probe-rs/cmd/dap_server/server/core_data.rs
- probe-rs/src/bin/probe-rs/cmd/dap_server/server/debug_rtt.rs
- probe-rs/src/bin/probe-rs/cmd/run.rs
- probe-rs/src/bin/probe-rs/util/rtt.rs
Improvement opportunity: configure down channel operating modes, add the option to debugger's rtt config, configure it during channel setup.
This PR removes a good chunk of duplicate code and brings debugger, probe-rs and cargo embed configuration a bit closer to each other. It's also making cargo embed more efficient, as only new log lines need to be rendered.
This didn't turn out exactly like the "mostly just remove code" PR I originally envisioned but the end result - provided I didn't break much - doesn't look too bad, IMO.
> Rtt refactor vol 2

- changelog/fixed-armv8a-memory-access.md
- probe-rs/src/architecture/arm/core/armv8a.rs
Fix a problem that RTT Attach fails because the core is not halted during memory access.
> Armv8a: Fix core is not halting during cpu memory access

- probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
- probe-rs/src/bin/probe-rs/cmd/dap_server/peripherals/svd_variables.rs
- probe-rs/src/bin/probe-rs/cmd/dap_server/server/debugger.rs
Previously, for "Erasing Sectors" and "Reading Old Pages" we displayed a non-rounded number between 0 and 1 as the progress. This PR fixes this issue by moving the % display into `update_progress`.
> Fix dap progress reporting UX

- Cargo.lock
- Cargo.toml
- probe-rs/Cargo.toml
Based on the maintainer dashboard from <https://lib.rs/crates/probe-rs>, especially including several megabytes of ELF files seems unnecessary.
> Exclude test files from published crate, cleanup some deps

- changelog/fixed-erasing-esp32.md
- probe-rs-target/src/memory.rs
- probe-rs/src/flashing/builder.rs
- probe-rs/src/flashing/erase.rs
- probe-rs/src/flashing/error.rs
- probe-rs/src/flashing/loader.rs
- probe-rs/targets/esp32.yaml
- probe-rs/targets/esp32c2.yaml
- probe-rs/targets/esp32c3.yaml
- probe-rs/targets/esp32c6.yaml
- probe-rs/targets/esp32c6_lp.yaml
- probe-rs/targets/esp32h2.yaml
- probe-rs/targets/esp32s2.yaml
- probe-rs/targets/esp32s3.yaml
- target-gen/src/commands/elf.rs
- target-gen/src/generate.rs
@Yatekii @MabezDev The issue I'm trying to solve here is that `probe-rs erase` fails if it encounters NVM regions whose addresses are not covered by flash algos. In case of ESP chips, the flash loaders are working with physical addresses in the flash chip, but the NVM addresses were defines as the CPU saw them. I'm not entirely sure, but I believe these memory ranges are read-only (because the write API basically operates by issuing commands to the flash ICs directly). Maybe a better approach would be to allow defining regions as read only, or to define them as alias regions - whichever we chose, we can re-add these regions after probe-rs becomes smart enough.
> ESP32: Remove external flash address ranges

- Cargo.lock
- probe-rs/Cargo.toml
- probe-rs/src/bin/probe-rs/main.rs
- probe-rs/src/config/sequences/esp.rs
- probe-rs/src/flashing/download.rs
- probe-rs/src/flashing/loader.rs
Closes #2300
Looks like hidapi still wants libudev-sys to stick around, but a good chunk of dependencies were cleaned up by this update. @MabezDev are you OK with the added tech debt regarding xtal freqs?
> Update espflash to v3

- changelog/added-autodetect-rtt-core.md
- probe-rs/src/bin/probe-rs/cmd/run/mod.rs
- probe-rs/src/bin/probe-rs/cmd/run/normal_run_mode.rs
Hi!
I would like to use the rtt on the nrf5340 net core, which is currently impossible because the rtt is hard coded to attach to the `core[0]`. I describe my problem [here](https://github.com/probe-rs/probe-rs/discussions/2294).
This PR implements the @Dirbaio idea to autodetect it by looking at which core can access the RAM where the RTT control block is.
This solves my issue with the nrf5340 net core.
I'm new to the code base, so the code could be probably well-placed. I'm open to refactories feedback.
> feat: chose core based on rtt controll block

- probe-rs/src/architecture/arm/communication_interface.rs
- probe-rs/src/probe/fake_probe.rs
The nRF51 doesn't like it we don't run the `debug_port_setup` sequence before the `debug_port_connect` sequence is executed.
> Fix: Ensure debug_port_setup sequence is run before trying debug_port_connect

- Cargo.lock
- changelog/fixed-cargo-embed-defmt.md
- probe-rs/Cargo.toml
- probe-rs/src/bin/probe-rs/cmd/cargo_embed/mod.rs
- probe-rs/src/bin/probe-rs/cmd/cargo_embed/rttui/app.rs
- probe-rs/src/bin/probe-rs/cmd/cargo_embed/rttui/channel.rs
- probe-rs/src/bin/probe-rs/cmd/cargo_embed/rttui/tab.rs
This PR removes code that interfered with the defmt data processing. The PR also stips ansi escape sequences from the log output because we don't currently process them, they interfere with text wrapping and look bad when not interpreted.
This PR intends to fix #2322. @FlareFlo can I ask you to test that your issue is no longer present with this? ~Your broken output does not reproduce on my F429, so I'm not sure if it was fixed already or I'm just lucky.~ The broken output reproduces with probe-rs v0.23.0, but not with this PR for me.
> Fix cargo-embed's defmt processing

- probe-rs/src/bin/probe-rs/cmd/cargo_embed/mod.rs
- probe-rs/src/bin/probe-rs/cmd/run/mod.rs
- probe-rs/src/bin/probe-rs/util/flash.rs
- probe-rs/src/bin/probe-rs/util/rtt.rs
> cargo-embed: select core based on rtt control block

- changelog/fixed-breakpoint-handling-dwarf4.md
- probe-rs/Cargo.toml
- probe-rs/src/debug/debug_info.rs
- probe-rs/src/debug/source_instructions.rs
- probe-rs/tests/source_location.rs
#2223 seems to have broken the breakpoint handling for a C binary I have.
When DWARF v4 is used, there seem to be duplicate file entries in the line program headers, due to how the compilation file is handled.
> Fix breakpoint search

- changelog/fixed-atsamd-jlink-reset.md
- probe-rs/src/architecture/arm/memory/romtable.rs
- probe-rs/src/config/sequences/atsam.rs
- probe-rs/src/probe/arm_debug_interface.rs
Running `probe-rs erase --chip atsamd51p19a` with a J-Link probe always ended up in an error. The problem is that `reset_hardware` tried to set `tms` and `tck` to known values before issuing the reset, but the probe does not have implementation for these, so the reset always failed. Otherwise, the erase was done correctly.
@jgust since you're the original author, do you see potential problems by _not_ setting `tms` and `tck`? Should we do a "try-but-fall-back-to-just-nrst" instead?
> ATSAM: fall back to only setting nRESET

- changelog/added-rtt-mode.md
- changelog/changed-defmt-mode.md
- probe-rs/src/bin/probe-rs/cmd/cargo_embed/mod.rs
- probe-rs/src/bin/probe-rs/cmd/dap_server/server/core_data.rs
- probe-rs/src/bin/probe-rs/cmd/run/mod.rs
- probe-rs/src/bin/probe-rs/util/rtt.rs
This PR attempts to resolve (external) https://github.com/knurling-rs/defmt/issues/818
In case the user somehow saturates the uplink, they can change the mode - which in turn may break the parsing in an unrecoverable way.
> Configure defmt channels to block

- probe-rs/src/architecture/arm/ap/generic_ap.rs
- probe-rs/src/architecture/arm/ap/memory_ap/mod.rs
- probe-rs/src/architecture/arm/ap/register_generation.rs
- probe-rs/src/bin/probe-rs/cmd/info.rs
Note: It may be worth doing in `TARGETID` but this is defined using `bitfield!` rather than `define_ap_register` (`TARGETID` is a dp register).
> arch/arm: use JEP106Code in GenericAp::IDR

- deny.toml
See <https://github.com/EmbarkStudios/cargo-deny/pull/611>.
Two new cargo-deny warnings are fixed by <https://github.com/probe-rs/probe-rs/pull/2342>, for other see below.
Open cargo-deny warnings:
> Update cargo-deny config to fix deprecation warnings

- changelog/fixed-corrupted-rtt.md
- probe-rs/src/bin/probe-rs/cmd/cargo_embed/mod.rs
- probe-rs/src/bin/probe-rs/cmd/run/mod.rs
- probe-rs/src/bin/probe-rs/util/rtt.rs
- probe-rs/src/flashing/flasher.rs
- probe-rs/src/rtt/channel.rs
> An attempt to solve the "Corrupted RTT channel" errors which sometimes appear when attaching to a RTT control block which hasn't been fully initialized.
Previously, probe-rs attached to partially initialized RTT control blocks. This meant that subsequent polls sometimes reported corrupted control block errors, because the read and/or write pointers were out of range. We now read and verify these pointers and delay initializing if they are clearly wrong.
This isn't a perfect solution. Problem is that we might still end up incorrectly accepting memory garbage with some low probability. At least now we reject garbage that is clearly incorrect, reducing the frequency of errors reported to users. I'm hoping defmt-rtt eventually fixes their initialization.
Thanks to @MabezDev for figuring out …
> Validate RTT channel pointers during attach, and make the logs less chatty

- Cargo.lock
- probe-rs/Cargo.toml
- probe-rs/src/rtt.rs
I don't think a KMP algorithm gives us much benefit while looking for the RTT magic string in the host's memory. It's only ever used once (per attach attempt) so we may be able to get away with something more... naive.
> Remove the kmp dependency

- probe-rs/src/probe/jlink/mod.rs
I'm not sure about changelog, but I'm also not sure if this is useful. `target_reset` seems to be unused in the binary, and maybe carrying it around may be somewhat redundant?
Closes #993
> Implement target_reset on J-Link

- probe-rs/src/bin/probe-rs/cmd/cargo_embed/mod.rs
- probe-rs/src/bin/probe-rs/cmd/cargo_flash/mod.rs
- probe-rs/src/bin/probe-rs/util/common_options.rs
This PR moves flash's CLI arg struct out of the utils folder to the only place of use, fixes a typo and unifies the way CWD is set. `cargo flash` is also not a library so this removes the doc comment that I believe isn't very valuable.
> Bring cargo flash a bit closer to cargo embed

- probe-rs/src/bin/probe-rs/cmd/cargo_embed/mod.rs
- probe-rs/src/bin/probe-rs/cmd/dap_server/server/core_data.rs
- probe-rs/src/bin/probe-rs/cmd/run/mod.rs
- probe-rs/src/bin/probe-rs/util/rtt.rs
- probe-rs/src/flashing/flasher.rs
- probe-rs/src/rtt.rs
This PR moves the common RTT attach logic out of the different binaries, and does a bit of cleanup. I've also marked a place that contains one more implementation of the loop-until-timeout logic that we'll be able to clean up in the near future. The shared Session in `cargo-embed` complicates things a bit but I'm hoping that by providing two small "how do I get the core (and try to attach to it once)" functions the end result won't be terrible.
Also, we no longer read the .elf files multiple times.
> Some more RTT churn

- probe-rs/build.rs
- probe-rs/src/bin/probe-rs/cmd/cargo_embed/mod.rs
- probe-rs/src/bin/probe-rs/cmd/cargo_flash/mod.rs
- probe-rs/src/bin/probe-rs/main.rs
Instead of a meta.rs, use env vars for the binary versions. The `meta.rs` file was only generated for the binaries, so library users are not affected by this change. However, `--version` now prints the git hash in the same line as the crate version as I did not find a way to place a newline into an env variable.
> Don't generate meta.rs file

- changelog/changed-cmd-info-default-dp.md
- probe-rs/src/bin/probe-rs/cmd/info.rs
This avoids uneccessary noise when a specific target is selected or when a valid default is found.
Caveat: on RP2040, running `info` several times will (in sequence):
1. Fail to select Default and enumerate the alternate multi-drop as expected
2. Detect instance 0 and the default DP and enumerate it only
3. Detect a dubious instance 0xF as the default DP and not find any AP
4. all subsequent run will be the same as 3 (until a power cycle of the target).
This is acceptable because:
- this command is not expected to be run several times
- the rp2040 is really the only multi-drop target known to this day
> cmd/info: Only try other multidrop addresses if the default failed

- probe-rs/src/bin/probe-rs/cmd/cargo_embed/rttui/channel.rs
- probe-rs/src/bin/probe-rs/cmd/dap_server/server/core_data.rs
- probe-rs/src/bin/probe-rs/util/rtt.rs
... and separate data processing out of the channel impl.
> Only read CWD once instead of on every RTT poll event

- changelog/added-dap-server-ip-option.md
- probe-rs/src/bin/probe-rs/cmd/dap_server/mod.rs
- probe-rs/src/bin/probe-rs/cmd/dap_server/server/startup.rs
In certain environments, such as WSL, Visual Studio Code and the probe-rs dap-server may run on separate (virtual) hosts.
To accommodate these scenarios, the probe-rs dap-server requires the ability to bind to an address other than the loopback interface.
This patch adds an `--ip` option for the dap-server subcommand, enabling users to specify the desired binding address.
> Make dap-server bind address configurable

- .github/workflows/smoketest.yml
- probe-rs/targets/esp32c6.yaml
- smoke-tester/README.md
- smoke-tester/src/dut_definition.rs
Previously, esp32c6 and probably other prefix-named chips failed with something like the following:
```
./smoke_tester --dut-definitions duts
For tests, chip definition must be exact. Chip name ESP32C6 matches multiple chips:
esp32c6_lp
esp32c6
Error: Failed to parse definition 'duts/c6.toml'
```
> smoke-tester: normalize chip name to lower case

- probe-rs/src/config/sequences/atsam.rs
Chip erase ended up putting my device into Reset Extension and ReattachRequired was not able to recover from that state. This PR should remedy this error.
> ATSAM: bring out of reset extension

- probe-rs/src/architecture/xtensa/communication_interface.rs
- probe-rs/src/architecture/xtensa/mod.rs
- probe-rs/src/architecture/xtensa/xdm.rs
This PR removes direct debug module control from `XtensaCommunicationInterface`. While this is a breaking change, these functions aren't necessary and even shouldn't be used anyway, but they were left over from the initial development pass.
> Slightly clean up the Xtensa code

- smoke-tester/src/tests.rs
Flashing progress is printed to stderr, but then terminated with a newline to stdout. This sometimes caused the progress dots to be printed after the log, making it look a bit funny. This PR hopefully clears this up. Important, I know.
> smoke-tester: print flashing progress to stdout

- changelog/added-list-break-to-debug.md
- probe-rs/src/bin/probe-rs/cmd/debug.rs
- probe-rs/src/core.rs
I found it helpful to list breakpoints when I'm troubleshooting probe-rs target integration. Here's a little demo, where `>>` denotes the command submitted to `probe-rs debug`:
Core is running.
>> list_break
Core is running.
>> break 0x30001030
Set new breakpoint at address 0x30001030
Core is running.
>> break 0x00001234
Set new breakpoint at address 0x001234
Core is running.
>> list_break
Breakpoint 0 - 0x30001030
Breakpoint 1 - 0x00001234
Core is running.
>> clear_break 0x30001030
Core is running.
>> list_break
Breakpoint 1 - 0x00001234
Core is running.
Notice that we start counting at zero. Furthermore, the user still needs to use the instruction address to clear the breakpoint; they can't clear breakpoints by the breakpoint number.
> Add `list_break` command to debug tool

- Cargo.lock
- target-gen/Cargo.toml
Reverts probe-rs/probe-rs#2399
cargo doc fails: https://github.com/probe-rs/probe-rs/actions/runs/8778261031/job/24084440769
> Revert "Update Rust crate zip to v1"

- probe-rs/src/architecture/riscv/mod.rs
My guess is that my chip (ESP32C2 and likes) are RV32C, but the flash algo encodes a 4-byte EBREAK anyway. This is I believe completely valid, however stepping through half of that EBREAK is not. We could do multiple things: read back the instruction at DPC and decide how much we need to advance it, use a different flash algo header if the chip is RV32C, or what this PR does: remove the shortcut altogether.
I'm hoping the performance implication aren't unbearably bad with this PR
> Fix flashing RISC-V chips after setting breakpoints

- probe-rs/src/architecture/riscv/communication_interface.rs
- probe-rs/src/config/sequences/esp32c3.rs
- probe-rs/src/flashing/flash_algorithm.rs
- probe-rs/src/flashing/flasher.rs
- probe-rs/src/probe/ftdi/mod.rs
- probe-rs/targets/esp32c2.yaml
- probe-rs/targets/esp32c3.yaml
The load-bearing commit is the last one.
- It seems the stack pointer can't point to the last 16 bytes of the RAM for some reason.
- We need to place the data into the same memory region as the loader, to force the stack pointer below the data blocks. (Layout assumes stack is below data if they are in the same region)
@MabezDev [this](https://github.com/esp-rs/esp-flash-loader/blob/353abbe4102785aee214ce38f182d618fdfe08df/src/main.rs#L21) has stopped being true in #2375. The algos still work because I've allocated more space for the decompressor state than what the stacks take up, but I guess the current issue highlights how fragile this is.
Xtensas are unaffected because they ignore the stack pointer calculated by probe-rs.
> Fix flashing ESP32-C2 and C3

- smoke-tester/src/dut_definition.rs
- smoke-tester/src/main.rs
- smoke-tester/src/tests.rs
I'm not entirely sure how the results were supposed to be tallied up but it seems all of them were instead accidentally ignored.
> Smoke tester: do not pass test suite with failing tests

- probe-rs/src/architecture/xtensa/arch/instruction/mod.rs
- probe-rs/src/architecture/xtensa/mod.rs
- probe-rs/src/config/sequences/esp.rs
Xtensa reset sequences may need executing short programs. This PR should plant the seed to implement those in a neater way than just dumping the binary into the source code.
> Simplify writing Xtensa instruction sequences

- changelog/added-armv8a-fast-memory-access.md
- probe-rs/src/architecture/arm/core/armv8a.rs
- probe-rs/src/architecture/arm/core/instructions.rs
- probe-rs/src/memory/mod.rs
Add fast memory access functions for AArch64.
The memory access speed will be about 100 times faster than using current codes.
I compared the memory access speeds using the download command.
The result is about 100 times faster than the master branch.
```
tnishinaga@devubuntu:~/projects/probe-rs$ RUST_LOG=info cargo run --bin probe-rs --features cli download --chip RaspberryPi4B --protocol jtag --speed 1000 /home/tnishinaga/projects/baremetal_raspi4/XX_jtag_startup/target/aarch64-unknown-none/debug/jtag_kernel
skip
INFO probe_rs::flashing::download: Found loadable segment, physical address: 0x00080000, virtual address: 0x00080000, flags: 0x5
INFO probe_rs::flashing::download: Matching section: ".text.boot"
INFO probe_rs::flashing::download: Matching section: ".text"
INFO …
```
> Armv8a: Add fast memory access functions

- probe-rs/src/architecture/arm/communication_interface.rs
- probe-rs/src/architecture/arm/sequences.rs
This PR contains three changes:
- Delays flushing the probe's batched commands. This change breaks RP2040 with CMSIS-DAP probes, which is somewhat intentional. Previously, the probes were working because the power-down request didn't take effect.
- Implements waiting for the de-assertion of the acknowledge bits.
- Only disable DPs when we disconnect. Disable the current DP _and_ all known DPs. This may disable one DP multiple times which shouldn't be an issue, but it will make sure the RP2040's rescue DP is disabled as well.
> Disable all DPs but only when disconnecting

- changelog/added-embed-config-opts.md
- changelog/removed-halt_afterwards.md
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/config/default.toml
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/config/mod.rs
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/mod.rs
- Remove long-deprecated `halt_afterwards`
- Add `verify`
- Add `disable_double_buffering` (https://github.com/probe-rs/probe-rs/issues/1891#issuecomment-2031103939)
> Update Embed.toml flashing options

- .github/workflows/ci.yml
I don't think CI failing on dependency documentation is useful.
> Only check our own documentation

- target-gen/src/commands/elf.rs
I broke this in #2428, sorry about that. The buffer needs to be cleared even if the line is skipped.
> Fix target-gen serialize

- Cargo.lock
- probe-rs-tools/Cargo.toml
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/request_helpers.rs
- probe-rs/Cargo.toml
- probe-rs/src/architecture/arm/ap/generic_ap.rs
- probe-rs/src/architecture/arm/ap/memory_ap/mod.rs
- probe-rs/src/architecture/arm/core/armv7a.rs
- probe-rs/src/architecture/arm/core/exception_handling/armv6m_armv7m_shared.rs
- probe-rs/src/architecture/arm/memory/romtable.rs
- probe-rs/src/debug/language/parsing.rs
- probe-rs/src/debug/variable.rs
- probe-rs/src/probe/jlink/speed.rs
- probe-rs/src/probe/jlink/swo.rs
- probe-rs/src/probe/stlink/constants.rs
- xtask/Cargo.toml
copilot is very eager to generate `from_u8` functions, and it looks like the macro also hid something unused. num-traits remains in the tree indirectly, but I really don't think we need to keep it around just for `.zero()` :)
> Remove direct use of num-traits, remove unused and trivial deps

- changelog/fixed-rust-toolchain.md
- rust-toolchain.toml
removed the patch part of `channel` to enable forwards compatibility (i.e. `channel = "1.77"` as proposed allows Rust 1.77.2, whereas `channel = "1.77.0"` does not)
> Update rust-toolchain.toml to allow patch-level forwards compatibility

- changelog/fixed-debugger-silent-fail.md
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/debugger.rs
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/startup.rs
- probe-rs/src/flashing/progress.rs
Ensure Flash errors, e.g. `No loadable segments were found in the ELF file.` are not  being "swallowed" by the debugger. Before this PR, the debugger session will terminate midway through flashing, with no error displayed to the user.
> Debugger: Propagate `launch`/`attach` errors to the DAP client.

- smoke-tester/src/dut_definition.rs
- smoke-tester/src/main.rs
esp32c2 does not work with the default FTDI speeds. This PR allows setting a different value and should allow me to re-enable testing the target.
> Smoke tester: allow setting probe speed

- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/config/default.toml
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/config/mod.rs
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/mod.rs
- probe-rs-tools/src/bin/probe-rs/cmd/run/mod.rs
- probe-rs-tools/src/bin/probe-rs/util/rtt.rs
- Rename motivated by https://github.com/probe-rs/vscode/pull/90#discussion_r1595789887 - it's not required, but it doesn't hurt to remain consistent.
- I've removed the remaining "default" log format configuration that was missed in #2377
- Removed an unused struct
- Defmt timestamp output now respects `show_timestamps`
I'm hoping the general "changed-embed-toml.md" changelog still applies here so I did not add a new one.
> Rename defmt_log_format to log_format, apply show_timestamps to defmt

- probe-rs/src/session.rs
This PR does two things:
- saves a register read
- extracts reading core status out of a tracing macro. This prevents printing messages for disabled levels
> `halted_access`: Only read cpu status once

- probe-rs/src/probe.rs
`probe_factory` was made private here https://github.com/probe-rs/probe-rs/pull/2238#discussion_r1504263362
However, that was the only way to get a human-readable description of what probe type this probe is. This PR
keeps it private, and adds a method to get the description instead.
> probe: add probe_type() to DebugProbeInfo.

- probe-rs/src/probe.rs
- probe-rs/src/probe/jlink/mod.rs
Before:
```
The following debug probes were found:
[0]: J-Link (J-Link) (VID: 1366, PID: 0101, Serial: 000260113020, J-Link)
```
After:
```
The following debug probes were found:
[0]: J-Link -- 1366:0101:000260113020 (J-Link)
```
It's more compact, and the probe selector is immediately copy-paste-ready.
> Change probe info format

- probe-rs/Cargo.toml
- probe-rs/src/config/mod.rs
- probe-rs/src/config/registry.rs
The new API is crate-public due to reexports (which I don't really like to be fair), so no changelog is included.
> Registry: use parking_lot, allow reading families without cloning them

- probe-rs/src/probe/stlink/mod.rs
> Fix stlink `swj_sequence` typo

- changelog/fixed-cmsis-dap-error-reporting.md
- probe-rs-tools/src/bin/probe-rs/util/common_options.rs
- probe-rs/src/architecture/arm/mod.rs
- probe-rs/src/architecture/arm/sequences.rs
- probe-rs/src/probe.rs
- probe-rs/src/session.rs
I'm working on improving error messages for probe-rs. No more "An ARM specific error has occurred" whilst refusing to elaborate.
> Better error messages for CMSIS-DAP probes

- CONTRIBUTING.md
- README.md
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/mod.rs
* Install target folder is now in probe-rs-tools
* Cargo embed was moved into main repo
> Update docs based on restructuring

- probe-rs-mi/Cargo.toml
mi release failed because of the missing feature: https://github.com/probe-rs/probe-rs/actions/runs/9198611949/job/25301691730
> Add missing features to mi

- changelog/fixed-probe-rs-tools-missing-git-panic.md
- probe-rs-tools/build.rs
If `git` doesn't exist during the build the build script will panic.
It is common not to have `git` installed in isolated build environments, such as docker containers or the nixpkgs sandbox.
> probe-rs-tools: do not panic when missing git

- changelog/added-interactive-probe-selection.md
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/mod.rs
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_flash/diagnostics.rs
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/configuration.rs
- probe-rs-tools/src/bin/probe-rs/util/common_options.rs
When multiple probes are present rather than erroring out allow for a user to input a probe to use from a list of available probes.
Example shell scenario
``` sh
probe-rs run --chip MIMXRT1060 ~/z/zephyr/build/zephyr/zephyr.elf
Available Probes:
0: DAPLink CMSIS-DAP -- 0d28:0204:0229000005d9a56800000000000000000000000097969905 (CMSIS-DAP)
1: J-Link -- 1366:0105:000683676916 (J-Link)
Selection: 0
WARN probe_rs::util::rtt: No RTT header info was present in the ELF file. Does your firmware run RTT?
WARN probe_rs::config::sequences::nxp_armv7m: MIMXRT10xx core type supplied as Armv7m, but the actual core is a Armv7em
Erasing ✔ [00:00:00] [############################################################################################################################################################# …
```
> Add interactive probe selection

- Cargo.toml
- changelog/added-musl.md
This will build binaries that can hopefully run on a raspberry pi. The installer script will still not properly install these because we build with 22.04 (see [this](https://github.com/axodotdev/cargo-dist/issues/519)) but at least a binary should be available.
> Provide prebuilts with musl libc

- probe-rs/src/rtt.rs
- probe-rs/src/rtt/channels.rs
Here I'm hiding a bunch of 32/64bit decision inside the existing structs and also deduplicating some of the code. Other changes include updating some address prints to the `{:#010x}` pattern we use, shortening a message to fix rustfmt, and making some code generally a bit more readable.
I'm also replacing the BTreeMap in Channels with Vec<Option>. The resulting code is a tad bit more complex, but there's really no reason to build a tree here.
> Rtt initialization cleanup

- changelog/fixed-debug-unwind-stops-early.md
- probe-rs/src/debug/debug_info.rs
The unwind processed checked LR against being 0 or max (e.g. 0xFFFF_FFFF for u32). If either condition was true, it would stop trying to unwind. 
In the case of a 0 value, on arm, the Rust compiler sometimes uses LR (register 14) as a scratch, and it is possible to have a legitimate 0 value.
In the case of the max, this was a hangover from when we only supported ARM, and represented the ABI calling standard "reset value". This is not the same for Risc-V.
In addition to being  invalid, neither of these conditions are necessary to control the unwind, as confirmed by manual testing as well as the fairly extensive automated testing we have in this area.
> Fix: Debug unwind stops when LR is zero.

- Cargo.lock
- probe-rs-tools/Cargo.toml
- probe-rs-tools/src/bin/probe-rs/cmd/benchmark.rs
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/mod.rs
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_flash/diagnostics.rs
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_flash/mod.rs
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/dap_types.rs
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/mod.rs
- probe-rs-tools/src/bin/probe-rs/cmd/debug.rs
- probe-rs/Cargo.toml
- probe-rs/examples/ram_download.rs
- probe-rs/src/architecture/arm/component/itm.rs
- probe-rs/src/architecture/arm/component/scs.rs
- probe-rs/src/core/memory_mapped_registers.rs
- probe-rs/src/session.rs
- target-gen/Cargo.toml
- target-gen/tests/extract_pack.rs
Note that the textwrap change may end up changing the default wrap algorithm depending on the outcome of https://github.com/zkat/miette/pull/379 but the effect shouldn't be important.
Also includes parts of https://github.com/probe-rs/probe-rs/pull/2441
The big change is caused by removing rand and crypto crates:
- we don't need it in examples and benchmark, fastrand should be just enough
- we don't currently decompress encrypted ZIPs, which require rand and a bunch of crypto
> Trim dependency features, clean up some code

- probe-rs-tools/src/bin/probe-rs/cmd/run/mod.rs
- probe-rs-tools/src/bin/probe-rs/util/rtt.rs
This looks like an oversight to me, because otherwise there is no way to get timestamps from defmt. Note that setting this to true is not enough to enable timestamps in defmt, the defmt table still needs to have timestamps. Also the default for serde is true.
> Enable timestamps by default in probe-rs

- changelog/added-lpc54102-family.md
- probe-rs/targets/LPC54102.yaml
This commit adds the YAML file generated by the great `target-gen`-tool provided in this repository (using the following command):
```shell
$ target-gen arm -f LPC54102 probe-rs/targets
```
This is a sub-series of the LPC54xxx microcontrollers: the [datasheet] groups the LPC54102 chips of this commit together with the LPC54101- chips, which are different as they don't have a secondary Cortex-M0+- core. Therefore they have a different CMSIS-pack and should be in a separate file.
[datasheet]: https://www.nxp.com/docs/en/data-sheet/LPC5410X.pdf
> Add support for the LPC54102 series

- Cargo.lock
- probe-rs-tools/Cargo.toml
- target-gen/Cargo.toml
The binary only does compression, so I'm removing the decompression-only features as well as unused compression methods.
I don't think we need to work with bzip2 in target-gen, so I'm removing that to get rid of a dependency, but I'm not adamant on this point.
> Trim zip features a bit

- changelog/fixed-cargo-embed-log.md
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/config/default.toml
- probe-rs-tools/src/bin/probe-rs/util/logging.rs
The log level was already optional in code, but had a default value. As RUST_LOG allows more flexible filtering and still defaults to WARN, this PR removes the TOML's default.
The PR also replaces the std RwLock to parking_lot's Mutex, which is somewhat cleaner.
> cargo-embed: Respect RUST_LOG unless configured

- Cargo.lock
- changelog/removed-tracing-log.md
- probe-rs-tools/Cargo.toml
- probe-rs/Cargo.toml
This allows the application to control whether or not it wants log tracing instead of being always enabled by the library crate. probe-rs-tools already specifies this feature.
More context from the Matrix chat: https://matrix.to/#/!vhKMWjizPZBgKeknOo:matrix.org/$ywmxH6VFKCSGCu4mSi-BavtEKc52QQadJ0k55mkw-9g?via=matrix.org&via=chat.berline.rs&via=tchncs.de
> Remove log feature from probe-rs tracing dependency

- probe-rs/Cargo.toml
`cargo-binstall` needs the package to contain a binary. Since `probe-rs` does not, binstall fails regardless of the existence of metadata.
We might be better off updating the instructions again, it seems.
> Remove dysfunctional binstall metadata

- .github/workflows/changelog.yml
- xtask/src/main.rs
Unfortunately as of https://github.com/probe-rs/probe-rs/pull/2504 the xtask can not check new fragments properly from the file system because the checked out sources don't contain the PR's changes.
This PR rewrites changelog checks into two parts:
- local checks that go through all changelog/ files
- PR check that goes through changes in a PR. This also allows commenting back the results, via a switch so the script can be called locally without litering on a PR.
The PR also changes how the github API is called, which means we no longer have to pass the token to it explicitly.
Demo is #2517
> Check new fragments, comment if changelog fragment is invalid

- changelog/fixed-multiple-chip-erase.md
- changelog/fixed-multiple-progress-bars.md
- probe-rs-target/src/memory.rs
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/debugger.rs
- probe-rs-tools/src/bin/probe-rs/cmd/erase.rs
- probe-rs-tools/src/bin/probe-rs/util/flash.rs
- probe-rs/src/flashing/builder.rs
- probe-rs/src/flashing/encoder.rs
- probe-rs/src/flashing/erase.rs
- probe-rs/src/flashing/flasher.rs
- probe-rs/src/flashing/loader.rs
- probe-rs/src/flashing/progress.rs
- target-gen/src/commands/test.rs
I would very much like to print the actual ranges instead of numbers, but we don't have the info for Programming at the point of initialization right now - we only calculate that range right before programming. The flasher does too many things right now for my taste but I don't have the brains to come up with something more suitable.
Also hidden in here is a fix that avoids multiple chip erases.
> Display multiple progress bars if necessary

- probe-rs/Cargo.toml
- probe-rs/build.rs
- probe-rs/src/config/registry.rs
Simplify registry a tiny bit by always deserializing *something*. The impact should be negligible, and I think the result's simplicity is preferable.
Alternative:
Do some of the cleanups in this PR, but make `bincode` optional via `builtin-targets`. This would not change the library code, but allow stripping out a dependency.
> Clean up build script and builtin targets

- probe-rs/src/probe/cmsisdap/commands/transfer/mod.rs
- probe-rs/src/probe/cmsisdap/mod.rs
Shouldn't affect behaviour, except for that one weird bug where the transfer count apparently is not equal to the vector length somehow. That case is now impossible, because I've deleted the transfer count field :)
> Clean up CMSIS-DAP response processing a bit

- changelog/fixed-panic-empty-batch.md
- probe-rs/src/probe/cmsisdap/commands/transfer/mod.rs
- probe-rs/src/probe/cmsisdap/mod.rs
... also fix an issue where aborting the transfer wasn't done correctly: the command was batched and the batch was not executed.
I guess we should get the CMSIS-DAP implementation aligned with arm_debug_interface, there are a few differences in fault/wait handling.
> Do not attempt to execute an empty batch

- changelog/fixed-at32f4.md
- probe-rs/targets/AT32F4_Series.yaml
We currently place stack and data at the end of the memory to allow maximum stack use automatically. This causes problems for devices that have more exotic options like RAM that can be mapped to act as 0 wait cycle flash.
This PR will place the data blocks to the end of the smallest ram in the family. Stack is placed below data, and all flash algos should have around 4-5KB worth of stack.
Closes #2537
> Specify data load address for AT32F4 devices

- changelog/added-hpm5300-series.md
- probe-rs/targets/HPM5300_Series.yaml
This Pull Request adds flash algorithm of the HPM5300 series of MCUs. (HPM53x1, where the last "1" means flash size in MB)
HPM5300 series is a general-purpose microcontroller from HPMicro Semiconductor Co., Ltd.
It uses Andes' D25(F) RISC-V IP core(RV32-IMAFDCPB).
- Flyer(English): [HPM5300.pdf](http://hpmicro.com/Temp/HPM5300.pdf)
- Official Site(Simplified Chinese 中文): [HPM5300](http://hpmicro.com/product/series.html?id=b793ac43-1155-43f8-abf9-33626c063f0e)
The flash algorithm is maintained in <https://github.com/hpmicro-rs/flash-algo> (an unofficial team working on Rust support for HPM MCUs).
While implementing the flash algorithm, the following resources are referenced:
- OpenOCD fork: https://github.com/hpmicro/riscv-openocd
- OpenOCD conf in Official SDK: …
> Add support for HPMicro's HPM5300 series of MCUs

- changelog/added-STM32F205RGEx.md
- probe-rs/targets/STM32F0_Series.yaml
- probe-rs/targets/STM32F1_Series.yaml
- probe-rs/targets/STM32F2_Series.yaml
This adds STM32F205RGEx, adds names to memory regions and includes some flash algo changes. While the names don't match #2556 I really did not want manually delete a million new strings especially that the names aren't the only change.
> Update STM32F0,F1,F2 from packs

- changelog/added-memory-access.md
- changelog/changed-is-boot-memory.md
- probe-rs-target/src/lib.rs
- probe-rs-target/src/memory.rs
- probe-rs/src/flashing/builder.rs
- probe-rs/targets/STM32F4_Series.yaml
- smoke-tester/src/tests/stepping.rs
- target-gen/src/commands/elf.rs
- target-gen/src/generate.rs
STM32F4 CCM RAM does not seem to be executable. This causes problems with the smoke tester, which downloads stepping code into the first RAM section it finds.
> Add memory access attributes

- probe-rs/targets/nRF51_Series.yaml
I've chosen to drop the 822 over the 422, based on data in the nRF51 compatibility matrices.
Interesting how serde doesn't care about the duplicate.
> Remove duplicate nrf51 entry

- target-gen/src/commands/elf.rs
The way target-gen trims unnecessary fields is a bit simplistic. Since `access` has some true-by-default fields, those fields need to be added as exceptions to this trimming.
> Improve/fix target-gen cutting off the wrong defaults

- changelog/added-cargo-embed-path.md
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/mod.rs
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_flash/mod.rs
It's an unthinkable sin that cargo-flash has this option, but not cargo embed. I wanted to use this today to test something, so here we go.
> Add `--path` to cargo embed

- changelog/added-chip-to-target-gen-test.md
- probe-rs-tools/src/bin/probe-rs/util/common_options.rs
- probe-rs/src/config/registry.rs
- target-gen/Cargo.toml
- target-gen/src/commands/test.rs
- target-gen/src/generate.rs
- target-gen/src/main.rs
Added `--chip` in case the tested description contains multiple chips. Cleaned up a few unnecessary `.clone()`s.
This PR undoes https://github.com/probe-rs/probe-rs/pull/1771/files#diff-a54dca91b1c085f16d7b7e573bb96cb37cf95a32fe5716a5b8a825571d45ecf7R66 which tried to flash generic targets for some reason. The PR also adds (back?) the known targets, so `only_supported_familes` has something to compare against.
> Some minor target-gen improvements

- changelog/changed-rtt-attach.md
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/mod.rs
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/core_data.rs
- probe-rs-tools/src/bin/probe-rs/cmd/run/mod.rs
- probe-rs-tools/src/bin/probe-rs/util/rtt.rs
- probe-rs/src/flashing/flasher.rs
- probe-rs/src/rtt.rs
- probe-rs/src/rtt/channel.rs
- rtthost/src/main.rs
`Core` already contains the target's memory map. This PR changes RTT code to use this map, which is actually an improvement in the sense that from now on RTT shouldn't try to access memory that the core itself can't access.
> Remove redundant memory map from RTT constructors

- probe-rs-target/src/memory.rs
- probe-rs/src/config/mod.rs
- probe-rs/src/config/registry.rs
- probe-rs/src/config/target.rs
- probe-rs/src/flashing/error.rs
- probe-rs/src/flashing/flash_algorithm.rs
- probe-rs/src/flashing/flasher.rs
- probe-rs/targets/LPC800_Series.yaml
- probe-rs/targets/STM32WL_Series.yaml
Includes (or will include) fixes made to targets that fail the validation.
- Set stack size for a small target
- Implement memory region merging for targets where we can't place the algorithm in a single block of RAM.
- Rename application core of STM32WL55JCIx to main
- Remove runtime family validation from Target
> Validate that flash algos can be constructed

- changelog/fixed-mimxrt10xx-stack-size.md
- probe-rs/targets/MIMXRT1010.yaml
- probe-rs/targets/MIMXRT1015.yaml
- probe-rs/targets/MIMXRT1020.yaml
- probe-rs/targets/MIMXRT1050.yaml
- probe-rs/targets/MIMXRT1060.yaml
- probe-rs/targets/MIMXRT1064.yaml
The new stack overflow checks (#2599) caught (at least) a 16 byte overflow in the 1010 flashing algorithm. To avoid this possibility for other users, this commit doubles stack sizes for most MIMXRT10xx targets. The 1050 already specified a 4K stack size for the Hyperflash algorithm, so I'm applying the same size for the QuadSPI algorithm.
I tested against a 1010 target, and I'm guessing the stack sizes for the remaining MCUs. CC @teburd @cstrahan just in case the 1K stack size isn't enough for a 1060.
> Increase stack sizes for MIMXRT10xx targets

- changelog/fixed-writing-riscv-rtt.md
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/rttui/app.rs
- probe-rs-tools/src/bin/probe-rs/util/rtt.rs
- probe-rs/src/architecture/riscv/communication_interface.rs
- probe-rs/src/architecture/riscv/mod.rs
I'm not sure if this is specific to esp32c2, but writing memory while running just throws errors. As far as I understand, the chip has no background memory access, even though reading seems to work just fine.
> Risc-V: halt core before writing memory

- changelog/added-cargo-embed-tab.md
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/rttui/app.rs
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/rttui/tab.rs
Maybe, hopefully :) This PR adds key bindings in the form of `ctrl+number` and `(shift)+tab` to switch between tabs.
PgUp/Down now scrolls more, and one-line scrolls can be done with up/down arrows.
> cargo-embed: better tab navigation and scrolling

- probe-rs/src/rtt.rs
At the latest, `RttControlBlockHeader::try_from_header` will check whether enough bytes are available. We are already relying on this check to catch undersized scan areas, if the magic string is located at any offset > 0.
> RTT: Remove redundant check

- probe-rs/src/architecture/arm/mod.rs
- probe-rs/src/probe/arm_debug_interface.rs
- probe-rs/src/session.rs
- probe-rs/src/vendor/mod.rs
It was quite impossible for probe-rs to detect anything non-ARM (an esp32c2 in this case), because the process errored before getting that far. This PR turns errors into "no chip found" situations, as well as avoids spamming the user with a particular error when using a bitbanging probe.
> Fix a bunch of chip-detection bugs

- changelog/added-name-to-test.md
- target-gen/src/commands/elf.rs
- target-gen/src/commands/test.rs
- target-gen/src/main.rs
target-gen no longer tries to update a hard-coded `algorithm-test` algorithm. Instead, the name is inferred from the .elf's file stem, or can be specified by the user
> Do not hardcode algorithm name in `target-gen test`

- probe-rs/Cargo.toml
- probe-rs/build.rs
- probe-rs/src/config/registry.rs
Small speedup if the built-in targets are disabled, couple of seconds maybe.
> Make bincode optional, disable build deps when not needed

- probe-rs-tools/src/bin/probe-rs/cmd/itm.rs
- probe-rs/src/architecture/arm/core/armv6m.rs
- probe-rs/src/architecture/arm/core/armv7a.rs
- probe-rs/src/architecture/arm/core/armv7m.rs
- probe-rs/src/architecture/arm/core/armv8a.rs
- probe-rs/src/architecture/arm/core/armv8m.rs
- probe-rs/src/architecture/arm/sequences.rs
- probe-rs/src/architecture/riscv/communication_interface.rs
- probe-rs/src/architecture/xtensa/communication_interface.rs
- probe-rs/src/architecture/xtensa/mod.rs
- probe-rs/src/architecture/xtensa/xdm.rs
- probe-rs/src/flashing/flasher.rs
- probe-rs/src/probe/ftdi/mod.rs
- probe-rs/src/vendor/infineon/sequences/xmc4000.rs
- probe-rs/src/vendor/microchip/sequences/atsam.rs
- probe-rs/src/vendor/nxp/sequences/nxp_armv7m.rs
- probe-rs/src/vendor/nxp/sequences/nxp_armv8m.rs
Apparently, when CPU load is high, test-before-loop can cause timeouts without giving the loop at least one chance to complete successfully.
> Align some timeout loops to be test-after-loop

- probe-rs/targets/GD32F10x_Series.yaml
- probe-rs/targets/LPC800_Series.yaml
- probe-rs/targets/STM32WL_Series.yaml
- probe-rs/targets/esp32.yaml
- probe-rs/targets/esp32c2.yaml
- probe-rs/targets/esp32c3.yaml
- probe-rs/targets/esp32c6.yaml
- probe-rs/targets/esp32h2.yaml
- probe-rs/targets/esp32s2.yaml
- probe-rs/targets/esp32s3.yaml
- target-gen/src/commands/elf.rs
- target-gen/src/fetch.rs
- target-gen/src/generate.rs
- target-gen/src/lib.rs
- target-gen/src/main.rs
target-gen has a few functions I want to use in https://github.com/bugadani/stm-probers.
> target-gen: split out library, update output cleaner

- probe-rs/src/flashing/loader.rs
The goal is to make vendor implementations able to register their own image formats. clap and serde will make this slightly complicated, but one piece of the puzzle is to create object-safe loaders like these.
> Extract ImageLoaders from FlashLoader

- probe-rs/targets/VA416xx_Series.yaml
- Better naming for memory regions
- Introduce `VA416xx_RAM` variant where region 0x0-0x40000 is marked as Ram instead of Nvm. These regions are aliased for the VA416xx target.
> Update VA416xx YAML file

- Cargo.lock
- target-gen/Cargo.toml
- target-gen/tests/extract_pack.rs
I don't think 2 uses in target-gen warrant the dependency and its tree and right now it's holding up renovate.
> Remove assert_cmd

- probe-rs/targets/STM32G0_Series.yaml
- probe-rs/targets/STM32G4_Series.yaml
The main change is the removal of STM32GBK1CBTx
This update also undoes #2061 so I'm very much uncomfortable with immediately pushing it in.
@jrmoulton can I please ask you to test that the PR doesn't unfix the STM32G431KBU?
@dlaw did you manage to get any additional information from Keil? The pack update is newer than your bug report so I'm hoping this is more correct than the previous one.
Rebased on top of #2677
> Update G0 and G4

- changelog/changed-stm.md
- probe-rs/targets/STM32C0_Series.yaml
- probe-rs/targets/STM32F0_Series.yaml
- probe-rs/targets/STM32F1_Series.yaml
- probe-rs/targets/STM32F2_Series.yaml
- probe-rs/targets/STM32F3_Series.yaml
- probe-rs/targets/STM32F4_Series.yaml
- probe-rs/targets/STM32F7_Series.yaml
- probe-rs/targets/STM32G0_Series.yaml
- probe-rs/targets/STM32G4_Series.yaml
- probe-rs/targets/STM32H5_Series.yaml
- probe-rs/targets/STM32H7RS_Series.yaml
- probe-rs/targets/STM32H7_Series.yaml
- probe-rs/targets/STM32L0_Series.yaml
- probe-rs/targets/STM32L1_Series.yaml
- probe-rs/targets/STM32L4_Series.yaml
- probe-rs/targets/STM32L5_Series.yaml
- probe-rs/targets/STM32U0_Series.yaml
- probe-rs/targets/STM32U5_Series.yaml
- probe-rs/targets/STM32WB_Series.yaml
- probe-rs/targets/STM32WL_Series.yaml
Generated using https://github.com/bugadani/stm-probers - this uses embassy/stm32-data with minimal exceptions (affecting STM32WB) and one modification: I'm re-merging flash regions, because we don't need to know about the different erase granularities.
Updated everything except WBA ([waiting for author on pack update](https://github.com/probe-rs/probe-rs/pull/2612))
Rebased on top of #2632
> Update STM32 memory regions

- changelog/added-arm-debug-sequence-for-stm32-armv8.md
- probe-rs/src/vendor/st/mod.rs
- probe-rs/src/vendor/st/sequences/mod.rs
- probe-rs/src/vendor/st/sequences/stm32_armv8.rs
Add arm debug sequence for stm32-armv8
This PR implements ArmDebugSequence for stm32-armv8, since  DBGMCU_CR of stm32-armv8 (stm32l5, stm32u5) is slightly different than the one for stm32-armv7
> Add arm debug sequence for stm32-armv8

- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/repl_commands.rs
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/core_data.rs
- probe-rs/src/architecture/arm/component/itm.rs
- probe-rs/src/core/memory_mapped_registers.rs
- probe-rs/src/debug/debug_info.rs
- probe-rs/src/debug/debug_step.rs
- probe-rs/src/debug/function_die.rs
- probe-rs/src/debug/source_instructions.rs
- probe-rs/src/debug/unit_info.rs
- probe-rs/src/debug/variable.rs
- probe-rs/src/rtt.rs
- rust-toolchain.toml
Clippy now checks indentation in documentation, because why not. PR includes a few drive-by fixes, too.
> Update to rustc 1.80.0 and fix clippy

- Cargo.lock
- probe-rs/Cargo.toml
- probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs
- probe-rs/src/probe/jlink/bits.rs
This sets up the necessary fixture for `tracing` to print during tests
(if the appropriate env variable is set)
> add test-log to dev-deps

- probe-rs/src/architecture/arm/mod.rs
This avoids duplication of the documentation
Follows:
- https://github.com/probe-rs/probe-rs/pull/2701
> arm: use docsplay::Display for ArmError

- changelog/changed-factorize-MemoryInterface-slight-variations.md
- probe-rs/src/architecture/arm/core/armv6m.rs
- probe-rs/src/architecture/arm/core/armv7a.rs
- probe-rs/src/architecture/arm/core/armv7m.rs
- probe-rs/src/architecture/arm/core/armv8a.rs
- probe-rs/src/architecture/arm/core/armv8m.rs
- probe-rs/src/architecture/arm/core/mod.rs
- probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs
- probe-rs/src/architecture/arm/mod.rs
- probe-rs/src/error.rs
- probe-rs/src/memory/mod.rs
- probe-rs/src/probe/fake_probe.rs
- probe-rs/src/probe/stlink/mod.rs
Probe-rs implements in several locations quasi identical version of `probe_rs::memory::MemoryInterface`.
This factorizes (some of) these ocurrences and reduces code duplication.
While doing this, it was noted that the default implementation of `MemoryInterface::write` didn’t pass all `architecture::arm::memory::adi_v5_memory_interface::test::*`. This fixes the issue by moving the implementation from `AdiMemoryInterface::write` back to `MemoryInterface`.
Follows:
- https://github.com/probe-rs/probe-rs/pull/2704
> Factorize memory interfaces implementations

- probe-rs-target/src/chip.rs
- probe-rs-target/src/lib.rs
- probe-rs-tools/src/bin/probe-rs/main.rs
- probe-rs/src/config/registry.rs
- probe-rs/src/config/target.rs
- probe-rs/src/flashing/download.rs
- smoke-tester/src/tests.rs
- target-gen/src/commands/snapshots/target_gen__commands__elf__test__serialization_cleanup.snap
If we ever end up having vendor-specific image formats, we can't hard-code them into the target YAMLs. Instead, we store their names and validate it as part of the builtin target validation.
This PR also removes a deprecated alias that was used by the VSCode plugin.
---
The end goal is to split up format and platform support. The plan is to keep a hard-coded set of formats, and an extensible set of platforms - "raw" and IDF being the first two of these platforms. Targets may declare a default platform, but the default image format should be dictated by the platform - and right now both should default to `Elf`.
The platform support code would receive something analogous to the current `Format`, file reader/path, `FlashLoader` and `Session`. "raw" would just load the image to `FlashLoader`, …
> Remove hardcoded BinaryFormat from target descriptors

- changelog/changed-use-FullyQualifiedApAddress-instead-of-MemoryAp-and-GenericAp.md
- probe-rs-tools/src/bin/probe-rs/cmd/info.rs
- probe-rs/src/architecture/arm/communication_interface.rs
- probe-rs/src/architecture/arm/component/mod.rs
- probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs
- probe-rs/src/architecture/arm/memory/romtable.rs
- probe-rs/src/architecture/arm/mod.rs
- probe-rs/src/architecture/arm/sequences.rs
- probe-rs/src/config/target.rs
- probe-rs/src/core/core_state.rs
- probe-rs/src/probe/fake_probe.rs
- probe-rs/src/probe/stlink/mod.rs
- probe-rs/src/session.rs
- probe-rs/src/vendor/infineon/mod.rs
- probe-rs/src/vendor/microchip/mod.rs
- probe-rs/src/vendor/microchip/sequences/atsam.rs
- probe-rs/src/vendor/nordicsemi/mod.rs
- probe-rs/src/vendor/nordicsemi/sequences/nrf.rs
- probe-rs/src/vendor/nordicsemi/sequences/nrf52.rs
- probe-rs/src/vendor/nordicsemi/sequences/nrf91.rs
- probe-rs/src/vendor/nxp/sequences/nxp_armv7m.rs
- probe-rs/src/vendor/nxp/sequences/nxp_armv8m.rs
- probe-rs/src/vendor/st/sequences/stm32_armv6.rs
- probe-rs/src/vendor/st/sequences/stm32_armv7.rs
- probe-rs/src/vendor/st/sequences/stm32_armv8.rs
- probe-rs/src/vendor/st/sequences/stm32h7.rs
- probe-rs/src/vendor/ti/sequences/cc13xx_cc26xx.rs
- probe-rs/src/vendor/vorago/sequences/va416xx.rs
- Those two type do not provide much value beyond being attached to a set
of registers.
- GenericAp can be converted to MemoryAp without checks.
Follows:
- https://github.com/probe-rs/probe-rs/pull/2708
> arm: Use FullyQualifiedApAddresses rather than GenericAp or MemoryAp

- probe-rs/src/debug/debug_info.rs
- probe-rs/src/debug/unit_info.rs
- probe-rs/src/debug/variable.rs
C-style enums were handled recursively, and mixed with the handling of structs and variables. To simplify this, the enum variants are now handled separately, to make the code easier to follow.
The larger goal is to try and reduce the use of the variable cache for things where we only create temporary entries.
> Refactor handling of debug information for C-style enums

- probe-rs/src/debug/unit_info.rs
Prevents #2687 from crashing, now an error will be returned if an array doesn't have any sub ranges.
But keeping that bug open, so that we can hopefully find the root cause.
> Refactor handling of array debug information

- changelog/added-stlink-v3pwr.md
- probe-rs/src/probe/stlink/mod.rs
- probe-rs/src/probe/stlink/usb_interface.rs
This PR adds support for [ST-Link V3PWR](https://www.st.com/en/development-tools/stlink-v3pwr.html).
Simply adding PID 0x3787 to the USB PID map doesn't make the probe work because it reports its version as `V4` instead of `V3`(e.g. `V4J5B1P5`).
This PR makes `hw_version >= 4` probes treated as the same with `hw_version == 3`.
> STLink: Add support for V3PWR

- changelog/added-ADuCM302x-family.md
- probe-rs/targets/ADuCM302x_Series.yaml
I generated a YAML file for the ADuCM302x series of devices and tested the result with a ADuCM3029 and JLink. Please let me know if this commit is lacking anything required as this is my first time contributing to this project. I have some confusion on how to define the memory when flash can be configured a few different ways, but kept the default layout as given by the pack file.
> Added aducm302x target support

- changelog/added-core-disabled.md
- probe-rs/src/architecture/xtensa/communication_interface.rs
- probe-rs/src/architecture/xtensa/mod.rs
- probe-rs/src/architecture/xtensa/sequences.rs
- probe-rs/src/architecture/xtensa/xdm.rs
- probe-rs/src/core/core_state.rs
- probe-rs/src/error.rs
- probe-rs/src/probe.rs
- probe-rs/src/probe/common.rs
- probe-rs/src/session.rs
- probe-rs/src/vendor/espressif/sequences/esp32.rs
- probe-rs/src/vendor/espressif/sequences/esp32s2.rs
- probe-rs/src/vendor/espressif/sequences/esp32s3.rs
- probe-rs/src/vendor/mod.rs
- probe-rs/targets/esp32.yaml
- probe-rs/targets/esp32s3.yaml
- In some places, we forgot to switch jtag taps, so we probably missed initializing some things or worked with the wrong core in places. (Or would have, if the second cores were defined)
- If the debugger writes the PC or resets the core, do not restore cached registers. (We might need to do this for all cores, but let's cross that bridge when we get to it)
- Make sure that the BreakIn/BreakOut interfaces are enabled on Xtensa
- Fiddle with logs a bit
- Use Session in the connect sequence
- Do not immediately die if a core is not enabled
- re-add the second core definitions
> Some improvements for better multicore ESP32 support

- probe-rs/src/flashing/flash_algorithm.rs
- probe-rs/src/vendor/espressif/mod.rs
Fixes a regression introduced in https://github.com/probe-rs/probe-rs/commit/3e65a72256e76ec3e26b95e8efb4159b2fff4dfd that prevents flashing ESP32 (and maybe others)
> Fix accidentally ignoring data_load_address

- probe-rs/src/probe/arm_debug_interface.rs
These bits are most likely unnecessary, OpenOCD does not add them.
> SWD: Remove two idle bits

- probe-rs/src/probe.rs
- probe-rs/src/probe/cmsisdap/commands/mod.rs
- probe-rs/src/probe/cmsisdap/mod.rs
- probe-rs/src/probe/espusbjtag/protocol.rs
- probe-rs/src/probe/ftdi/ftdaye/error.rs
- probe-rs/src/probe/ftdi/mod.rs
- probe-rs/src/probe/jlink/error.rs
- probe-rs/src/probe/stlink/mod.rs
- probe-rs/src/probe/stlink/usb_interface.rs
- probe-rs/src/probe/wlink/mod.rs
Use the probe-specific errors internally more, replace the generic probe firmware error with probe-specific variants.
Probe-specific errors can now be downcast to concrete error types, which I hope will make it simpler to inspect ProbeSpecificError variants.
Somewhat experimental and we might reuse the AnyShim idea for other trait-upcasting-at-home tasks (like Probe -> concrete probe impl)
> Probe error related cleanups

- changelog/changed-esp32.md
- probe-rs/targets/esp32.yaml
cc @MabezDev @SergioGasquez
I'm still mildly uncomfortable here but maybe fearing an invisible monster hurts more than it helps right now. Keeping the target's name aligned with the actual HAL feature name has some benefits that I want to build on.
cc #2756
> Rename ESP32 and add chip detection info

- Cargo.lock
- probe-rs-target/src/flash_algorithm.rs
- probe-rs/Cargo.toml
- probe-rs/src/flashing/encoder.rs
Renovate has some trouble updating miniz_oxide, and our dependencies all use flate2, so why not do it in probe-rs, too. I'm keeping the transfer encoding as `Miniz` for no good reason, but we can rename it to zlib as well if we want to.
> Use flate2 instead of directly using miniz_oxide

- probe-rs/src/architecture/riscv/communication_interface.rs
The Xtensa changes have no effect, they are there mostly for consistency and general "looks right"-ness.
This PR is meant to reduce the intrusiveness of probe-rs but it also increases flashing speed of ESP32-C2 by a bit less than 10% (tested locally). C3 is surprisingly less affected, while C6 is less affected too, but in that case it is expected - we don't halt the C6 to read memory from it.
> Speed up halting RISC-V cores

- probe-rs/src/vendor/espressif/mod.rs
https://github.com/probe-rs/probe-rs/pull/2755 introduced a regression that meant the chip was no longer using the correct reset sequence. Oops.
> Fix ESP32 target sequence

- probe-rs/src/architecture/xtensa/communication_interface.rs
- probe-rs/src/architecture/xtensa/mod.rs
- probe-rs/src/architecture/xtensa/xdm.rs
- probe-rs/src/session.rs
- probe-rs/src/vendor/espressif/sequences/esp32.rs
- probe-rs/src/vendor/espressif/sequences/esp32s2.rs
- probe-rs/src/vendor/espressif/sequences/esp32s3.rs
This PR should allow batching up more JTAG commands, although it doesn't really have any visible effect for e.g. flashing speed.
Queue utilisation for RTT polling:
```
before
core status
Executing 2 commands
read pointers
Executing 8 commands
Executing 14 commands
Executing 10 commands
core status
Executing 2 commands
read pointers
Executing 8 commands
Executing 14 commands
Executing 10 commands
read buffer
Executing 8 commands
Executing 12 commands
Executing 10 commands
write pointer
Executing 8 commands
Executing 12 commands
Executing 10 commands
after
core status
Executing 2 commands
read pointers
Executing 22 commands
Executing 10 commands
core status
Executing 2 commands
read pointers
Executing 22 commands
Executing 10 commands
read buffer
Executing 22 commands
Executing 10 commands …
```
> Xtensa: slight efficiency improvements

- probe-rs/src/architecture/riscv/communication_interface.rs
- probe-rs/src/vendor/espressif/mod.rs
- probe-rs/src/vendor/espressif/sequences/esp32c2.rs
- probe-rs/src/vendor/espressif/sequences/esp32c3.rs
Reverts the halting parts of #2748. I can't seem to be able to reproduce the weird memory reading errors that I had with these devices, and we've fixed the RTT attaching issues since then.
> Undo the halting hack for ESP32-C2/C3

- changelog/added-digilent-probes
- probe-rs/src/probe/ftdi/ftdaye/mod.rs
- probe-rs/src/probe/ftdi/mod.rs
This change sets different FTDI pin layouts depending on which probe is detected, which is required to support Digilent HS* JTAG probes.
The layout is determined by the `vendor_id`, `product_id`, and `product_string`. The product description is required because the USB `vendor_id` and `product_id` are not enough to identify Digilent probes (e.g. Digilent HS2 & HS3 are the same).
I have several Digilent JTAG probes that are based on FTDI chips, but they did not work as expected when tested with probe-rs. After digging into the FTDI module, I found that probe-rs [defaults the pin configurations](https://github.com/probe-rs/probe-rs/blob/7dfe7ae8f8d5b5f1d3e6a698aad488edac4e92ef/probe-rs/src/probe/ftdi/mod.rs#L78-L83) to `output: 0x0008, direction: 0x000b`. However, the Diligent probes …
> Add support for Digilent probes

- changelog/added-riscv-jtag-tunnel.md
- probe-rs-target/src/chip.rs
- probe-rs-target/src/lib.rs
- probe-rs/src/architecture/riscv/communication_interface.rs
- probe-rs/src/architecture/riscv/dtm/jtag_dtm.rs
- probe-rs/src/session.rs
This change adds `TunneledJtagDtm` in `architecture::riscv::dtm::jtag_dtm` that allows access to a RISC-V target through a JTAG tunnel with a configurable instruction and data register width. Additionally, this change adds `attached_tunneled` and `attach_auto` in `RiscvInterfaceBuilder` to allow `Session` to use a tunnel if configured on the `Target`.
The JTAG tunnel is configurable in YAML for a variant like this:
```yaml
jtag:
riscv_tunnel:
ir_id: 0x23
ir_width: 6
```
I've tested it with a VexRiscv soft-core running on a Xilinx XC7A200T using a Digilent HS3 probe.
It's common to use a JTAG tunnel to access RISC-V soft-cores running on FPGAs. A tunnel allows using the same cable for configuring the FPGA and debug access to the soft-core within. The simple protocol was originally created …
> Add support for tunneled JTAG access to RISC-V targets

- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/mod.rs
- probe-rs-tools/src/bin/probe-rs/cmd/run/mod.rs
- probe-rs/src/flashing/loader.rs
Without this change, probe-rs clears the RTT header after downloading and resetting a target. When downloading to and running from flash memory, this is fine since the startup code in flash will put the RTT header back into RAM. However, when downloading to RAM, the RTT header stays cleared and prevents RTT from working.
This change detects whether any flash memory was written during the download. If so, then it clears the RTT header like before. Otherwise if only RAM was written, then it does not clear the header.
I was trying to get defmt_rtt to work with a VexRiscv soft-core on a FPGA, but no data was showing up. Debug logs showed that probe-rs was repeatedly looking for the Segger RTT header, but only finding zeros at the expected address.
When I tried rtt_target (without defmt), it …
> Fix RTT when downloading to RAM

- changelog/added-privileged-bit-to-amba_apb4_apb5.md
- probe-rs/src/architecture/arm/ap/memory_ap/amba_apb4_apb5.rs
This bit is the lower bit of `PPROT[2:0]` and there are cases where it must be set. Add it to the CSW register.
> arm: add `Privileged` bit to amba_apb4_apb5

- changelog/added-support-tiva-c.md
- probe-rs/targets/Tiva_C_Series.yaml
Added the Tiva-C Series Targets with the yaml generated by the cmsis-pack. Also see [Issue  #2779](https://github.com/probe-rs/probe-rs/issues/2779)
> Added Tiva C targets

- probe-rs/src/architecture/riscv/communication_interface.rs
- probe-rs/src/vendor/espressif/mod.rs
- probe-rs/src/vendor/espressif/sequences/esp32c2.rs
- probe-rs/src/vendor/espressif/sequences/esp32c3.rs
This reverts commit 0fb93950ed1e4ff507b6dd472d4634f0a9878ac8 from PR "Undo the halting hack for ESP32-C2/C3 (#2769)"
> Fix ESP32-C3 once again

- probe-rs/src/architecture/riscv/assembly.rs
- probe-rs/src/architecture/riscv/communication_interface.rs
- probe-rs/src/vendor/espressif/mod.rs
- probe-rs/src/vendor/espressif/sequences/esp.rs
- probe-rs/src/vendor/espressif/sequences/esp32.rs
- probe-rs/src/vendor/espressif/sequences/esp32c2.rs
- probe-rs/src/vendor/espressif/sequences/esp32c3.rs
- probe-rs/src/vendor/espressif/sequences/esp32c6.rs
- probe-rs/src/vendor/espressif/sequences/esp32h2.rs
- probe-rs/src/vendor/espressif/sequences/esp32s2.rs
- probe-rs/src/vendor/espressif/sequences/esp32s3.rs
Call `spi_attach_flash` like how the flasher calls functions, instead of progbuf.
> Simplify ESP flash attach and handle SPI config where needed

- probe-rs-tools/src/bin/probe-rs/util/flash.rs
Before:
```
Running `target\debug\probe-rs.exe run C:\_Hobby\rpi-smoke-tester-setup\embedded-test\esp-hal\output\esp32s2`
Erasing ✔ [00:00:01] [########################################] 192.00 KiB/192.00 KiB @ 189.88 KiB/s (eta 0s )
Programming ✔ [00:00:02] [############################################] 27.95 KiB/27.95 KiB @ 9.52 KiB/s (eta 0s )
Finished in 2.9602304s
```
After:
```
Running `target\debug\probe-rs.exe run C:\_Hobby\rpi-smoke-tester-setup\embedded-test\esp-hal\output\esp32s2`
Erasing ✔ [00:00:01] [###################################] 192.00 KiB/192.00 KiB @ 189.35 KiB/s (ETA 00:00:00)
Programming ✔ [00:00:02] [###################################]  27.95 KiB/ 27.95 KiB @   9.53 KiB/s (ETA 00:00:00)
Finished in 2.96s
```
- Changed the display format of ETA, and Finished
- …
> Make progress bars constant width

- changelog/fixed-riscv-unwind.md
- probe-rs/src/debug/debug_info.rs
- probe-rs/src/debug/exception_handling.rs
- probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__esp32c3_full_unwind.snap
This should fix stack traces for Risc-V ESP32 devices. It also helps with Xtensa to resolve the function name of `abort`.
> Adjust PC for Xtensa and RiscV

- changelog/fixed-xtensa-unwind.md
- probe-rs/src/debug/debug_info.rs
- probe-rs/src/debug/exception_handling.rs
- probe-rs/src/debug/exception_handling/xtensa.rs
- probe-rs/src/debug/unit_info.rs
The Xtensa enabled rustc doesn't seem to emit the debuginfo necessary for unwinding. However, we can implement an architecture-specific frame-pointer chasing to at least get a full backtrace without any more details.
This PR allows other architectures to implement similar schemes by moving the fallback unwinding method into `ExceptionInterface`.
> Unwind: Xtensa: follow frame pointer

- probe-rs/src/probe/espusbjtag/protocol.rs
This won't change anything, really, just avoids panics like the following:
```
thread 'main' panicked at probe-rs\src\probe\espusbjtag\protocol.rs:374:9:
Output buffer too large: 153 elements, max 128
```
These happen if we return a USB error, so the device has most likely restarted unexpectedly, but at least we'll properly display a USB error instead.
> Ensure that we can't queue more bits than the buffer can hold

- changelog/fixed-halting.md
- probe-rs-tools/src/bin/probe-rs/cmd/read.rs
- probe-rs-tools/src/bin/probe-rs/cmd/run/mod.rs
- probe-rs/src/session.rs
Fixes #2799 (at least for me). Processing the elf can take multiple 100ms, and I guess the C6 just doesn't tolerate being halted for so long.
I think maybe we should resume cores before we return from `Session::new` but I was worried about side effects.
> Resume cores before parsing elf data

- changelog/added-semihosting-stdout.md
- changelog/changed-semihosting.md
- probe-rs-tools/src/bin/probe-rs/cmd/run/mod.rs
- probe-rs-tools/src/bin/probe-rs/cmd/run/normal_run_mode.rs
- probe-rs-tools/src/bin/probe-rs/cmd/run/test_run_mode.rs
- probe-rs/src/architecture/arm/core/cortex_m.rs
- probe-rs/src/architecture/arm/core/mod.rs
- probe-rs/src/architecture/riscv/mod.rs
- probe-rs/src/architecture/xtensa/mod.rs
- probe-rs/src/core/core_status.rs
- probe-rs/src/lib.rs
- probe-rs/src/semihosting.rs
If there is already a semihosting command cached, the previous code read PC, read around the PC, and then did nothing. This PR removes these reads, while making additional cleanups.
This PR also implements limited handling of SYS_OPEN, SYS_CLOSE and WRITE to allow the `semihosting` crate to print panic messages.
> Semihosting: print to console

- changelog/added-api-to-disable-pc-sample-in-arm.md
- probe-rs/src/architecture/arm/component/dwt.rs
This PR adds an API to disable pc sampling in ARM, as it is done with data trace and exception trace
> Add API to disable PC sample in ARM

- probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__atsamd51p19a_static_variables.snap
- probe-rs/src/debug/unit_info.rs
- probe-rs/src/debug/variable.rs
- Handle the `DW_AT_specification` attributes
- Store the linkage name (I'm using this in some tests in another branch of mine, to handle some variables with duplicate names
> Various debugger improvements

- changelog/fixed-is-some-and.md
- probe-rs-tools/src/bin/probe-rs/main.rs
- probe-rs/src/debug/source_instructions.rs
- probe-rs/src/debug/variable.rs
- target-gen/src/generate.rs
- target-gen/src/main.rs
`bool::is_some_and()` better carries the meaning of the operation being done, and is stable since Rust 1.70.0.
> Use `bool::is_some_and()` rather than `bool::map_or(false, …)`

- changelog/added-embed-config-file.md
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/config/mod.rs
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/mod.rs
Closes: https://github.com/probe-rs/probe-rs/issues/2845
I went with --config-file because the profile selected is called `config` in the code, and having a different option called "config" would be quite confusing; config-file is expected to be rarely used, so let's just be explicit.
<del>Keeping this as a draft while waiting for CI to confirm tests (locally, many failed).</del>
> embed: Add --config-file parameter

- probe-rs/targets/CH32V3_Series.yaml
The ch32v305 variant differs from ch32v307 in flash and ram. Add a target with half the amount of flash and ram according to the datasheet.
> target/ch32v3: add ch32v305 variant

- changelog/added-warn-rtt-channel-name.md
- probe-rs/src/rtt/channel.rs
When using probe-rs to access a target's RTT stream with an incomplete target description (missing memory map), channel names will not be read, resulting in all content being presented as raw strings instead of interpreting e.g. defmt.
If this happens, it is almost certainly by mistake, so issue a warning.
> Add warning when refusing to read RTT channel name

- changelog/added-rt1189.md
- probe-rs/src/architecture/arm/ap/mod.rs
- probe-rs/src/architecture/arm/communication_interface.rs
- probe-rs/src/architecture/arm/sequences.rs
- probe-rs/src/vendor/nxp/mod.rs
- probe-rs/src/vendor/nxp/sequences/nxp_armv7m.rs
- probe-rs/src/vendor/nxp/sequences/nxp_armv8m.rs
- probe-rs/targets/MIMXRT1180.yaml
The chip requires authentication before the DP can be accessed. This is not implemented here, so unlocking has to be done with external tools for now.
This change allows `probe-rs read` and `probe-rs write` to work on an already unlocked chip, but more work is needed to get e.g. `probe-rs download` working.
The existing strategy for AP discovery (probing every AP until one fails) does not work with this chip. Attempting to read IDR from AP5 causes the whole DP to lock down and require re-authentication. The existing strategy is turned into a default that can be overridden by debug sequences.
The target description is heavily cut down from the target-gen output to avoid hitting currently unsupported features like memory access through the AP for the M7.
> Add support for MIMXRT118x M33 memory access

- Cargo.lock
- changelog/added-black-magic-probe-support.md
- probe-rs/Cargo.toml
- probe-rs/src/probe.rs
- probe-rs/src/probe/blackmagic/arm.rs
- probe-rs/src/probe/blackmagic/mod.rs
- probe-rs/src/probe/list.rs
This adds initial support for using a Black Magic Probe with probe-rs.
This initial commit adds basic support for JTAG and SWD. The probe is operated using bit-bang commands, so it is very slow right now. JTAG in particular is operating bit-by-bit.
Future patches will increase performance.
```
$ cargo run -- info --probe 1d50:6018:97B6DC14
Compiling probe-rs-tools v0.24.0 (/Users/seancross/Code/probe-rs/probe-rs-tools)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 2.55s
Running `target/debug/probe-rs info --probe '1d50:6018:97B6DC14'`
Probing target via JTAG
ARM Chip with debug port Default:
Debug Port: DPv0, DP Designer: <unknown>
└── 0 MemoryAP (AmbaAhb3)
└── ROM Table (Class 1), Designer: STMicroelectronics
├── Cortex-M4 SCS   (Generic IP component)
│   └── CPUID
│ …
```
> probe-rs: add initial support for black magic probe

- probe-rs-tools/src/bin/probe-rs/cmd/complete.rs
This PR checks if the parent folders are missing when creating the completions, and if they are, it creates them.
It also checks if the completions folder is in the `FPATH` variable, and if not, adds it to `.zshrc`.
Not sure if it's necessary to add an entry in the changelog folder for this; I can create one if you'd like.
> Check if completions folder exists before writing

- changelog/fixed-hnonsec.md
- probe-rs/src/architecture/arm/ap/memory_ap/amba_ahb3.rs
- probe-rs/src/architecture/arm/ap/memory_ap/amba_ahb5.rs
- probe-rs/src/architecture/arm/ap/memory_ap/amba_ahb5_hprot.rs
Some MCUs appear to have HNONSEC set to non-privileged mode by default. Because ADIv5 calls for HNONSEC to be privileged (that is, false) by default when the bit is implemented, let's default to that for AHB3 and AHB5 interconnects.
Fixes #2788
> probe-rs: arm: memory_ap: Default HNONSEC to !SPIDEN

- changelog/changed-register-names-lowercase.md
- probe-rs/src/gdb_server/target/desc/data.rs
lldb requires the "pc" register to be lower-case. A capital "PC" confuses it to a point where it thinks it is not debugging at all.
This was already the case for RISC-V. For consistency, I feel it's better to simply lower-case every register.
Confirmed that armv6-m and risc-v debugging now works just fine with lldb (tested on Raspberry Pi Pico and esp32c6).
Also confirmed that gdb debugging still works fine - register names are now lower-case of course.
> Make gdb-server compatible with lldb

- changelog/fixed-bash-completion-install.md
- probe-rs-tools/src/bin/probe-rs/cmd/complete.rs
The completion installation for Bash was calling the ZSH install method. Use the correct Bash install method.
Tested by running`probe-rs complete install` and confirming the expected file is created.
> Shell completion: Use correct install method for Bash completions.

- changelog/removed-arm-flash-header.md
- probe-rs/src/architecture/arm/assembly.rs
- probe-rs/src/architecture/arm/mod.rs
- probe-rs/src/flashing/flash_algorithm.rs
This drops the ARM flash header down to a simple breakpoint.
The original flash algo header was introduced [at the start of the project (`FLASH_BLOB_HEADER`)](https://github.com/bobrippling/probe-rs/commit/ac2676604ab8d9c838995413334a0b3d88f95188), likely taken from elsewhere, similarly to `pyocd`.
Going off [the discussion at pyocd], all but the first instruction are unnecessary. They were originally part of a checksum, but now the flash algorithms just jump to the start of the header to trigger a breakpoint, to halt the core when they're done.
This change preserves the 32-bit wide instructions by using two breakpoints.
The only mention of CRCs (which is the dropped algo code) is in 4e4c1675f, which was removed in 26c9b07a3 and 4dda1fc14, so I'm confident this is dead code.
[the …
> flash algorithm: drop unnecessary ARM instructions

- changelog/added-cores-to-conjured-regions.md
- probe-rs/src/config/target.rs
- probe-rs/src/flashing/loader.rs
I found this was necessary to execute a flash algorithm for an external memory lacking an explicit NvmRegion in the YAML.
> Assign cores to NvmRegions created from flash algorithms

- changelog/added-manufacturer-code.md
- probe-rs/targets/CC13XX_CC26XX_Series.yaml
This is an attempt to fix the manufacturer filtering on the website https://github.com/probe-rs/webpage/issues/152
If this is how it should be solved, I can add it to more of the files!
> Add manufacturer code to fix filtering on website

- probe-rs/src/probe/common.rs
Some devices return `10100` during JTAG IR scan. Previously, the `n_taps == 1` case was supposed to handle these, but the ESP32-P4 will have two JTAG TAPs, and the IR scan is `1010010000`. This PR essentially special-cases the 101 prefix to support such devices.
> `extract_ir_lengths`: handle 101x IR scans

- probe-rs/targets/HC32F005-Series.yaml
- probe-rs/targets/PAC52XX_Series.yaml
- probe-rs/targets/PAC55XX_Series.yaml
This adds a few more manufacturer codes that were just added to jep106.
This improves website filtering issue: https://github.com/probe-rs/webpage/issues/152
Previous PR: https://github.com/probe-rs/probe-rs/pull/2892
Still some manufacturers missing that are not in JEP106, WCH for example. Not sure what to do about them? Discoverability is poor when I go to the website to check if WCH supports my chip and the manufacturer is not in the list.. That's was how I ended up here in the first place.. (Maybe this is not the best place to discuss? I'll add this comment to the issue too)
> Add more manufacturer codes

- changelog/fixed-esp32s2-s3-swdt.md
- probe-rs/src/vendor/espressif/sequences/esp32h2.rs
- probe-rs/src/vendor/espressif/sequences/esp32s2.rs
- probe-rs/src/vendor/espressif/sequences/esp32s3.rs
H2 TRM is incorrect, values are updated from ESP-IDF. There is one more config register in the H2 that is not taken into account in the documentation, offsetting every address after by 4.
> Disable SWDT, fix H2

- probe-rs/src/flashing/flasher.rs
879c53e wants to prevent us from loading flash algorithms multiple times.  However, the commit never marked the algos as loaded. This commit marks the algorithms as loaded if it ever succeeded. I observed no issues with this commit when testing on an MIMXRT1170.
For MIMXRT1170 users, this removes a warning about "no program in flash" observed during flashing. As of this commit, the tool stops issuing subsequent resets that would detect the previously-erased flash.
> Mark lazy-loaded flash algos as loaded

- changelog/fixed-timeout-cortex-m-reset-system.md
- probe-rs/src/architecture/arm/sequences.rs
Previously `continue` on `Err` bypassed timeouting logic.
> Fix timeout in cortex_m_reset_system

- probe-rs/src/architecture/riscv/communication_interface.rs
- probe-rs/src/flashing/flasher.rs
- probe-rs/src/probe/espusbjtag/protocol.rs
A bit fuzzy but reduces error rate considerably. No changelog since we broke it in this cycle.
Bug is a side-effect of #2839
> Fix `--restore-unwritten` with espusbjtag

- changelog/added-nrf54.md
- probe-rs/targets/nRF54_Series.yaml
Current status: 
- flashing, running RTT etc all work. 
- No recover implementation yet. If APPROTECT trips, you have to do `nrfjprog --recover` to get rid of it.
- Ignoring the riscv core for now.
Uses algo from https://github.com/embassy-rs/nrf54l-flash-algo
Something interesting is nrf54l uses RRAM, not flash. You can directly write words anywhere,
changing both 0->1 and 1->0 bits. There's no page/sector erase operation.
I've made the erase implementation a nop in the flash algo. Do we have a better way of dealing
with NVMs like these?
> Add nRF54L15.

- changelog/added-support-domant-sequence-as-fallback-for-swdv2-targets.md
- probe-rs/src/architecture/arm/sequences.rs
* Previously the code assumed that the dormant sequence was only present/needed on Multidrop devices. This is not the case.
* Now we try to setup the debug port and wake the device using the SWDv1 method and fallback to the dormant sequence if this fails
* All credit to @konkers  https://github.com/konkers/probe-rs/commit/37660106aba307cbab5cf6c2b0da57b72b6dc4e9
> arm: Fall back on SWDv2 wake from dormant on SWDv1 failure

- probe-rs-target/src/flash_algorithm.rs
- probe-rs-tools/src/bin/probe-rs/cmd/debug.rs
- probe-rs/src/architecture/arm/component/tmc.rs
- probe-rs/src/architecture/arm/core/armv6m.rs
- probe-rs/src/architecture/arm/core/armv7a.rs
- probe-rs/src/architecture/arm/core/armv7m.rs
- probe-rs/src/architecture/arm/core/armv8a.rs
- probe-rs/src/architecture/arm/core/armv8m.rs
- probe-rs/src/architecture/arm/memory/romtable.rs
- probe-rs/src/architecture/arm/swo/mod.rs
- probe-rs/src/architecture/riscv/mod.rs
- probe-rs/src/architecture/xtensa/communication_interface.rs
- probe-rs/src/architecture/xtensa/mod.rs
- probe-rs/src/core.rs
- probe-rs/src/debug/debug_info.rs
- probe-rs/src/debug/function_die.rs
- probe-rs/src/debug/stack_frame.rs
- probe-rs/src/debug/unit_info.rs
- probe-rs/src/flashing/flasher.rs
- probe-rs/src/probe/blackmagic/mod.rs
- probe-rs/src/probe/cmsisdap/mod.rs
- probe-rs/src/probe/jlink/swo.rs
- probe-rs/src/vendor/microchip/sequences/atsam.rs
- rust-toolchain.toml
- target-gen/src/generate.rs
Mostly automatic fixes, biggest change is a simplification of the lifetime in the `FunctionDie` struct.
> Fix clippy warnings added in 1.83, update Rust version in CI

- Cargo.lock
- changelog/changed-defmt-decoder-v0.4.0.md
- probe-rs-tools/Cargo.toml
- probe-rs-tools/src/bin/probe-rs/cmd/run/mod.rs
- probe-rs-tools/src/bin/probe-rs/util/rtt.rs
This PR upgrades to `defmt-decoder v0.4.0`. While it is a breaking change it only adds a variant to an enum which was not marked as `non_exhaustive` before.
Additionally this release removed the `unstable` feature. This means that we gonna uphold semver from now on.
Opening this as a draft PR, because I want to ensure this release works for probe-rs, before actually making the release. Can you please review and if it works for you, I will make the release and will update the PR from the git to the crates.io version?
> Upgrade to defmt-decoder v0.4.0

- changelog/fixed-blackmagic-write-alignment.md
- probe-rs/src/probe/blackmagic/arm.rs
This is a fix for bug #2941.
When sending large data _via_ several write commands to a Black Magic probe, make sure the data is split in chunks whose length is a multiple of the word size, otherwise the probe will reject the command.
> Blackmagic write word-aligned chunks

- changelog/fixed-blackmagic-connect-under-reset.md
- probe-rs/src/probe/blackmagic/mod.rs
The `--connect-under-reset` command uses the `swj_pins()` function which this platform previously didn't support. Since this platform generally cannot manually set the pins, this returned an error `CommandNotSupportedByProbe`.
However, it does support setting the reset pin directly.
Allow `swj_pins()` to succeed if and only if the only selected pin is the nRST pin.
> blackmagic: support connect-under-reset

- changelog/fixed-nrf-debug-sequence-on-bmp.md
- probe-rs/src/vendor/nordicsemi/sequences/nrf.rs
- probe-rs/src/vendor/nordicsemi/sequences/nrf53.rs
- probe-rs/src/vendor/nordicsemi/sequences/nrf91.rs
This fixes the nrf91 sequence for the BMP probe by removing of accessing
the memory_interface. Accessing this interface before the cores results
in a non-function debug sequence.
Fixes #2944
> fix: nrf91 sequence on BMP

- changelog/added-api-to-configure-itm.md
- probe-rs/src/architecture/arm/component/itm.rs
This PR adds a few public functions to the ITM implementation that help with enabling/disabling:
- DWT packet forwarding
- Synchronization packets
- Local timestamp packets
- Stimulus registers
It could also serve as a base if the `probe-rs itm` command is ever extended to support packet
configuration flags (e.g. `--disable-dwt-forwarding`).
> Extend the ITM api to support packet configuration

- changelog/fixed-jlink-cmsis-dap-detection.md
- probe-rs/src/probe/jlink/mod.rs
Improve the detection of J-Link probes configured
as CMSIS-DAP compatible probes.
Some variants of the J-Link probe can be configured to provide
a CMSIS-DAP compatible interface instead. These probes were still
detect as J-Link compatible by probe-rs. To fix this, the product
ID is now checked as well when looking for J-Links, not only the
vendor ID.
> fix: Improve detection of J-Link CMSIS-DAP

- .github/workflows/release_crates.yml
A workaround for the behaviour described in https://github.com/probe-rs/probe-rs/pull/2964.
By default, pushing a tag from a workflow doesn't trigger a workflow, this should be a workaround.
> Manually set github token when running the crates release flow

- changelog/added-libtest-ignored-flags.md
- probe-rs-tools/src/bin/probe-rs/cmd/run/test_run_mode.rs
The libtest framework allows adding `#[ignore]` to a test, which a libtest compatible harness should list when getting the `--ignored` flag.
I found this when trying to wrap the runner with `nextest`.
This just needed wiring up to work (literally three lines, too bad I missed the release).
E.g., for [this test](https://github.com/kaspar030/ariel-os/blob/pr/integrate-embedded-test/examples/testing/tests/example_test.rs), the output without `--ignored` becomes this:
```
❯ probe-rs run '--protocol=swd' --chip nrf52840_xxAA --preverify /home/kaspar/src/own/rust/ariel-os/examples/testing/../../build/bin/nrf52840dk/testing/cargo/thumbv7em-none-eabi/debug/deps/example_test-9af699a2b54d0715 --list --format terse
Finished in 1.67s
tests::trivial_async: test
tests::trivial: test …
```
> probe-rs-tools: support `--ignored` and `--include-ignored` libtest options

- changelog/fixed-progressbar-eta.md
- probe-rs-tools/src/bin/probe-rs/util/flash.rs
In 0.25 there are improved progress bars, but they don't get reset properly.
This means the ETA of e.g. the programming is wrong since the bar has been started since the erasing has been started which can be a long time before.
This fixes that!
> Reset progress bar ETA and elapsed on start of that bar

- changelog/fixed-memory-port-enable-check.md
- probe-rs-tools/src/bin/probe-rs/cmd/info.rs
- probe-rs/src/architecture/arm/ap/memory_ap/amba_ahb3.rs
- probe-rs/src/architecture/arm/ap/memory_ap/amba_ahb5.rs
- probe-rs/src/architecture/arm/ap/memory_ap/amba_ahb5_hprot.rs
- probe-rs/src/architecture/arm/ap/memory_ap/amba_apb2_apb3.rs
- probe-rs/src/architecture/arm/ap/memory_ap/amba_apb4_apb5.rs
- probe-rs/src/architecture/arm/ap/memory_ap/amba_axi3_axi4.rs
- probe-rs/src/architecture/arm/ap/memory_ap/amba_axi5.rs
- probe-rs/src/architecture/arm/ap/memory_ap/mod.rs
- probe-rs/src/architecture/arm/ap/mod.rs
- probe-rs/src/architecture/arm/communication_interface.rs
- probe-rs/src/architecture/arm/sequences.rs
This seems to have changed at some point, version 0.24.0 had that check.
Might be useful to have this check at a more general place, this is not only an issue for the `info` command.
> bugfix: Don't try to access disabled MemoryAPs in the info command

- changelog/added-extra-rtt-check.md
- probe-rs/src/rtt/channel.rs
Added extra checks for RTT control block integrity so partially trashed blocks are now more likely to be rejected as corrupted.
Fixes #2969 
This was a fun one to figure out! Learned a lot about the flashing parts of probe-rs.
It was a coincidence that 0.24 worked. Here's the rundown:
- Device had already run and so has an RTT block at 0x2000_0000
- Target yaml specifies a load_address of 0x2000_0020
- Flash header and instructions are written to RAM
- In 0.24 arm flash header was 32 bytes and was thus put at 0x2000_0000
- In 0.25 arm flash header is 4 bytes and was thus put at 0x2000_001C
- Flashing process is done and the chip is rebooted into its new firmware
- RTT is trying to be attached to
- The U0 is a slow chip. RTT attach is before the device has set up RTT
- In 0.24 probe-rs …
> Added extra checks for RTT control block integrity

- probe-rs/src/architecture/arm/ap/memory_ap/amba_ahb3.rs
- probe-rs/src/architecture/arm/ap/memory_ap/amba_ahb5.rs
- probe-rs/src/architecture/arm/ap/memory_ap/amba_ahb5_hprot.rs
- probe-rs/src/architecture/arm/ap/memory_ap/amba_apb2_apb3.rs
- probe-rs/src/architecture/arm/ap/memory_ap/amba_apb4_apb5.rs
- probe-rs/src/architecture/arm/ap/memory_ap/amba_axi3_axi4.rs
- probe-rs/src/architecture/arm/ap/memory_ap/amba_axi5.rs
- probe-rs/src/architecture/arm/ap/memory_ap/mod.rs
- probe-rs/src/architecture/arm/communication_interface.rs
- probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs
- probe-rs/src/architecture/arm/memory/mod.rs
- probe-rs/src/architecture/arm/sequences.rs
- probe-rs/src/probe/blackmagic/arm.rs
- probe-rs/src/probe/fake_probe.rs
- probe-rs/src/probe/stlink/mod.rs
- probe-rs/src/session.rs
- probe-rs/src/vendor/infineon/sequences/xmc4000.rs
- probe-rs/src/vendor/microchip/sequences/atsam.rs
- probe-rs/src/vendor/mod.rs
- probe-rs/src/vendor/nxp/sequences/nxp_armv8m.rs
- Remove the need for `ArmMemoryInterface` to implement `SwdSequence`, the sequences using it now just create a memory interface, if they need one
- read_chip_info_from_rom_table seems to be doing the same for all the probes, so one implementation of it should be enough.
> Cleanup ArmMemoryInterface and ROM table search

- changelog/fixed-adi-sticky-err.md
- probe-rs-tools/src/bin/probe-rs/cmd/info.rs
- probe-rs/src/probe/arm_debug_interface.rs
We didn't clean the sticky error bit after all failing SWD transfers, which meant that the code basically got stuck in state where all future transactions failed.
This PR adds cleanup for the bit-banging code for the ARM Debug Interface.
> Clear sticky error after SWD fault

- changelog/fixed-regression-usb-timeout.md
- probe-rs/src/probe/cmsisdap/commands/mod.rs
Fixes #2995
The regression was introduced with PR #1842, when we moved from **rusb** to **nusb**.
I have only tested it on Windows.
> Fix regression in USB timeout handling

- changelog/added-lpc80x-sequences.md
- probe-rs/src/vendor/nxp/mod.rs
- probe-rs/src/vendor/nxp/sequences/mod.rs
- probe-rs/src/vendor/nxp/sequences/nxp_armv6m.rs
This target (unlike most other LPC chips) requires special handling during reset.
I ported the CMSIS-PACK sequences across, and now the existing flash algo for this chip works correctly.
> Add NXP LPC80x sequence

- changelog/changed-probe-selector.md
- probe-rs/src/probe.rs
Not all FTDI-based probes have EEPROMs to store a serial number. One such example is the ESP32 ethernet devkit. However, `esp-prog` boards use the same FTDI chip, but have the EEPROM, so they can have serial number.
This PR means that from now on, these two devices can be present in a system at the same time, and probe-rs can now work with the ethernet devkit, too.
> Allow explicitly selecting probes without serial

- changelog/fixed-mimxrt-reset.md
- changelog/fixed-mimxrt10xx-flashing.md
- probe-rs/src/vendor/nxp/sequences/nxp_armv7m.rs
We'll need this for the same reasons we need it on the MIMXRT10xx parts (see #3014): changing the FlexRAM layout while a program is accessing FlexRAM will cause trouble. Tested on systems carrying an 1170 MCU.
> Halt the MIMXRT11xx before changing FlexRAM

- .github/workflows/v-release.yml
- Cargo.lock
- dist-workspace.toml
- probe-rs-debug/Cargo.toml
- probe-rs-tools/Cargo.toml
- probe-rs/Cargo.toml
- smoke-tester/Cargo.toml
- target-gen/Cargo.toml
- Update colored to v3
- Use correct features for insta
- Update cargo-dist to version 0.28.0
> chore: Fix features for insta, update cargo-dist to 0.28.0

- changelog/fixed-inherited-access.md
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/peripherals/svd_variables.rs
When working with ATSAM SVDs, most of the peripherals don't have their `access` field specified, and thus are not retrieved.
A device-wide `access` is present and the SVD spec says that register and fields should inherit from the device value: https://arm-software.github.io/CMSIS_5/SVD/html/elem_special.html#registerPropertiesGroup_gr
This PR tries to check for this device-wide value when looking for registers and fields `access` property.
I didn't take the time to explore the whole code base, so I'm not sure if there is any other place where a change would be necessary.
The way I tested that is to load an SVD when debugging an ATSAM MCU in VSCode with the `probe-rs` extension and navigate through the `peripherals` list.
> Inherit access configuration from device if any

- changelog/fixed-svd-alignment.md
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/peripherals/svd_cache.rs
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/peripherals/svd_variables.rs
Some 8-bits registers in the ATSAM family are aligned to the byte and not 32-bits words, thus returning a `MemoryNotAligned` error.
This PR provides a safe way to read those smaller registers (and similarly, fields) without reading others that might be read-protected.
Since there are no mechanism to read single bit without reading at least a whole byte AFAIK, I don't think there is a safe way of reading only parts of a register if any of its field is read-protected. In this PR we don't care about this case (I'm not sure there are any examples in the SVDs I'm having right now) and still read the whole byte/bytes.
This has been tested in addition to https://github.com/probe-rs/probe-rs/pull/3040 and works in the same test conditions.
> Fix SvdVariable alignment when reading

- changelog/fixed-looping-unwind.md
- probe-rs-debug/src/debug_info.rs
I hit a case where unwinding ended up in an infinite loop. This PR works around that issue.
> Unwind: work around an infinite loop

- changelog/added-black-magic-probe-reinitialize.md
- probe-rs/src/probe/blackmagic/arm.rs
- probe-rs/src/probe/stlink/mod.rs
Implement `ArmProbeInterface::reinitialize()` for `BlackMagicProbeArmDebug`. This should get it working to the same level as the standard `ArmCommunicationInterface`.
> blackmagic: implement reinitialize()

- changelog/fixed-c-language-64bits-support.md
- probe-rs-debug/src/language/c.rs
Fixes #3046 
Added 64-bits variable formatting for the C language:
- int64_t
- uint64_t
- double
I have not been able to get a 128b variable in my 32bits MCU, apparently GCC supports the type only for 64b targets hence I did not added support to them.
NOTE: I found it weird that a `u64` comes in as `long long unsigned int, but it seems to be according to the standard: https://en.wikipedia.org/wiki/C_data_types
Based on the wiki table, I wander if `unsigned long long` (without `int`) and variants would be a valid match here?
> fix(c-language): added 64b values formatting

- probe-rs-debug/src/debug_info.rs
- probe-rs-debug/src/exception_handling.rs
- probe-rs-debug/src/exception_handling/armv6m.rs
- probe-rs-debug/src/exception_handling/armv6m_armv7m_shared.rs
- probe-rs-debug/src/exception_handling/armv7m.rs
- probe-rs-debug/src/exception_handling/xtensa.rs
- probe-rs-debug/src/registers.rs
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__RP2040_full_unwind.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__RP2040_svcall.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__RP2040_systick.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__atsamd51p19a.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__nRF52833_xxAA_full_unwind.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__nRF52833_xxAA_hardfault_from_busfault.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__nRF52833_xxAA_hardfault_from_usagefault.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__nRF52833_xxAA_hardfault_in_systick.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__nRF52833_xxAA_svcall.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__nRF52833_xxAA_systick.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__print_stacktrace.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__unwinding_in_exception_handler.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__unwinding_in_exception_trampoline.snap
- probe-rs/src/architecture/arm/core/registers/cortex_m.rs
This changes the general flow of unwinding to better handle exceptions. The existing code first checked for an exception, before using the unwind information from the debug information. This is wrong if we're inside an exception handler which modifies the stack pointer. In such a case, we first have to unwind to the call site of the exception handler, and only then can we check for an exception.
- When unwinding an exception, ensure that we get a program counter pointing to the calling instruction, not one to the next instruction to be executed after returning from the exception. This is achieved by subtracting one from the PC.
> Improve exception unwinding

- probe-rs/src/flashing/erase.rs
- probe-rs/src/flashing/flasher.rs
- probe-rs/src/flashing/loader.rs
The long-term plan with this PR is to allow the RPC implementation to reuse a FlashLoader object, to not require compressing an image three times - once for preverification, once for programming and once for verification. This PR makes the inner Flasher storable, and only creates it once per program/verify call. It's not the whole story, just a step toward it.
The PR should not have user-facing changes.
> Mildly refactor Flasher/FlashLoader

- probe-rs/src/architecture/arm/ap_v2/root_memory_interface.rs
- probe-rs/src/architecture/arm/dp/mod.rs
> Updating ADIv6 root memory interface to enumerate without BASEPTR registers

- probe-rs/src/rtt/channel.rs
RTT name was read before it was checked to be located within expected memory range. It was causing errors when RTT block corrupted.
> Fix RTT channel init

- changelog/added-mcxa-support.md
- probe-rs/src/vendor/nxp/mod.rs
- probe-rs/src/vendor/nxp/sequences/mcx.rs
- probe-rs/src/vendor/nxp/sequences/mod.rs
- probe-rs/targets/MCXA.yaml
This PR add supports for parts of NXP MCXA series MCUs. Test passed on FRDM-MCXA276 and FRDM-MCXA166.
Created a new source file `mcx.rs` rather than `nxp_armv8m.rs`, because MCX series will include non-armv8m chips.
The other series like `MCXN`, `MCXC` and etc are also under development, will raise other PRs later.
> Add Support for NXP MCXA Series MCUs.

- changelog/fixed-flashing-mass-erased-efm32xg2.md
- probe-rs/src/architecture/arm/sequences.rs
- probe-rs/src/vendor/silabs/sequences/efm32xg2.rs
The generic reset sequence from `cortex_m_reset_system` fails for flashing mass-erased devices. This custom sequence does the trick in this case.
Previously as of 999a3597:
```
$ commander-cli device masserase
Erasing chip...
Flash was erased successfully
DONE
$ cargo run --release -- download --chip EFM32PG22C200F512IM40 test.elf
Finished `release` profile [optimized] target(s) in 0.14s
Running `target/release/probe-rs download --chip EFM32PG22C200F512IM40 test.elf`
WARN probe_rs::architecture::arm::core::armv8m: The core is in locked up status as a result of an unrecoverable exception
WARN probe_rs::architecture::arm::core::armv8m: The core is in locked up status as a result of an unrecoverable exception
WARN probe_rs::architecture::arm::core::armv8m: The core is in locked up status as …
```
> Use custom reset sequence for EFM32xG2 devices

- probe-rs/Cargo.toml
Should fix the [docs build error](https://docs.rs/crate/probe-rs/0.27.0/builds/1731882)
```
[INFO] [stderr] error: the package 'probe-rs' does not contain this feature: debug
```
> Remove debug docsrs feature

- changelog/fixed-xtensa-reattach.md
- probe-rs/src/architecture/xtensa/mod.rs
- probe-rs/src/architecture/xtensa/xdm.rs
This PR should recognise if a core is shut down unexpectedly - it should be impossible as per Xtensa debug docs, but apparently not. We should now correctly return CoreDisabled for such cores if we can't reconnect.
> Xtensa: try to reattach if debug domain is powered down

- changelog/fixed-rtt-no-name.md
- probe-rs/src/rtt/channel.rs
This PR removes a redundant check. We don't attach if the name pointer is not valid, and we also don't read the name pointer again, so this check is doubly unnecessary, and also causes problems because the name pointer is allowed to be null.
> Allow RTT channels without names

- probe-rs/src/probe/stlink/mod.rs
- probe-rs/src/probe/stlink/usb_interface.rs
For some reason I have two STM32F051 discovery kits with st-links that have empty serial numbers. (read: they show up as `[0]: STLink V2 -- 0483:3748: (ST-LINK)` - I probably broke them). These devices work with probe-rs 0.27, but not with master.
> Work with st-links without serial

- changelog/changed-defmt-default.md
- changelog/fixed-defmt.md
- probe-rs-tools/src/bin/probe-rs/cmd/attach.rs
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/config/mod.rs
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/mod.rs
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/rttui/app.rs
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/rttui/channel.rs
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/rttui/tab.rs
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/dap_types.rs
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/core_data.rs
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/debug_rtt.rs
- probe-rs-tools/src/bin/probe-rs/cmd/run.rs
- probe-rs-tools/src/bin/probe-rs/main.rs
- probe-rs-tools/src/bin/probe-rs/rpc/client.rs
- probe-rs-tools/src/bin/probe-rs/rpc/functions.rs
- probe-rs-tools/src/bin/probe-rs/rpc/functions/flash.rs
- probe-rs-tools/src/bin/probe-rs/rpc/functions/monitor.rs
- probe-rs-tools/src/bin/probe-rs/rpc/functions/rtt_client.rs
- probe-rs-tools/src/bin/probe-rs/rpc/functions/test.rs
- probe-rs-tools/src/bin/probe-rs/rpc/utils/run_loop.rs
- probe-rs-tools/src/bin/probe-rs/util/cli.rs
- probe-rs-tools/src/bin/probe-rs/util/rtt.rs
- probe-rs-tools/src/bin/probe-rs/util/rtt/client.rs
- probe-rs-tools/src/bin/probe-rs/util/rtt/processing.rs
- probe-rs/src/rtt.rs
- probe-rs/src/rtt/channel.rs
This PR builds on top of the RPC PR and moves RTT processing from the server to the client. This mainly means the firmware doesn't need to be uploaded for monitoring operations. I'm also fixing a bug where the defmt processor couldn't deal with data arriving split into multiple reads, and I'm also changing the default log format to "oneline" because it's just so much more readable.
Closes #2981
> Rework the RTT processing code

- probe-rs-tools/src/bin/probe-rs/util/rtt/processing.rs
This PR prevents emitting empty strings from `RttDecoder`, fixing a cargo-embed issue where text was scrolling without anything being actually printed by the target.
> Skip processing empty RTT buffers

- changelog/added-config-presets.md
- probe-rs-tools/src/bin/probe-rs/main.rs
This PR adds a primitive way to define config presets. A preset is just a list of CLI arguments that will be added to the arguments unless they are already preset. A preset may look like this in the config file:
```toml
[presets]
esp32c2 = { probe = "0403:6010:FT929K8X", speed = 15000 }
```
And they can be applied as `probe-rs <command> --preset esp32c2` for example.
Presets are key-value pairs, or `flag = true/false` flags. The schema isn't checked, but we don't just use strings to allow external tools to define a schema for the config.
> Support config presets that can modify the CLI arguments

- probe-rs/src/gdb_server/target/monitor.rs
I don't see any reason why we need to convert them to a string just for matching, so let's try not.
> Match monitor commands as they are

- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
- probe-rs/src/architecture/arm/dp/mod.rs
- probe-rs/src/architecture/arm/memory/adi_memory_interface.rs
- probe-rs/src/architecture/arm/sequences.rs
- probe-rs/src/architecture/riscv/assembly.rs
- probe-rs/src/architecture/riscv/communication_interface.rs
- probe-rs/src/architecture/riscv/mod.rs
- probe-rs/src/architecture/xtensa/arch/instruction/format.rs
- probe-rs/src/architecture/xtensa/arch/instruction/mod.rs
- probe-rs/src/probe/blackmagic/mod.rs
- probe-rs/src/probe/cmsisdap/commands/transfer/mod.rs
- probe-rs/src/probe/cmsisdap/mod.rs
- probe-rs/src/probe/espusbjtag/protocol.rs
- probe-rs/src/probe/wlink/mod.rs
- probe-rs/src/vendor/espressif/sequences/esp32c2.rs
- probe-rs/src/vendor/espressif/sequences/esp32c3.rs
- probe-rs/src/vendor/espressif/sequences/esp32c6.rs
- probe-rs/src/vendor/espressif/sequences/esp32h2.rs
- rust-toolchain.toml
Updates the Rust version to 1.85, and fixes the new clippy warnings.
Prepares for updating the edition.
> Use Rust 1.85

- probe-rs-tools/src/bin/probe-rs/cmd/serve.rs
- probe-rs-tools/src/bin/probe-rs/main.rs
- The outermost Config no longer has `deny_unknown_fields` so the same config is valid even without the `remote` feature. This is a QoL change for my own sanity.
- Server configuration is now grouped into a single structure. This means `[[server_users]]` becomes `[[server.users]]` in the config TOML, for example.
- The PR adds `port` and `address` under the server configuration.
> Allow configuring server port and address

- changelog/fixed-rtt-in-run-loop.md
- probe-rs-tools/src/bin/probe-rs/rpc/functions/monitor.rs
- probe-rs-tools/src/bin/probe-rs/rpc/functions/test.rs
- probe-rs-tools/src/bin/probe-rs/rpc/utils/run_loop.rs
- probe-rs-tools/src/bin/probe-rs/util/rtt/client.rs
This PR fixes a - maybe somewhat theoretical - error where between embedded-test runs, the RTT channel modes are reset. This issue may affect tests that are run from RAM, otherwise the RTT control block is reset and reconfigured upon the next connection.
The PR refactors RTT polling by distancing it from the run loop itself, allowing us to maybe support different transports in the future, as well as to make the run loop more extensible if needed.
> Runloop tweaks

- probe-rs/src/probe/stlink/mod.rs
The changes made to `probe-rs info` mean that now we try to unconditionally scan through known DPs. This resulted in hitting an ST-Link assertion for some devices, which I think is not ideal.
The result was that calling `probe-rs info` on these devices could just error like this:
```
❯ cargo probe-rs info --preset stm32u545re --protocol swd
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.54s
Running `target\debug\probe-rs.exe info --preset stm32u545re --protocol swd`
Probing target via SWD
----------------------
WARN postcard_rpc::host_client::util: in_worker: wire receive error, exiting
WARN probe_rs::rpc::client: Failed to read topic
Error while probing target: Connection closed
```
> ST-Link: do not panic when trying to initialize with multidrop DP address

- changelog/added-psoc-62.md
- probe-rs-target/src/chip_detection.rs
- probe-rs/src/vendor/infineon/mod.rs
- probe-rs/targets/PSOC_62.yaml
- probe-rs/targets/XMC4000.yaml
This PR makes minor changes to acquire/reset sequences to be tolerant of some PSOC 6 quirks:
- A system reset resets the SWD interface as well, causing all requests to return NACK until we reinitialize the debug probe.
- Vector catch reset-and-halt takes up to 100ms, because it applies after the core's boot ROM finishes executing & before jumping into application code.
- A power-up request can succeed and return NACK under some circumstances, such as if the request causes the device to wake from deep sleep.
With these changes, probe-rs is able to successfully acquire, program, and debug PSOC 6 devices. I implemented these changes under `architecture/arm` because they're only minor tweaks that add robustness to error paths and should not affect the behavior of any other supported devices; …
> Add support for Infineon PSOC 62 family

- changelog/fixed-jlink-multiple-chunks.md
- probe-rs/src/probe/jlink/mod.rs
We read the result into the command buffer, overwriting the command header in the process. This PR re-writes the command header in every iteration of the chunking loop, so that it is a valid command for each chunk.
> j-link: Reinitialize command byte for all chunks

- probe-rs-tools/src/bin/probe-rs/cmd/chip.rs
- probe-rs-tools/src/bin/probe-rs/cmd/serve.rs
- probe-rs-tools/src/bin/probe-rs/main.rs
- probe-rs-tools/src/bin/probe-rs/rpc/functions.rs
This PR adds the ability to limit a user's access to probes. The configuration looks like this in TOML:
```toml
[[server.users]]
name = "user1"
token = "token1"
access = "all"
[[server.users]]
name = "user2"
token = "token2"
access = { allow = ["0403:6010:12345678"] }
[[server.users]]
name = "user3"
token = "token3"
deny = { allow = ["0403:6010:12345678"] }
```
A probe selector can be either `VID:PID:serial` or `VID:PID`, both matches. Empty serials are permitted as `VID:PID:`.
> Implement probe access lists

- Cargo.lock
- target-gen/Cargo.toml
Changes in new version:
- Dependency on minidom crate replaced with roxmltree (Fixes https://github.com/pyocd/cmsis-pack-manager/issues/236)
- Handle inheritance of <debug> element attributes (see https://github.com/pyocd/cmsis-pack-manager/pull/233)
> Update to cmsis-pack v0.7.1

- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/mod.rs
- probe-rs-tools/src/bin/probe-rs/rpc/functions/flash.rs
- probe-rs-tools/src/bin/probe-rs/rpc/functions/monitor.rs
- probe-rs-tools/src/bin/probe-rs/rpc/functions/test.rs
- probe-rs-tools/src/bin/probe-rs/util/rtt/client.rs
This PR changes how the RTT control block is cleared (i.e. the client can be set to prevent clearing, if the flasher initializes the control block), and makes sure the control block is cleared when needed, and that the CPU is reset on `probe-rs run` even if `--preverify` causes the flash process to be skipped.
> Reset CPU when flashing is skipped

- changelog/fixed-debugger-rtt-names.md
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/core_data.rs
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/debugger.rs
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/session_data.rs
This fixes an issue where channels show up as unnamed in the debugger. Also RTT location is re-read when the binary is reflashed on session reset.
> Only show RTT window when actually initialized

- changelog/fixed-idf-debug-timeout.md
- probe-rs/src/architecture/riscv/mod.rs
- probe-rs/src/architecture/riscv/sequences.rs
- probe-rs/src/architecture/xtensa/mod.rs
- probe-rs/src/architecture/xtensa/sequences.rs
- probe-rs/src/vendor/espressif/sequences/esp32.rs
- probe-rs/src/vendor/espressif/sequences/esp32c2.rs
- probe-rs/src/vendor/espressif/sequences/esp32c3.rs
- probe-rs/src/vendor/espressif/sequences/esp32c6.rs
- probe-rs/src/vendor/espressif/sequences/esp32h2.rs
- probe-rs/src/vendor/espressif/sequences/esp32s2.rs
- probe-rs/src/vendor/espressif/sequences/esp32s3.rs
If the target re-enables WDTs without our knowledge, halting (i.e. by the debugger UI) will just cause a WDT reset. This PR brute forces the WDTs to be off.
Probably closes https://github.com/probe-rs/probe-rs/issues/2859 and closes https://github.com/probe-rs/probe-rs/issues/2317 as this is one source of DMI timeouts.
> Disable WDTs every time MCU is halted

- probe-rs-tools/src/bin/probe-rs/util/rtt/client.rs
> RTT control block clearing: Fix incorrect initial state

- changelog/changed-debug.md
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/core_status.rs
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/dap_types.rs
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/repl_commands.rs
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/repl_commands_helpers.rs
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/mod.rs
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/debugger.rs
- probe-rs-tools/src/bin/probe-rs/cmd/debug.rs
- probe-rs-tools/src/bin/probe-rs/main.rs
This PR nukes the CLI implementation as we don't want to maintain two separate set of REPL commands. This is the first step of improving debug experience, and a big cut of available commands at that. Follow-up steps include:
- Porting the old commands into the DAP REPL command list.
- TUI that can display RTT output.
- Rewriting some commands to be more user friendly (looking at you, `backtrace`).
- Moving the server into the RPC space so that we can debug remote devices that are managed by a probe-rs server.
> Rewrite debug on top of DAP server

- changelog/added-reset-for-dpv0.md
- probe-rs/src/architecture/arm/sequences.rs
Add a reset sequence for devices that are DPv0. These are older parts that are found on devices such as the TMS570 and devices that are JTAG-only.
These devices only have one bit in the `ABORT` register. In order to clear error conditions, bits must be set in the `CTRL` register as well.
> dpv0: add reset sequence for dpv0

- changelog/fixed-xtensa-halt.md
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
- probe-rs/src/architecture/xtensa/mod.rs
Since a lot of operations need the CPU to execute instructions, the CPU needs to be halted otherwise the debug module will just return errors. This is most noticeable during a debug session, where trying to set a breakpoint on a running target can just fail.
> Halt Xtensa core before manipulating registers or breakpoints

- changelog/fixed-psoc-reset-quirks.md
- probe-rs/src/architecture/arm/ap/memory_ap/mock.rs
- probe-rs/src/architecture/arm/communication_interface.rs
- probe-rs/src/architecture/arm/core/armv6m.rs
- probe-rs/src/architecture/arm/core/armv7m.rs
- probe-rs/src/architecture/arm/core/armv8m.rs
- probe-rs/src/architecture/arm/sequences.rs
- probe-rs/src/architecture/arm/traits.rs
- probe-rs/src/probe/blackmagic/arm.rs
- probe-rs/src/probe/fake_probe.rs
- probe-rs/src/probe/sifliuart/arm.rs
- probe-rs/src/probe/stlink/mod.rs
This PR adds error recovery paths for a few situations encountered when working with PSOC devices:
- A system reset resets the debug interface, causing a NACK and requiring us to reinitialize the interface.
- PSOC devices take some time to enter a halted state after performing a reset with vector catch, since the vector catch applies after the core's boot ROM finishes executing (or not at all if there is no user application present in flash).
- A power-up request can cause a spurious NACK, requiring a line reset.
Split out from #3110 as requested by @Yatekii.
> Improve error handling paths of acquire/reset sequences for PSOC compatibility

- changelog/added-pcsr-profiling.md
- probe-rs-tools/src/bin/probe-rs/cmd/profile.rs
- probe-rs/src/architecture/arm/component/dwt.rs
Some DWT implementations expose the program counter sample register. We can use this to observe the PC value during profiling. It's similar to the naive approach, but we don't need to halt the core to take the measurement.
This commit adds program counter sampling support (PCSR) to `probe-rs profile`. Tested on an i.MX RT MCU. When compared to naive, I measure over 4x more samples during the same duration.
> Add program counter sampling support to profiling

- changelog/fixed-handling-idf-syscall.md
- probe-rs-tools/src/bin/probe-rs/util/cli.rs
- probe-rs/src/architecture/riscv/mod.rs
- probe-rs/src/architecture/riscv/sequences.rs
- probe-rs/src/architecture/xtensa/mod.rs
- probe-rs/src/architecture/xtensa/sequences.rs
- probe-rs/src/semihosting.rs
- probe-rs/src/vendor/espressif/sequences/esp.rs
- probe-rs/src/vendor/espressif/sequences/esp32.rs
- probe-rs/src/vendor/espressif/sequences/esp32c2.rs
- probe-rs/src/vendor/espressif/sequences/esp32c3.rs
- probe-rs/src/vendor/espressif/sequences/esp32c6.rs
- probe-rs/src/vendor/espressif/sequences/esp32h2.rs
- probe-rs/src/vendor/espressif/sequences/esp32s2.rs
- probe-rs/src/vendor/espressif/sequences/esp32s3.rs
It's not perfect, as we can't actually detect if the caller is esp-idf, but this allows `probe-rs run` to run a panicking IDF-based firmware and not end up in a warning-printing loop.
> Handle esp-idf `ESP_SEMIHOSTING_SYS_BREAKPOINT_SET` and `ESP_SEMIHOSTING_SYS_PANIC_REASON` syscalls

- changelog/added-gdb-spawn.md
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/mod.rs
- probe-rs-tools/src/bin/probe-rs/cmd/gdb_server/mod.rs
- probe-rs-tools/src/bin/probe-rs/cmd/gdb_server/stub.rs
This makes attaching gdb to a microcontroller a single step process rather than a three step process (run gdbserver, run gdb, attach gdb to gdbserver)
An example usage would be `probe-rs gdb --reset-halt --chip nRF52840_xxAA --gdb gdb-multiarch target/thumbv7em-none-eabi/debug/nrf52840-test -- -ex "b main" -ex "c"` which attaches the debugger, resets the microcontroller, sets a breakpoint on main and then continues until main.
> Add an option to the probe-rs gdb subcommand to directly spawn gdb

- probe-rs/src/architecture/arm/core/armv6m.rs
- probe-rs/src/architecture/arm/core/armv7m.rs
- probe-rs/src/architecture/arm/core/armv8m.rs
- probe-rs/src/architecture/arm/memory/mod.rs
- probe-rs/src/core.rs
- probe-rs/src/probe.rs
- rust-toolchain.toml
Not sure if I got all cases where it could be used.
> Update to Rust 1.86, use trait upcasting

- Cargo.lock
- probe-rs-tools/Cargo.toml
defmt has stabilized at 1.0.
To my understanding, the format has remained compatible since decoder 0.4, and the crate itself only had [minimal changes](https://github.com/knurling-rs/defmt/blob/main/CHANGELOG.md#defmt-decoder-v100-2025-04-01) (but, with CBOR support, a feature addition that is very significant to me).
> Update defmt-decoder to 1.0

- changelog/fixed-sifli-debug-open.md
- probe-rs/src/probe/sifliuart/mod.rs
On macos systems, opening the /dev/cu device enables RTS, which is not friendly to boards that have the RTS/DTR line connected as an automatic download.
Therefore this pr sets the status of DTR and RTS to false by default
> fix: restore the sifli debug's serial port dtr and rts to their false

- probe-rs-tools/src/bin/probe-rs/cmd/gdb_server/mod.rs
- probe-rs-tools/src/bin/probe-rs/cmd/gdb_server/stub.rs
You need ctrl-c to ask gdb to interrupt execution of the tracee. It would be bad if the gdbserver gets killed at the same time. We do still exit on two consecutive ctrl-c within half a second though as a fail-safe.
Missed this in https://github.com/probe-rs/probe-rs/pull/3203
> Don't exit on ctrl-c when running gdb

- changelog/changed-catch-defaults.md
- probe-rs-tools/src/bin/probe-rs/cmd/attach.rs
- probe-rs-tools/src/bin/probe-rs/cmd/run.rs
`--catch-reset` and `--catch-hardfault` were added in #1899. Since then, we've had quite a few new folk getting confused when probe-rs doesn't output any info on hardfault.
This commit switches the default, which will hopefully be better for most people, and fail loudly + obviously for everyone else.
Closes #3157
> Change reset/hardfault catch behaviour for run and attach

- changelog/added-cmsis-jtag.md
- changelog/removed-jtag-chain-item.md
- probe-rs-target/src/chip.rs
- probe-rs/src/architecture/riscv/dtm/jtag_dtm.rs
- probe-rs/src/probe.rs
- probe-rs/src/probe/arm_debug_interface.rs
- probe-rs/src/probe/cmsisdap/commands/jtag/mod.rs
- probe-rs/src/probe/cmsisdap/commands/jtag/sequence.rs
- probe-rs/src/probe/cmsisdap/mod.rs
- probe-rs/src/probe/common.rs
- probe-rs/src/probe/wlink/mod.rs
- probe-rs/src/session.rs
- probe-rs/src/vendor/mod.rs
Slightly on the hacky side but the default CMSIS-DAP command set doesn't implement any sort of JTAG IR/DR scan helpers without the ARM-specific bits being attached to the sequence, which is unfortunate. We could define our own but the documentation doesn't really explain how we could add vendor-specific commands - and we would still need to polyfill for non-dap-rs-based probes.
The PR also fixes the JTAG_Sequence command which previously assumed that only whole bytes were captured.
> Add raw JTAG IO to CMSIS-DAP probes

- .github/workflows/ci.yml
- .github/workflows/v-release.yml
- changelog/changed-ci-image.md
- dist-workspace.toml
20.04 is no longer supported, see https://github.com/actions/runner-images/issues/11101
> Update github runner image to ubuntu 22.04

- probe-rs/src/vendor/espressif/sequences/esp32s2.rs
This PR adds the peripheral address space to the LDDR32.P/SDDR32.P-enabled memory ranges. This is fixing an issue around system reset - I don't really know why (i.e. why the normal memory access instructions result in a timeout during reset), but regardless, this fixes an issue we have.
> ESP32S2: access peripherals via fast instructions

- probe-rs/src/architecture/xtensa/communication_interface.rs
- probe-rs/src/architecture/xtensa/mod.rs
Spilling on every halt broke ESP32 (and S2, but that was fixable in some other way). This PR cleans some things up, and makes sure we only spill registers before reading memory (because we may read from the stack for unwinding, which needs the registers to be spilled).
> Xtensa fixes

- probe-rs/src/architecture/xtensa/arch/mod.rs
- probe-rs/src/architecture/xtensa/communication_interface.rs
- probe-rs/src/architecture/xtensa/mod.rs
- probe-rs/src/architecture/xtensa/register_cache.rs
- probe-rs/src/vendor/espressif/sequences/esp32.rs
- probe-rs/src/vendor/espressif/sequences/esp32s2.rs
- probe-rs/src/vendor/espressif/sequences/esp32s3.rs
This PR allows being more lazy about restoring scrach registers, resulting in a bit of a speedup during flashing.
> Rework Xtensa register cache

- changelog/added-mec172x.md
- probe-rs/src/vendor/microchip/mod.rs
- probe-rs/src/vendor/microchip/sequences/mec17xx.rs
- probe-rs/src/vendor/microchip/sequences/mod.rs
- probe-rs/targets/MEC17xx_Series.yaml
Added support for Microchip MEC172x series of MCUs.
Testing was done on a Microchip MEC1723 EVB: https://docs.zephyrproject.org/latest/boards/microchip/mec172xmodular_assy6930/doc/mec172xmodular_assy6930.html
* Verified downloading and executing from SRAM
* Created flash routines for (external) Winbond W25M512
* Verified sector erase and page writes (able to store image to flash and execute)
> Add support for Microchip MEC172x series of MCUs

- changelog/changed-swd-probe-interface-sequence-type.md
- probe-rs/src/probe/arm_debug_interface.rs
- probe-rs/src/probe/blackmagic/mod.rs
- probe-rs/src/probe/ftdi/mod.rs
- probe-rs/src/probe/jlink/bits.rs
- probe-rs/src/probe/jlink/mod.rs
The change introduces new type for representing data IO sequence values and replaces bool. Only data i.e. SWD-IO and JTAG TDI signals are replaced with new type.
Advantages:
- Binds both logical meanings i.e. Direction and Value into single type
- Encompasses the bus logic sequence of the direction and value into single enum.
- Allows to avoid passing both vectors and thus dismissing all the validation of the lengths before using the sequence
- encourages to produce valid input from the source by more bounds i.e. input does not have value
- more control over conversion: i.e. one may use .into()/.try_into() instead of ‘as’
Disadvantages:
- some extra conversion needed, on a plus side those are simple and should not introduce more performance overhead
> SWD: Encompass direction and value of IO sequence into single type 

- changelog/changed-jtag-traits.md
- probe-rs/src/probe.rs
- probe-rs/src/probe/blackmagic/mod.rs
- probe-rs/src/probe/cmsisdap/mod.rs
- probe-rs/src/probe/common.rs
- probe-rs/src/probe/espusbjtag/mod.rs
- probe-rs/src/probe/ftdi/mod.rs
- probe-rs/src/probe/jlink/mod.rs
- probe-rs/src/session.rs
This PR changes the JTAG traits a bit so that scan_chain can be called from select_target - this should ensure that - at least the bitbanging implementations - scan the chain before trying to use it.
> Undo recently added scan-hack

- changelog/added-store-log.md
- probe-rs-tools/src/bin/probe-rs/cmd/attach.rs
- probe-rs-tools/src/bin/probe-rs/cmd/run.rs
- probe-rs-tools/src/bin/probe-rs/main.rs
- probe-rs-tools/src/bin/probe-rs/util/cli.rs
cargo-embed has the convenient feature to send a copy of the output stream over the network; I'd like to use this in Ariel OS both for interactive commissioning (where a process in the background scans the running program's output, eg. for public keys generated there) and for testing (exceeding what embedded-test can do: eg. listen for readiness signals or chosen address, start a network interaction test from the host).
This PR brings that feature to probe-rs run, albeit with subtle differences, which are all IMO sensible in the context of a CLI rather than a TUI tool:
* It embraces the asyncness a bit more (IIUC, the cargo-embed version will either start blocking or indefinitely grow buffers)
* Failure to connect is fatal here. This fits because a TUI tool can give visual warnigns and …
> run/attach: Allow sending output to other applications

- deny.toml
[RUSTSEC-2023-0089](https://rustsec.org/advisories/RUSTSEC-2023-0089) is an advisory on atomic-polyfill being unmaintained. That is a dependency from heapless 0.7 coming via postcard (where this is [also tracked](https://github.com/jamesmunns/postcard/issues/223)), showing up in Cargo.lock but [not used on std platforms](https://github.com/rust-embedded/heapless/blob/0eea6da5bc159823d0564fcd6974eab299073dcf/Cargo.toml#L30).
> deny: Allow inapplicable advisory on atomic-polyfill

- changelog/added-skip-section-option.md
- probe-rs-tools/src/bin/probe-rs/main.rs
- probe-rs-tools/src/bin/probe-rs/util/flash.rs
- probe-rs/src/flashing/download.rs
- probe-rs/src/flashing/loader.rs
I'm working on an application which has ~100 KiB of application code and a ~450KiB firmware image for a WiFi module. In order to speed up iteration, I would like the option to skip reflashing the firmware image when I just made a simple code change.
To this end, this PR adds a `--skip-section` command-line flag to the flashing tools, allowing the user to specify one or more section names from the input ELF file to be skipped during flashing. This way, I can modify my linker script to place the firmware image in a specific section at a constant address, and use this option to avoid flashing that section if I haven't changed the firmware image.
> Add --skip-section option to flashing commands

- changelog/changed-nrf91-series-targets.md
- probe-rs/targets/nRF91_Series.yaml
I was having some issues with programming and `cargo run` with a nRF9151 target. I did see that the CMSIS packs from Nordic have some newer entries. Specifically the nRF9120_xxAA target, so far, seems to work with the nRF9151. 
Feedback on the PR is greatly appreciated. Any input on testing methodology to make sure it's solid is also greatly appreciated.
> Updating nRF91_Series.yaml to account for newer nRF91 SiPs

- changelog/changed-slice-debug.md
- probe-rs-debug/src/language.rs
- probe-rs-debug/src/language/rust.rs
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__esp32s3_esp_hal_panic.snap
- probe-rs-debug/src/unit_info.rs
- probe-rs-debug/src/variable.rs
This PR introduces a language-specific way to transform variables, resolves slices to look like array pointers, and prevents some errors from being eaten before the user can see them.
For example, a PanicInfo may now look like this:
> Debugger: resolve slices

- changelog/added-debug-info-ref.md
- probe-rs-debug/src/debug_info.rs
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__esp32s3_esp_hal_panic.snap
- probe-rs-debug/src/unit_info.rs
This PR implements handling of `DW_AT_type = DebugInfoRef` which is a rare case where a variable's debuginfo is encoded in a different compilation unit.
> Resolve `DW_AT_type = DebugInfoRef`

- probe-rs-tools/src/bin/probe-rs/rpc/client.rs
- probe-rs-tools/src/bin/probe-rs/rpc/functions.rs
- probe-rs-tools/src/bin/probe-rs/rpc/functions/monitor.rs
- probe-rs-tools/src/bin/probe-rs/rpc/functions/test.rs
- probe-rs-tools/src/bin/probe-rs/util/cli.rs
This PR separates the MonitorEvent topic into two, adding mechanisms to bundle multiple topics together for more ergonimic use in the CLI. The point is to reduce breaking changes - while modifying a Topic (i.e. by adding more Semihosting events) is still breaking, adding a whole new stream (like Serial, or tracing output) will not be.
> RPC: Split up RTT and Semihosting topics

- probe-rs/src/architecture/xtensa/mod.rs
This should fix a random firmware crash
> Xtensa: Do not spill in exception mode

- changelog/added-session-attach-with-registry.md
- changelog/fixed-target-gen-registry.md
- probe-rs/src/session.rs
- target-gen/src/commands/test.rs
With the recent reorganization of target definitions, the ability to specify an external target definition was lost.
Add new versions of various session initialization functions that support taking an external registry, and use them as part of `target-gen`.
> target-gen: support external definitions again

- changelog/added-jtag-ntrst-pin.md
- probe-rs/src/probe/cmsisdap/commands/swj/pins.rs
- probe-rs/src/probe/cmsisdap/mod.rs
Add support for deasserting the test reset machinery. This signal is wired up on some safety-critical parts to ensure JTAG doesn't accidentally get triggered.
This enables debugging devices such as the TMS570 with built-in XDS110.
> cmsisdap: add ntrst support

- changelog/changed-protocol-traits.md
- probe-rs/src/architecture/arm/mod.rs
- probe-rs/src/architecture/arm/traits.rs
- probe-rs/src/architecture/arm/traits/polyfill.rs
- probe-rs/src/architecture/riscv/dtm/jtag_dtm.rs
- probe-rs/src/architecture/xtensa/communication_interface.rs
- probe-rs/src/architecture/xtensa/xdm.rs
- probe-rs/src/probe.rs
- probe-rs/src/probe/blackmagic/mod.rs
- probe-rs/src/probe/cmsisdap/commands/jtag/mod.rs
- probe-rs/src/probe/cmsisdap/mod.rs
- probe-rs/src/probe/common.rs
- probe-rs/src/probe/espusbjtag/mod.rs
- probe-rs/src/probe/ftdi/mod.rs
- probe-rs/src/probe/jlink/mod.rs
- probe-rs/src/probe/wlink/mod.rs
The idea behind this PR (and its follow up work) is to separate architecture implementations from raw protocol IO. The goal is to implement, for each of the architectures, a fallback interface that uses lower level IO for probe compatibility, but also to allow using higher level probe commands where available to accelerate operations.
Bitbanging ARM debug interface implementation was moved to the ARM module as a first approximation of the idea.
> Refactor probe IO traits

- probe-rs/src/probe.rs
- probe-rs/src/probe/blackmagic/mod.rs
- probe-rs/src/probe/cmsisdap/mod.rs
- probe-rs/src/probe/common.rs
- probe-rs/src/probe/espusbjtag/mod.rs
- probe-rs/src/probe/ftdi/mod.rs
- probe-rs/src/probe/jlink/mod.rs
In theory, the CMSIS-DAP probe can define more efficient operations for JTAG access than what we implement for bitbanging probes. This is not possible with the current blanket implementation of JtagAccess. The `AutoImplemntJtagAccess` trait now serves as a marker for when the probe wants JtagAccess to be implemented.
I expect other similar marker traits to be introduced in the future.
> Allow opting out of JtagAccess blanket impl

- Cargo.lock
- changelog/changed-debugger-unknown.md
- probe-rs-debug/Cargo.toml
- probe-rs-debug/src/debug_info.rs
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__print_stacktrace.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__unwinding_in_exception_handler.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__unwinding_in_exception_trampoline.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__unwinding_inlined.snap
This PR tries to provide a function name from object symbol tables. This has the obvious drawback of not always succeeding - see `esp32s3::__INTERRUPTS` in the screenshot. This is likely related to https://github.com/gimli-rs/addr2line/issues/324
> Try to provide a function name when missing from debuginfo

- changelog/added-core-set-hw-breakpoint-unit.md
- probe-rs/src/core.rs
- smoke-tester/src/main.rs
- smoke-tester/src/tests.rs
This PR fixes `CoreInterface::set_hw_breakpoint` to use the specified HW breakpoint unit, and adds a matching function to the inherent methods (Core::set_hw_breakpoint_unit). This means `CoreInterface::set_hw_breakpoint` can no longer fail with an unavailable breakpoint unit error if the specfied breakpoint unit exists.
> Update the actually specified breakpoint unit

- probe-rs-tools/src/bin/probe-rs/rpc/client.rs
- probe-rs-tools/src/bin/probe-rs/rpc/functions.rs
- probe-rs-tools/src/bin/probe-rs/rpc/functions/monitor.rs
- probe-rs-tools/src/bin/probe-rs/rpc/functions/test.rs
- probe-rs-tools/src/bin/probe-rs/rpc/utils/run_loop.rs
- probe-rs-tools/src/bin/probe-rs/util/cli.rs
This PR separates errors and abnormal firmware exit conditions in `monitor`. This technically closes #3307 although the solution is "good enough" as opposed to "good".
> Separate probing errors from firmware exits

- Cargo.lock
- smoke-tester/Cargo.toml
- smoke-tester/src/dut_definition.rs
- smoke-tester/src/main.rs
- smoke-tester/src/tests.rs
- smoke-tester/src/tests/stepping.rs
Normally, miette would be a fine library to print human-consumable diagnostics, but we don't use any of that in the smoke tester - and I don't think the offered features would even be that useful. The smoke tester's error output could probably be improved without the library and its added code noise.
> Remove miette from smoke tester

- Cargo.lock
- changelog/added-read-output.md
- probe-rs-tools/Cargo.toml
- probe-rs-tools/src/bin/probe-rs/cmd/read.rs
Closes #2957 
---
I implemented this as a second read because of endianness reasons.
I don't know how to write (say) u64 bytes back into their byte representation for saving out to a file.
> Add --output and --format to the read command

- changelog/added-probe-argument-to-target-gen.md
- target-gen/src/commands/test.rs
- target-gen/src/main.rs
Support specifying --probe when doing `target-gen test`. This enables generating flash algorithms when there are multiple probes attached to a system, or when one probe has multiple drivers.
> target-gen: support specifying a probe for testing

- changelog/fixed-target-gen-algorithm-yaml-fields.md
- target-gen/src/commands/elf.rs
- target-gen/src/generate.rs
- target-gen/src/parser.rs
Support passing through yaml fields that aren't touched by the elf generator. This allows for passing fields such as the `stack_size`, which otherwise would be lost.
> algorithm: pass through untouched yaml fields

- changelog/added-read-implementation-to-memoryinterface.md
- changelog/fixed-adi-memory-interface-read.md
- changelog/fixed-smoke-tester-readme-command.md
- probe-rs/src/architecture/arm/memory/adi_memory_interface.rs
- probe-rs/src/memory/mod.rs
- smoke-tester/README.md
The default implementation of `read()` was left out of an earlier implementation that forwarded a bunch of calls to the underlying `self.memory_mut().read()`.
> memory: delegate `read()` to the memory object

- Cargo.lock
- changelog/added-blank-check-to-flasher.md
- probe-rs-target/src/flash_algorithm.rs
- probe-rs/src/flashing/erase.rs
- probe-rs/src/flashing/flash_algorithm.rs
- probe-rs/src/flashing/flasher.rs
- target-gen/Cargo.toml
- target-gen/src/commands/test.rs
- target-gen/src/parser.rs
Add blank_check to flash algorithms. This is code that runs on the target, and is used for checking whether flash is blank or not on parts where the blank status isn't a simple pattern. This is common on ECC parts, where frequently a blank flash isn't even valid.
> Add blank check to algorithm

- changelog/added-armv7a-cpsr-updating.md
- changelog/fixed-jumping-to-algorithms-on-armv7a.md
- probe-rs/src/architecture/arm/core/armv7a.rs
- probe-rs/src/architecture/arm/core/instructions.rs
Miscellaneous fixes for ARMv7A (and ARMv7R).
A note on the `bx r0` -> `mov pc, r0` change: The former just doesn't seem to work on Cortex-A cores. I can't find any documentation on this, but I do see [this from openocd](https://github.com/openocd-org/openocd/blob/6a3abda0b46a777490a8ce5bc748e6fed6775354/src/target/arm_dpm.c#L616-L621):
```cpp
/* on Cortex-A5 (as found on NXP VF610 SoC), BX instruction
* executed in debug state doesn't appear to set the PC,
* explicitly set it with a "MOV pc, r0". This doesn't influence
* CPSR on Cortex-A9 so it should be OK. Maybe due to different
* debug version?
*/
```
> Armv7a instruction fixes

- Cargo.toml
This PR removes most debuginfo from the dev builds, and adds line-tables to release/dist build. The goal is to improve build times for dev, and to be able to provide better stack traces on crashes on release.
> Tweak the generated debuginfo

- changelog/changed-cargo-embed-profile-argument-name.md
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/mod.rs
Its named configuration profile in the documentation on the web page and having profile in the argument's name points this out more clearly (to me).
> Rename cargo-embed config profile arg for more clarity

- changelog/changed-cargo-embed-status-output-cleanup.md
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/mod.rs
This is a follow-up to https://github.com/probe-rs/probe-rs/pull/3361. It also renames the configuration profile in the status output and harmonizes indentation.
Before:
```bash
$ cargo embed --path firmware.elf with_rtt
Config with_rtt
Target firmware.elf
Erasing ✔ 100% [####################] 168.00 KiB @ 125.87 KiB/s (took 1s)
Programming ✔ 100% [####################] 168.00 KiB @  20.30 KiB/s (took 8s)                                                                                                                  Finished in 9.61s
GDB stub listening at 127.0.0.1:1337
```
Now:
```bash
$ cargo embed --path firmware.elf with_rtt
Profile with_rtt
Target firmware.elf
Erasing ✔ 100% [####################] 168.00 KiB @ 126.84 KiB/s (took 1s)
Programming ✔ 100% [####################] 168.00 …
```
> Clean up status messago formatting for cargo-embed

- changelog/added-big-endian-flag-to-flash-algorithm.md
- changelog/added-big-endian-for-armv7a.md
- changelog/added-big-endian-support-for-rtt.md
- probe-rs-target/src/flash_algorithm.rs
- probe-rs/src/architecture/arm/core/armv7a.rs
- probe-rs/src/flashing/flash_algorithm.rs
- probe-rs/src/flashing/flasher.rs
- probe-rs/src/rtt.rs
- target-gen/src/parser.rs
Add big endian support for ARMv7A. This includes supporting `target-gen` as well as basic RTT support.
> Armv7a big endian support

- changelog/added-armv7a-dcc-fast-mode.md
- probe-rs/src/architecture/arm/core/armv7a.rs
- probe-rs/src/architecture/arm/core/armv7a_debug_regs.rs
Add DCC Fast mode for reads and writes on ARMv7A. When accessing more than two words, it becomes faster to use this mode to perform repeated reads or writes. By using banked access, this further improves performance, yielding a net 10x speedup versus the previous word-wise approach.
This also adds a `BankedHelper` to lock the memory interface to ensure the Target Address Register doesn't change while in banked mode. This helper also has a function to ensure that the interface is taken out of DCC Fast mode even if there is a memory access failure.
> armv7a: add dcc fast mode (and some banked access)

- probe-rs/src/architecture/arm/core/armv7a.rs
Ensure that the ARMv7A core is halted when asking what its endianness is if the value has not yet been cached. This is necessary because this operation reads the state from a register.
> armv7a: ensure core is halted when querying endianness

- changelog/fixed-delegate-endianness-to-core-inner.md
- probe-rs/src/core.rs
Have `core.endianness()` call `self.inner.endianness()`. This is required to get interfaces such as gdb working.
> delegate `core.endianness()` to inner interface

- changelog/changed-try-get-interface.md
- probe-rs/src/core.rs
- probe-rs/src/core/core_state.rs
- probe-rs/src/probe.rs
- probe-rs/src/probe/blackmagic/mod.rs
- probe-rs/src/probe/cmsisdap/mod.rs
- probe-rs/src/probe/espusbjtag/mod.rs
- probe-rs/src/probe/fake_probe.rs
- probe-rs/src/probe/ftdi/mod.rs
- probe-rs/src/probe/jlink/mod.rs
- probe-rs/src/probe/sifliuart/mod.rs
- probe-rs/src/probe/stlink/mod.rs
- probe-rs/src/probe/wlink/mod.rs
- probe-rs/src/session.rs
- probe-rs/src/vendor/mod.rs
Kinda-sorta extracted (the idea) from #3000
> Return architecture-specific errors from `try_get_X_interface` functions

- changelog/fixed-ctrl-c-trace.md
- probe-rs-tools/src/bin/probe-rs/rpc/functions/monitor.rs
- probe-rs-tools/src/bin/probe-rs/util/cli.rs
Ctrl-C was considered a type of error that prevented printing stack traces for some reason.
> Fix printing stacktrace on ctrl-c

- Cargo.lock
- changelog/added-glasgow-interface-explorer-support.md
- probe-rs/Cargo.toml
- probe-rs/src/probe.rs
- probe-rs/src/probe/glasgow/mod.rs
- probe-rs/src/probe/glasgow/mux.rs
- probe-rs/src/probe/glasgow/net.rs
- probe-rs/src/probe/glasgow/proto.rs
- probe-rs/src/probe/glasgow/usb.rs
- probe-rs/src/probe/list.rs
The corresponding Glasgow PR is [#866](https://github.com/GlasgowEmbedded/glasgow/pull/866). 
This driver works in concert with the `probe-rs` applet and the Glasgow Python framework; it is not able to function standalone.
I would consider this implementation feature-complete within the scope of "supports SWD only". It has acceptable performance (~100 KB/s when loading a small ELF on an IMXRT1052 with maximum 24 MHz SWCLK), supports all of the features you would expect from an SWD debugger (~~except perhaps for hardware SRST#~~ this is implemented now), and is flexible enough to be extended with support for FPGA-accelerated algorithms and JTAG later.
This driver supports three transports (USB, TCP, and Unix domain sockets) equally and with a similar level of performance. The USB transport …
> Add a Glasgow Interface Explorer probe driver

- Cargo.lock
- changelog/added-gdb-load-command-support.md
- probe-rs-tools/Cargo.toml
- probe-rs-tools/src/bin/probe-rs/cmd/gdb_server/target/desc/mod.rs
- probe-rs-tools/src/bin/probe-rs/cmd/gdb_server/target/flash.rs
- probe-rs-tools/src/bin/probe-rs/cmd/gdb_server/target/mod.rs
Closes #1057
Currently marked as draft because the flash operations extension in gdbstub PR is not merget yet:
(https://github.com/daniel5151/gdbstub/pull/172)
Maybe someone who's interested could test it meanwhile.
Some notes:
- I don't know if it make sense to reset after flash is done. Usually a `monitor reset` is necessary anyways.
- For the board I test flash sector info are wrong for OTP, option bytes etc.. That's not a problem for the load use case, but I wonder if there's some way to filter out those non-suited-for-exec-binary regions.
> Support gdb load command

- probe-rs/src/architecture/arm/traits/polyfill.rs
- probe-rs/src/architecture/riscv/dtm/jtag_dtm.rs
- probe-rs/src/architecture/xtensa/xdm.rs
- probe-rs/src/probe.rs
- probe-rs/src/probe/common.rs
I'm trying to get debugging of a mixed architecture chip working, by implementing the `DtmAccess` backed by the `ArmMemoryInterface`.
This is a small part, making the `CommandQueue` generic makes it easier to create an implementation of a DTM not based on JTAG.
> Generic deferred result handling

- changelog/fixed-flashing-with-multiple-different-cores.md
- probe-rs/src/flashing/erase.rs
- probe-rs/src/flashing/loader.rs
For targets such as stm32wl, multiple algorithms are present. The code does not know how to deal with this, and prints an error:
```
$ probe-rs run --chip STM32WL55JCIx test.elf
Error: An error with the flashing procedure has occurred.
Caused by:
Trying to write flash, but found more than one suitable flash loader algorithim marked as default for
NvmRegion { name: Some("BANK_1"), range: 134217728..134479872, cores: ["cm4", "cm0p"], is_alias: false,
access: Some(MemoryAccess { read: true, write: false, execute: true, boot: true }) }.
$
```
Algorithms can specify which core they support, but this is not currently
being checked. Add a check that the core name matches a given algorithm.
This patch fixes flashing on STM32WL55.
> Check core name on algorithm selection

- probe-rs/src/architecture/arm/traits/polyfill.rs
- probe-rs/src/probe.rs
- probe-rs/src/probe/blackmagic/mod.rs
Bit of a follow-up to #3398, this removes the `From` implementations which could panic.
> Cleanup some IoSequence related code

- changelog/changed-reject-pico.md
- probe-rs/src/probe/cmsisdap/commands/mod.rs
- probe-rs/src/probe/cmsisdap/tools.rs
- probe-rs/src/probe/stlink/mod.rs
- probe-rs/src/probe/wlink/mod.rs
Closes #2950 as the 2.22 firmware seems to work just fine*.
> Reject old RPi debugprobes

- changelog/fixed-armv8-aarch32-pc-update.md
- probe-rs/src/architecture/arm/core/armv8a.rs
Fix updating the PC value on ARMv8 in AArch32 mode via the Debug Link Register by using the `mcr` 
instruction instead of `mrc`.
> Fix setting PC value on ARMv8 in AArch32 mode

- changelog/added-export-of-arm-dapprobe.md
- changelog/added-export-of-riscv-jtag-dtm-builder.md
- probe-rs/src/architecture/arm/mod.rs
- probe-rs/src/architecture/riscv/dtm/jtag_dtm.rs
- probe-rs/src/architecture/riscv/mod.rs
Export `arm::communications_interface::DapProbe` to enable creating Sequences that require this struct in their arguments.
Similarly, export `riscv::dtm::JtagDtmBuilder` to enable creating RISC-V probes by implementing `DebugProbe::try_get_riscv_interface_builder()`
> Export dapprobe and jtagdtmbuilder

- probe-rs/src/architecture/arm/core/armv6m.rs
- probe-rs/src/architecture/arm/core/armv7m.rs
- probe-rs/src/architecture/arm/core/armv8m.rs
These error messages are unconditionally visible, and look scary to the user, suggesting
something's wrong that they should fix, while in fact it's perfectly normal to see a locked up
core in some situations (for example when flashing a blank chip). I've seen a few people misled by
this on Matrix already.
IMO it should be higher-level tools (the debugger, `probe-rs` run) that inform the user of lockup,
not the low-level ARM arch code. They know when lockup is expected or not (for example it's expected
before flashing, unexpected after).
> cortex-m: do not log errors on lockup.

- CHANGELOG.md
- changelog/added-multisubscription-draining.md
- probe-rs-tools/src/bin/probe-rs/rpc/client.rs
This is intended to allow time for any pending messages to be processed.
> Add the ability to notify a multisubscription that an event has ended

- changelog/changed-erase-blankcheck.md
- probe-rs/src/flashing/erase.rs
- target-gen/src/commands/test.rs
The previous code operated with sector indices, which is ambiguous
if the chip has multiple algos. What's worse, it'd erase that
sector index range on *every* algo, which is never what you want.
Changing it to use addresses makes it non-ambiguous and consistent
with FlashLoader.
> flashing: change erase, blank_check to work with address ranges.

- changelog/changed-cmsisdap-feature.md
- probe-rs/Cargo.toml
- probe-rs/src/probe.rs
- probe-rs/src/probe/cmsisdap/commands/mod.rs
- probe-rs/src/probe/cmsisdap/tools.rs
Putting cmsisdap behind a feature gate allows us to make hidapi an optional dependency, which makes it much easier (or even possible?) to build for Android. With this change I was able to compile my custom toolchain for Android, run it as root, and flash some devices.
Related discussion: #3274
> Feature gate cmsisdap

- changelog/fixed-verify-use-correct-core.md
- probe-rs/src/flashing/flasher.rs
Otherwise verifying fails e.g. for the network core on the nRF5340.
> verify: Use correct core_index

- changelog/added-large-data-support-for-axi34-memap.md
- probe-rs/src/architecture/arm/ap/memory_ap/amba_axi3_axi4.rs
This adds support for the Large Data Extension to natively write U64, U128 or U256 (depending on chip support) over AXI MEM-APs.
Tested with 64-bit writes on Stellar SR6G7.
> arm axi3/4 mem-ap: Add large data support

- probe-rs/src/probe/cmsisdap/commands/transfer/mod.rs
- probe-rs/src/probe/cmsisdap/mod.rs
This should prevent the panic which is seen in #3448, by replacing it with an error.
Not sure why this actually happens though.
> Handle case where CMSIS-DAP probe does not execute all transfers

- changelog/removed-retries-cmsisdap-probe.md
- probe-rs/src/probe/cmsisdap/mod.rs
Retrying commands that result in a FAULT flag being set is problematic for the NXP IMXRT685s:
When issuing SYSRESETREQ to AIRCR the target responds with a FAULT flag @ https://github.com/probe-rs/probe-rs/blob/master/probe-rs/src/vendor/nxp/sequences/nxp_armv8m.rs#L687-L696. Probe-rs retries the command for 5 times in this case. https://github.com/probe-rs/probe-rs/blob/master/probe-rs/src/probe/cmsisdap/mod.rs#L523
Depending on the speed of the host machine, this presumably results the target being reset in the bootloader, which causes the target to no longer respond (hence the WAIT states). Validated this by temporarily removing retries on a slow host, removing the issue, and introducing the issue by adding a 1ms delay after a FAULT in the batch processor.
Basically, on my slower …
> Remove retries for faults in CmsisDap probe

- changelog/added-embedded-test-v2.md
- probe-rs-tools/src/bin/probe-rs/cmd/run.rs
- probe-rs-tools/src/bin/probe-rs/rpc/functions/test.rs
- probe-rs-tools/src/bin/probe-rs/util/cli.rs
Host-side changes for the next version of embedded-test, which:
* reads the testcases directly from the ELF, instead of requesting them from the target via semihosting
* supports unit tests (apart from integration tests)
More Infos: https://github.com/probe-rs/embedded-test/issues/62
> embedded test: read testcases directly from elf

- probe-rs/src/vendor/raspberrypi/sequences/rp2040.rs
Read back the value of the RESCUE_DP after writing it. This works around an issue on WCH-Link probes where not doing this causes the probe to lock up.
Additionally, it was discovered that the `debug_port_setup()` implementation was breaking things on this probe. The comment said "This works around an issue where the multidrop DP becomes unavailable.", however it didn't say what the issues were. If the problem resurfaces, this code will be brought back and the comment will be updated with the actual issue it solves.
Closes #3480.
> rp2040: read back value of rescue dp after writing it

- probe-rs-tools/src/bin/probe-rs/rpc/functions/monitor.rs
- probe-rs-tools/src/bin/probe-rs/rpc/functions/test.rs
- probe-rs-tools/src/bin/probe-rs/rpc/utils.rs
- probe-rs-tools/src/bin/probe-rs/rpc/utils/semihosting_file_manager.rs
- probe-rs/src/semihosting.rs
This makes all function of the the [`semihosting` crate](https://docs.rs/semihosting/) work with `probe-rs`.
The function needs enabled by setting the `PROBE_RS_SEMIHOSTING_ALLOW_FILE_ACCESS` environment variable, to avoid giving the target to much power over the host. Maybe there is a better way to achieve this or we don't want it at all. It only affects the last commit.
> Adds support for file access via semihosting

- changelog/added-efm32pg26.md
- probe-rs/targets/EFM32PG26_Series.yaml
Add support for the EFM32PG26 series mcus using target-gen.
> Add EFM32PG26 series mcus

- changelog/added-option-no-timestamps.md
- changelog/fixed-show-timestamps-string.md
- probe-rs-tools/src/bin/probe-rs/cmd/attach.rs
- probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/rttui/app.rs
- probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/core_data.rs
- probe-rs-tools/src/bin/probe-rs/cmd/run.rs
- probe-rs-tools/src/bin/probe-rs/util/cli.rs
- probe-rs-tools/src/bin/probe-rs/util/rtt/processing.rs
Fixes an issue where the show_timestamps property for RTT channels was ignored when using the String format in both the DAP server and `cargo embed`.
Adds an option `--no-timestamps` to `probe-rs run` and `probe-rs attach` commands to suppress timestamps of String and Defmt messages.
> Allow to control timestamps for RTT channels using String format

- changelog/fixed-thumb-unwinding.md
- probe-rs-debug/src/debug_info.rs
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__RP2040_full_unwind.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__RP2040_svcall.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__RP2040_systick.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__atsamd51p19a.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__nRF52833_xxAA_full_unwind.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__nRF52833_xxAA_hardfault_from_busfault.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__nRF52833_xxAA_hardfault_from_usagefault.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__nRF52833_xxAA_hardfault_in_systick.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__nRF52833_xxAA_svcall.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__nRF52833_xxAA_systick.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__print_stacktrace.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__unwinding_in_exception_handler.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__unwinding_in_exception_trampoline.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__unwinding_inlined.snap
By -2 of the LR, we get the address of the branch instruction, rather than the next instruction, which might not be part of the function (in particular for fns where the compiler has realised they will never return, the next instruction is [unreachable](https://www.nmichaels.org/musings/d4d4/d4d4/), and doesn't end up in the unwind info so unwinding gives up)
one example of a before/after
unreachable instr in question
> Fix unwinding on thumb targets for functions that never return

- changelog/added-armv8a-fast-writes-for-aarch32.md
- probe-rs/src/architecture/arm/core/armv8a.rs
- probe-rs/src/architecture/arm/core/instructions.rs
MA fast memory access works almost identical in AArch32 mode so there is no need to gate this on 64-bit state.
However, `write_cpu_memory_aarch64_bytes`, used to handle unaligned prefix/suffix, is AArch64 specific, but can be replaced by the regular `write_word8`, thereby simplifying the differences between AArch32 and AArch64. (`write_word8` does a RMW for byte-access but that's an orthogonal optimization.)
This further fixes a bug where r1 was not clobbered; but it is set UNKNOWN based on the pseudo-code of `shared/debug/dccanditr/DBGDTRRX_EL0`:
```
[...]
R[1] = bits(32) UNKNOWN;
[...]
```
This previously corrupted r1 when there was no unaligned part.
> ARMv8: Allow memory write fast path on AArch32

- changelog/changed-arm-reset-deassert-before-core-debug.md
- probe-rs/src/session.rs
This change is a bit intrusive, so some more explanation:
The (non-normative) explanation of Debug Access Sequences on https://developer.arm.com/documentation/ka002249/latest/ describes the following sequence for "Connect under Reset", which is also what `probe-rs` implements: (Slightly simplified here)
- ResetHardwareAssert
- DebugPortSetup
- DebugPortStart
- DebugDeviceUnlock
- DebugCoreStart
- ResetCatchSet
- ResetHardwareDeassert
(`probe-rs` swaps the order of ResetCatchSet and DebugCoreStart)
What we observed is that on some chips (ST SR6G7 with Cortex-R52+), with SRST asserted, the core is not powered up (PRSR consistently reads as 2, i.e. powered down). EDECR (especially RCE) can still be accessed, but e.g. access to EDLAR and OSLAR will fail. (It is a bit unclear what the exact …
> call `enable_arm_debug` sequence after srst deassertion

- changelog/added-rp235x-reset-sequence copy.md
- probe-rs/src/vendor/raspberrypi/mod.rs
- probe-rs/src/vendor/raspberrypi/sequences/mod.rs
- probe-rs/src/vendor/raspberrypi/sequences/rp235x.rs
Add a sequence for the RP235x family of parts. This pokes the Rescue DP core on these parts to initiate a reset.
> rp235x: add reset sequence

- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__esp32s3_coredump_elf.snap
- probe-rs-debug/src/snapshots/probe_rs_debug__debug_info__test__esp32s3_esp_hal_panic.snap
- probe-rs/src/architecture/xtensa/registers.rs
This causes `info reg` to print PS as well.
> Include Xtensa PS register in the register map

- changelog/changed-exit-code.md
- probe-rs-tools/src/bin/probe-rs/util/cli.rs
When a firmware uses semihosting to [exit](https://docs.rs/cortex-m-semihosting/latest/cortex_m_semihosting/debug/fn.exit.html) with an error, the probe-rs CLI reports
```
Firmware exited with: Unknown runtime error
Core 0
Frame 0: syscall1 @ 0x002012dc inline
...
Frame 8: Reset @ 0x00200348> @ 0x0000000000200348
```
but exits with exit code 0. I expected it to exit with a non-zero exit code.
Allow the error to affect the exit status. As a side effect of this change, the error message is printed again at the end.
```
Firmware exited with: Unknown runtime error
Core 0
Frame 0: syscall1 @ 0x002012dc inline
...
Frame 8: Reset @ 0x00200348> @ 0x0000000000200348
Error: Unknown runtime error
```
> Return non-zero exit code when firmware exits with an error

- probe-rs-tools/src/bin/probe-rs/util/cli.rs
Reverts #3379, so that channels should be named `defmt`, rather than assuming a single RTT channel in a firmware with defmt present is actually defmt-formatted.
This allows, for example, non-defmt RTT messages in a firmware where defmt is used for another transport. It prevents a situation where RTT messages can appear to the user as being "lost", as probe-rs is still waiting for the defmt framing.
The change is just to remove the extra condition check; rustfmt shifts the blocks over which makes the diff larger.
> Don't assume defmt if a single RTT channel exists (reverts #3379)

- changelog/added-linux-setup-hints.md
- probe-rs/src/probe/list.rs
This should fix confusion for new users not following the guide and for existing users upgrading their OS (ie systemd)
See also https://github.com/probe-rs/probe-rs/issues/3566
Replaces (builts on) https://github.com/probe-rs/probe-rs/pull/3576
> Add hints on Linux if the probe list is empty or probe can not be opened
