probe-rs/probe-rs

ocd/src/memory/romtable/mod.rs

This is the potential fix for the weird romtable reading behavior.
This works with the nRF51822, STM32L053R8, STM32F401 and STM32F429.
It needs to be tested with more targets.

Honor entry_present flag

---

cli/src/info.rs
ocd/src/coresight/ap_access.rs

This function returns a Vec of all valid access ports found at the
current target so users don't have to know which ones could exist and
scan them manually.

Introduce a new function valid_access_ports

---

cli/Cargo.toml
cli/src/common.rs
cli/src/debugger.rs
cli/src/info.rs
cli/src/main.rs

Fix all clippy lints in the cli/ folder, and use rustfmt on it.

Cleanup clippy lints and format cli crate

---

ocd-targets/targets/nRF52840.yaml

Tested on nRF52840-MSK with cargo-flash.

Changed part identifier for the nRF52480 target

---

cargo-flash/src/main.rs
cli/src/common.rs
cli/src/info.rs
cli/src/main.rs
ocd/src/probe/debug_probe.rs
ocd/src/probe/flash/download.rs
ocd/src/probe/flash/flasher.rs
ocd/src/probe/flash/loader.rs
ocd/src/target/info.rs

Improve CLI error handling by removing some unwraps,
so that a proper error message will be reported.
Also, automatically select the probe if only a single probe
is attached to the system, and try to automatically select the
target.

Better CLI error handling, auto-select probe and target (fix #2)

---

.github/workflows/ci.yml
cargo-flash/src/main.rs
probe-rs-targets/build.rs

Fix the probe-rs build on Windows.
Points to fix:

Fix windows build (close #53)

---

probe-rs/src/probe/stlink/mod.rs

For ST-Link v3, read the version from the correct byte and then ignore it

---

cargo-flash/src/main.rs
cli/src/common.rs
probe-rs-targets/src/lib.rs
probe-rs/src/probe/flash/download.rs
probe-rs/src/target/info.rs
probe-rs/src/target/mod.rs

This gets rid of all the unwraps, moves error printing to a single spot, and makes errors look like Cargo ones.
This required adding yet another error type and error variants. We should try to remove some of them, or at least switch to a crate that makes us write less boilerplate.

Improve cargo-flash error handling

---

CHANGELOG.md
cargo-flash/Cargo.toml
cargo-flash/src/main.rs
probe-rs-targets/targets/nRF52832.yaml
probe-rs/src/coresight/access_ports/custom_ap/mod.rs
probe-rs/src/coresight/access_ports/generic_ap/mod.rs
probe-rs/src/coresight/access_ports/memory_ap/mod.rs
probe-rs/src/coresight/access_ports/mod.rs
probe-rs/src/coresight/access_ports/register_generation.rs
probe-rs/src/coresight/ap_access.rs
probe-rs/src/probe/debug_probe.rs
probe-rs/src/probe/stlink/mod.rs
probe-rs/src/target/info.rs

Nordic has a protection scheme where you can completely lock the MEMAP (AP#0), when that happens the only way to unlock the chip is using the CTRL-AP (AP#1) which has a custom set of registers. For more information see: https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.nrf52832.ps.v1.1%2Fdif.html&anchor=debugandtrace
I don't see a reason why this wouldn't work for st-link, but it doesn't. It's only working with dap-link. This is kinda weird, because when the chip isn't locked I can use st-link to successfully communicate with AP#1 and send an erase (unlock) command with no problem, and it works, I know that because the flash gets indeed erased. However, when the chip is locked the stlink only gets the `0x05` error (`JtagNoDeviceConnected`) when communicating with …

Add feature to unlock nRF52 micros

---

probe-rs/src/collection/cores/m0.rs
probe-rs/src/collection/cores/m4.rs
probe-rs/src/probe/debug_probe.rs
probe-rs/src/target/mod.rs

This removes a potential endless loop, which could have happened in the `reset_and_halt` function, which was waiting for the core to reset without a timeout.
All functions in the `Core` trait which halt the core now return the `CoreInformation` struct, to make the interface more consistent. The `CoreInformation` struct is also renamed from `CpuInformation`, and placed next to the `Core` trait, where it is actually used.

Remove potential endless loop, and cleanup Core trait a bit.

---

RESOURCES.md
probe-rs/src/collection/cores/m33.rs
probe-rs/src/collection/cores/mod.rs
probe-rs/src/collection/mod.rs

Most of the code is based on the M0, with some small adaptions
to the register definitions.
Support for hardware breakpoints is not yet implemented.

Add initial support for Cortex-M33

---

probe-rs/build.rs
probe-rs/src/config/chip.rs
probe-rs/src/config/chip_family.rs
probe-rs/src/config/registry.rs
probe-rs/src/config/target.rs
probe-rs/src/target/info.rs
probe-rs/targets/nRF51 Series.yaml
probe-rs/targets/nRF52 Series.yaml

During the rewrite of probe-rs targets for automatic CMSIS-Pack usage, the automatic chip detection broke. This has been fixed.
Furthermore, the error messages have been improved to properly report that the chip detection was unfruitful.

Fix the automatic chip detection

---

probe-rs/targets/STM32F4 Series.yaml

The STM32F412ZG target has been tested a bit, the others not yet. Created from the .pdsc file provided by ST. 
Auto-detection works for the STM32F1412ZG.

Add STM32F4 targets

---

probe-rs/src/cores/m4.rs

As discussed, this fixes break point settings for Cortex-M4.

Fix breakpoint setting for Cortex-M4

---

cargo-flash/src/main.rs
cli/src/common.rs
cli/src/main.rs
probe-rs/examples/ram_download.rs
probe-rs/src/probe/mod.rs

Add some helper functions to the `MasterProbe` struct, which makes it easier to select a debug probe to use.
Also fix a small bug, where a debug probe was selected automatically even though multiple probes are connected.

Add probe open helper functions

---

probe-rs/Cargo.toml
probe-rs/examples/ram_download.rs
probe-rs/src/lib.rs
probe-rs/src/probe/daplink/commands/mod.rs
probe-rs/src/probe/daplink/mod.rs
probe-rs/src/probe/mod.rs
probe-rs/src/probe/stlink/constants.rs
probe-rs/src/probe/stlink/mod.rs
probe-rs/src/probe/stlink/usb_interface.rs

Move ST-Link specific errors to a ST-Link specific error type,
to clean up the DebugProbeError type.
The rental crate is also removed, to simply the implementation of
the ST-Link support.

Refactor probe error handling, especially regarding st-link

---

probe-rs/src/cores/m0.rs
probe-rs/src/cores/m4.rs
probe-rs/src/probe/daplink/commands/mod.rs
probe-rs/src/probe/daplink/mod.rs
probe-rs/src/probe/mod.rs
probe-rs/src/probe/stlink/mod.rs
probe-rs/src/probe/stlink/usb_interface.rs
probe-rs/src/session.rs

Instead of mapping DAPlink specific error to the `DebugProbeError::UnknownError`, we can wrap them into a `ProbeSpecific` error, so that they don't get lost.

Refactor daplink specific errors

---

probe-rs/targets/STM32G0 Series.yaml

the 'STM32G0 Series.yaml' file is created with `target-gen` from the
'Keil.STM32G0xx_DFP.1.2.0.pack' downloaded from
https://www.keil.com/dd2/pack/

add STM32G0 series

---

cli/src/debugger.rs
probe-rs/src/architecture/arm/core/m0.rs
probe-rs/src/architecture/arm/core/m33.rs
probe-rs/src/architecture/arm/core/m4.rs
probe-rs/src/architecture/arm/core/mod.rs
probe-rs/src/core/mod.rs
probe-rs/src/flash/flasher.rs
probe-rs/src/session.rs

Initial implementation of a more generic way to describe registers.
The goal is to have a struct which works for different platforms, at least RISCV and ARM.
The code of the ARM cores itself is not yet fully adapted right now.

Initial implementation of new register description

---

probe-rs/src/core/mod.rs

The architectures are identical enough to just reuse the M4 module.

Add Cortex-M3 support by re-using Cortex-M4

---

probe-rs/targets/STM32L0 Series.yaml

Generated with target-gen using
https://keilpack.azureedge.net/pack/Keil.STM32L0xx_DFP.2.0.1.pack
Right now it doesn't seem to work though. Output of `RUST_LOG=probe_rs=DEBUG cargo run -p probe-rs --example ram_download -- --address 0x20000000 --size 16 > out.txt 2>&1`:
[out-example.txt](https://github.com/probe-rs/probe-rs/files/4246980/out-example.txt)
@Yatekii

Add STM32L0xx target

---

CHANGELOG.md
cli/src/info.rs
probe-rs/src/architecture/arm/ap/memory_ap/mod.rs
probe-rs/src/architecture/arm/ap/mod.rs
probe-rs/src/architecture/arm/ap/register_generation.rs
probe-rs/src/architecture/arm/communication_interface.rs
probe-rs/src/architecture/arm/dp/mod.rs
probe-rs/src/flash/loader.rs
probe-rs/src/probe/stlink/constants.rs
probe-rs/src/probe/stlink/mod.rs
probe-rs/targets/STM32WB Series.yaml

Add support for the STM32WB55 chips.
Also fixes some small issues with support for multiple APs which I found while using them.
It also includes initial support to read the TARGETID, which is only present on DP version 2.

Add support for STM32WB55, small fixes for multiple AP support

---

probe-rs/src/probe/stlink/mod.rs

According to the PyOCD sources, [this check](https://github.com/mbedmicro/pyOCD/blob/89a53ca63ac2557be9d77bc81cee95891f62a3b8/pyocd/probe/stlink/stlink.py#L261) performs not only a JTAG version check, but also a [hardware version check](https://github.com/mbedmicro/pyOCD/blob/89a53ca63ac2557be9d77bc81cee95891f62a3b8/pyocd/probe/stlink/stlink.py#L149-L150).

Fix checks for STLINK-V3

---

probe-rs/src/core/mod.rs
probe-rs/src/flash/builder.rs
probe-rs/src/flash/download.rs
probe-rs/src/flash/flasher.rs
probe-rs/src/flash/loader.rs
probe-rs/src/flash/progress.rs

Add additional progress states to indicate when erasing or programming fails. This can be used to improve the error output in cargo-flash.
The error handling in the flash module now uses the `thiserror` crate as well. The endless loop while waiting for a flash algorithm function to finish is changed to a timeout, to avoid waiting forever.

Improve error handling when flashing

---

probe-rs/src/probe/stlink/mod.rs

I encountered an issue where the STLink was not using the default speed of 1800 kHz, even though this was reported by the `speed_khz` function.
The problem was that I used a different speed setting during an earlier usage of `cargo-flash`, which meant that this setting was still effect.
I've added an additional call to `set_speed`, to ensure the configured speed actually matches the speed which is used by the STLink.

Ensure default speed is actually used for STLink

---

CHANGELOG.md
probe-rs/Cargo.toml
probe-rs/src/config/flash_algorithm.rs

This fixes a bug where `ChipFamily::from_yaml_reader(file)` would fail because it didn't expect a base64 encoded string.
This function is used for cargo-flash to add additional chips. It is really useful for testing new chip configurations.

Fix parsing of yaml files on the go

---

probe-rs/src/architecture/arm/ap/memory_ap/mock.rs
probe-rs/src/architecture/arm/ap/mod.rs
probe-rs/src/architecture/arm/communication_interface.rs
probe-rs/src/architecture/arm/dp/mod.rs
probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs
probe-rs/src/probe/daplink/mod.rs

When using a Memory AP to write data into memory, we only
wrote the value into the `DRW` register of the AP.
The problem is that this does not mean that the value will
be actually written into memory. The SWD protocol requires
that the host does continue to clock the SWD clock after
writing data, to ensure that the SWD transfer can be
completed. In the case of the ST-Link, it seems that
the probe itself does not do this, as least in the
way it is used by probe-rs right now. To ensure that
all transfers can be completed, I have added a read
of the DP  register `RDBUFF` after all writes.
This seems to fix probe-rs/cargo-flash#9

Fix memory writes on ST-Link

---

cli/src/main.rs
probe-rs-t2rust/src/lib.rs
probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs
probe-rs/src/config/flash_algorithm.rs
probe-rs/src/probe/daplink/commands/general/info.rs
probe-rs/src/probe/daplink/commands/swj/clock.rs
probe-rs/src/probe/daplink/commands/transfer/configure.rs
probe-rs/src/probe/daplink/commands/transfer/mod.rs
probe-rs/src/probe/stlink/mod.rs

If endianness isn't specified, host machine endianness is assumed. Everybody is probably using a little endian machine, so I specified little endian wherever it was undefined.

Specify endianness for pread/pwrite everywhere

---

CHANGELOG.md
probe-rs/src/architecture/arm/ap/memory_ap/mock.rs
probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs

Refactored 8-bit memory access in ADIMemoryInterface, fixing some edge case crashes in the process.
Also rewrote all tests to test more edge cases and also make sure writes don't clobber adjacent memory.

Simplify and fix ARM memory interface

---

probe-rs/src/config/registry.rs

Fix building probe-rs without built-in targets.

Fix build without builtin-targets

---

probe-rs/src/config/memory.rs
probe-rs/src/config/target.rs
probe-rs/src/core/mod.rs
probe-rs/targets/STM32H7 Series.yaml

Add generic support for M7 chips by aliasing them to the same behaviour
as the M4 and the M3. Furthermore add the STM32H7 series as a new chip
family. I added them with a reduced sets of flash algorithms as all the
others were
1. For special eval boards
2. Caused false positives in the flash algorithm detection which made
cargo flash not work correctly anymore
TODO: GDB support is behaving kinda weird on my setup right now. I can't
step I can't really anything.

 Adding support for M7 and STM32H7

---

probe-rs/src/probe/jlink/mod.rs

I suppose this is just a mere typo.
I was experimenting with multi tap JTAG chain and noticed this bug.
More precisely total number of bits in IR register chain of GD32VF103 is 10, leading tms.len() == 16 and tdi.len() == 17, hence JayLink::jtag_io() complaining "TMS and TDI must have the same number of bits" .
note : JayLink::jtag_io() is actually counting byte-wise.

[FIX] typo: tms_enter_idle -> tdi_enter_idle

---

probe-rs/targets/STM32F3 Series.yaml

I built `cargo-flash` with the changes, but get the following error:
```
$ cargo flash --chip stm32f303k8tx --protocol swd
...
Error A core architecture specific error occured: Failed to write register CSW at address 0x00000000 because: An error specific to a probe type occured: JTAG does not support multiple APs.
```
Running the `ram_download` example with a `dbg!(Probe::list_all());` statement added gives this output:
```
[probe-rs/examples/ram_download.rs:29] Probe::list_all() = [
STLink V2-1 (VID: 1155, PID: 14155, STLink),
]
Error: "Failed to attach probe to target"
```

Add STM32F3 support

---

probe-rs/src/probe/daplink/mod.rs

Currently DAP probes always set a clock of 1MHz in `attach()`, even if `set_speed()` has been previously called. Since you can't call `set_speed()` after `attach()` (because the returned Session borrows the probe), this means there's no way to set the SWD speed.
This patch sets the speed at attach to whatever was previously set by `set_speed()`, which defaults to the same 1MHz, but allows users to call `set_speed()` on the Probe before calling `attach()`.
I removed the first `set_speed()` call and left the second one, because the there are no SWD transfers initiated due to connecting (so only the second call made any difference), and because sometimes the clock speed is reset by connecting (so it makes sense to set it afterwards instead of before).

Support setting SWD speed on DAP probes

---

probe-rs/src/probe/daplink/mod.rs

At the moment if you interrupt a programming session it can leave a response from the device still in the OS' HID buffer, so when you try to program again, the first response probe-rs sees is an old one to a previous command, which it rejects and quits. Of course, when you retry, you now see the response to that last command, and so on, which only recovers when you unplug and replug the probe.
By reading until the buffer is empty at connection time we ensure the next read is a response to our request and not stale data. In testing I can no longer reproduce the problem.

Drain USB HID buffer at connection

---

CHANGELOG.md
probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs
probe-rs/src/flashing/flasher.rs
probe-rs/src/probe/daplink/commands/transfer/mod.rs
probe-rs/src/probe/daplink/mod.rs
probe-rs/src/probe/mod.rs

This PR implements automatic queuing of `read_register` and `write_register` commands for CMSIS-DAP probes. I see a typical 1kB page program time improvement of **2.5x** with this enabled (290ms -> 118ms or 3.4kB/s -> 8.5kB/s), mainly because the `write32` and `read32` commands in `write_core_reg` during `call_function` are each run as a single CMSIS-DAP `DAP_Transfer` command instead of seven.
At first I tried to implement this by exposing a queue interface in DAPAccess, which then had to be exposed in APAccess and DPAccess, and then in MemoryInterface and ADIMemoryInterface, which ended up being really complicated, especially because APAccess and DPAccess are different traits so it wasn't clear how you combine AP and DP operations in a single queue.
Instead, this PR is much simpler …

Queue DAPlink read/write register commands

---

cli/src/common.rs
cli/src/info.rs
probe-rs/src/probe/mod.rs

This fixes the unattached error when determining the chip info from a probe.
Before a probe would always attach on creation.
Now this has to be done manually.

Adapt CLI to new attach

---

probe-rs/src/probe/mod.rs
probe-rs/src/probe/stlink/mod.rs
probe-rs/src/probe/stlink/usb_interface.rs

Improve error handling when multiple APs are not supported, as long as only a single one is used it now works fine. Also, the error is changed to indicate that the probe firmware should be updated.

Better handling of old ST-Links

---

probe-rs/src/probe/daplink/commands/mod.rs
probe-rs/src/probe/daplink/mod.rs
probe-rs/src/probe/daplink/tools.rs
probe-rs/src/probe/mod.rs

This PR adds support for CMSIS-DAP v2 compliant probes, using bulk transfers instead of HID interrupts. It's also called "WinUSB" but that mostly refers to the device descriptors telling Windows what driver to use and doesn't affect probe-rs.
I've modified the existing DAPlink code so the underlying `device` can now be an enum which is either a hidapi device or an rusb device, and implemented read and write methods on that enum. Consequently very little runtime code changes at all (the packet format is identical).
The main difference is in detecting and opening probes, which now uses `rusb` if possible. I've made sure if `rusb` doesn't work, it will always fall back to using `hidapi` to both enumerate and open the device. This is helpful because rusb might fail due to driver or permission …

Add support for CMSIS-DAP v2 probes

---

cli/src/debugger.rs
probe-rs/src/architecture/arm/core/m0.rs
probe-rs/src/architecture/arm/core/m33.rs
probe-rs/src/architecture/arm/core/m4.rs
probe-rs/src/architecture/arm/core/mod.rs
probe-rs/src/architecture/riscv/mod.rs
probe-rs/src/core/mod.rs
probe-rs/src/lib.rs

This is an intial draft of a status function, which can be used to retrieve the current state.
It is implemented for RISCV and Cortex-M4 currently. The other ARM cores would be similar.
It is trickier than expected, due to the need to cache the current core state for the Cortex-M4. This is necessary because the bits which indicate what the reason for the halt was are sticky, so we always need to clear them, otherwise you cannot reliably figure out what caused the reset. But this means that we have to cache the state, as we can get multiple calls to the status function and have to answer them.
Please have a look at this, especially also at `CoreStatus` and `HaltReason`, if this looks good.

Add status function (implement #138)

---

cli/src/common.rs

See #216 , the error message for no connected probes was wrong.

Show correct error message when no probe is detected

---

probe-rs/src/config/chip_family.rs

This fixes a bug where `ChipFamily::from_yaml_reader` would always return an error when being used. This also fixes the issues with `cargo-flash` and `cargo-embed`, as they just use this function.
To prevent further breakage, I added a simple test to see whether deserialization works :)

Fix flash algo deserialization

---

gdb-server/src/handlers.rs
gdb-server/src/worker.rs

* Make the endlessly polling function await_halt in worker.rs
sleep for 1ms on every iteration so we don't constantly draw
100 % from the CPU core we're running on
* Return a T02 instead of a T05hwbreak when a user requests a
break via an interrupt with Ctrl-c (stolen from OpenOCD, I don't
actually know the meaning of the 02)
* Previously await_halt would send a constant stream of T05hwbreak
to the GDB client once the core was haltet as await_halt was never
set to false when a breakpoint was hit, change this behaviour so
breaking actually works.

Performance and functionality improvements for gdb

---

gdb-server/src/handlers.rs
gdb-server/src/worker.rs

Some `vCont` commands and the memory-map command had a stray `b` at the end, which meant that they were not working.
This PR also add support for debugging with LLDB, using `gdb-remote <port>`.
LLDB is using some different commands, which we don't support (yet).
It gets confused when we reply with 'OK' to these, so we just send an empty
response now. With these changes, LLDB seems to work pretty well.
See also: https://github.com/llvm/llvm-project/blob/master/lldb/docs/lldb-gdb-remote.txt

Fix broken vCont and memory-map, add LLDB support

---

cli/src/common.rs
cli/src/debugger.rs
cli/src/info.rs
cli/src/main.rs
gdb-server/src/handlers.rs
gdb-server/src/worker.rs
probe-rs/examples/ram_download.rs
probe-rs/src/architecture/arm/ap/mod.rs
probe-rs/src/architecture/arm/communication_interface.rs
probe-rs/src/architecture/arm/core/m0.rs
probe-rs/src/architecture/arm/core/m33.rs
probe-rs/src/architecture/arm/core/m4.rs
probe-rs/src/architecture/arm/core/mod.rs
probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs
probe-rs/src/architecture/arm/memory/romtable.rs
probe-rs/src/architecture/arm/mod.rs
probe-rs/src/architecture/riscv/communication_interface.rs
probe-rs/src/architecture/riscv/mod.rs
probe-rs/src/config/target.rs
probe-rs/src/core/mod.rs
probe-rs/src/debug/mod.rs
probe-rs/src/flashing/builder.rs
probe-rs/src/flashing/download.rs
probe-rs/src/flashing/flasher.rs
probe-rs/src/flashing/loader.rs
probe-rs/src/flashing/visualizer.rs
probe-rs/src/lib.rs
probe-rs/src/memory/mod.rs
probe-rs/src/session.rs

This PR is intended to adjust the probe-rs API just slightly, such that the user can use it as conveniently as before while being threadsafe.
Before this change, the `Core`, `Memory`, `Session` etc. structs all contained an `Rc<RefCell<dyn T>>` with `T` being the respective interface trait. This enabled us to have `Core`, `Memory`, `Session` etc. implement clone such that the user could pass around objects conveniently without ever worrying about lifetimes etc.
While this is not very nice from an engineering view, it also can't be used across threads due to the nature of `RefCell<T>`.
While it is possible to just always operate probe-rs single threaded with taking turns on reading/writing to the probe and basically do this polling based, this is not very nice for implementers to use.
A …

API changes to make multithreading easier.

---

probe-rs/src/probe/stlink/mod.rs

Current code check if version < 28 and if not, it uses open_ap().
But then open_ap() ensure that version > 28.
So currently stlink with verion 28 is not working at all.
open_ap() should instead check that version >= 28.

Fix stlink version check

---

probe-rs/src/architecture/arm/ap/mod.rs
probe-rs/src/architecture/arm/communication_interface.rs
probe-rs/src/lib.rs
probe-rs/src/probe/mod.rs

I realized that the `nrf-recover` method is no longer included, which makes sense, it's probably not a good idea to start maintaining very vendor specific code, that's why I wrote an external utility to use probe-rs to do this, but I need these changes to make it work.

Modifications to allow an external nrf-recover utility

---

probe-rs/src/probe/daplink/tools.rs

This is a PR against #246 to slightly rejig the DAPlink part.
I moved the check that the device is valid to after checking the VID/PID inside the loop, which reduces unnecessary device opening/reading, and rework the HID fallback logic so we don't need the duplicated code and instead check that the HID device is a CMSIS-DAP probe before returning it.
I've tested this on a system with two DAPlink and one STlink devices running at once and was able to select any of them correctly by VID:PID or by VID:PID:SN.

Rework DAPlink scanning for new ProbeSelector

---

cli/src/info.rs
probe-rs/Cargo.toml
probe-rs/src/architecture/arm/ap/mod.rs
probe-rs/src/architecture/arm/dp/mod.rs
probe-rs/src/architecture/arm/memory/romtable.rs
probe-rs/src/architecture/riscv/communication_interface.rs
probe-rs/src/config/registry.rs
probe-rs/src/debug/mod.rs
probe-rs/src/error.rs
probe-rs/src/flashing/download.rs
probe-rs/src/flashing/error.rs
probe-rs/src/flashing/flasher.rs
probe-rs/src/probe/daplink/commands/general/connect.rs
probe-rs/src/probe/daplink/commands/general/info.rs
probe-rs/src/probe/daplink/commands/general/reset.rs
probe-rs/src/probe/daplink/commands/mod.rs
probe-rs/src/probe/daplink/commands/swj/sequence.rs
probe-rs/src/probe/daplink/mod.rs
probe-rs/src/probe/mod.rs

In conjunction with `anyhow` enabled applications this generates nicer
error messages like:
```
Error failed to flash /Users/egger/OSS/stm32f429i-disc/target/thumbv7em-none-eabihf/release/examples/serial_echo
Caused by:
0: Error while flashing
1: Something during the interaction with the core went wrong
2: An error with the usage of the probe occured
3: Operation timed out
```
or
```
Error failed attaching to target
Caused by:
0: An error with the usage of the probe occured
1: An error specific to a probe type occured
2: Command failed with status JtagGetIdcodeError
```

Start using anyhow for errors and get rid of manual error stacking

---

CHANGELOG.md
cli/Cargo.toml
gdb-server/Cargo.toml
probe-rs/Cargo.toml
probe-rs/src/lib.rs

I will add an entry to the changelog once https://github.com/probe-rs/probe-rs/pull/261 is merged, to avoid conflicts.

Make DebugProbeType public and prepare 0.7.1 release

---

probe-rs/src/config/chip.rs
probe-rs/src/config/chip_family.rs

Without this patch `target-gen` generates fields with value `~`

Annotate structs to not serialize Option fields when value is None

---

CHANGELOG.md
probe-rs/targets/STM32F7 Series.yaml

This PR adds the target descriptions for the STM32F7 series. I was able to successfully flash a STM32F730 using `cargo-flash` after applying these changes.

Add STM32F7 target descriptions

---

probe-rs/Cargo.toml
probe-rs/src/probe/jlink/mod.rs

On INFO level, log the following information:
- Serial number
- Firmware version
- Hardware version
Debug also includes capabilities:
Based on #285, merge that first.
Firmware version will look shitty until https://github.com/jonas-schievink/jaylink/pull/16 is merged and released.

J-Link: Log some useful information when attaching

---

probe-rs/src/lib.rs

* CoreInformation is used as return type in our debugging functions (halt, step etc.)
* Architecture is the return type of the architecture functions, defined for Core, Session etc.

Public types

---

cli/src/main.rs
probe-rs/examples/ram_download.rs
probe-rs/src/architecture/arm/communication_interface.rs
probe-rs/src/architecture/arm/core/m4.rs
probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs
probe-rs/src/architecture/riscv/communication_interface.rs
probe-rs/src/architecture/riscv/mod.rs
probe-rs/src/config/flash_algorithm.rs
probe-rs/src/core/mod.rs
probe-rs/src/flashing/error.rs
probe-rs/src/flashing/loader.rs
probe-rs/src/probe/daplink/commands/general/info.rs
probe-rs/src/probe/daplink/commands/swj/clock.rs
probe-rs/src/probe/daplink/commands/transfer/configure.rs
probe-rs/src/probe/daplink/commands/transfer/mod.rs
probe-rs/src/probe/daplink/mod.rs
probe-rs/src/probe/jlink/mod.rs
probe-rs/src/probe/mod.rs
probe-rs/src/probe/stlink/mod.rs
probe-rs/src/session.rs

* remove possible runtime panics from riscv code
* replace asserts by returned Err in stlink
* replace asserts by returned Err in jlink
* Remove DebugProbeError::Unknown
* Remove assert in daplink
* remove unreachable!
* replace panic by returning Err
* remove runtime assertion of flash_algorithm length, replace the magic number 4 with size_of
* change unwrap to anyhow error
Co-authored-by: René Rössler <rene@freshx.de>

Reduce runtime panics. Addresses #190

---

probe-rs/targets/STM32L5 Series.yaml

This PR adds the yaml file for stm32l5 family of targets, which was generated with https://github.com/probe-rs/target-gen

Add support for STM32L5 targets

---

probe-rs/src/probe/daplink/tools.rs
probe-rs/src/probe/stlink/tools.rs

See #301
Open for comments regarding explicit `cloned` calls and the usage of `rusb::Error::BadDescriptor`

Prevent index out of bounds for USB devices without language support

---

probe-rs/targets/STM32H7 Series.yaml

I rebuilt the STM32H7 targets with the latest target-gen, including a modification to sort Flash blocks. I then removed the algorithms for writing to external flash and checked that the RAM and flash addresses and lengths are correct for each STM32 based on its part number. In the process I changed all the addresses to hex to make it easier to check manually.
Compared to what was here previously, I've also removed the `stm32h7xx_mt25tl01g` and `stm32h7xx_mt25tl01g_dual` algorithms; I don't think they should have been included in the first place as they're used for programming off-chip MT25TL01 memories.
I'm fairly confident all these STM32H7 entries now:
* Have correct flash start and end addresses for their entire onboard flash memory
* Have suitable RAM start and end addresses for at …

Update STM32H7 targets

---

CHANGELOG.md
probe-rs/src/flashing/flasher.rs
probe-rs/src/flashing/progress.rs

Rename events to make naming more consistent, and ensure the events
are emitted in the correct places.

Cleanup flash ProgressEvent

---

probe-rs/src/probe/daplink/commands/swj/pins.rs

The [DAP_SWJ_Pins](https://arm-software.github.io/CMSIS_5/DAP/html/group__DAP__SWJ__Pins.html) command is two bytes and a word, so six bytes in total.

Fix command length on daplink DAP_SWJ_Pins

---

probe-rs/src/architecture/arm/core/m0.rs
probe-rs/src/architecture/arm/core/m33.rs
probe-rs/src/architecture/arm/core/m4.rs
probe-rs/src/session.rs

Always call `debug_core_start` when attaching. This ensures that the debug mode is always activated when a `Session` is created, regardless of the attach method.
The `reset_and_halt` function now doesn't  call the `debug_core_start` function anymore, which fixes #324 .
Tested with a board which requires attach under reset, and a board which does not require it.

Always call debug_core_start when attaching

---

probe-rs/src/session.rs

I refactored this bit of code into `get_arm_interface` earlier but didn't spot this other instance of it.

Small tidyup in session.rs

---

probe-rs/examples/tcp_itm.rs
probe-rs/src/architecture/arm/component/mod.rs
probe-rs/src/architecture/arm/swo/mod.rs
probe-rs/src/probe/stlink/mod.rs

After chatting with @jonas-schievink about jlink today it seems like adding this new optional `poll_interval_hint` could be useful: right now we don't have anything for end user applications to do except poll `read_swo` in a loop, and no way to know how frequently they should poll. For some probes (cmsis-dap in bulk endpoint mode) it doesn't matter; they can just block waiting for new data. However for polled probes (jlink, cmsis-dap without bulk endpoint, stlink), it wastes USB bandwidth and CPU time to send polls too often. Probe drivers know the SWO buffer size and baud rate, so they can estimate how frequently it makes sense to poll.
I've also extended `SwoConfig` in two ways:
* It now has a constructor and accessor methods, rather than pub fields. This way we can add additional …

SwoAccess and SwoConfig updates

---

probe-rs/src/architecture/arm/ap/memory_ap/mock.rs
probe-rs/src/architecture/arm/ap/mod.rs
probe-rs/src/architecture/arm/communication_interface.rs
probe-rs/src/architecture/arm/component/mod.rs
probe-rs/src/architecture/arm/core/m0.rs
probe-rs/src/architecture/arm/core/m33.rs
probe-rs/src/architecture/arm/core/m4.rs
probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs
probe-rs/src/architecture/riscv/communication_interface.rs
probe-rs/src/architecture/riscv/mod.rs
probe-rs/src/core/communication_interface.rs
probe-rs/src/core/mod.rs
probe-rs/src/memory/mod.rs
probe-rs/src/probe/daplink/mod.rs

This PR is @bcantrill's https://github.com/oxidecomputer/probe-rs/commit/a12a8ffc0d537fb74d31fc5dc1e763a5deda9fc8 plus adding a call to `flush()` to `setup_swv()`. The commit message describes the motivation:
> With probes batching writes, there is a need for higher-level
software to flush any buffered writes.  This assures that (say)
operations like run() do not run the risk of returning to the caller
with their operations not sent to the MCU.  (This issue was the
reason for failures in SWO processing on the LPC55, as higher level
software's resume of the halted part was not, in fact, resuming
the part.)

Add flush method to Probe interface

---

probe-rs/src/probe/daplink/commands/general/host_status.rs
probe-rs/src/probe/daplink/commands/general/mod.rs
probe-rs/src/probe/daplink/mod.rs

The [DAP_HostStatus](https://arm-software.github.io/CMSIS_5/DAP/html/group__DAP__HostStatus.html) command lets probe-rs tell the probe that it is connected or not and the target is running or not.
It seems a bit difficult to work out if the target is running at the probe level, but it's very easy to send this command for the 'connected' state during attach and detach, which is what this PR does. The status LED on my CMSIS-DAP probe now lights up during flash programming and SWO printing.
I ignore errors when calling this because it's entirely non-essential functionality, so it would be a shame to error out if for example some probe reported that it didn't support this command. That said probes _should_ all support it, so I could raise the errors up instead.

Add HostStatus command to daplink, allowing control of probe LEDs

---

probe-rs-t2rust/src/lib.rs
probe-rs/build.rs

* Show an error message when the build script is unable to run
rustfmt.
* Don't generate a struct without values for the JEP106 code in the
target generation. The whole struct should be `None` in that case.

Improve target generation

---

probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs

The aligned_range function could panic when called with a range
right at the end of allowed values in u32.
This just fixes the panic, long-term we should find a way
to build an inclusive range which can include the maximum u32 value.

Fix panic in aligned_range

---

gdb-server/Cargo.toml
gdb-server/src/handlers.rs
gdb-server/src/lib.rs
gdb-server/src/parser/mod.rs
gdb-server/src/parser/query.rs
gdb-server/src/parser/util.rs
gdb-server/src/parser/v_packet.rs
gdb-server/src/worker.rs

Use `nom` to parse GDB packets into an Enum, which allows cleaner handling of them. Should make it easier to expand the GDB server to more packets.

Use nom based parser for GDB packets

---

README.md

I think it's worth adding instructions as the dependencies grow. I kept the instructions brief because I think most people reading the readme can figure out how to install the dependencies on their platform of choice once they know what they are. I expanded on the Windows instructions because vcpkg is newer and probably less familiar and it has some nuance with target triplets and env variables. It may not be obvious to look at a build-dependency of a dependency to find the vcpkg crate documentation.

Add brief build instructions to README.md

---

probe-rs/src/probe/daplink/tools.rs

The SWO endpoint on CMSIS-DAP probes is optional, so we shouldn't
panic if it doesn't exist.

Only check SWO endpoint if it exists

---

probe-rs/src/architecture/riscv/mod.rs
probe-rs/src/session.rs

To clean all HW breakpoints on RISCV, core needs to be halted.
This is also more consistent with the behaviour on ARM.
Should fix #352

Halt RISCV cores on attach

---

probe-rs/src/config/registry.rs
probe-rs/src/session.rs
probe-rs/targets/STM32WB Series.yaml

The autodetect code was not verifying that only a single chip with
the given manufacturer and part ID exists in the registry.
This led to problems with some STM32 chips, as the part-number is
not unique for them. It might also be a problem for other chips.
This commit fixes this by returning an error if more than a single
chip is found, to ensure no chips are wrongly detected.

Only autodetect chips if there is a unique chip found

---

cli/src/info.rs
probe-rs/src/architecture/arm/ap/memory_ap/mock.rs
probe-rs/src/architecture/arm/ap/mod.rs
probe-rs/src/architecture/arm/communication_interface.rs
probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs
probe-rs/src/architecture/arm/memory/mod.rs
probe-rs/src/architecture/arm/mod.rs
probe-rs/src/architecture/riscv/communication_interface.rs
probe-rs/src/architecture/riscv/mod.rs
probe-rs/src/core/mod.rs
probe-rs/src/probe/daplink/mod.rs
probe-rs/src/probe/ftdi/mod.rs
probe-rs/src/probe/jlink/mod.rs
probe-rs/src/probe/mod.rs
probe-rs/src/probe/stlink/mod.rs
probe-rs/src/session.rs

Proposal for a refactor of the code responsible for ARM cores. The goal is to move the creation of the actual interface to the probe,
to make it easier to support different probes.
The ideas is that a Probe is responsible for creating the `ArmCommunicationInterface`, or a similar struct. The ST-Link for example could then create another implementation of this, which supports the ST-Link API better.

Refactor ARM Memory code

---

probe-rs/src/architecture/arm/core/m0.rs

the current logic matches both halfwords, meaning that given the following machine code:
``` text
000003e0 DefaultPreInit:
3e0: 70 47                         bx      lr
000003e2 HardFaultTrampoline:
3e2: 70 46                         mov     r0, lr
```
if you place a breakpoint at `HardFaultTrampoline` (address = `0x3e2`) then that breakpoint also triggers when `DefaultPreInit` is invoked
with this PR the breakpoint only fires when `HardFaultTrampoline` is called

m0/set_breakpoint: match a single halfword

---

probe-rs/src/probe/stlink/mod.rs
probe-rs/src/probe/stlink/usb_interface.rs

This fixes SwdDpWait errors with probe-run with certain binaries.
I took the opportunity to do some minor refactoring:
- Centralized all JTAG commands to use `send_jtag_command`, so the retry applies to all
- changed `cmd` from `Vec<u8>` to `&[u8]`. This avoids having to clone it in send_jtag_command when retrying, since `device.write` no longer requires an owned vec.
each is a separate commit, so review is easier :) 
download and extract this: [nonworking.elf.tar.gz](https://github.com/probe-rs/probe-rs/files/5198640/nonworking.elf.tar.gz)
and then:
```
[dirbaio@mars example]$ probe-run --chip nRF52840_xxAA --defmt nonworking.elf 
(HOST) INFO  flashing program
(HOST) INFO  success!
────────────────────────────────────────────────────────────────────────────────
Error: Error communicating …
```

stlink: send_jtag_command retry if target returns SwdApWait/SwdDpWait.

---

probe-rs/src/architecture/arm/communication_interface.rs
probe-rs/src/probe/stlink/constants.rs
probe-rs/src/probe/stlink/mod.rs

This uses the dedicated APIs for memory read / write and core register read / write on ST-Links.
This improves the flash speed from about 121 kB/s Erase and 15 kB Write to about 145 kB/s Erase and 30 kB/s Write :rocket:,
measured with a ST-Link v2 with a SWD Frequency of 4.6 MHz.
The API is still a bit of a mess now, but I assume that with the support for debug sequences, this will have to be adapted anyway.

Use dedicated ST-Link APIs

---

probe-rs/src/probe/daplink/tools.rs

This resolves an issue where specifying `--probe vid:pid` meant a CMSIS-DAP device was only ever opened in V1 mode, even if it was V2 capable, because it always tried to match using the SN too.

CMSIS-DAP: Match only on VID/PID if no SN is specified

---

README.md
probe-rs/targets/SAM D Series.yaml
probe-rs/targets/SAMD51.yaml

hey this is, so cool! i'm trying to flash some atmel/microchip ICs and found a missing target, then couldn't work out how to generate the required files to add them. So, this PR:
- adds target files for ATSAMD21, ATSAMD51, generated from the related Kiel packs
- adds a note on target file generation to the readme to help others looking for the same
(thanks @nzsmartie for the tip!)

Added target files for ATSAMD21, ATSAMD51

---

probe-rs/src/probe/stlink/mod.rs

This follows the pattern already implemented for 8-bit writes; small reads go in one 8-bit read, while large reads are split into three phases with the bulk of the transfer done with aligned 32-bit reads.
There is an extra restriction on reads, which is that they must read at least 2 bytes. When 1 is requested, 2 are read and then the returned buffer is truncated to the requested length of 1 before it is returned.
I've exercised (on a stlinkv2 clone) both the small 8-bit read and the large 3-phase read, including when one of the 8-bit reads is only 1 byte, and it seems to be working properly in all cases I've seen so far.

Implement chunking of large 8-bit reads for stlinkv2/v3

---

probe-rs/targets/EFM32PG12B Series.yaml

Extracted from `SiliconLabs.GeckoPlatform_EFM32PG12B_DFP.3.0.0.pack`
Removed duplicates. Differences between the contained chips is only the temperature range.

Add EFM32PG12 target

---

gdb-server/src/parser/v_packet.rs
probe-rs/examples/tcp_itm.rs
probe-rs/src/architecture/arm/swo/decoder.rs
probe-rs/src/architecture/riscv/communication_interface.rs
probe-rs/src/core/mod.rs
probe-rs/src/flashing/builder.rs
probe-rs/src/probe/daplink/tools.rs
probe-rs/src/probe/ftdi/ftdi_impl.rs
probe-rs/src/probe/ftdi/mod.rs
probe-rs/src/probe/jlink/mod.rs
probe-rs/src/probe/stlink/mod.rs
probe-rs/src/session.rs

I did this some time ago and thought this might as well be of some use.
The nested `if` and `<< 0` are arguably worse now, not sure if you just
want to have the clippy warning on, want an ignore or want the lint
applied. The `default` is also a bit useless...idk
I don't see a way to fix the two remaining `.collect` and `Box<Self>` warnings.

apply some clippy hints to remove them from showing up in code review

---

probe-rs-cli-util/Cargo.toml
probe-rs-cli-util/src/lib.rs
probe-rs-cli-util/tests/cargo_integration.rs

fixes [probe-rs/cargo-embed#119]
switch from `fs::canonicalize` to `dunce::canonicalize` to canonicalize file paths for better path-handling on windows.  On all other targets `dunce::canonicalize` drops to the standard `fs::canonicalize`.
Tested with [cargo-embed-workspace](https://github.com/berkowski/cargo-embed-workspace) on windows and was able to compile the virtual workspace with `cargo embed`

use `dunce` crate for path conanicalized paths

---

probe-rs/src/architecture/arm/ap/mod.rs
probe-rs/src/architecture/arm/communication_interface.rs
probe-rs/src/architecture/arm/core/m0.rs
probe-rs/src/architecture/arm/core/m33.rs
probe-rs/src/architecture/arm/core/m4.rs
probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs
probe-rs/src/memory/mod.rs
probe-rs/src/probe/stlink/mod.rs
probe-rs/src/probe/stlink/usb_interface.rs

With this PR, the dedicated ST-Link APIs for register read / write are used.
This complicates the whole API a bit, by creating an additional `ArmProbe` trait, which offers both memory access,
as well as register access.
@mvirkkunen  The API for the debug sequences is probably also influenced by this. From what I've seen, the debug sequences need access to memory read write, AP/DP read write, as well as direct access to the individual pins. Would it make sense to extend the new `ArmProbe` trait, so that this can be handled, or do you have other ideas already?
(This is split-off from #369)

Use dedicated ST-Link API for CPU Register Read / Write

---

probe-rs/src/architecture/arm/ap/mod.rs
probe-rs/src/architecture/arm/communication_interface.rs
probe-rs/src/architecture/arm/dp/mod.rs
probe-rs/src/flashing/error.rs
probe-rs/src/flashing/flasher.rs
probe-rs/src/probe/daplink/mod.rs
probe-rs/src/probe/jlink/mod.rs

In https://github.com/probe-rs/probe-rs/issues/395 we found that when scanning for aps to use, the second ap seemed to make the probe unusable going forward. 
https://developer.arm.com/documentation/ka001433/1-0/?search=5eec6f69e24a5e02d07b2655
> The Stick Error flag, STICKYERR, as defined in the ARM Debug Interface v5 Architecture Specification, can come from either:
>    Error signals returned from the Debug Bus or slave debug component to the Access Port (AP).
>    The Debug Port (DP) trying to access an AP that is not present. For example, it is powered down or is not present at that address, or from protocol errors in Serial Wire. 
In attempting to clear that bit, it seemed to me the abort register was indexed incorrectly. 
https://developer.arm.com/documentation/ddi0413/c/debug-acces …

Cleanup after fault, fix abort bit layout

---

probe-rs/src/architecture/riscv/communication_interface.rs

The implicit ebreak after the last program buffer word can only be used when the whole program buffer is used, otherwise we need to add the ebreak command explicitly.
@Disasm This should fix the debugging problems with GDV32, could you please try it again?

[RISCV] Fix program buffer handling

---

probe-rs/src/architecture/arm/core/m0.rs

The address mask used when setting the breakpoint comparator register on Cortex-M0(+) devices does not match the specification in the declaration of the BpCompx register ([m0.rs#L126](https://github.com/probe-rs/probe-rs/blob/master/probe-rs/src/architecture/arm/core/m0.rs#L126)). Bits 26-28 of the address are cleared when they should not be, causing breakpoints set at addresses higher than 0x03ffffff to end up at the wrong location.
This PR sets the correct mask according to the specification.

M0: Use correct mask when setting breakpoint

---

probe-rs/src/probe/stlink/mod.rs

Fix for panic during ST-Link 8-bit memory reads (#425). Split the reads into 64-byte chunks as suggested in the issue.

Divide 8-bit reads into chunks of 64 bytes to satisfy ST-Link v2 max length

---

probe-rs/src/session.rs

The title says it all. Now an auto attach error can be caught by user code

Session auto attach no longer panics when no probes are connected

---

probe-rs/src/probe/jlink/mod.rs

Improvements to the SWD protocol handling for JLInk:
- Add idle cycles after a register write, to ensure it is actually performed.
This is only necessary when no other command is performed afterwards, but
is now done everytime, for increased stability. It also helps with avoiding
WAIT responses for the next requests, after the writes.
- When we don't receive a response from the target, perform a line reset to
try and recover.

Improved protocol error handling for JLink

---

probe-rs/targets/SAMD11.yaml

Following the instructions @ryankurte left in the README.md, to add the Microchip ATSAMD11 targets.  Thanks!

Add Microchip SAMD11 to supported targets

---

probe-rs/src/architecture/arm/communication_interface.rs
probe-rs/src/probe/daplink/mod.rs
probe-rs/src/probe/jlink/mod.rs

To avoid protocol errors in case of WAIT or FAULT responses,
we use the *sticky overun* behaviour of the debugport.
This behaviour means that WAIT and FAULT responses are also followed
by the normal data phases, instead of stopping immediately like normal.
We cannot stop the data transmission on the JLink, so this helps
avoiding protocol errors and should improve performance.

Use sticky overrun behaviour for improved JLink performance

---

probe-rs/src/probe/jlink/mod.rs
probe-rs/src/probe/mod.rs

Change to return `Vec<DebugProbeInfo>` instead of `Result<impl Iterator>` to match the other `list_x_devices()` methods and prevent a jlink error from stopping other drivers operating. The original patch was only a two-line change but sadly rustfmt had other ideas!
Closes #399.
I don't have any j-link probes, so this is untested beyond checking it builds.

Return plain Vec<DebugProbeInfo> from list_jlink_devices()

---

CHANGELOG.md
cli/src/info.rs
probe-rs/src/architecture/arm/ap/generic_ap.rs
probe-rs/src/architecture/arm/ap/memory_ap/mod.rs
probe-rs/src/architecture/arm/communication_interface.rs
probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs
probe-rs/src/architecture/arm/mod.rs
probe-rs/src/probe/stlink/mod.rs
probe-rs/src/session.rs

Add support for the HNONSEC bit, which is used in the CSW register of a MemoryAP.
Support for the HNONSEC bit is automatically detected, and it is set to 0, meaning secure access,
if it's supported.
This might fix #404, and might help with #310.

Add support for HNONSEC bit in CSW register (MemoryAP)

---

probe-rs/targets/STM32WB Series.yaml

The flash address for some chips were wrong, which
meant that probe-rs was unable to find the correct
flash algorithm.

Update target description for STM32WB55 (fix #466)

---

probe-rs/src/architecture/arm/communication_interface.rs
probe-rs/src/core/mod.rs
probe-rs/src/session.rs

Two small changes:
Currently we try to clean all HW breakpoints when dropping,
which can make the log output very confusing when some error 
occurs. It should be sufficient to just clean the breakpoints
we actually configured ourselves.
When the information for an AP is missing, we currently panic.
As a first step, this is replaced by an error with this PR.
In the future, this should probably be handled better, especially
when multiple cores are used.

Avoid panic when AP doesn't exist, clean-up log

---

probe-rs/src/flashing/download.rs

download_hex was returning before loading the buffer

probe-rs: fix download_hex

---

probe-rs/src/architecture/arm/communication_interface.rs
probe-rs/src/probe/daplink/commands/mod.rs
probe-rs/src/probe/daplink/mod.rs
probe-rs/src/probe/ftdi/mod.rs
probe-rs/src/probe/jlink/mod.rs
probe-rs/src/probe/mod.rs
probe-rs/src/session.rs

Simplify some probe implementations by not requiring the Session to
be `Sync`.

Remove internal Mutexes

---

probe-rs/src/probe/ftdi/mod.rs

Add another valid usb vendor id / product id pair to ftdi backend.
Tested, at least jtag scanning works, so communication is probably ok.

added FTDI C232HM-DDHSL-0 to compatible usb id list

---

gdb-server/Cargo.toml
gdb-server/src/bin.rs

I made some improvements to the gdb-server cmdline included in the repository.
The cmdline is not probably not really used that much, because projects like cargo-embed exist.
Anyway, I want to add these improvements, because the gdb-server makes it easy to test other parts of probe-rs, and I intend to do some testing / improving of the riscv target.

Improve gdbserver cmdline

---

probe-rs/src/architecture/riscv/communication_interface.rs
probe-rs/src/architecture/riscv/mod.rs
probe-rs/src/core/mod.rs

Instead of using program buffer for accessing (almost) all CSR, try to use abstract commands directly access CSR. If a given CSR fails with abstract cmd err 2 (unsupported), the program buffer is used as a fallback strategy.
The given read / write failure is also stored in a cache, and the next try on the same register will use the program buffer directly.
This leads to a massive (almost 4x) speedup of e.g. discovering breakpoints in get_available_breakpoint_units().
I tested this against a GD32V riscv core with a ftdi based debug probe.

riscv: try to use abstract commands for CSR access (speed improvement)

---

probe-rs-t2rust/src/lib.rs

Rename `Flash` to `Nvm` in probe-rs-t2rust, otherwise the flash ranges are not included in the built-in targets.

Rename flash to Nvm in probe-rs-t2rust

---

gdb-server/Cargo.toml
gdb-server/src/bin.rs

failure is not supported anymore, so it's best to replace it with anyhow.

Replace failure with anyhow

---

probe-rs/targets/nRF52 Series.yaml

- Changed all addresses to hex (much more readable!)
- Removed unused old flash algos
- Added nrf52_uicr flash algo, which is identical to the main one (the algo checks the address and does the right thing)
- Added uicr NVM region to all chips.

Add support for flashing nrf52 uicr

---

probe-rs/src/probe/mod.rs

Before:
[0]: Dual RS232-HS (VID: 0403, PID: 6010,  FTDI)
[1]: J-Link (J-Link) (VID: 1366, PID: 0101, Serial: 00026010xxxx, JLink)
After:
[0]: Dual RS232-HS (VID: 0403, PID: 6010, FTDI)
[1]: J-Link (J-Link) (VID: 1366, PID: 0101, Serial: 00026010xxxx, JLink)
(Double whitespace in front of "FTDI" is now gone.)

Fix double whitespace in DebugProbeInfo

---

probe-rs/Cargo.toml
probe-rs/src/flashing/download.rs

Reduce the number of dependencies by replacing the `goblin` crate with `object`, which we're already using anyways.

Replace goblin crate with object crate

---

probe-rs/src/architecture/riscv/communication_interface.rs

`abstractauto` was incorrectly specified as being at 0x38, which is actually the address of `sbcs` (which is specified correctly).
Implementations may choose not to implement `abstractauto` -- in this case writes to the register are ignored, and reads produce all zeros. The following code attempts to detect it, by writing a 1 and seeing if is read back:
https://github.com/probe-rs/probe-rs/blob/205a8088aa8f9f303ba1a162fc7417b9517bad58/probe-rs/src/architecture/riscv/communication_interface.rs#L255-L265
Here's what that looks like in practice:
```
DEBUG > Write DM register 'abstractauto' at 0x00000038 = 0x00000001
DEBUG > Reading DM register 'abstractauto' at 0x00000038
DEBUG > Read DM register 'abstractauto' at 0x00000038 = 0x20040407
DEBUG > Support for autoexec: false
```
`0x20040407` …

riscv: fix abstractauto register address

---

probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs

Cache the CSW register, so that it's only written when necessary.

Cache value of CSW register

---

probe-rs/src/probe/jlink/mod.rs
probe-rs/src/probe/mod.rs
probe-rs/src/probe/stlink/mod.rs

Added `get_target_voltage()` to `DebugProbe`, based off the original implementation of it
on `STLink`, but generalised to return `Result<Option<f32>, DebugProbeError>` to allow for
probes which don’t support reading target voltage. Added a default implementation on the
trait which returns `Ok(None)`.
Added a `LOW_TARGET_VOLTAGE_WARNING_THRESHOLD` constant to the `probe` module, currently
set to 1.4V as an initial guideline.
Implemented `get_target_voltage()` on `STLink` and `JLink`, based off existing code which
did a similar thing.
Altered `STLink::attach()` and `JLink::attach()` to use `get_target_voltage()` and
`LOW_TARGET_VOLTAGE_WARNING_THRESHOLD` for consistent target voltage reporting.

Implemented Target Voltage Measurement

---

probe-rs/src/probe/jlink/mod.rs
probe-rs/src/probe/jlink/swd.rs

With these changes, errors related to WAIT states seem to be gone in my tests with a JLink (up to 4MHz SWD).
The `SwdStatistics` and `SwdSettings` structs are not very useful right now, but the goal would be to make them available on the Probe or Session, so that they can be used for testing. I would prefer to merge this PR already, without implementing this part,
as the improved SWD communication alone should be a useful improvement.

Improved SWD WAIT state handling for JLink

---

probe-rs/Cargo.toml

bitvec doesn't compile anymore, due to an update in the `funty` crate.
Fixing the `funty` version to 1.1.0 is a temporary workaround for this.
See https://github.com/bitvecto-rs/bitvec/issues/105.

Fix funty to version 1.1.0 to ensure bitvec compiles

---

probe-rs/targets/EFR32BG21 Series.yaml
probe-rs/targets/EFR32BG22 Series.yaml
probe-rs/targets/EFR32FG12P Series.yaml
probe-rs/targets/EFR32FG13P Series.yaml
probe-rs/targets/EFR32FG14P Series.yaml
probe-rs/targets/EFR32FG14V Series.yaml
probe-rs/targets/EFR32FG1P Series.yaml
probe-rs/targets/EFR32FG22 Series.yaml
probe-rs/targets/EFR32MG12P Series.yaml

Adds support for various SiLabs EFR32 targets, generated using `target-gen`, while removing duplicates.

Add EFR32 targets

---

Cargo.toml
probe-rs-target/Cargo.toml
probe-rs-target/src/chip.rs
probe-rs-target/src/chip_family.rs
probe-rs-target/src/flash_algorithm.rs
probe-rs-target/src/flash_properties.rs
probe-rs-target/src/lib.rs
probe-rs-target/src/memory.rs
probe-rs/Cargo.toml
probe-rs/src/config/flash_algorithm.rs
probe-rs/src/config/mod.rs
probe-rs/src/config/registry.rs
probe-rs/src/config/target.rs
probe-rs/src/flashing/loader.rs

As discussed in Matrix, it would be nice to replace `t2rust` with embedding the YAMLs in the binary. The advantage is that we don't have to maintain two parsers for the YAML format.
This is a previous step to achieve that: separate all the structs defining the YAML schema into its own crate, so it can be used from build.rs and other crates.

Split target description schema to its own crate.

---

probe-rs-target/src/chip.rs
probe-rs-target/src/chip_family.rs
probe-rs-target/src/flash_algorithm.rs
probe-rs-target/src/flash_properties.rs
probe-rs/src/config/flash_algorithm.rs
probe-rs/src/config/registry.rs
probe-rs/src/config/target.rs
probe-rs/src/flashing/builder.rs

The reason for Cow was to be able to use Borrowed in t2rust-generated code, but that no longer applies. IMO it is more readable without Cow, and I can't think of any downside.
:no_entry_sign: :cow:

Remove Cow in probe-rs-target.

---

probe-rs/src/config/mod.rs
probe-rs/src/flashing/builder.rs
probe-rs/src/flashing/flash_algorithm.rs
probe-rs/src/flashing/flasher.rs
probe-rs/src/flashing/loader.rs
probe-rs/src/flashing/mod.rs

The FlashAlgorithm struct contains actual flashing logic (mostly setting up the algo ASM and stack), rather than just configuration. This PR moves it to the `flashing` module.

Move FlashAlgorithm from `config` to `flashing` module.

---

probe-rs/src/flashing/loader.rs

NOTE: I haven't actually tested this because I don't have any chip with such "contiguous" memory ragions,
but I'm like 90% sure this is a bug.
The MemoryRegion end address is exclusive (ie 0x2000_1000, not 0x2000_0fff). If we're
flashing a big data block at0x2000_0000, `program_length` needs to be 0x1000,
but the previous calculation gave 0x1001.

Fix off-by-one error splitting data overlapping multiple MemoryRegions.

---

probe-rs/src/flashing/download.rs

Path itself is unsized, without this you can't pass an actual &Path as `path` arg.

Allow unsized AsRef<Path>

---

probe-rs/Cargo.toml

This PR removes the sub-dependencies `flate2`, `indexmap`, `wasmparser` by disabling all expect required features for `gimli` and `object`. Also it ~~bumps `rusb` to `0.8.0` and~~ sorts the dependencies.
Fixes #559 
The compile time decreases by `~6s` in release mode and `~3s` in dev mode. All of this is only tested on my laptop, but should still give a good enough estimate.
* `master` (17c71ef72a4b1d7635517626af5966a9aeb730e3)
* `cargo clean && cargo build`
* 35.45s
* 36.62s
* 34.91s
* `cargo clean && cargo build --release`
* 1m 02s
* 57.50s
* 57.75s
* `minimize-deps` (de68f2582763d59cdbfa987ed4323eb622223ab3)
* `cargo clean && cargo build`
* 32.95s
* 32.48s
* 32.92s
* `cargo clean && cargo build --release`
* 52.01s
* 53.08s
* 51.66s
... _(someone knows a good approach for this?)_

Minimize deps

---

probe-rs/src/flashing/download.rs

We need to make sure that the only loadable sections are actually
downloaded to the core. This check seems to be missing currently.
Fixes #581

Only load segments with type PT_LOAD

---

probe-rs/Cargo.toml
probe-rs/src/probe/jlink/mod.rs

Released `jaylink` currently uses 0.6.3 of `rusb`.
Upstream uses `0.8.0` which matches our used version.
This is required because it will lead to segfaults on macOS otherwise.

Fix jaylink dependency by temporarily using upstream

---

probe-rs/Cargo.toml

Removes `anyhow` and `structopt` from library dependencies and thereby reduces dependency count from 115 to 97 in `release`- and from 101 to 83 in `dev`-mode **!** (see diff below).
Blocker
**diff** (produced by `cargo tree -e normal`)
```diff
probe-rs v0.10.1
├── anyhow v1.0.38
├── base64 v0.13.0
├── bincode v1.3.2
│   ├── byteorder v1.3.4
│   └── serde v1.0.124
│       └── serde_derive v1.0.124 (proc-macro)
│           ├── proc-macro2 v1.0.24
│           │   └── unicode-xid v0.2.1
│           ├── quote v1.0.9
│           │   └── proc-macro2 v1.0.24 (*)
│           └── syn v1.0.63
│               ├── proc-macro2 v1.0.24 (*)
│               ├── quote v1.0.9 (*)
│               └── unicode-xid v0.2.1
├── bitfield v0.13.2
├── bitvec v0.19.5
│   ├── funty v1.1.0
│   ├── radium v0.5.3
│   ├── …
```

Disable default-features of dep `itm-decode`

---

probe-rs/src/flashing/loader.rs

- Fixed u16 overflow in ExtendedSegmentAddress.
- ExtendedSegmentAddress is now taken into account.
- Address offset is added, not ORed.
This matches what python intelhex does: https://github.com/python-intelhex/intelhex/blob/c9beea9f1000d632057efa7ee15f8d1645d0ca97/intelhex/__init__.py#L140-L167

Fix hex flash loading.

---

probe-rs/src/flashing/builder.rs
probe-rs/src/flashing/download.rs
probe-rs/src/flashing/loader.rs

This PR includes 2 usability improvements to the flashing API:
- FlashLoader/FlashBuilder own the data with `Vec<u8>`s, instead of borrowing it. This makes the `buffer: &'buffer mut Vec<Vec<u8>>` arguments in `load_xx_data()` no longer needed.
- use DownloadOptions struct in `FlashLoader::commit()`. More consistent with the `download_xx` APIs, and not having many bools in arguments makes user code more readable.
Commits best reviewed separately.

Flashing API improvements

---

probe-rs-cli-util/Cargo.toml
probe-rs-cli-util/src/lib.rs

Export the `indicatif` and `log` crates to avoid versioning problems with the `cargo-embed` and `cargo-flash` crates.

Export libs from util

---

probe-rs/src/architecture/riscv/communication_interface.rs

It looks like the hart scanning code for riscv uses the wrong status bit in the dmstatus register.
On my chip (GD32V), this causes the debugger to scan through 2^10 harts, which takes quite a while.
Use anynonexistent flag instead, for determining a non-existing hart index.
https://raw.githubusercontent.com/riscv/riscv-debug-spec/master/riscv-debug-stable.pdf section 3.3 describes the recommended procedure for scanning harts.

Fix riscv backend hart scanning

---

probe-rs/src/architecture/riscv/communication_interface.rs

I bisected the codebase, and found, that the following commit introduced the regression: 63eb1379b47f1353239b287bd665d5ab983962df
Turns out, this is not the real bug, but it made the bug manifest itself.
enter_debug_mode() probes for autoexec capability, but forgets to reset the register in the dm. This causes spuriously executed abstract commands on hardware implementations, that support autoexec.
To fix the issue, clear the register after probing.

fix riscv abstract command handling (register writes failing)

---

probe-rs/src/probe/stlink/mod.rs

Before this PR, reads of a single byte on ST-Link were extended
to a read of 2 bytes, to work around some issues with the ST-Link.
This is problematic when trying to read the last byte in
a memory region, the extended read will then read from
another part of memory, which can fail.
Reading just a single byte seems to work, but the buffer for returned
data has to be at least two bytes in size, otherwise a USB overflow
occurs.
This has only been tested on a ST-Link v2.

Fix 8 bit reads on ST-Link

---

probe-rs/src/architecture/arm/core/m0.rs
probe-rs/src/architecture/arm/core/m33.rs
probe-rs/src/architecture/arm/core/m4.rs
probe-rs/src/flashing/flasher.rs

Previously, when waiting for a flash algorithm routine to complete, the algorithm on the host side would poll the core state relentlessly, leading to frequent timeouts when polling longer operations, such as sector erase, for completion. Now we do two things: a) we honor the timeouts given to us with the flash algorithm description files properly, and b) we poll the core at maximum once per 10ms with increasing delays each time. This results in significantly less traffic and as a nice byproduct way less log traffic.

Fix a bus congestion when polling the chip too often.

---

probe-rs/src/flashing/builder.rs
probe-rs/src/flashing/download.rs
probe-rs/src/flashing/error.rs
probe-rs/src/flashing/flash_algorithm.rs
probe-rs/src/flashing/flasher.rs
probe-rs/src/flashing/loader.rs

This PR refactors the FlashBuilder code, to simplify it.
- FlashLoader owns all the data in a `BTreeMap<u32, Vec<u8>>`
- FlashLoader has a `data_in_range` function allowing iterating data inside a range. Data blocks that are not fully contained inside the range are cut, so calling code can assume all the returned blocks are fully contained, drastically simplifying the code.
- FlashBuilder iterates over all sectors and pages, requesting data contained in them using `data_in_range`.
The new FlashBuilder passes all the existing tests with no modifications (ignoring order, because the old code returned unsorted data in one test and the new code always returns sorted data)
TODO:

FlashBuilder refactor

---

debugger/src/debugger.rs
probe-rs/src/flashing/download.rs
probe-rs/src/flashing/flasher.rs
probe-rs/src/flashing/loader.rs

Hi there,
This pull request added a flag at `DownloadOption` that allows the user to skip the erasing.  
This flag is helpful for mass production, especially in some cases the chip can be erased with external erasing rigs. To be more specific, CMSIS pack does not provide chip erasing support for some chips like STM32L031K6U6, but the reference manual does indicate that it supports chip erase by toggling RDP bit. So I have made my own chip eraser tool for it. However, probe-rs always re-erase the chip even though the chip is cleared before, as it is impossible to skip the erasing. Therefore here's the PR for adding skip erase support.
Regards,
Jackson

flasher: allow skip erasing

---

probe-rs/src/architecture/arm/core/m0.rs
probe-rs/src/architecture/arm/core/m33.rs
probe-rs/src/architecture/arm/core/m4.rs
probe-rs/src/architecture/arm/core/mod.rs
probe-rs/src/core/mod.rs

The status bits used for the core status are sticky, so we need to ensure
that we read the status register when it's expected to change.
If we don't read it, multiple bits will be set which means it's not
possible anymore to find out why the core is halted.

Improve tracking of core status

---

.github/bors.toml
.github/workflows/ci.yml

This PR adds a Github Action that will fail if no entry in the CHANGELOG.md was made.
This will make sure every change will make its way into the changelog and makes releases less nerve wrecking :)

Make CHANGELOG changes mandatory in PRs

---

CHANGELOG.md
cli/Cargo.toml
debugger/Cargo.toml
gdb-server/Cargo.toml
probe-rs-cli-util/Cargo.toml
probe-rs-target/Cargo.toml
probe-rs/Cargo.toml

Bump probe-rs versions in preparation for the v0.11.0-alpha.1 release.

Release v0.11.0-alpha.1

---

CHANGELOG.md
cli/Cargo.toml
debugger/Cargo.toml
gdb-server/Cargo.toml
probe-rs-cli-util/Cargo.toml
probe-rs-target/Cargo.toml
probe-rs/Cargo.toml

Bump probe-rs versions in preparation for the v0.11.0-alpha.2 release.

Release v0.11.0-alpha.2

---

.github/workflows/ci.yml
probe-rs/src/config/registry.rs

This fixes the probe-rs build without built-in targets, which is necessary for the `target-gen` tool.
It also adds a check to CI, to ensure it doesn't break again.

Fix build without built-in targets

---

CHANGELOG.md
probe-rs/src/architecture/arm/ap/generic_ap.rs

Locked nrf5840 chips have an AP 0 with IDR=0x47475245, which is a class of 0b1010. This would crash attach.
This PR fixes this by treating unknown ApClass as Undefined.
```
DEBUG probe_rs::probe::stlink                > Opening AP 0
TRACE probe_rs::probe::stlink                > JTAG_INIT_AP 0
TRACE probe_rs::probe::stlink::usb_interface > Sending command [f2, 4b, 0] to STLink, timeout: 1s
TRACE probe_rs::probe::stlink::usb_interface > Read 2 bytes, 0 bytes remaining
TRACE probe_rs::probe::stlink::usb_interface > Sending command [f2, 45, 0, 0, fc, 0] to STLink, timeout: 1s
TRACE probe_rs::probe::stlink::usb_interface > Read 8 bytes, 0 bytes remaining
DEBUG probe_rs::probe::stlink                > Read register    IDR, value=0x47475245
thread 'main' panicked at 'called `Option::unwrap()` …
```

Fix crash on unknown AP class.

---

CHANGELOG.md
debugger/src/debug_adapter.rs
probe-rs/src/architecture/arm/core/m0.rs
probe-rs/src/architecture/arm/core/m33.rs
probe-rs/src/architecture/arm/core/m4.rs
probe-rs/src/architecture/riscv/mod.rs
probe-rs/src/core/mod.rs
probe-rs/src/session.rs

I've removed breakpoint caching from `CoreStatus`, and added a new trait `CoreInterface::get_hw_breakpoints`
The new trait has an implementation for `m4.rs`, and a default `todo!()` implementation for the other architectures.
If you are OK with this new implementation, then we should extend implementation and testing to the other architectures.

Fix HW breakpoints and remove caching of breakpoints in CoreStatus

---

probe-rs/src/flashing/flasher.rs
probe-rs/src/flashing/loader.rs
probe-rs/src/flashing/mod.rs

- Flasher now no longer takes a Region, allowing reusing it for multiple regions that use the same algo.
- Load algo on `new`, not on `init`, so it's loaded only once. 
- Make Flasher private, remove `flash_block` since it's now unused. There already was no way to create a `Flasher` with the public API.

flashing: Load flash algo once, not at every reinit.

---

CHANGELOG.md
probe-rs/examples/raw_dap_access.rs
probe-rs/src/architecture/arm/communication_interface.rs
probe-rs/src/probe/mod.rs
probe-rs/src/probe/stlink/mod.rs

Allow using DapAccess from the public API, by adding it to ArmProbeInterface. 
Example nrf52840 recover operation:
```rust
let mut probe: Probe = open_probe(opts)?;
probe.attach_to_unspecified()?;
let mut iface = probe.try_into_arm_interface().unwrap();
let port = PortType::AccessPort(1);
const RESET: u16 = 0;
const ERASEALL: u16 = 4;
const ERASEALLSTATUS: u16 = 8;
const APPROTECTSTATUS: u16 = 12;
// Reset
iface.write_register(port, RESET, 1)?;
iface.write_register(port, RESET, 0)?;
// Start erase
iface.write_register(port, ERASEALL, 1)?;
// Wait for erase done
while iface.read_register(port, ERASEALLSTATUS)? != 0 {}
// Reset again
iface.write_register(port, RESET, 1)?;
iface.write_register(port, RESET, 0)?;

Allow accessing DapAccess from the public API

---

CHANGELOG.md
probe-rs/targets/STM32F2 Series.yaml

This PR adds support for the STM32F2 series of chips from STMicroelectronics (STM32F205/215 and STM32F207/217).
The target YAML file has been generated by running `target-gen pack Keil.STM32F2xx_DFP.2.9.0.pack` with the `.pack` file from https://developer.arm.com/tools-and-software/embedded/cmsis/cmsis-search with only some minor edits (renaming `Nvm` memory to `Flash`).
The changes have been confirmed to work by flashing an application to the [NUCLEO-F207ZG](https://www.st.com/en/evaluation-tools/nucleo-f207zg.html) development board.
Closes #674

Add support for STM32F2 series of chips

---

CHANGELOG.md
probe-rs/src/flashing/flasher.rs
probe-rs/src/flashing/loader.rs
probe-rs/targets/nRF52 Series.yaml

nrf52 had 2 algorithms: one for the main flash and one for UICR. However, "chip erase" of either erases the entire chip. So probe-rs would do this when flashing:
- chip erase, write flash contents
- chip erase, write uicr contents
- end result is flash is empty
We assume algo X's chiperase erases all NvmRegions controlled by the algo. This seems to hold for all chips (doesn't for nrf52, but does if we merge the algos since they're actually the same one).
First, group all NvmRegions by flash algo. For each flash algo, do chip erase only once (if requested), then flash all its NvmRegions.
This has the nice bonus that all regions of the same algo are flashed together, so the algo is only loaded once. This should make it *ever so slightly* faster.

Fix chip erase in multi-region chips.

---

CHANGELOG.md
debugger/src/debugger.rs
probe-rs/src/flashing/download.rs
probe-rs/src/flashing/error.rs
probe-rs/src/flashing/loader.rs

Only verifies the actually-written data. Data written by `keep_unwritten` is not verified. 
Doing that would require refactoring how flash building is done (first build for all the algos, then flash all the data keeping around the built pages, then use them to verify). I've opted not to do that for simplicity, and because keep_unwritten is not likely to be used in situations where verify is wanted (for example, factory programming usually does full chip erases). 
Depends on #670

Flashing verify

---

CHANGELOG.md
probe-rs/targets/STM32F2 Series.yaml

This is a follow-up to PR #675 regarding @Tiwalun's [comment](https://github.com/probe-rs/probe-rs/pull/675#pullrequestreview-675573651):
> We prefer to use Nvm now in the target description, because it's not always flash but can also be some other kind of non-volatile memory. But Flash is fine as well.
I was not aware of the new name as I based my original PR on tag `v0.10.1`, the last released version. This PR now uses the name `Nvm` as all the other STM32 targets (and others), introduced in commit 7a0b0507beeb42424248ecf9c9e69b0363bb6b5e in December 2020.
The PR also fixes an unintended white line in the changelog that was introduced by the merge.

Fix inconsistencies in STM32F2 target

---

CHANGELOG.md
debugger/src/debugger.rs
probe-rs/src/flashing/download.rs

This PR marks the flash `DownloadOptions` as `non_exhaustive`. This should make it easier to add additional flags in the future,
without having to update all consumers of the library.

Make DownloadOptions non_exhaustive

---

CHANGELOG.md
probe-rs/src/flashing/download.rs

Hi there, 
As per this pull request https://github.com/probe-rs/probe-rs/pull/677, I think you have forgotten to add the `skip_erase` setter function. So here I add it back.
Jackson

Add back the missing skip_erase setter

---

CHANGELOG.md
probe-rs/examples/raw_dap_access.rs
probe-rs/src/architecture/arm/ap/memory_ap/mock.rs
probe-rs/src/architecture/arm/ap/memory_ap/mod.rs
probe-rs/src/architecture/arm/ap/mod.rs
probe-rs/src/architecture/arm/ap/register_generation.rs
probe-rs/src/architecture/arm/communication_interface.rs
probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs
probe-rs/src/lib.rs
probe-rs/src/memory/mod.rs
probe-rs/src/probe.rs
probe-rs/src/probe/cmsisdap/mod.rs
probe-rs/src/probe/jlink/swd.rs
probe-rs/src/probe/stlink/mod.rs

Exposing the `DAPAccess` trait directly can be problematic, since it bypasses the handling of the `APBANKSEL` field. The new `RawApAccess` exposes the same functionality, but handles the AP bank selection as well.
@Dirbaio Can you check if the nRF unlock still works with these changes?
There is also some further cleanup of the ApAccess traits.

Add RawApAccess trait, cleanup ApAccess trait

---

CHANGELOG.md
probe-rs/src/probe/stlink/mod.rs

All the commands have the full DP/AP number and register address. The stlink
firmware switches SELECT on its own to do the requested operration automatically,
there's no need to handle SELECT manually.
~~Depends on #689 #691~~

stlink: remove bank handling.

---

probe-rs-cli-util/Cargo.toml
probe-rs/Cargo.toml
probe-rs/examples/tcp_itm.rs
probe-rs/src/architecture/arm/swo/mod.rs

- Remove itm-decode dependency, seems unused
- Remove sentry from default features, improve workspace build time

Remove itm-decode dependency, don't build sentry by default

---

CHANGELOG.md
debugger/src/debug_adapter.rs
debugger/src/debugger.rs
probe-rs/src/architecture/arm/core/m0.rs
probe-rs/src/architecture/arm/core/m33.rs
probe-rs/src/architecture/arm/core/m4.rs
probe-rs/src/core/mod.rs

Add `CoreStatus::LockedUp` and handle appropriately when read from the core during a `status()` call. This signals that the Cortex core encountered an unrecoverable exception and needs to be reset. For the debugger, this means sending a notification and terminating the debugging session.

Handle Cortex `LOCKUP` status during debugging

---

CHANGELOG.md
probe-rs/src/probe.rs
probe-rs/src/probe/cmsisdap/tools.rs
probe-rs/src/probe/ftdi/mod.rs
probe-rs/src/probe/jlink/mod.rs
probe-rs/src/probe/stlink/tools.rs

Some CMSIS-DAP probes have multiple HID interfaces, and the correct interface has to be used to access the CMSIS-DAP functionality. On MacOS, the HID interfaces seem to be returned in a randomized order, so access to the probe will only work sometimes, if the first found interface is the correct one by chance.
With this PR, we look for the correct HID interface while enumerating devices using `rusb`. The correct interface number is then stored in the `DebugProbeInfo` struct, and used when the device is opened with the `hidapi`library to select the correct HID device.
Unfortunately the `hidapi`library does not offer a direct way to access the interface description string, so we have to use `rusb`to detect the correct interface.
This might fix #681, but has only been tested with a MCUlink …

Detect correct USB HID interface for CMSIS-DAP v1

---

CHANGELOG.md
probe-rs/src/architecture/arm/component/itm.rs

This enables generation of global timestamps every 8192 or after every
packet, depending on read register value. Preferably, [0] (which binds
into #727) would be used here instead.
[0] https://github.com/rust-embedded/cortex-m/pull/342/files#diff-4a52d1ab15248eae14ea79bf2efcaf399b0cb20abd65e5be7d05654ddf252835R177

arm/itm: doc fields, enable global timestamps

---

probe-rs/src/probe.rs
probe-rs/src/probe/cmsisdap/tools.rs

Storing the HID interface in the DebugProbeSelector does not work well together with cargo-embed.
With this PR, the interface is found when the probe is opened, not when listing probes. This
fixes #726.﻿

Do not store HID interface in DebugProbeSelector, retrieve interface when opening Probe

---

.github/bors.toml

Avoid problems when bors wants to merge but macOS CI has not completed yet.

Add macOS test to bors

---

CHANGELOG.md
probe-rs/src/probe/cmsisdap/commands/mod.rs

The return value from `HidDevice::read_timeout`was not checked, so we did not detect when a timeout occured.
With the changes in this PR, it should be possible to try multiple reports when connecting to a CMSIS-DAP probe, as is planned in #721.

Detect timeout when reading from USB HID device

---

CHANGELOG.md
probe-rs/src/probe/cmsisdap/commands/mod.rs
probe-rs/src/probe/cmsisdap/mod.rs
probe-rs/src/probe/cmsisdap/tools.rs

This should hopefully resolve #681. I've only been able to test it on Linux so far though, which does not suffer the same problem (but at least continues to work correctly).
The appraoch is number 3 from https://github.com/probe-rs/probe-rs/issues/681#issuecomment-855300380; we attempt to query the device's max packet size over CMSIS-DAP with different HID report sizes until it works. For V2 devices and V1 devices on Linux and Windows, the first query will succeed (so it works the same as before this PR) and we use whatever size it tells us. For V1 devices on MacOS, hopefully _one_ of the queries succeeds, and then we use that size thereafter.
It's possible that making one wrong request will cause MacOS to error on everything afterwards or some other workaround will be needed, I haven't …

CMSIS-DAP: Fix connecting to EDBG by repeating PacketSize request

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
probe-rs/Cargo.toml

`hidapi` has two possible backends on Linux, `libusb` and `hidraw`. `hidraw` seems to require less permissions, so I think we should use it. This might help with #357.

Use hidraw backend for hidapi on Linux

---

CHANGELOG.md
probe-rs/targets/LPC5526.yaml
probe-rs/targets/LPC5528.yaml
probe-rs/targets/LPC55S26.yaml
probe-rs/targets/LPC55S28.yaml

Am having issues compiling (bad ssd probably) so I was only able to compile and verify LPC55S28, but the others should be fine as the core sections are copied manually from that one.

Add LPC552x / LPC55S2x to targets

---

CHANGELOG.md
probe-rs/src/flashing/error.rs
probe-rs/src/flashing/loader.rs

fixes #741 
Adds a new error type; but it could be seen as too inclusive.
Improves the error message for `NoFlashLoaderAlgorithmAttached` to include the target name
aside: `NoRamDefined` has a chip string that wasn't used in the error message.

Define better errors for multiple default flash alg

---

CHANGELOG.md
probe-rs/src/probe/cmsisdap/commands/general/connect.rs
probe-rs/src/probe/cmsisdap/commands/general/disconnect.rs
probe-rs/src/probe/cmsisdap/commands/general/host_status.rs
probe-rs/src/probe/cmsisdap/commands/general/info.rs
probe-rs/src/probe/cmsisdap/commands/general/reset.rs
probe-rs/src/probe/cmsisdap/commands/mod.rs
probe-rs/src/probe/cmsisdap/commands/swd/configure.rs
probe-rs/src/probe/cmsisdap/commands/swj/clock.rs
probe-rs/src/probe/cmsisdap/commands/swj/pins.rs
probe-rs/src/probe/cmsisdap/commands/swj/sequence.rs
probe-rs/src/probe/cmsisdap/commands/swo.rs
probe-rs/src/probe/cmsisdap/commands/transfer/configure.rs
probe-rs/src/probe/cmsisdap/commands/transfer/mod.rs
probe-rs/src/probe/cmsisdap/mod.rs

Because the response length is now handled properly, we need to fix parsing the response to transfer requests.
Only read responses return data, so we need to take this into account, otherwise parsing fails.
- Remove use of offset in CMSIS-DAP code, use slices instead
- cmsis-dap: Cleanup info command implementation, add info commands and caps for UART
- cmsis-dap: Rename category to command_id to clarify meaning
- Further cleanup, use enum for Command ID

Improve CMSIS-DAP response parsing

---

cli/Cargo.toml
cli/src/common.rs
cli/src/info.rs
cli/src/main.rs
probe-rs-cli-util/src/common_options.rs

Use the new shared options in the `probe-rs-cli`.
@tmplt: I would like to change `ProbeOptions::protocol` into an `Option`, instead of using `SWD` as the default value. There are probes which only support JTAG, so it's better to not choose any protocol if nothing is specified. Otherwise users of these probes are forced to always specify `--protocol=jtag`. Is that OK for you?

Use shared options in cli

---

probe-rs/src/flashing/download.rs
probe-rs/targets/STM32H7_Series.yaml

Since the latest rebase from master, the `probe-rs-debugger` fails for me with an error: 
```
Trying to write flash, but found more than one suitable flash loader algorithim marked as default for NvmRegion { range: 134217728..136314880, is_boot_memory: true, cores: ["main"] }.
```
The RUST_LOG=debug shows that it finds two identical flash algorithms. 
```
[2021-07-29T18:50:16Z INFO  probe_rs::flashing::download] Found loadable segment, physical address: 0x08000000, virtual address: 0x08000000, flags: 0x4
[2021-07-29T18:50:16Z INFO  probe_rs::flashing::download] Matching section: ".vector_table"
[2021-07-29T18:50:16Z INFO  probe_rs::flashing::download] Found loadable segment, physical address: 0x08000298, virtual address: 0x08000298, flags: 0x5
[2021-07-29T18:50:16Z INFO …
```

Fix errors introduced into the debugger by new flashing algorithms and error improvements

---

probe-rs/src/probe/cmsisdap/commands/transfer/mod.rs

Fixes a regression when flashing the rp2040 inrdocued in #745. Logs: https://gist.github.com/Dirbaio/7c7bc3fc7023679b9f36aa4c627a7f40
@Tiwalun was there a particular reason to change it to use the buffer len? Does changing it back break something?

cmsisdap: Fix block transfer response parsing

---

CHANGELOG.md
probe-rs/src/architecture/arm/component/mod.rs

Later down the line some option struct would be helpful for the SWV/ITM API.

arm: enable exception trace on setup_swv

---

.github/workflows/ci.yml
probe-rs/Cargo.toml

- Use vendored libftdi
- Remove libftdi from CI
This should help with the build issues on Windows. libftdi is LGPL, so this should be considered. From what I understand, this does not require probe-rs to be LGPL, but users of probe-rs based programs need to be able to rebuild it with a different version of libftdi.

Use vendored libftdi

---

rtt/README.md

This was fixed for the main README in 0d4ea32191b4d94e47ad3d30d160cf39a6040531, this is the same fix for the `probe-rs-rtt` README.

Fix badge for crates.io in rtt readme

---

probe-rs/src/session.rs

Due to the introduction of sequences, the `inner_attach` method was not called anymore when RISCV chips were used.
This led to issues with FTDI, because the detection of JTAG taps was now missing, and no connection as possible.

Call inner_attach for RISCV

---

CHANGELOG.md
probe-rs-cli-util/src/lib.rs
probe-rs-cli-util/tests/cargo_integration.rs
probe-rs/src/session.rs

This patch includes information on whether a code rebuild occurred, in addition to the path of the output artefact. This information if e.g. you want to avoid flashing your device unnecessarily.
It's a breaking change, but allows extra information to be included with the artefact in future without a breaking change.
Let me know if this is something you'd like included or not.

Emit fresh as well as path when running rustc.

---

probe-rs/targets/RP2040.yaml

This adds support for "in-chip" probes that use core1 to bitbang
the SWD lines of core0 (or viceversa), such as [pico-debug](https://github.com/majbthrd/pico-debug/).
The differences are:
- We only have 1 core.
- There's no SWD multidrop, since the bitbanging is after the multidrop mux.

Add RP2040_SELFDEBUG chip target.

---

probe-rs/src/config/registry.rs

If there are two chip variants where one's name is a prefix of
the other's, without this change it's not possible to reliably
select the shorter one.
Eg. if there are RP2040 and RP2040_SELFDEBUG, `--chip RP2040` may
accidentally select RP2040_SELFDEBUG.
To avoid that, ignore a variant if it's only a substring match and
there was already some match.

Make sure that an exactly matching chip name can't be overridden by substring matches

---

probe-rs/src/architecture/riscv/mod.rs
probe-rs/src/architecture/riscv/sequences/esp32c3.rs
probe-rs/src/architecture/riscv/sequences/mod.rs
probe-rs/src/config/target.rs
probe-rs/src/core/mod.rs
probe-rs/src/session.rs

- Open up debug sequences to riscv targets.
- On stage method, for after connecting and halting the target
(`on_connect`).
- Implementation for the esp32c3 to disable watchdogs.
I couldn't find any discussion about adding custom reset sequences for riscv, so I implemented a simple mechanism that suits my need.
Edit: would the long term goal to push custom sequences to the target yaml files by the way?

riscv debug sequences

---

CHANGELOG.md
probe-rs/src/config/registry.rs
probe-rs/src/probe/fake_probe.rs

As suggested by dirbaio: Forbid ambiguous chip names.
(But ignore partial matches if exactly one exact match exists.)

Forbid ambiguous chip names

---

probe-rs/src/probe/ftdi/mod.rs

This slightly reduces the FTDI batching chunk size to make it work with the Pine64 JTAG adapter.
Performance impact shouldn't be too hard (but there certainly is some impact).

Reduce batch chunk size to make Pine64 jtag work

---

.vscode/launch.json
cli/src/info.rs
debugger/src/dap_types.rs
debugger/src/debug_adapter.rs
debugger/src/debugger.rs
debugger/src/info.rs
debugger/src/main.rs
debugger/src/rtt.rs
probe-rs/src/architecture/arm/component/dwt.rs
probe-rs/src/architecture/arm/core/armv6m.rs
probe-rs/src/architecture/arm/core/armv7m.rs
probe-rs/src/architecture/arm/core/armv8m.rs
probe-rs/src/architecture/arm/sequences/mod.rs
probe-rs/src/architecture/arm/sequences/nxp.rs
probe-rs/src/architecture/riscv/communication_interface.rs
probe-rs/src/architecture/riscv/mod.rs
probe-rs/src/core/mod.rs
probe-rs/src/debug/mod.rs
probe-rs/src/debug/variable.rs
probe-rs/src/probe.rs
probe-rs/src/probe/cmsisdap/commands/transfer/mod.rs
probe-rs/src/probe/cmsisdap/mod.rs
probe-rs/src/probe/jlink/swd.rs
probe-rs/src/session.rs
smoke-tester/src/tests/stepping.rs

- Add spaces after the // or ///.
- Add full stops.
- Also quote some variable names with backticks.
- Remove dead code.
- Move comments that were on the same line as actual code (I consider it bad style and it breaks rustfmt https://github.com/rust-lang/rustfmt/issues/4119)

Clean up a lot of comments.

---

CHANGELOG.md
probe-rs-target/src/flash_algorithm.rs
probe-rs/src/flashing/error.rs
probe-rs/src/flashing/flash_algorithm.rs

* Add optional `load_address` to the raw yaml target def to allow for non PIC flash loaders.
* Modify stack size finding algo, to place stack after instruction code.
- `load_address` currently includes the arch header - so in my WIP flash loader, I have to offset to account for this (riscv is 8byte long), perhaps it should be `code_start` and probe-rs will load the header before it (if it can, what happens if you specify the beginning of ram as the code start?)
- Should this be limited to RISCV? I think the cmsis spec for arm flash loaders dictates that they must be PIC.

Fixed address flashing flash algorithms

---

probe-rs/src/flashing/error.rs
probe-rs/src/flashing/flash_algorithm.rs
probe-rs/src/flashing/flasher.rs

I was trying to improve my flash loading algorithm for the esp32c3 and found even when boosting clocks, switching to qio mode for the spi flash the speed would not improve. It took me a while to track down, because I assumed everything in probe-rs was okay, as running the `ram_download` example yielded good results.
Eventually I spotted that the flash data (note: not algorithm) was loaded one byte at a time instead of words. This PR changes that to write words.
Time to load 256byte page _before_: 250ms~
Time to load 256byte page _after_: 25ms~

Improve flash data load times

---

CHANGELOG.md
cli/src/debugger.rs
debugger/src/debug_adapter.rs
gdb-server/src/handlers.rs
probe-rs/src/debug/mod.rs
probe-rs/src/debug/variable.rs
probe-rs/src/flashing/flasher.rs
rtt/src/channel.rs
rtt/src/rtt.rs

* Both API's allow the reading for target memory into a byte slice, however `read` will use Word access under the hood for better performance. 
* Not all targets have byte level access to system memory, however word access is pretty much guaranteed (this is the case for the esp32c3).

Prefer `read` over `read_8`

---

CHANGELOG.md
probe-rs/targets/SAM3U.yaml

Adds SAM3U targets. (yes it is old, but it has HS usb so here I am)
I wasn't able to build the whole repo with this added, but since its just adding a target I'm hoping bors will pass it so I can avoid playing find the missing dependency  .

add SAM3U targets

---

CHANGELOG.md
probe-rs/targets/STM32WL_Series.yaml

Per [RM0453 Rev 2](https://www.st.com/resource/en/reference_manual/rm0453-stm32wl5x-advanced-armbased-32bit-mcus-with-subghz-radio-solution-stmicroelectronics.pdf) page 1331:
> 0x0: AP0 - CPU1 (Cortex-M4) debug access port (AHB-AP)
> 0x1: AP1 - CPU2 (Cortex-M0+) debug access port (AHB-AP)
I have confirmed that this can communicate with both cores.

Add STM32WL55JCIx target

---

CHANGELOG.md
probe-rs/targets/GD32VF1_Series.yaml

This is a very basic flash algorithm for the GD32VF1 series.
The source for the algo is here: https://github.com/9names/gd32vf103-flashloader
It was only (briefly) tested on the GD32VF103CBT6 as found on the longan-nano.
Flash and verify was confirmed using both probe-rs and segger's tools.
probe-rs needed patching to ignore failure when attempting to reset the chip, since this microcontroller does not conform to the riscv debug spec and we haven't added the sequences to reset it yet.

Add flash algo for GD32VF1_Series

---

CHANGELOG.md
probe-rs-target/src/memory.rs
probe-rs/src/flashing/builder.rs
probe-rs/targets/STM32H7_Series.yaml

Covers all of them except for the H7A3/H7B3 parts. ST didn't put the memory map into the reference manual so I didn't bother.
One issue I ran into is that [`Flasher::new()` uses the first RAM region found](https://github.com/probe-rs/probe-rs/blob/4ba46f40f436e8cec452ce4a5ae570b21d26d156/probe-rs/src/flashing/flasher.rs#L69-L83). When DTCM was the first RAM in the list, flashing would fail sporadically or the program would fail soon after startup. I moved the AXI-SRAM back to the start of the list to work around this. I'm not familiar enough with the flashing algorithms to know if there's a more principled solution. Should the flash algo specify which RAM region it wants to use?

Add all RAM regions to STM32H7 parts

---

CHANGELOG.md
debugger/src/debug_adapter.rs
debugger/src/debugger.rs

Add basic support to show a progress message while flashing is in progress. The `supports_progress_reporting`  flag of the client is respected.
Currently, only a notification that flashing is in progress is shown. This could be enhanced with additional information, like a proper progress bar.

debugger: Show progress message while flashing is in progress

---

cli/src/debugger.rs
debugger/src/debugger.rs

Fix a typo in debugger help text

---

CHANGELOG.md
debugger/src/debug_adapter.rs

When pressing enter without entering a command, simply call readline again in a loop instead of panicking.
This way, the empty command will not be added to the history either, the line will be fully ignored.
Without this fix:

Debugger: Do not crash CLI on empty lines

---

CHANGELOG.md
debugger/src/dap_types.rs
debugger/src/debug_adapter.rs

Previously, calling a command in the CLI debugger (e.g.
`set_breakpoint`) without passing any arguments would lead to a panic
due to unwrapping of the arguments.
By passing an Option to the argument parsing helpers, this an be
avoided, and instead the help is shown.

Debugger: Do not panic when using a command without arguments

---

.gitattributes

If you enforce changelog entries for every contribution, then every contribution submitted in parallel will lead to a merge conflict.
With the `.gitattribute` file, conflicts should be resolved automatically by accepting lines from both sides in a 3-way merge.
GitHub doesn't support this yet, I think, but bors may support it. Worth a try.

Add .gitattributes with merge=union for changelog

---

debugger/Cargo.toml
debugger/src/debug_adapter.rs
debugger/src/debugger.rs
debugger/src/main.rs
debugger/src/protocol.rs
debugger/src/snapshots/probe_rs_debugger__debug_adapter__test__receive_request_with_invalid_json.snap
debugger/src/snapshots/probe_rs_debugger__debug_adapter__test__receive_request_with_wrong_content_length.snap
debugger/src/snapshots/probe_rs_debugger__debug_adapter__test__receive_request_would_block.snap
debugger/src/snapshots/probe_rs_debugger__debug_adapter__test__receive_valid_request.snap
debugger/src/snapshots/probe_rs_debugger__protocol__test__receive_request_with_invalid_json.snap
debugger/src/snapshots/probe_rs_debugger__protocol__test__receive_request_with_wrong_content_length.snap
debugger/src/snapshots/probe_rs_debugger__protocol__test__receive_request_would_block.snap
debugger/src/snapshots/probe_rs_debugger__protocol__test__receive_valid_request.snap

Refactoring of the debug adapter code, so that code specific to CLI / DAP is now in separate structs. 
More work can be done to improve this, this is just initial work to gather some feedback if this goes into a useful direction.

debugger: Initial refactoring of protocol specific code into module

---

debugger/src/debug_adapter.rs
debugger/src/protocol.rs
probe-rs/src/core/mod.rs
probe-rs/src/debug/mod.rs

This PR improves the register handling, so stack traces should work better on RISCV. It improves the register handling, so that program counter / stack frame address are no longer hardcoded, but architecture specific. `Registers::from_core` now handles both RISCV and ARM, which fixes #851.
There is more work to be done, which is tracked in #877
See also probe-rs/vscode#11.

debugger: Improve register handling for RISCV

---

CHANGELOG.md
debugger/src/debugger.rs
probe-rs/src/probe/jlink/mod.rs

Improved user experience, by handling and forwarding errors that would previously cause the debugger to panic. This gives the user the feedback needed to either correct something and proceed, or to report bugs with better information.

Reduce panics caused by `unwrap()`

---

debugger/src/debug_adapter.rs
debugger/src/debugger.rs
debugger/src/main.rs
debugger/src/protocol.rs
debugger/src/snapshots/probe_rs_debugger__protocol__test__receive_request_with_invalid_json.snap
debugger/src/snapshots/probe_rs_debugger__protocol__test__receive_request_with_wrong_content_length.snap

The DAP protocol only allows a single response for a request, so this PR adapts the code to send events instead of responses, when no request applies.
Also, a lot return values are refactored to use `Result` instead of `bool`, to be more idiomatic Rust. In cases where the return value was ignored, it is now
properly handled.

debugger: Do not send DAP response without request

---

CHANGELOG.md
probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs
probe-rs/src/debug/mod.rs

To avoid endless loops while unwinding the call stack, add a check to ensure that the PC changes.
This fixes #892.

Prevent endless loops while unwinding, ensure PC changes

---

CHANGELOG.md
probe-rs/src/lib.rs

I think this is probably just an oversight since the `pub fn core::registers()` returns a `&'static RegisterFile`, but that type isn't currently publically visible (despite itself being `pub`).

Export core::RegisterFile

---

CHANGELOG.md
cli/src/main.rs
probe-rs-cli-util/src/flash.rs
probe-rs/src/flashing/loader.rs

Stuff like softdevice needs to erase before flashing, wwhich means were replacing 1 command with 2, and if its not noticed the binary cant start with any decent error meessage
So add -e --erase flag to the download
- `probe-rs-cli erase --chip nRF52840_xxAA`
- `probe-rs-cli download --format hex s140_nrf52_7.2.0_softdevice.hex --chip nRF52840_xxAA`
becomes
- `probe-rs-cli download --format hex s140_nrf52_7.2.0_softdevice.hex --chip nRF52840_xxAA -e`

probe-rs-cli: download: add erase option

---

CHANGELOG.md
probe-rs/src/probe/cmsisdap/commands/transfer/mod.rs

In #922 it looks like `transfer_count` which is read from the response data could be larger than `self.transfers.len()`, so we try and access `self.transfers` out of bounds. This isn't expected from a probe (it shouldn't be able to execute _more_ transfers than we asked...) but at least makes sense to emit a useful error log and return an Error instead of panicking.
Still a draft because there might be more we can do to fix #922.

cmsisdap: Check for DAP_Transfer response with more transfers than requested

---

target-gen/Cargo.toml

Revert futures to version 0.3.17 in target-gen, version 0.3.18 was yanked.
See rust-lang/futures-rs#2529.﻿

Fall back to older version of futures, version 0.3.18 was yanked

---

CHANGELOG.md
probe-rs/src/architecture/arm/core/mod.rs
probe-rs/src/architecture/riscv/register.rs
probe-rs/src/core/mod.rs

Added support for core registers:
- msp
- psp
- extra 
// ARM DDI 0403E.d (ID070218)
// C1.6.3 Debug Core Register Selector Register, DCRSR
// Bits[31:24] CONTROL.
// Bits[23:16] FAULTMASK.
// Bits[15:8]  BASEPRI.
// Bits[7:0]   PRIMASK.
Added notes for debug access for floating point, if anyone feels like having a go.

msp, psp, and extra register added

---

CHANGELOG.md
probe-rs/src/config/target.rs

The lpc55s19 seems to use the same start sequence as lpc55s69.
Enabling the same sequence allows erase/download operations to
appear to succeed.
FWIW, when I dump memory locations, it matches the contents of the binary I downloaded, so I think this is working. My guess that is we need to rework this into a more generic form for nxp (not just lpc55s69) since it's common code now.

Add start sequence for lpc55s19.

---

CHANGELOG.md
probe-rs/src/architecture/arm/mod.rs
probe-rs/src/architecture/arm/swo/mod.rs
probe-rs/src/session.rs

An upcoming release of `itm` (queued to replace the now deprecated `itm-decode`) now takes an `std::io::Read` impl
instead of requiring the end-user to push bytes manually.

arm: add `std::io::Read` wrapper around `read_swo`

---

CHANGELOG.md
debugger/src/debugger.rs
gdb-server/src/bin.rs
probe-rs-cli-util/src/common_options.rs
probe-rs/examples/benchmark.rs
probe-rs/examples/ram_download.rs
probe-rs/examples/tcp_itm.rs
probe-rs/src/architecture/arm/sequences/mod.rs
probe-rs/src/architecture/arm/sequences/nrf53.rs
probe-rs/src/config/target.rs
probe-rs/src/error.rs
probe-rs/src/flashing/mod.rs
probe-rs/src/lib.rs
probe-rs/src/probe.rs
probe-rs/src/probe/fake_probe.rs
probe-rs/src/session.rs
probe-rs/tests/flash_dry_run.rs
rtt/src/lib.rs
rtthost/src/main.rs
smoke-tester/src/main.rs

Added a permissions system to tell the session what it is allowed to do.
Currently only one permission is present: `erase_all`
This permission allows the debug sequence to use erase the entire device, including secure keys and 3rd party firmware that is read-only locked. This is required for the nRF53 for which a debug sequence has been added.
The permissions are passed through the Session::attach method.
In relevant places, a CLI option has been added.
Everywhere else, the default permissions are passed which does not allow anything.
I've also made a branch for cargo-flash to add a diagnostic for the new error: https://github.com/diondokter/cargo-flash/commit/d0d075db48d0eaa033ec8932d11d5ce609ace107

Permissions & nRF53 unlocking sequence

---

debugger/src/debugger.rs
debugger/src/main.rs

Fix parsing, new clap seems to require that we specify the flags with a hyphen.
Also, some of the unnecessary clap attributes are removed.

Fix argument parsing in debugger

---

CHANGELOG.md
probe-rs/src/config/registry.rs

(In response to #963).
This PR means that an 'x' in the registry chip name, like in `STM32F303VCTx` or `nRF9160_xxAA`, is treated as a wildcard, so that specifying `--chip STM32F303VCT6` (the full actual chip name) matches correctly.
If the match depends on the wildcard, it emits a warning, the same as is done for partial matches.

Treat 'x' in registry chip names as a wildcard when matching user-supplied chip names

---

CHANGELOG.md
target-gen/src/generate.rs

I suppose lack of this definition is just a mere oversight or something.
I needed this to process [Nuvoton.NuMicro_DFP.1.3.9.pack](https://github.com/OpenNuvoton/cmsis-packs/) by target-gen.
And I can report that at least basic operations are working fine with Cortex-M23 based Nuvoton chips, M252 series for example.

Add CortexM23 to Armv8m mapping

---

probe-rs-cli-util/src/lib.rs
probe-rs/examples/tcp_itm.rs
probe-rs/src/architecture/arm/communication_interface.rs
probe-rs/src/architecture/arm/dp/mod.rs
probe-rs/src/architecture/arm/memory/romtable.rs
probe-rs/src/architecture/riscv/communication_interface.rs
probe-rs/src/config/registry.rs
probe-rs/src/config/target.rs
probe-rs/src/error.rs
probe-rs/src/flashing/download.rs
probe-rs/src/probe.rs
probe-rs/src/probe/ftdi/mod.rs
probe-rs/src/probe/stlink/mod.rs

i encountered `Error: A core architecture specific error occured`
i went to look for the source of that typo, and found a few more occurrences

treewide: occured → occurred

---

CHANGELOG.md
cli/src/main.rs
cli/src/run.rs
debugger/Cargo.toml
debugger/src/dap_types.rs
debugger/src/debug_adapter.rs
debugger/src/debugger.rs
debugger/src/main.rs
probe-rs-cli-util/Cargo.toml
probe-rs-cli-util/src/lib.rs
probe-rs-cli-util/src/rtt.rs

Add a `probe-rs-cli run` command.
The goal is a simpler-to-use `cargo-embed` alternative that doesn't require a configuration file.
Coming in future PRs:
- Break on HardFault
- Stack trace on HardFault or Control+C
- RTT input support (keystrokes are sent to the target).
[relevant XKCD](https://xkcd.com/927/)

Add `probe-rs-cli run`

---

cli/src/debugger.rs
debugger/src/debug_adapter.rs
debugger/src/debugger.rs
probe-rs/src/core/mod.rs
probe-rs/src/debug/mod.rs
probe-rs/src/debug/variable.rs

I've tried to clean up the debugger code a bit, by replacing some of the hardcoded strings with an enum. 
I've also added some logging, which helped me find an issue where the debugger tried to print a string with length 130000, which blocked the whole debugger. For that, there is now also a workaround which limits the string length. The best way to work around this would probably be to implement lazy loading for variable values.

DAP debugger refactoring

---

CHANGELOG.md
cli/src/debugger.rs
cli/src/main.rs
debugger/src/debug_adapter.rs
probe-rs/src/debug/mod.rs
probe-rs/src/debug/variable.rs
probe-rs/tests/inlined_function.rs

This is both some in progress work on the CLI debugger, as well as support for multiple inlined functions.
This probably conflicts with #999 , since it changes the stack frame iterator as well. 
@noppej Do you think the approach in this PR would also work with your changes?
```
StackFrame data for copy_forward #[inline]
/cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.66/src/mem/impls.rs:76:29
StackFrame data for memcpy @0x08030a06
/cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.66/src/mem/mod.rs:25:5
StackFrame data for free<stm32wb55_homekit::ble::receive_event::{closure#0}, core::result::Result<bluetooth_hci::host::uart::Packet<stm32wb55::event::Stm32Wb5xEvent>, nb::Error<bluetooth_hci::host::uart::Error<(), …
```

Support multiple inlined functions

---

README.md

The existing link pointed to [https://github.com/probe-rs/target-gen](https://github.com/probe-rs/target-gen),
which is an archived repo that redirects users to the probe-rs repo.
By linking to the target-gen path, they land on the readme for the
tool which saves digging through the repo looking for it.

Update README hyperlink to target-gen

---

probe-rs/targets/STM32H7_Series.yaml
target-gen/README.md
target-gen/src/generate.rs

#1010 deduplicates the algos themselves, but leaves duplicate algo names in `variants.flash_algorithms`. This PR dedups algo names and updates the troublesome H7 yaml.
This causes this issue when flashing:
```
Error: Error while flashing
Caused by:
Trying to write flash, but found more than one suitable flash loader algorithim marked as default for NvmRegion { name: None, range: 134217728..136314880, is_boot_memory: true, cores: ["main"] }.
```

target-gen: fix duplicate algo names

---

CHANGELOG.md
probe-rs/src/architecture/arm/sequences/mod.rs

With a hs-probe (current firmware e955d5246b) connected to an ATSAMD21 target, flashing fails when the SWD speed is set above about 500kHz.  @adamgreig and I traced this over chat, back to this read failing while the target chip is still in reset.

ARM: Permit register read errors while resetting

---

CHANGELOG.md
cli/src/main.rs
cli/src/run.rs
probe-rs-cli-util/src/common_options.rs
probe-rs-cli-util/src/flash.rs
probe-rs/src/flashing/download.rs
probe-rs/src/flashing/loader.rs

This commit adds the "disable_double_buffer" option in
probe-rs::flashing::download::DownloadOptions to disable use
of double buffering when downloading firmware even if the target
reports it is supported.  probe-rs-cli has been updated with
the "--disable-double-buffering" options for "run" and "download".
Some targets, like STM32L071 seem to have issues with double
buffering (see #883).

Add option to disable double-buffer use in downloading flash

---

CHANGELOG.md
rtt/Cargo.toml
rtt/src/channel.rs

This is required to allow cargo-embed to use ChannelMode in
configuration files.

Derive serde traits on rtt::ChannelMode

---

probe-rs/targets/STM32H7_Series.yaml

This is a temporary fix for the probe-rs/targets entry for STM32H7, until such time as there is a permanent fix for #1023

Temp fix for STM32H7 multi-core flashing

---

CHANGELOG.md
cli/src/debugger.rs
debugger/Cargo.toml
debugger/src/dap_types.rs
debugger/src/debugProtocol.json
debugger/src/debug_adapter.rs
debugger/src/debugger.rs
probe-rs-cli-util/src/rtt.rs
probe-rs/src/debug/mod.rs
probe-rs/src/debug/variable.rs
probe-rs/targets/STM32H7_Series.yaml

There are three linked PR's that depend on each other:
- [probe-rs/probe-rs](https://github.com/probe-rs/probe-rs/pull/1035)
-  When RTT is enabled, it waits for a custom request from VSCode to confirm that the output window is opened, before it starts polling the target for RTT data. This is to ensure that target RTT data is not sent into the 'void' before the VSCode output window has completed opening.
- Implements the debug adapter capabilities to support new requests from VSCode, i.e. `ReadMemory`, `WriteMemory`, `Evaluate` and `SetVariable`
- [probe-rs/vscode](https://github.com/probe-rs/vscode/pull/29)
-  The VSCode debug extension changes to implement the RTT interactions described above.
- A WIP release is available for testing at …

RTT Reliability and new DAP Requests (ReadMemory, WriteMemory, Evaluate & SetVariable)

---

CHANGELOG.md
debugger/src/dap_types.rs
debugger/src/debug_adapter.rs
debugger/src/debugger.rs
debugger/src/main.rs
debugger/src/protocol.rs
probe-rs/src/core/mod.rs
probe-rs/src/debug/mod.rs
probe-rs/tests/source_location.rs

Add support for MS DAP `Disassemble` and `SetInstructionBreakpoints` requests. 
Note: The changes are entirely on the `probe-rs-debugger` side, and will work with the existing/latest VSCode extension installed.
As part of stabilization, I also tracked down all unwrap/panic/expect statements in the probe-rs-debugger and probe-rs/src/debug code, and added clippy lints to ensure they cannot creep back in.

VSCode: Add support for Disassembly View and Set Instruction Breakpoints

---

probe-rs/src/probe/stlink/usb_interface.rs

Add additional USB ID for ST-Link V3 variant without mass storage. Fix #1069.

Add additional USB id for ST-Link V3 without mass storage

---

CHANGELOG.md
probe-rs/Cargo.toml
probe-rs/examples/ram_download.rs

Clap requires the `derive` feature: https://github.com/clap-rs/clap/blob/v3.1.8/examples/demo.md

Fixed missing `derive` feature in Clap examples, migrated from structopt

---

CHANGELOG.md
probe-rs/src/probe/cmsisdap/mod.rs

We currently send to the probe that it should retry when it receives a WAIT response for 80 times. But this doesn't seem to be enough, so I've increased it to the maximum of 0xFFFF.
This should fix #994 and possibly #1058. Both issues should be checked by the original issue reporter.

Increase SWD wait timeout

---

CHANGELOG.md
probe-rs/targets/STM32L4_Series.yaml

This PR contains an updated `STM32L4_Series.yaml` target-gen'ed from Keil.STM32L4xx_DFP.2.5.0.
It contains fixes issues with STM32L475VGTx's flash algorithm once crossing into Bank 2.
Fixes #1074

Update STM32L4_Series.yaml from Keil.STM32L4xx_DFP.2.5.0

---

CHANGELOG.md
target-gen/Cargo.toml
target-gen/src/fetch.rs
target-gen/src/generate.rs

cmsis-pack 0.6.0 contains the following changes:
- pyocd/cmsis-pack-manager#183 (from @Yatekii + @mbrossard)
- pyocd/cmsis-pack-manager#186 (from @david-sawatzke)
- pyocd/cmsis-pack-manager#189 (from @Tiwalun)

Update to cmsis-pack 0.6.0

---

CHANGELOG.md
debugger/Cargo.toml
debugger/src/peripherals/svd_variables.rs

`probe-rs-debugger` now uses the `expand` feature of the `svd-parser` crate. 
The primary impact is that we were able to loose about 120 lines of obsolete code in probe-rs, as well as gain the ability to navigate clusters and arrays in SVD files.

Use new svd-parser `expand` feature.

---

debugger/src/debugger/configuration.rs
debugger/src/debugger/session_data.rs

To fix VSCode `wireProtocol` setting is ignored by `probe-rs-debugger`

Fix VSCode `wireProtocol` setting is ignored.

---

debugger/src/debugger/debug_entry.rs
debugger/src/peripherals/mod.rs

Currently the debugger continuously polls the target for RTT data, even while halted. 
This change will poll only once after halting, to drain the RTT buffers, and then won't poll again until the next time the core status has changed.

probe-rs-debugger: Poll RTT only once after halting.

---

CHANGELOG.md
debugger/src/debug_adapter/dap_adapter.rs
debugger/src/debugger/session_data.rs

The DAP Specification states the following for the `set_breakpoints()` request:
```
Sets multiple breakpoints for a single source and clears all previous breakpoints in that source.
```
The current probe-rs-debugger implementation sets and clears breakpoints on a 'per session' basis, as opposed to the specified 'per source' basis. This results in a behaviour where breakpoints for the any source is cleared when breakpoitns for any subsequent source is set.
With this fix, the breakpoints are now set and cleared 'per source'.

Fix debugger breakpoints for multiple files.

---

CHANGELOG.md
gdb-server/src/architecture.rs
probe-rs-target/src/chip.rs
probe-rs-target/src/chip_family.rs
probe-rs/src/architecture/arm/core/armv6m.rs
probe-rs/src/architecture/arm/core/armv7a.rs
probe-rs/src/architecture/arm/core/armv7m.rs
probe-rs/src/architecture/arm/core/armv8m.rs
probe-rs/src/architecture/arm/core/mod.rs
probe-rs/src/architecture/arm/mod.rs
probe-rs/src/architecture/arm/sequences/mod.rs
probe-rs/src/architecture/arm/sequences/nxp.rs
probe-rs/src/core/mod.rs
probe-rs/src/probe/jlink/arm.rs
probe-rs/src/probe/jlink/mod.rs
probe-rs/src/session.rs
probe-rs/targets/iMX7ULP.yaml
target-gen/src/generate.rs
target-gen/src/main.rs

With these changes the base APIs fully function for v7-A devices.
Some CLIs still assume Cortex-M which will need cleaned up in a follow up
check-in.
Summary of changes:
* Add new Armv7a core type
* Add debug base address to ARM core options
* Refactor ARM debug sequence to handle core type differences
* Fix fault detection logic in JLink JTAG probe
* Add i.MX 7ULP target used for testing

Add preliminary support for ARMv7-A

---

CHANGELOG.md
cli/src/common.rs
cli/src/debugger.rs
cli/src/main.rs
debugger/src/debug_adapter/dap_adapter.rs
debugger/src/debugger/core_data.rs
debugger/src/debugger/session_data.rs
gdb-server/src/architecture.rs
probe-rs-target/src/chip_family.rs
probe-rs-target/src/lib.rs
probe-rs/src/architecture/arm/core/armv6m.rs
probe-rs/src/architecture/arm/core/armv7a.rs
probe-rs/src/architecture/arm/core/armv7m.rs
probe-rs/src/architecture/arm/core/armv8m.rs
probe-rs/src/architecture/riscv/mod.rs
probe-rs/src/config/mod.rs
probe-rs/src/core/mod.rs
probe-rs/src/debug/registers.rs
probe-rs/src/flashing/flasher.rs
probe-rs/src/lib.rs

* Break assumptions around ARM being Cortex-M only in CLI debugger programs
* Fix ARMv7-A race condition related to data transfer between CPU and probe
* Memory accesses on ARMv-7A now go through the CPU to ensure consistency with the MMU
* Expose instruction set so programs can use it for things like disassembly
* Generalize some logic for register access
* Update debugger CLI to support 8 bit memory access and re-enable disassembly
* GDB server support for ARMv7-A

CLI fixes for ARMv7-A support

---

debugger/Cargo.toml
debugger/src/peripherals/svd_variables.rs

Tested improvements made by `svd-parser` for  nested `deriveFrom`
@burrbull

Bump svd-parser to 0.13.4

---

CHANGELOG.md
cli/src/debugger.rs
gdb-server/src/architecture.rs
probe-rs-target/src/chip.rs
probe-rs-target/src/chip_family.rs
probe-rs/src/architecture/arm/core/armv6m.rs
probe-rs/src/architecture/arm/core/armv7a_debug_regs.rs
probe-rs/src/architecture/arm/core/armv7m.rs
probe-rs/src/architecture/arm/core/armv8a.rs
probe-rs/src/architecture/arm/core/armv8a_debug_regs.rs
probe-rs/src/architecture/arm/core/armv8m.rs
probe-rs/src/architecture/arm/core/instructions.rs
probe-rs/src/architecture/arm/core/mod.rs
probe-rs/src/architecture/arm/mod.rs
probe-rs/src/architecture/arm/sequences/mod.rs
probe-rs/src/core/mod.rs
probe-rs/src/session.rs
probe-rs/targets/BCM2711.yaml
target-gen/src/generate.rs
target-gen/src/main.rs

* 32-bit only for now
* Tested with a Raspberry Pi 4 (target included)
* All basic debugger operations work
* This includes minor refactoring to share code between v7-a and v8-a
* Both Cortex-A targets have updated register cache logic to fix some bugs
found while testing

Add preliminary ARMv8-A support

---

CHANGELOG.md
probe-rs/src/architecture/arm/component/dwt.rs
probe-rs/src/architecture/arm/component/itm.rs
probe-rs/src/architecture/arm/component/mod.rs
probe-rs/src/architecture/arm/component/tpiu.rs
probe-rs/src/architecture/arm/memory/mod.rs
probe-rs/src/architecture/arm/memory/romtable.rs
probe-rs/src/session.rs

This PR works towards supporting the SWV (#1113) configuration on Arm components by refactoring CoreSight component access to be associated with specific DAP access points. This ensures that accessing the registers of the component is done through the correct AP so that addresses specified in ROM tables are usable.
I'm opening this PR as a draft in case anyone has any opinions on this subject - I'm fairly new to Arm's CoreSight components and debug architecture, so feedback is welcome!
TODO:

Refactoring Arm components to reference specific access points

---

CHANGELOG.md
cli/src/debugger.rs
debugger/src/debug_adapter/dap_adapter.rs
gdb-server/src/handlers.rs
probe-rs/src/architecture/arm/core/armv6m.rs
probe-rs/src/architecture/arm/core/armv7a.rs
probe-rs/src/architecture/arm/core/armv7m.rs
probe-rs/src/architecture/arm/core/armv8a.rs
probe-rs/src/architecture/arm/core/armv8m.rs
probe-rs/src/architecture/arm/core/mod.rs
probe-rs/src/architecture/riscv/mod.rs
probe-rs/src/architecture/riscv/register.rs
probe-rs/src/core/mod.rs
probe-rs/src/debug/mod.rs
probe-rs/src/debug/registers.rs
probe-rs/src/debug/stepping_mode.rs
probe-rs/src/flashing/flasher.rs
probe-rs/src/lib.rs
smoke-tester/src/tests.rs
smoke-tester/src/tests/stepping.rs

* ArmProbe::read_core_reg / write_core_reg now use an enum to support different sized registers
* Core::read_core_reg / write_core_reg are generic to support working with u32 and u64
* New methods on RegisterDescription allow inspecting register size

Convert core register access to handle 64-bit values

---

CHANGELOG.md
probe-rs/src/probe/jlink/arm.rs

When no chip is connected, the J-Link ends up in an endless loop, because no
answer is received. To avoid this, we can't call the register read function in the
line_reset function.
This might help with #531.

jlink: Avoid endless recursion in line_reset

---

README.md

Error: ChipNotFound(ChipNotUnique("nrf52"))

Old target name

---

CHANGELOG.md
cli/src/debugger.rs
probe-rs/src/architecture/arm/core/armv7a.rs
probe-rs/src/architecture/arm/core/armv8a.rs
probe-rs/src/core/mod.rs
probe-rs/src/session.rs

* Add a new session cleanup hook to write out any pending cached writes.  This ensures when a probe-rs based program exits data isn't lost.
* Fix a bug where ARMv8-a was resetting its cached registers each time it was accessed
* Fix bug that caused failures in `halt()` or `run()` if the target was already in the desired state
* Update CLI debugger to read core state after every command.  This fixes issues where the CLI things the core is halted but it isn't, or vise-versa.

Fixes for ARMv7-a and ARMv8-a

---

CHANGELOG.md
gdb-server/src/arch.rs
gdb-server/src/target/base.rs
gdb-server/src/target/desc/data.rs
gdb-server/src/target/desc/mod.rs
gdb-server/src/target/desc/snapshots/probe_rs_gdb_server__target__desc__test__target_description_microbit.snap
gdb-server/src/target/desc/snapshots/probe_rs_gdb_server__target__desc__test__target_with_features.snap
gdb-server/src/target/desc/test.rs
gdb-server/src/target/mod.rs
probe-rs/src/architecture/arm/core/armv6m.rs
probe-rs/src/architecture/arm/core/armv7a.rs
probe-rs/src/architecture/arm/core/armv7m.rs
probe-rs/src/architecture/arm/core/armv8a.rs
probe-rs/src/architecture/arm/core/armv8m.rs
probe-rs/src/architecture/arm/core/cortex_m.rs
probe-rs/src/architecture/arm/core/mod.rs

* Send a full register description to GDB to support optional feautures, like FP
* Fix Cortex-M FP support to detect if the hardware is present, even if it's not enabled in software
* Update register file returned to not include FP registers if the core doesn't support them
Closes #495

Update GDB target generation to include registers

---

CHANGELOG.md
cli/src/gdb.rs
gdb-server/src/stub.rs
gdb-server/src/target/base.rs
gdb-server/src/target/breakpoints.rs
gdb-server/src/target/desc/mod.rs
gdb-server/src/target/mod.rs
gdb-server/src/target/monitor.rs
gdb-server/src/target/resume.rs

In the last round of refactoring Mutex was removed from the run() function signature due to no longer needing within the GDB logic.  However, consumers of this API, such as cargo-embed, depend on being able to run multiple threads so the GDB code cannot take exclusive ownership of the Session object.

Add Mutex back to GDB run method

---

probe-rs/Cargo.toml

`thousands` was introduced as a dependency in #631. The only usage was removed #895.

Remove unused dependency 'thousands'

---

CHANGELOG.md
probe-rs/targets/nRF91_Series.yaml

The UICR section was missing from the memory_map, I've added it now.

Fixing nrf9160 target file so it can erase UICR section

---

CHANGELOG.md
probe-rs/src/probe/cmsisdap/mod.rs

The CMSIS-DAP firmware does not configure the nRESET pin for output
until it receives the DAP_Connect command. In the connect under reset
flow we try to toggle the pins via swj_pins before calling connect.
This fix addresses that by connecting if needed during swj_pins calls.

Fix CMSIS-DAP connect under reset

---

CHANGELOG.md
probe-rs/src/probe.rs

I submit this PR because I'm using egui ComboBox and the selectable_value function require  the comparison Trait.
Here is the example:
egui::ComboBox::from_label("Take your pick")
.selected_text(format!("{:?}", self.get_probe_name(&self.probe_selected)))
.show_ui(ui, |ui| {
for (i, pr) in self.probes.iter().enumerate() {
ui.selectable_value(&mut self.probe_selected, Some(pr.clone()), pr.identifier.clone());
}
});
Definitions:
struct MyApp {
probes: Vec<probe_rs::DebugProbeInfo>,
probe_selected: Option<probe_rs::DebugProbeInfo>,
}
impl Default for MyApp {
fn default() -> Self {
Self {
probes: Probe::list_all(),
probe_selected: None,
}
}
}
impl MyApp {
pub fn get_probe_name(&self, probe: &Option<probe_rs::DebugProbeInfo>) -> String {
match probe {
Some(p) => p.identifier.clone(),
_ => "No …

added PartialEq Trait to struct DebugProbeInfo

---

CHANGELOG.md
cli/Cargo.toml
cli/src/main.rs
cli/src/trace.rs

This PR brings initial ITM tracing support to the probe-rs-cli. Specifically, the ITM tracer lets you:
* Specify a trace destination (SWO or TraceMemory)
* Configure SWO when needed
* Specify trace duration
TODO:
Future work:
* Support ITM stimulus ports
* Allow other DWT tracing, such as PC sampling and memory watching
* Support TPIU+SWO combinations

ITM Tracing CLI support

---

CHANGELOG.md
probe-rs/src/architecture/arm/component/mod.rs

The M4 architecture pre-dates the CoreSight Technical Reference Manual. Because of this, the Cortex-M4 Trace Port Interface Unit (TPIU) is responsible for controlling both serial (SWO) and parallel trace (TRACED).
To accomodate this, this PR updates the configuration functions to configure the TPIU if the SWO peripheral is not found, as is the case on M4 devices.
I tested this by tracing an STM32F407ZGTx device (M4) architecture using the CLI tool. On `master`, I received:
```
$ cargo run -- itm --chip STM32F407ZGTx 100 swo 168000000 115200
Finished dev [unoptimized + debuginfo] target(s) in 9.05s
Running `C:\Users\rsummers\Documents\repositories\probe-rs\probe-rs\target\debug\probe-rs-cli.exe itm --chip STM32F407ZGTx 100 swo 168000000 115200`
Error: A core architecture specific error …
```

Updating tracing to support M4 architectures

---

probe-rs/Cargo.toml

This commit removes the use of `libusb1-sys`'s "vendored" feature by
default. In short, this was causing problems in building libusb v0.6.3.
The issue needs to be reported to the upstream dependency, but in the
meantime, it can be fixed by disabling this default feature.
It should be noted that, without this feature, `libusb1-sys` first
checks to see if you have installed `libusb` yourself. If that does not
exist, it continues to try to install the library from source. So, just
to confirm, nothing is lost here—removing this feature only allows
`libusb1-sys` to first check if you've already installed the library.

[WIP] build: removes libusb1-sys vendored as a default feature

---

README.md

This PR fixes the examples in the `README.md` by adding the now required `Permissions` argument.

docs: fixes examples to include permissions argument

---

CHANGELOG.md
rtt/src/rtt.rs

Currently specifying memory range with --scan-region will always fail to find the control block.

Fix scan-region range scan

---

debugger/README.md

The README was out of date and included outdated instructions for CLI mode, which is no longer relevant.

`probe-rs-debugger` README update

---

CHANGELOG.md
debugger/src/debug_adapter/dap_adapter.rs
debugger/src/debugger/core_data.rs
debugger/src/debugger/debug_entry.rs
gdb-server/src/target/mod.rs
probe-rs-cli-util/src/rtt.rs
probe-rs/src/architecture/arm/core/armv6m.rs
probe-rs/src/architecture/arm/core/armv7a_debug_regs.rs
probe-rs/src/architecture/arm/core/armv7m.rs
probe-rs/src/architecture/arm/core/armv8a_debug_regs.rs
probe-rs/src/architecture/arm/core/armv8m.rs
probe-rs/src/architecture/arm/core/mod.rs
probe-rs/src/architecture/riscv/mod.rs
probe-rs/src/core/mod.rs
probe-rs/src/debug/debug_step.rs
probe-rs/src/flashing/flasher.rs
probe-rs/src/lib.rs
probe-rs/src/session.rs
probe-rs/targets/esp32.yaml
smoke-tester/src/tests/stepping.rs

This implements the ability to step over / run past, software breakpoints on the Arm Cortex-M and RISCV architectures.
I do not have any Arm Cortex-A hardware to test changes against, so for now, software breakpoints on Arm Cortex-A will continue to behave as pre- this PR, i.e. you cannot step past them.

Step over BKPT instruction for Arm  Cortex-M / EBREAK instruction for RISC-V

---

CHANGELOG.md
cli/src/debugger.rs
debugger/src/debug_adapter/dap_adapter.rs
probe-rs-target/src/chip_family.rs
probe-rs/src/architecture/riscv/mod.rs

The current implementation of RISC-V assumed that the instruction set architecture (isa) was always compressed. 
WIth this change, we read the `misa` register to determine the actual value of compressed vs non-compressed, and use the value to define behavior for things like stepping and disassembly.
PS. I believe this is the last outstanding 'known' issue in #877

Handle RISC-V compressed instruction sets.

---

CHANGELOG.md
probe-rs/src/probe/cmsisdap/commands/transfer/mod.rs

Debuggers such as HS-Probe (rightfully) send no response data when
DAP Transfer Read requests fail. Instead of always expecting response
data from such requests, only attempt to parse the response data for the
requests that were successful. This propagates the FAULT status properly
up the stack as opposed to triggering a NotEnoughData error.
Fixes #1058

 Don't expect data in faulty DAP Transfer responses

---

CHANGELOG.md
probe-rs/src/debug/debug_info.rs

This fixes an error where stack unwinding would give an error, 
```
UNWIND: Failed to read from address 0xfffffffffffffff8 (4 bytes): A core architecture specific error occurred [2022-09-16T14:08:52Z ERROR probe_rs::debug::debug_info] UNWIND: Rule: Offset -16 from address 0x00000008
```
The correct behaviour is to detect the case where the CFA register rule references a FP with a zero value, and gracefully end the  unwind process. The error was only reproduce-able on NRF chips, and the same code would unwind successfully on ST, PICO and ESP32-C3 tests.

Debug: Gracefully handle stack unwind when CFA rule references a FP with value of zero.

---

CHANGELOG.md
debugger/src/debug_adapter/dap_adapter.rs
probe-rs/src/architecture/riscv/mod.rs

In rare cases the debugger and core would be out of synch immediately after launch. The known cases where this could be reproduced involved a situation where the core would halt on a breakpoint shortly after the debugger read a `CoreStatus::Running` from the core.
The fix also includes a change to RISC-V `wait_for_core_halted()` which returned a different timeout error than the one returned by other architectures.

Fix: Debugger: Improve core status checking during launch.

---

CHANGELOG.md
probe-rs/src/debug/mod.rs
probe-rs/src/debug/unit_info.rs

There was an error in the logic that prevented cetain variable types from being loaded in a deferred/lazy way. This resulted in situations where recursively referenced types (as in a linked list) would loop forever trying to resolve all children of a structured variable.
Fixes #1231
Additional fixes: 
- This also fixes a new issue (exposed by testing of this PR). Recent changes in RUST have removed the intermediate `DW_AT_name` attribute for the `DW_AT_type` of the `data_ptr` child of `&str` variables, resulting in a failure to resolve those variable values during debug.
- A [RUST compiler issue](https://github.com/rust-lang/rust/issues/32574) resulted in a reference to a variable being left behind in the debug info, even though the value has been optimized out. This PR updated the error …

Stack overflow when expanding "static" section in probe-rs-debugger

---

CHANGELOG.md
probe-rs/src/architecture/arm/sequences/atsame5x.rs
probe-rs/src/architecture/arm/sequences/mod.rs
probe-rs/src/config/target.rs
probe-rs/src/probe.rs
probe-rs/src/session.rs

This change implements full support for the ATSAMD5x and ATSAME5x families by providing a custom `ArmDebugSequence` implementation for these devices which utilizes the vendor specific "CPU Reset Extension" and "Chip-Erase" features of these devices.
This implementation may work out-of-the-box (or used as a base) for other ATSAM families of devices but since I do not have any of those devices at hand, I could not test them.
With this change `--connect-under-reset` performs the Debugger Cold-Plugging which required to connect to locked devices or devices where the SWD pins have been remapped in firmware.
`--connect-under-reset --allow-erase-all` will unlock a locked device by issuing a Chip-Erase followed by a re-attach of the debug probe.
Tested on HS-Probe with ATSAME51N20A and on EDBG …

Full support for ATSAM D5x/E5x Devices

---

CHANGELOG.md
probe-rs-cli-util/src/rtt.rs

Fixes #1236
The current code panics when `defmt-decoder` reports an invalid frame index for the source location of the string.
This update intercepts (and reports) that condition, rather than panicking.
The user's test case only prints a single string, and for that string, the frame index is `8`, but every so often, `defmt_decoder` reports a frame index of `2`, which used to panic when trying to lookup the source location using that index. 
The updated code will now report the error as part of the output, e.g.
```
Set 24.0 min 0 reached true step 1
└─ src/main.rs:225
Set 24.0 min 0 reached true step 1
└─ src/main.rs:225
1
└─ <invalid location: defmt frame-index: 2>
```

Prevent panicking in probe-rs-cli-util.

---

CHANGELOG.md
cli/src/run.rs
debugger/src/debugger/debug_rtt.rs
probe-rs-cli-util/src/rtt.rs
probe-rs/src/architecture/arm/memory/romtable.rs
probe-rs/src/probe/jlink/arm.rs
probe-rs/src/probe/stlink/mod.rs

Report data decode errors when RTT channel format is `defmt`.
Notes: 
- This is a breaking API change for `probe_rs_cli::rtt::RttActiveChannel::get_rtt_data()`.
- To mitigate the impact of this change:
- `probe_rs_cli::rtt::RttActiveTarget::poll_rtt()` will maintain the original signature and behaviour of ignoring errors from `defmt` until deprecated in 0.14.0.
- The new `probe_rs_cli::rtt::RttActiveTarget::poll_rtt_fallible()` will propagate errors from `get_rtt_data()` on any of the active channels.
- `probe-rs-debugger` will now report any errors from `get_rtt_data()`.

Add RTT defmt error checking.

---

CHANGELOG.md
probe-rs/src/flashing/loader.rs

This adds:
```rust
impl FlashLoader {
pub fn data(&self) -> impl Iterator<Item = (u64, &[u8])>;
}
```
This allows users to inspect the binary data that will be flashed.
I needed this for analyzing a bug in `cargo objcopy`.
Usage:
```rust
let target = probe_rs::config::get_target_by_name(chip).unwrap();
let mut loader = probe_rs::flashing::FlashLoader::new(target.memory_map.to_vec(), target.source().clone());
loader.load_elf_data(&mut file).unwrap();
let data: Vec<(u64, &[u8])> = loader.data().collect();
```
If there's anything I should change or add, let me know 😄

Add public get_data method to FlashLoader

---

CHANGELOG.md
probe-rs/src/debug/unit_info.rs

Fixes #1252 
The problem is caused when a variable unwind generates an error message with excessively long strings. In this case, those strings contained irrelevant data, so this fix truncates those error messages after 100 characters.  
The new error message is now 
```
<variable not found "< Unimplemented: extract_location() found a location type: Bytes { value: EndianReader { range: SubRange { bytes: [255, 255, 255, 255, 240, 1, 0, 16, 0, 0, 0,  >">
``` 
Note. This fixes the reported crash, but makes no attempt at implementing the unimplemented functionality. New PR's are welcome :)

Prevent `probe-rs-debugger` from crashing when error messages are excessively long.

---

CHANGELOG.md
probe-rs/targets/MAX32660.yaml

This pull request adds a target descriptor for the MAX32660 device. The descriptor has been generated using target-gen, using [this](https://www.mxim.net/microcontroller/pack/Maxim.MAX32660.1.4.0.pack) CMSIS pack as input.

Add MAX32660 target

---

CHANGELOG.md
probe-rs/targets/STM32G0_Series.yaml

Updated the file based on the procedure outlined to me in the matrix chat by dirbaio. The diff looks a little messy, is there some formatting script I should be using? or would it be ok if I reformatted it manually?
I also have no clue how to test this. I tried replacing the probe-rs dependencies in `cargo-embed`, but it seems like there are a lot of errors, i think from previous changes to probe-rs the v0.13 release.

Update STM32G0_Series.yaml, to include latest variants (STM32G0B1 and STM32G0C1)

---

CHANGELOG.md
probe-rs/src/probe/ftdi/mod.rs

Report more verbose error message in case of insufficient access privileges to open connected/found probe devices.
This is usually caused by missing udev rules specifying unprivileged access.

Error message in case of usb device access issues.

---

Cargo.toml

This temporarily fixes #1283, but for a release it will not work.

Add a patch for the yanked funty version

---

CHANGELOG.md
probe-rs/targets/W7500.yaml

This pull request adds a target descriptor for the W7500 device from Wiznet.
The descriptor has been generated using target-gen, using this [FLM (ELF)](https://docs.wiznet.io/img/products/w7500/overview/w7500_128_flm.zip) file as input.
Some correction has been done in the memory_map section according to supplier [memory map](https://docs.wiznet.io/Product/iMCU/W7500/system-and-memory#memory-map) documentation (both !Nvm and !Ram ranges were wrong and is_boot_memory was wrongly applyed to !Ram instead of !Nvm).
Smoke_tester was successfully run with a J-Link EDU probe on real target :
```bash
georges@Goten:~/Dev/Rust/probe-rs (master)$ ./target/debug/smoke_tester --chip W7500 --probe 1366:0105
[1/1](W7500) - Starting Test
[1/1](W7500) - Probe: "J-Link"
[1/1](W7500) - Chip:  "W7500" …
```

Add Support for W7500 from Wiznet

---

CHANGELOG.md
probe-rs/src/architecture/riscv/communication_interface.rs

Previously, a call to `Riscv32::read_core_reg` could panic when passed an invalid CSR number.  The panic originated in `i_type_instruction` call as it asserts `imm <= 0xFFF`.  
Snippet of a backtrace:
```
2: core::panicking::panic
at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:48:5
3: probe_rs::architecture::riscv::assembly::i_type_instruction
at /home/fawaz/.cargo/git/checkouts/probe-rs-c1a8b38a079f9523/6ff8fae/probe-rs/src/architecture/riscv/assembly.rs:69:5
4: probe_rs::architecture::riscv::assembly::csrrs
at /home/fawaz/.cargo/git/checkouts/probe-rs-c1a8b38a079f9523/6ff8fae/probe-rs/src/architecture/riscv/assembly.rs:43:5
5: probe_rs::architecture::riscv::assembly::csrr
at /home/fawaz/.cargo/git/checkouts/probe-rs-c1a8b38a079f9523/6ff8fae/probe-rs/src/ …
```

riscv: validate csr address in read/write_csr_progbuf

---

CHANGELOG.md
probe-rs-target/src/flash_algorithm.rs
probe-rs/src/flashing/flash_algorithm.rs

This proposes one of the ideas described in #1251. If accepted, I'll immediately use this feature in #1250.
Flash algorithms support a new field, `stack_size`, to configure the flash algorithm's stack size. probe-rs prefers the flash algorithm's stack size, but defaults to 512 bytes if the stack size isn't specified.
With this commit, I could configure my MIMXRT1170EVK target's flash algorithm with a 4K stack size, and program it. I could also program an MIMXRT1010EVK, which doesn't specify any stack size.

Support target-specific flash algo stack size

---

CHANGELOG.md
probe-rs/src/architecture/arm/sequences/atsame5x.rs
probe-rs/src/architecture/arm/sequences/mod.rs
probe-rs/src/flashing/erase.rs
probe-rs/src/flashing/flasher.rs
probe-rs/src/flashing/loader.rs
probe-rs/src/session.rs

An experimental way of enabling Custom Erase Sequences during erasing and flashing
I thought I'd try to implement the idea of Custom Erase Sequences as per our Matrix discussion. 
This PR is tested to work fine on ATSAM D5x/E5x that have this custom Chip-Erase procedure but I'm not expecting it to be merged as is but rather as a discussion on whether its at all a feasible way forward.  If you think its in the right direction, I'll be happy to finalize it. Likewise, if there are better ways to do it I'm open for that too.

Debug Erase Sequences

---

CHANGELOG.md
probe-rs/targets/GD32E50x_Series.yaml

Tested and working with GD32E503E-START dev board with a onboard GD32E503CE. Generated from GigaDevice.GD32E50x_DFP.1.3.2.pack found here: https://developer.arm.com/tools-and-software/embedded/cmsis/cmsis-packs

added support for GD32E50x series

---

CHANGELOG.md
cli/Cargo.toml
cli/src/info.rs
probe-rs/src/architecture/arm/communication_interface.rs
probe-rs/src/architecture/arm/memory/romtable.rs
probe-rs/src/probe/fake_probe.rs
probe-rs/src/probe/stlink/mod.rs

Nicer info output, in tree structure:
```
Debug Port: Version 2, Designer: ARM Ltd
├── 0 MemoryAP
│   └── ROM Table (Class 1)
│       ├── ROM Table (Class 1)
│       │   ├── Cortex-M33 SCS  (Coresight Component)
│       │   ├── Cortex-M33 DWT  (Coresight Component)
│       │   ├── Cortex-M33 BPU  (Coresight Component)
│       │   └── Cortex-M33 ITM  (Coresight Component)
│       └── Cortex-M33 TPIU  (Coresight Component)
├── 1 MemoryAP
│   └── Error during access: A core architecture specific error occurred
└── 2 Unknown AP (Designer: NXP (Philips), Class: Undefined, Type: 0x0, Variant: 0x0, Revision: 0x0)
```

Better info output in probe-rs-cli

---

CHANGELOG.md
probe-rs/src/probe/ftdi/commands.rs
probe-rs/src/probe/ftdi/mod.rs

- Refactors `read_register()`, `write_register()`, `transfer_ir()`, `transfer_dr()`, and `reset()` to use `JtagCommand`s                                                     
- Changes several function returns to use `Result` instead of `io::Result`
- Creates new JtagCommands `ReadRegisterCommand` and `TransferIrCommand`
- Changes `TransferDrCommand`'s impl to be `pub(super)`, matching `WriteRegisterCommand`
- Removes individual transfer JtagAdapter functions `shift_tms()`, `shift_tdi()`, `transfer_tdi()`
Fixes #1307.

WIP Refactor FTDI impl to use all JtagCommand logic

---

CHANGELOG.md
probe-rs/src/architecture/arm/core/armv7m.rs
probe-rs/src/architecture/arm/sequences/infineon.rs
probe-rs/src/architecture/arm/sequences/mod.rs
probe-rs/src/config/target.rs
probe-rs/targets/XMC4000.yaml

This PR adds [Infineon XMC4000](https://www.infineon.com/cms/en/product/microcontroller/32-bit-industrial-microcontroller-based-on-arm-cortex-m/32-bit-xmc4000-industrial-microcontroller-arm-cortex-m4/) support, fixing #1134.
I intend to test this PR again with all my XMC4xxx boards before marking it as ready for review. I'm opening it as a draft for discussion.
This product family requires a series of nonstandard debug sequences. This module adds them.
CMSIS provides a means for Infineon to describe these sequences in a machine-readable way. Infineon chose not to do so, instead directing everyone to use SEGGER J-Link instead. I developed my own understanding of the requirements from the reference materials, implemented it, and documented my implementation here.
In my view, the main …

Add Infineon XMC4000 support

---

cli/src/info.rs
probe-rs/src/architecture/arm/communication_interface.rs
probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs
probe-rs/src/architecture/arm/memory/romtable.rs
probe-rs/src/probe/fake_probe.rs
probe-rs/src/probe/jlink/arm.rs

- Detect when Memory-AP is not enabled, and show in output.
- Show TARGETID register in output when available.
- Fix endless recursion in J-Link register access.

Improve cli info output

---

CHANGELOG.md
probe-rs/src/config/target.rs

The STM32F1 also needs the sequence to function correctly when wfi is used (see #350).
The lowest 8 bits of the DBGMCU_CR register (which are used in the [stm32f sequence](https://github.com/probe-rs/probe-rs/blob/7243f5afe17bea45610a10f829aabd635d4f3b47/probe-rs/src/architecture/arm/sequences/stm32f_series.rs#L34-L38)) are the same as with the STM32F4 so the sequence should be applicable for the STM32F1 as well.
Unfortunately this still doesn't work correctly when the device is first connected to the st-link. ("Command failed with status SwdDpWait") But at least all subsequent flashes after the first flash (done with `--connect-under-reset` and manual resetting) work now with this patch.

Use sequence for STM32F1

---

CHANGELOG.md
debugger/src/debug_adapter/dap_adapter.rs
debugger/src/debugger/core_data.rs
debugger/src/debugger/debug_entry.rs
debugger/src/debugger/session_data.rs
probe-rs/src/debug/mod.rs
probe-rs/src/debug/unit_info.rs
probe-rs/src/debug/variable.rs

When the debugger is stepping or halting at breakpoints, it fails to retrieve (and display) all RTT data from the target.
The root cause of this is related to how the debugger queried and cached the core status from the target. Over various iterations of development, the status handling spread through various parts of the code and the 'last_known_status' was not always in synch between the DAP Client (VSCode), the DAP server (probe-rs-debugger) and the target itself.
This PR is a refactor of the status handling, and centralizes code that checks target status, as well as code that notifies the DAP Client of the status of the target.
Hint: For testing, you can install this branch with `cargo install --force --git https://github.com/probe-rs/probe-rs --branch debugger_rtt_fix …

Debugger: Fix RTT data from target is not polled/reported in a timely manner - during stepping, and after breakpoint halting.

---

CHANGELOG.md
probe-rs/targets/EFM32GG11B_Series.yaml

This was generated by target-gen from the SiliconLabs GeckoPlatform EFM32GG11B DFP 4.2.0 pack.

targets: add EFM32GG11B series

---

CHANGELOG.md
probe-rs/build.rs

Not sure if it makes sense to add tests when the only change is made to `build.rs`.

Added support for finding targets externally

---

cli/src/info.rs
cli/src/main.rs

See #1349, show the error message if an error occurs, and don't warn about JTAG when SWD is used.

Show error message when an error occurs in info command

---

CHANGELOG.md
probe-rs/Cargo.toml
probe-rs/src/probe/ftdi/commands.rs
probe-rs/src/probe/ftdi/mod.rs

As discussed in the matrix chat, recent commits I have authored break the FTDI probe implementation (thank you @9names for testing). These are commits #1303 and #1308 (tracking issues #1302 and #1307). This commit reverts both commits (but not the merge commits), so I can work on and test these changes out of tree without blocking the upcoming release. I apologize for any headache this may have caused and will ensure proper testing and better communication on my part in the future.
To verify this revert, I have side-by-side reviewed the reverted commits and flashed my test RISCV board using an FTDI probe. Applying relevant patches to get my FTDI probe and RISCV testing target working  (change interface, different GPIO pin direction/output for FTDI probe and custom reset sequence for RISCV …

Revert recent broken FTDI changes

---

debugger/src/debug_adapter/dap_adapter.rs
probe-rs-target/src/flash_algorithm.rs

#1355 Introduced new deprecation warnings for `base64::encode/decode`.
As per [their deprecation note in docs](https://docs.rs/base64/latest/base64/) I replaced those calls and used the `STANDARD` engine.
They do have a `BIN_HEX` specific alphabet, but using that fails the build script when trying to encode existing target flash algorithms, and as such I've not tried to implement `BIN_HEX`.

Replace deprecated `base64::encode/decode`

---

CHANGELOG.md
probe-rs/src/probe/cmsisdap/tools.rs

It turns out it's legitimate for CMSIS-DAP devices to just put that in an interface string, even though most put it in the product string too (as required for non-composite devices). This PR tries to check interface strings too, though this requires rusb and permission to access the device. Apparently on some platforms hidapi will report the interface string in the path, but not on mine, so it's included here as a talisman for good luck...
It's a bit hard to read the diff because mostly it changes indentation on existing code, but essentially we now always loop through all the interfaces to see if any are CMSIS-DAP _or_ HID, and then return Some(DebugProbeInfo) if the product string or any interface string had CMSIS-DAP in it. Consequently I'm fairly sure this shouldn't break any existing …

CMSIS-DAP: Check for CMSIS-DAP string in interface strings too

---

CHANGELOG.md
Cargo.toml
cargo-embed/CHANGELOG.md
cargo-flash/CHANGELOG.md
rtt/Cargo.toml
target-gen/Cargo.toml

This is the release PR for **0.14.0**.
---
It releases:
- probe-rs
- probe-rs-target
- probe-rs-rtt
- probe-rs-cli-util
- probe-rs-cli
- probe-rs-debugger
- gdb-server
- target-gen
- rtthost
- cargo-embed
---
Use `bors r+` to merge.

Release release/0.14.0

---

CHANGELOG.md
probe-rs/src/probe/stlink/mod.rs

Memory accesses send the command, then get the result with `get_last_rw_status()`. We were retrying only getting the status. We have to retry the command as well.
This fixes SwdDpWait errors when flashing stm32c0 chips.

stlink: fix retries on DP/AP WAIT errors.

---

CHANGELOG.md
probe-rs/targets/STM32C0_Series.yaml

Adding support for STM32C0 targets (STM32C011 and STM32C031) .
Generated via `target-gen arm -f STM32C0xx_DFP`

Add target support for STM32C0 series

---

CHANGELOG.md
probe-rs/src/flashing/flasher.rs

Avoid nested calls to the tracing functions, to avoid the issue described in #1415.

Avoid emitting nested tracing messages (fix #1415)

---

CHANGELOG.md
Cargo.lock
target-gen/Cargo.toml
target-gen/src/algorithm_binary.rs
target-gen/src/generate.rs
target-gen/src/main.rs
target-gen/src/parser.rs

Add a new `--fixed-load-address` flag to the `target-gen elf` command. This will determine the load address automatically from the ELF and set the appropriate field in the YAML file.
This can be used if the flash algorithm is *not* position independent.

target-gen: Add load address to generated target file

---

CHANGELOG.md
cli/src/run.rs

A very high polling frequency can lead to USB connection instability,
so we should sleep between polling.

probe-rs-cli: Reduce RTT polling frequency in run command

---

cargo-embed/CHANGELOG.md
cargo-embed/src/main.rs
cargo-embed/src/rttui/app.rs
cargo-embed/src/rttui/channel.rs
cli/CHANGELOG.md
cli/src/main.rs
cli/src/run.rs
debugger/src/debugger/core_data.rs
debugger/src/debugger/debug_entry.rs
debugger/src/debugger/session_data.rs
debugger/src/main.rs
probe-rs-cli-util/src/rtt.rs

The offset between local time and UTC can only be determined when
only a single thread is running. If it's done with multiple threads,
it will fail.
This PR changes all tools to determine the offset once at the beginning,
and then store it.

fix: Determine local time as early as possible

---

Cargo.lock
cargo-embed/CHANGELOG.md
cargo-flash/CHANGELOG.md
probe-rs-cli-util/Cargo.toml
probe-rs-cli-util/src/logging.rs

The logging was done in the format call, which is not the correct place. Also, some logging calls where missing when the output was redirect to a file, since indicatif does not print the messages in that case.
This PR also changes the log output target, the log messages are now sent to stderr, not stdout. This is the default behaviour of the logger. The log target could be changed back to stdout if desired.

Improve logging in probe-rs-cli-util

---

CHANGELOG.md
cli/src/info.rs
probe-rs/src/architecture/arm/ap/memory_ap/mock.rs
probe-rs/src/architecture/arm/ap/mod.rs
probe-rs/src/probe.rs
probe-rs/src/probe/stlink/mod.rs
probe-rs/src/probe/stlink/usb_interface.rs
probe-rs/src/session.rs

`probe-rs-cli info` was updated to also read the DPIDR register, which led to errors with ST-Link probes.
Newer ST-Link firmware actually supports reading this register, so this PR adds a firmware version check.
This should fix #1349.

Fix: Support reading banked DP register on ST-Link

---

.github/dependabot.yml

With the checked in lockfile, I find the daily dependabot PRs a bit too frequent.
Weekly updates are still enough to not become too outdated.

ci: Reduce dependabot frequency to weekly

---

CHANGELOG.md
probe-rs/src/architecture/riscv/sequences/esp32c6.rs
probe-rs/src/architecture/riscv/sequences/mod.rs
probe-rs/src/config/target.rs
probe-rs/targets/esp32c3.yaml
probe-rs/targets/esp32c6.yaml

- Adds a flash loader algo generated from https://github.com/esp-rs/esp-flash-loader/pull/2
- Adds a reset sequence which disables watchdogs
As with the ESP32C3, this only supports flashing [direct-boot](https://github.com/espressif/esp32c3-direct-boot-example#esp32-c3-direct-boot-example) format elf files.
There is an experimental branch adding ESP32C6 support to esp-hal [here](https://github.com/JurajSadel/esp-hal/commits/esp32c6), which you can use to test this algo. `cargo build --example $NAME --features direct-boot` and flash with probe-rs-cli, or `cargo flash --protocol jtag --speed 1000 --chip esp32c6 --example hello_world --features direct-boot`

ESP32C6 support

---

CHANGELOG.md
probe-rs/src/architecture/arm/sequences/nxp.rs

This fixes a race condition between the debugger and the MCU during reset.
Prior to this change, flashing would often fail.
After this change, I can reliably flash my Teensy 4.1 (which uses an NXP i.MX RT1062) using JTAG.
For reference, my original observations were captured here: https://github.com/probe-rs/probe-rs/pull/1174#issuecomment-1275568493
/cc @mciantyre

nxp: fix reset sequence

---

.vscode/launch.json
CHANGELOG.md
debugger/src/debugger/core_data.rs

During the 'step' processing, the debugger would send a `StoppedEvent` with reason `step`, and immediately after, the regular polling operation would send another `StoppedEvent` with reason `breakpoint`. The result of this was that the client would duplicate the identical sequence of  `Threads->Stacktrace->Scopes->Variables` requests. This caused duplicated processing in `probe-rs-debugger`.

Fix extraneous MSDAP "StoppedEvent" being sent from `probe-rs-debugger`

---

CHANGELOG.md
target-gen/src/generate.rs

STAR-MC1 is a variant of Armv8-M with TrustZone designed by Arm China.
See-also: https://github.com/pyocd/cmsis-pack-manager/pull/204

Add support for Star-MC1 core

---

CHANGELOG.md
probe-rs/targets/STM32F3_Series.yaml

Hi,
This PR adds a second ram section to `memory_map` of `STM32F303VCTx`. This is to fix https://github.com/knurling-rs/defmt/issues/713.
The `memory.x` generated by `stm32fxx-hal` ([link to function which generates it](https://github.com/stm32-rs/stm32f3xx-hal/blob/master/build.rs#L113)) looks like following:
```
MEMORY {
FLASH (rx) : ORIGIN = 0x8000000, LENGTH = 256K
CCMRAM (rwx) : ORIGIN = 0x10000000, LENGTH = 8K
RAM (rwx) : ORIGIN = 0x20000000, LENGTH = 40K
}
```
The `memory_map` so far only specified the `CCMRAM` and not the `RAM`. This PR fixes this and also fixes https://github.com/knurling-rs/defmt/issues/713.
Likely a few other chips stm32f3 chips also miss the second ram. If you generally agree with this PR I can also add those.

Update `probe-rs/targets/STM32F3_Series.yaml` with `target-gen`

---

CHANGELOG.md
probe-rs/src/probe/jlink/arm.rs

Fixes flashing the nrf91 with the onboard jlink. 
Chip erase still fails though. I think it has never worked, even in past versions where flashing did work.
related: #1223

jlink: correctly return WAIT status for AP reads.

---

CHANGELOG.md
probe-rs/src/flashing/flasher.rs

This PR fixes #1469 ( again) by updating emission of the flash erase start/stop events to not depend on the presence of the erase debug sequence.
CC @Yatekii

Fixing erase progress event emission

---

CHANGELOG.md
debugger/src/debugger/core_data.rs

Fixes #1497
The long delay is caused when RTT attach attempts to scan the target memory for the RTT control block. Since there is none, this retries and has no hope of ever succeeding.
The change now scans the binary file for the RTT control block, and will not fall back to scanning the target memory.
This makes the user experience much better, but ultimately the overhead can be completely avoided by deleting, or setting `rttEnabled: false` in the launch.json, if the target application does not use RTT.

Fix: VSCode using probe-rs debugger is very slow if `rttEnabled: true` and target application has no RTT.

---

CHANGELOG.md
debugger/src/debug_adapter/dap_adapter.rs

Fixes #1275
The original issue was more noticeable against the ESP32-C3 RISC-V chip, but the solution will improve performance of this operation for all core types.

`prober-rs-debugger`: Improve performance of the `readMemory` request.

---

CHANGELOG.md
probe-rs/src/architecture/arm/sequences/nxp.rs
probe-rs/src/config/target.rs

Adding support for LPC55Sxx chips besides the LPC55S69, which was already supported.
Tested with cargo flash and cargo embed, working for both on LPC55S28

Add target support for LPC55Sxx chips

---

CHANGELOG.md
probe-rs/src/architecture/arm/sequences/mod.rs
probe-rs/src/architecture/arm/sequences/stm32_armv6.rs
probe-rs/src/architecture/arm/sequences/stm32_armv7.rs
probe-rs/src/config/target.rs

Currently probe-rs supports custom sequences on STM32F1/2/4/7 and H7. I've checked the reference manuals and F3, G4, WB, WL, L1, and L4 all have the same DBGMCU_CR register in the same location with the same bits as the F1/2/4/7 we already support, so this PR renames the "stm32f_series" to "stm32_armv7" and includes all those families. STM32H7 remains a separate case.
The STM32s with Cortex-M0/M0+ CPUs (ie ARMv6) have a very different DBGMCU which is on the APB bus, has its own clock enable bit in RCC, and only supports DBG_STOP and DBG_STANDBY. On these CPUs, going to normal sleep does not disable the debug interface (unlike the ARMv7 ones). This PR adds support for these CPUs, enabling the DBG clock in RCC and setting those DBG_STOP/DBG_STANDBY bits. I think this is probably worth …

Add custom sequence support for STM32 F0, F3, G0, G4, WB, WL, L0, L1, L4

---

CHANGELOG.md
probe-rs/src/architecture/arm/sequences/mod.rs
probe-rs/src/architecture/arm/sequences/stm32_armv6.rs
probe-rs/src/architecture/arm/sequences/stm32_armv7.rs
probe-rs/src/architecture/arm/sequences/stm32h7.rs
probe-rs/src/session.rs
target-gen/Cargo.toml

Add the default implementation for `debug_core_stop`, taken from https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/debug_description.html#debugCoreStop.

Feat: Add default debug_core_stop sequence

---

debugger/src/debug_adapter/dap_adapter.rs
debugger/src/debug_adapter/protocol.rs
debugger/src/debugger/configuration.rs
debugger/src/debugger/debug_entry.rs
debugger/src/debugger/session_data.rs
debugger/src/main.rs
probe-rs/src/core.rs
probe-rs/src/debug/source_statement.rs
probe-rs/src/debug/variable.rs
probe-rs/src/probe/stlink/mod.rs

I've tried to refactor the "startup" code of the debugger to make it a bit easier to read, the actual functionality should be unchanged.
It's mostly splitting up the `debug_session` function into different functions, so it's easier to see what's going on, and trying to reduce the nesting level, by returning early.
@noppej This probably conflicts with #1506, I'm happy to wait until that one gets merged and will then update this PR.

Refactor startup code in debugger

---

.github/workflows/ci.yml

Uses cargo & clippy provided by dtolnay/rust-toolchain
Fixes #1396

Removes actions-rs/cargo and actions-rs/clippy-check from GitHub Actions

---

cargo-embed/CHANGELOG.md
cargo-embed/README.md

The cargo-embed install was complaining about being "Unable to find libusb-1.0" until I also installed libusbx-devel, so am suggesting that the readme gets updated to reflect this.

Update fedora prerequisites

---

CHANGELOG.md
target-gen/src/commands/test.rs

Hi all,
This PR is an attempt to fix this issue: https://github.com/probe-rs/flash-algorithm-template/issues/4
I've tested it on STM32WLE5JC with my DIY flash algorithm and it works fine.
Regards,
Jackson

Use the correct flash base address when testing flash algorithm with target-gen

---

CHANGELOG.md
probe-rs/targets/EFM32TG11B_Series.yaml

Closes #1420. Not sure what changed, but after rebuilding with version 0.16.0 and the new target yaml everything works as expected.

Add support for EFM32TG11B family

---

CHANGELOG.md
debugger/src/debug_adapter/dap_adapter.rs
debugger/src/debug_adapter/debugProtocol.json

- Update to 1.60.0 of the MS DAP Specification.
- The timing and lifetime of the `Threads->StackTrace->Scopes->Variables` requests have been clarified in the documentation, and how and when VSCode sends these requests, have also been updated. 
- In response, this PR moves the 'unwinding' of the probe-rs-debugger stackframes, from 'Threads' request to the 'StackTrace` request, to avoid mismatches in cached data when VSCode refreshes the `Threads` and `Scopes` data, without refreshing the `StackTrace` data.

`probe-rs-debugger` updates related to MS DAP protocol implementation.

---

CHANGELOG.md
debugger/src/debugger/configuration.rs
debugger/src/debugger/debug_entry.rs

- Remove `reset_after_flashing` option.
- The debugger will silently ignore this option if requested from the VSCode configuration.
- Future VSCode extension updates will remove this option.
- Fix Issue #1529
The new behaviour is that the target connect sequence will be as follows.
- During `Launch/Attach` request processing
- Halt the target.
- For `Launch` requests optionally flash the target.
- For `Launch` requests, reset the target and halt the target.
- After completion of `ConfigurationDone` from VSCode
- For `Launch` requests, optionally resume the target.
- For `Attach` requests, resume the target.

probe-rs-debugger: Fix "Launch/Attach" behavior.

---

CHANGELOG.md
cargo-embed/src/main.rs
probe-rs-cli-util/src/common_options.rs
probe-rs/src/config/mod.rs
probe-rs/src/config/registry.rs
target-gen/src/commands/test.rs

Currently, the `add_target_from_yaml` function only accepts yaml file with the specified file path and cannot accept yaml file embedded in executable file (use `include_bytes!` macro).
This PR modification allows the `add_target_from_yaml` function to accept arguments that implement the `std::io::Read` trait, which takes a yaml string, a byte stream embedded in an executable, and a file object as arguments.

Allows add_target_from_yaml function to accept multiple sources

---

CHANGELOG.md
gdb-server/src/target/monitor.rs

Fixes #1564
I have little experience with rust OR embedded dev so this implementation is quite naive — please let me know what can be improved.
Thanks!

Add support for `monitor reset` and `monitor reset halt` commands

---

CHANGELOG.md
probe-rs/build.rs

If any file in `PROBE_RS_TARGETS_DIR` is changed, rebuild of the `probe-rs` library gets triggered.

 Detect changes in the PROBE_RS_TARGETS_DIR

---

CHANGELOG.md
probe-rs/src/architecture/arm/sequences/efm32xg2.rs
probe-rs/src/architecture/arm/sequences/mod.rs
probe-rs/src/config/target.rs

At least my EFR32BG22C224F512IM40 does not obey VC_CORERESET.  The JLink system uses a breakpoint on the reset vector for this chip.

Add reset catch sequence for Silicon Labs EFM32/EFR32 Series 2 chips

---

CHANGELOG.md
debugger/src/server/debugger.rs

With this PR, we now allow restart, but will not re-flash, so that we avoid the issue #1519, while still allowing users to restart their target during debugging.
cc: @MabezDev please confirm that this is what you requested :)

Debugger: Slightly relax the RISC-V restriction when handling of `restart` request.

---

CHANGELOG.md
probe-rs/targets/STM32H5_Series.yaml

Tested working on nucleo-h563zi.
Something interesting is that the core is on AP1, not AP0. AP0 contains some mailbox bullshit so that when the debug port is locked you can talk to the bootloader to unlock it.

targets: add stm32h5.

---

CHANGELOG.md
debugger/src/debug_adapter/dap/adapter.rs
debugger/src/debug_adapter/protocol.rs
debugger/src/server/core_data.rs
debugger/src/server/debug_rtt.rs
debugger/src/server/debugger.rs
debugger/src/server/session_data.rs

When errors happen in MS DAP requests `initialize`, `launch` or `attach`, requests, the VSCode client terminates the session, and any late arriving error messages from 'probe-rs-debugger' are ignored.
This PR ensures that error messages are logged/displayed to the client, before sending the error response to these requests.
- This fixes errors such as reported in https://github.com/probe-rs/vscode/issues/57.
In addition to changing the timing of the user facing messages, this PR also updated the following related to error handling:
- Updates the `Request` handling to follow the MS DAP guideline more strictly, and makes use of the `ErrorResponse` struct, rather than just reporting the error message in the `Response` struct.
- Renamed `DebugAdapter::send_error_response()` to …

Fix: Show errors that happen before the VSCode startup has completed.

---

.github/actions/setup/action.yml
.github/workflows/release.yml
.github/workflows/release_crates.yml
Cargo.toml

This updates the Rust version in CI to 1.68.2, and installs the build dependencies for the binary creation in the correct step.
It also splits `cargo release` into multiple steps, to avoid the issue seen in the [latest CI run](https://github.com/probe-rs/probe-rs/actions/runs/4576125486/jobs/8079840403#step:9:1344), where pushin the commit failed due to branch protection.
Tip: Hiding the whitespace changes makes the diff much clearer.

Update Rust version in CI, try to fix release CI

---

CHANGELOG.md
probe-rs/src/probe/ftdi/mod.rs

Thanks for making `probe-rs`, it's very nice!
This PR adds the PID/VID for the [Olimex ARM-USB-TINY-H] JTAG adapter ([datasheet]) as being compatible with FTDI devices.
This device contains an FTDI `FT2232H` chip internally.
Here's the OpenOCD config for reference: [olimex-arm-usb-ocd.cfg](https://github.com/openocd-org/openocd/blob/573a39b36cf133bb7403b12337301a5616112f1a/tcl/interface/ftdi/olimex-arm-usb-ocd.cfg).
I tested this manually and was able to halt, resume, and read the memory of a RISC-V chip running on an FPGA.
Let me know if there's any more thorough testing I can do.
There are other Olimex devices using the `FT2232H/C` chips with PIDs `0x0004`, `0x0003`, and `0x002B` but I don't have any to test with so didn't add them.
[Olimex ARM-USB-TINY-H]: …

Add support for the Olimex ARM-USB-TINY-H JTAG adapter

---

probe-rs/targets/GD32E10x_Series.yaml

Adding support for GD32E10x series chip.
Generated via target-gen from https://gd32mcu.com/data/documents/pack/GigaDevice.GD32E10x_DFP.1.2.1.pack
Tested and working with cargo-embed/cargo-flash and cmsis-dap on GD32E103TBU6.

Add target file for GD32E10x series chip

---

CHANGELOG.md
probe-rs/src/architecture/arm/ap/memory_ap/mock.rs
probe-rs/src/architecture/arm/communication_interface.rs
probe-rs/src/architecture/arm/core/armv6m.rs
probe-rs/src/architecture/arm/core/armv7a.rs
probe-rs/src/architecture/arm/core/armv7m.rs
probe-rs/src/architecture/arm/core/armv8a.rs
probe-rs/src/architecture/arm/core/armv8m.rs
probe-rs/src/architecture/arm/core/mod.rs
probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs
probe-rs/src/architecture/arm/traits.rs
probe-rs/src/core.rs
probe-rs/src/probe/cmsisdap/mod.rs
probe-rs/src/probe/fake_probe.rs
probe-rs/src/probe/jlink/arm.rs
probe-rs/src/probe/stlink/mod.rs

Add `set_running` functionality to all ARM related traits to propagate running state to probes.
This is mostly to actually use `HostStatus::Running`, which some probes support (including the rusty probe),  working.
I have basically taken a shortcut and just added the method to all relevant traits in the tree, and propagated it on from there. Feedback is welcome and refusal would be understandable, though I think it'd be quite nice to get this functionality implemented.

Propagate running state to probes

---

CHANGELOG.md
cargo-flash/CHANGELOG.md
cargo-flash/src/main.rs
probe-rs-cli-util/src/flash.rs

Fixes #1593 
Should [this println](https://github.com/probe-rs/probe-rs/blob/master/cargo-flash/src/main.rs#L139) also be an `eprintln`?

Print "Finished" message to stderr instead of stdout when flashing with `probe-rs-cli run`

---

README.md

This depends on https://github.com/probe-rs/webpage/pull/78 to actually add the trouble-shooting page.

Mention troubleshooting page in README.md

---

CHANGELOG.md
probe-rs/targets/PY32F0_Series.yaml

Adding support for PY32F0 series chip.
Generated via target-gen from https://www.puyasemi.com/uploadfiles/2023/PY32F030-PY32F003-PY32F002A-230410.rar
(Puya.PY32F0xx_DFP.1.1.7.pack inside)
Tested and working with cargo-embed/cargo-flash and cmsis-dap on PY32F002AF15P6.

Add target file for PY32F0 series chip

---

cargo-embed/CHANGELOG.md
cargo-embed/src/config/mod.rs
cargo-embed/src/main.rs

The documentation of the default.toml embed configuration suggests, that to turn of logging, one must change log_level to "OFF".
Error Failed to parse supplied configuration:
unknown variant: found `OFF`, expected `one of `ERROR`, `WARN`, `INFO`, `DEBUG`, `TRACE`` for key "default.general.log_level" in
This does not work yet, as this options is parsed to `log::Level`, which does not contain such option. Change it to `log::LogLevel` to enable this otpion.

fix(embed): enable turning off logging messages

---

CHANGELOG.md
debugger/src/debug_adapter/dap/adapter.rs
debugger/src/debug_adapter/dap/debugProtocol.json
debugger/src/server/core_data.rs
debugger/src/server/session_data.rs
probe-rs/src/probe.rs

- Updated MS DAP Protocol to version 1.61.0
- Fix an "unreported" issue, where the MS DAP Request `setBreapoints` cleared breakpoints for all `Source` 's, instead of only clearing existing breakpoints for the specified `Source`.

probe-rs-debugger: Fix MS DAP Request `setBrakpoints` cleared too many breakpoints.

---

.github/actions/setup/action.yml
.github/workflows/release.yml
Cargo.lock
Cargo.toml
probe-rs/Cargo.toml
probe-rs/src/bin/probe-rs/cargo_embed/mod.rs
probe-rs/src/bin/probe-rs/cargo_flash/diagnostics.rs
probe-rs/src/bin/probe-rs/cargo_flash/mod.rs
probe-rs/src/bin/probe-rs/dap_server/mod.rs
probe-rs/src/bin/probe-rs/dap_server/server/session_data.rs
probe-rs/src/bin/probe-rs/dap_server/server/startup.rs
probe-rs/src/bin/probe-rs/main.rs
probe-rs/src/bin/probe-rs/run.rs
probe-rs/src/bin/probe-rs/util/common_options.rs
probe-rs/src/debug/debug_step.rs

Follow-up cleanup to #1637 
- Remove duplicate list-chips and list-probes commands/flags. Only left are `probe-rs list` for listing probes, `probe-rs chip list` for listing chips.
- Command to start DAP server is now `probe-rs dap-server`, not `probe-rs dap-server debug`.

Remove duplicate list-chips and list-probes.

---

CHANGELOG.md
probe-rs/src/flashing/error.rs

The start address was zero-padded, but the end address was not. This is an entirely cosmetic change to make it easier to read this error message.
(I originally wrote this while working on #1642 but have extracted it into its own PR because it's independent of what I was doing over there.)

flashing: Fix small inconsistency in FlashError::NoSuitableNvm error message

---

CHANGELOG.md
probe-rs/src/flashing/flasher.rs

Some targets have constraints on where flash algorithms can be loaded, such as if the flash algorithm relies on target ROM routines that use certain RAM regions as scratch space, if the flash algorithm must run from secure memory (e.g. Arm TrustZone), or if the algorithm just doesn't use position-independent code for some reason.
The flash algorithm model already supported fixed load addresses, but the flasher did not take that into account when selecting a RAM region and so it worked only if the chosen load address happened to be in the very first RAM region.
Instead we'll now remove from consideration any RAM region that doesn't contain the required load address, and therefore choose the first region that contains that address. This will work only if the chosen load address leaves …

flashing: Select RAM region by fixed algorithm load address

---

CHANGELOG.md
Cargo.lock
probe-rs/Cargo.toml
probe-rs/src/bin/probe-rs/cmd/download.rs
probe-rs/src/bin/probe-rs/cmd/run.rs
probe-rs/src/bin/probe-rs/main.rs
probe-rs/src/flashing/download.rs
probe-rs/src/flashing/loader.rs

ESP-IDF bootloader format is essentially a binary format with a header and splits the application into different segments. Read more [here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/app_image_format.html#app-image-structures).
Overall I feel like this has gone in quite cleanly, and seems to work well from my limited testing (minus the fact that the current esp32c3 bootloader is slow as hell).
~~I don't like having to depend on xmas elf. We should make this internal to espflash or use the object crate in espflash.~~
Whilst adding support for the esp-idf bootloader, I also refactored the `cli` module a bit.

ESP-IDF bootloader format

---

.vscode/launch.json
CHANGELOG.md
probe-rs/src/bin/probe-rs/cmd/dap_server/server/configuration.rs
probe-rs/src/bin/probe-rs/cmd/dap_server/server/debugger.rs
probe-rs/src/bin/probe-rs/main.rs
probe-rs/src/flashing/download.rs

In addition to the currently supported `Elf` format, this adds support for binary formats `Bin`, `Hex`, and `Idf`.
Fixes #1647 
Note: Needs updated probe-rs VSCode extension from https://github.com/probe-rs/vscode/pull/62

dap-server: Add support for non `Elf` binary formats.

---

CHANGELOG.md
probe-rs/targets/PAC55XX_Series.yaml

Add support for PAC55XX SoCs. Target file has been generated using `target-gen` and the latest CMSIS pack from
https://www.qorvo.com/extra/keil_pack/.
Tested with `probe-rs download/reset` on PAC5527. Note that there seem to be some issues with RTT (not when using VSCode extension, though).

targets: add support for PAC55XX

---

CHANGELOG.md
probe-rs/src/probe.rs
probe-rs/src/probe/espusbjtag/mod.rs
probe-rs/src/probe/espusbjtag/protocol.rs

* Split single execution writes in `prepare_` and `recieve_` parts.
* Add batched writes which runs `prepare` x times and batches results.
* To facilitate batching, an `OwnedBitIter` struct was added to keep the
bits around longer than a single write call.
* Added the ability to query the probe speed
* Finally, add a warning when using the default implementation for `JTAGAccess::write_register_batch`.

esp-usb-serial-jtag: Add write batching

---

CHANGELOG.md
probe-rs/src/bin/probe-rs/cmd/download.rs
probe-rs/src/bin/probe-rs/main.rs

fix: download cmd `--base-address` collision
In debug mode this would cause a panic due to duplicate arg.
In release, it would effectively silently ignore `--base-address`.
Regression happened in PR #1649.
fix: download cmd removed obsolete `--skip-bytes`
Literally did nothing, correct arg is `--skip`.
Regression happened in #1649.
fix: download cmd `--skip` now supports hexadecimal
Obsolete `--skip-bytes` would accept hexadecimal, but had no effect.
Regression happened in PR #1649.

Fix regressions in `download` subcommand caused by PR #1649

---

README.md

The links to the subdirectories don't make any sense now, the directories are gone.

Mention cargo-flash etc. in readme

---

CHANGELOG.md
Cargo.lock
probe-rs/Cargo.toml
probe-rs/src/architecture/arm/component/dwt.rs
probe-rs/src/bin/probe-rs/cmd.rs
probe-rs/src/bin/probe-rs/cmd/profile.rs
probe-rs/src/bin/probe-rs/cmd/run.rs
probe-rs/src/bin/probe-rs/main.rs

This PR adds a very naive profiler to the cli toolkit, the output looks something like this:
As discussed in matrix, there are several ways to improve this, but these are arch specific. For example, on RISCV, once we have support for the quick access abstract command interface we can poll the PC without halting the core. I'm sure there are ARM equivalents, and of course, we could plug this into SWO output too.

probe-rs-cli: add a simple profiler

---

CHANGELOG.md
probe-rs/targets/MSP432E4_Series.yaml

Adding support for MSP432E4 targets (MSP432E401Y and MSP432E411Y) .
Generated via target-gen from https://software-dl.ti.com/msp430/msp430_public_sw/mcu/msp430/msp432cmsis/latest/exports/TexasInstruments.MSP432E4_DFP.3.2.6.pack
Tested with probe-rs-cli download and hs-probe - working!
~~Tested via the onboard XDS110 CMSIS-DAP compatible debugger on MSP-EXP432E401Y - not functional.
XDS110 also fails with known good targets (STM32H7, RP2040) so I expect the issue lies with the debugger, not the algo.~~
XDS110 actually works fine, but the probe defaults to JTAG which probe-rs doesn't support.
Works fine when specifying protocol as SWD

Add target support for MSP432E4 series

---

CHANGELOG.md
probe-rs/src/probe.rs

This fixes every instance of the word "occured" to be "occurred"

Fix spelling of error message for word "occurred"

---

probe-rs/src/architecture/arm/core/armv7m.rs

This makes `reset()` not actually do "reset and run", because reset catch stays set. Fixes RTT attach issues with `probe-rs run`.

Fix missing reset catch clear.

---

CHANGELOG.md
probe-rs/src/config/registry.rs

```
Error: The chip 'stm32l4r5zi' was not found in the database.
Caused by:
Found multiple chips matching 'stm32l4r5zi', unable to select a single chip.
```
```
Error: The chip 'stm32l4r5zi' was not found in the database.
Caused by:
Found multiple chips matching 'stm32l4r5zi', unable to select a single chip. (STM32L4R5ZITx, STM32L4R5ZITxP, STM32L4R5ZIYx)
```
----
This helps beginners like me who don't appreciate the difference between the order code (Nucleo-L4R5ZI) and the actual target board (STM32L4R5ZIT6U)

Better error message for ambigous chips

---

.gitignore

We have a lot of crates, it's easier to blanket ban all `target` dirs instead of listing every crate.

gitignore: ignore all target dirs.

---

CHANGELOG.md
probe-rs/src/bin/probe-rs/cmd.rs
probe-rs/src/bin/probe-rs/cmd/attach.rs
probe-rs/src/bin/probe-rs/main.rs

To attach to rtt logging. Behaves exactly as `run`, but does not flash binary.

Implement `attach` sumbcommand (closes #1616)

---

Cargo.lock

This avoids a warning during `cargo install` with the  `--locked` option:
```
warning: package `hermit-abi v0.3.1` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
```
It doesn't affect the actual compilation result unless you compile for the hermit os as a target.

Update version of hermit-abi in Cargo.lock

---

CHANGELOG.md
probe-rs/src/bin/probe-rs/cmd/itm.rs

The `memory` subcommand of the CLI `itm` tool currently attempts to use
SWO to read out the trace.
This won't work as with `TraceMemory` as the sink, the TMC is configured
in software mode to be read out through the debug registers
(see https://github.com/probe-rs/probe-rs/blob/5f9c30a9de90516480cefb14b91b710b47d9256f/probe-rs/src/architecture/arm/component/mod.rs#L264-L266).
This implements reading out the trace through the debug registers,
implements parsing the timestamped packets and outputs them.
The code is taken from `etf-trace`
(https://github.com/quartiq/etf-trace/blob/main/src/main.rs) which is
made redundant by this change.
```
$ cargo run --release --bin probe-rs --features=cli -- itm --chip STM32H743ZITx memory 400000000
Ok(TimestampedTracePackets { timestamp: Sync(5.528µs), …
```

cli/itm/memory: read trace through the debug registers

---

CHANGELOG.md
target-gen/Cargo.toml

Fix https://github.com/probe-rs/flash-algorithm-template/issues/3

Build target-gen with RTT enabled by default

---

CHANGELOG.md
probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/debugProtocol.json
probe-rs/src/bin/probe-rs/cmd/dap_server/server/debugger.rs

Please see the [VSCode extension PR](https://github.com/probe-rs/vscode/pull/63) for details on this fix.
Additional changes here are to prevent duplicate messages from being reported in the VSCode extension.

`dap-server`: Ensure VSCode extension catches all STDERR errors if process initialization fails.

---

CHANGELOG.md
probe-rs/src/debug/debug_info.rs
probe-rs/src/debug/mod.rs

This fixes an error in the stack unwind, caused when add/subtract against 32-bit register address values resulted in incorrect register addresses being read by the core.

Stack unwind : Consider `RegisterValue` byte size when doing arithmetic on register addresses.

---

probe-rs/src/debug/debug_info.rs
probe-rs/src/debug/registers.rs

Some messages reported during stack unwind were too aggressive and caused noise and/or needed clarification.
Note: Temporarily added `skip-changelog` label until the changes are verified.

UNWIND: Clarify WARN and TRACE  messages during exception handling.

---

CHANGELOG.md
probe-rs/src/bin/probe-rs/cmd/run.rs

If no RTT location is found in the ELF file, probe-rs tries to find the RTT block by scanning all memory regions. That can take a while, during which it should be possible to interrupt it with CTRL-C.
This patch achieves that by only registering the SIGINT signal  handler after calling `attach_to_rtt`.
As an alternative, the `exit` flag could be passed down into `attach_to_rtt` and the memory scanning routine, and the scan could be aborted as soon as the flag is `true`. That would be a lot of boilerplate, and I don't see a significant advantage.

Register SIGINT handler after RTT scan

---

CHANGELOG.md
probe-rs/src/bin/probe-rs/cmd/run.rs

This will suppress the filename and line number information from the RTT log.
Without `--no-location`:
```
2252 >cargo run --bin probe-rs --features=cli -- run --chip rp2040 ~/pico-rust/embassy/examples/rp/target/thumbv6m-none-eabi/release/wifi_blinky
Compiling probe-rs v0.19.0 (/home/dhylands/rust/probe-rs/probe-rs)
Finished dev [unoptimized + debuginfo] target(s) in 16.24s
Running `/home/dhylands/rust/probe-rs/target/debug/probe-rs run --chip rp2040 /home/dhylands/pico-rust/embassy/examples/rp/target/thumbv6m-none-eabi/release/wifi_blinky`
Erasing sectors ✔ [00:00:04] [############################################################################################################] 284.00 KiB/284.00 KiB @ 68.19 KiB/s (eta 0s )
Programming pages   ✔ [00:00:10] …
```

Add --no-location option to the run command

---

CHANGELOG.md
probe-rs/targets/RA4M1.yaml

RA4M1 / R7FA4M1AB is the MCU used in Arduino Uno R4.
Source code of the FlashAlgo can be found here.
https://github.com/elfmimi/ra4m1-flash-algorithm
Known shortcoming: no data flash support yet.
---  
as a side note: here are hello-world and led-blinker demo.
https://github.com/elfmimi/rust-rtt-sample
Beware of option-setting memory section which is resident in sector 0 of the main code flash.
pyocd script below should help if you happen to make your target semi-bricked.
https://gist.github.com/elfmimi/d0a8ba4b469ce7d748c4dccf416ecd99

Add RA4M1 Series flash algorithm

---

CHANGELOG.md

#1704 incorrectly added the CHANGELOG entry to the 0.20 section.

Fix the CHANGELOG.md file from #1704

---

CHANGELOG.md
probe-rs/src/bin/probe-rs/cmd/run.rs

The run command would fail for targets that don't currently support enable_vector_catch. We now just ignore the error.

Ignore the error when calling enable_vector_catch

---

CHANGELOG.md
probe-rs/src/architecture/arm/core/armv7a_debug_regs.rs
probe-rs/src/architecture/arm/core/armv8a_debug_regs.rs

The  refactor in #1604 interpreted the register numbers used before here as addresses, which results in the offsets being off by a factor of 4. This fixes that.

Fixed address offsets for the armv7a and armv8a debug registers.

---

CHANGELOG.md
probe-rs/src/probe/cmsisdap/tools.rs

`probe-rs` recognizes _Cmsis Dap devices_ by looking for the string `CMSIS-DAP`. Some of these probes are called `CMSIS_DAP` (note underscore) instead. These are missed.
This commit fixes that by checking for the string `CMSIS-DAP` or `CMSIS_DAP`
I ran into this while using `probe-run`, see linked [issue](https://github.com/knurling-rs/probe-run/issues/400).
This PR was tested by building `probe-run` with it applied and flashing an stm32 using my probe that is listed in lsusb as "CMSIS_DAP". I do not have a CMSIS DAP with a dash in the name however given the changes I can not imagine they will stop working.

fix CMSIS_DAP named probes not recognised

---

CHANGELOG.md
probe-rs/src/bin/probe-rs/cmd/run.rs

I found it could be unreliable, especially when using a bootloader which executes before the main application. This PR now retries a few times before continuing.

cli: retry RTT attach a few times before giving up

---

CHANGELOG.md
Cargo.lock
target-gen/Cargo.toml
target-gen/src/commands/test.rs
target-gen/src/main.rs

Spun out of this comment. https://github.com/probe-rs/probe-rs/pull/1706#issuecomment-1656812105
it will be used to avoid writing to sector 0, by passing valid sector aligned address other than 0.
ex. `target-gen test template.yaml definition.yaml target/thumbv7em-none-eabi/algorithm --base-address 0x800`

Add --test-address option to target-gen test

---

CHANGELOG.md
deny.toml
probe-rs/src/bin/probe-rs/util/common_options.rs
probe-rs/src/bin/probe-rs/util/flash.rs

This PR adds a `--verify` option to the `BinaryDownloadOptions`. So it gets added to the `download`, `flash` and `run` subcommands.
Testing it on my `nrf52840-dk` the verification shows up in the logs:
```console
$ probe-rs run --chip nRF52840_xxAA --verify target/thumbv7em-none-eabihf/debug/hello
<...>
DEBUG probe_rs::flashing::loader: committing RAM!
DEBUG probe_rs::flashing::loader:     region: 20000000-20040000 (262144 bytes)
DEBUG probe_rs::flashing::loader:      -- empty.
DEBUG probe_rs::flashing::loader: Verifying!
DEBUG probe_rs::flashing::loader:     data: 00000000-00001498 (5272 bytes)
<...>
```
---
Style question: For the other fields of the `BinaryDownloadOptions` you explicitly specify the `name`, `long` and `help`. Is there a reason for that? Usually `clap` just infers this …

Add `--verify`

---

CHANGELOG.md
probe-rs-target/src/chip.rs
probe-rs/src/bin/probe-rs/cmd/run.rs
probe-rs/src/bin/probe-rs/util/rtt.rs
probe-rs/src/config/registry.rs
probe-rs/src/config/target.rs
probe-rs/src/rtt.rs
target-gen/src/commands/elf.rs
target-gen/src/generate.rs

For targets that have very large amounts of RAM, that have some RAM regions that don't make sense for RTT, or that have multiple aliases for the same RAM, the default behavior of scanning the entirety of all RAM regions is sub-optimal.
This allows such targets to specify the what subset of RAM to scan for a RTT block. In extreme cases, a target can specify no ranges at all if there's no reasonable way to narrow down the search space.
The `_SEGGER_RTT` symbol will still always "win" and totally prevent any attempt to scan, and so applications are in practice still free to place their RTT header anywhere as long as they include that symbol in the given ELF executable, even if that symbol points outside of any of the configured scan regions.
This PR is part of my work on supporting i.MX …

rtt: Allow targets to constrain the ranges of RTT scanning

---

.github/workflows/release.yml

Uses the same version as used in the other CI workflows.
cargo-dist recommends the use of `rust-toolchain.toml` instead of, but I think that doesn't work together with the action we currently use to install rustc.
What do you think, should we switch to `rust-toolchain.toml`?

Sync rustc version in release CI with other builds

---

probe-rs/src/probe.rs
probe-rs/src/probe/arm_jtag.rs
probe-rs/src/probe/common.rs
probe-rs/src/probe/espusbjtag/mod.rs
probe-rs/src/probe/jlink/mod.rs

This PR moves the generic parts of JLINK arm support into a module separate of the probe support. It also splits the jtag_io function to make it more efficiently implementable on other probes such as the ftdi probe.
This is a first step in an attempt of getting probe-rs working with the arty z7 development board. This code is known to work to the degree that I am able to use it in getting a connection to the arm cores and query them about their halted status.

Refactored jlink arm dap over jtag support to make it more widely usable.

---

CHANGELOG.md
probe-rs/targets/EFM32HG_Series.yaml

This change adds support for the EFM32 Happy Gecko MCUs.
Example boards built on these MCUs would be
* [The SLSTK3400A starter kit board](https://www.silabs.com/development-tools/mcu/32-bit/efm32hg-starter-kit)
* [The open source Tomu board](https://tomu.im/)
For validation I built a [tiny demo](https://github.com/kromych/slstk3400a-blink-rs) that prints via RTT:
```
Running `probe-run --chip EFM32HG322F64 target/thumbv6m-none-eabi/release/slstk3400a-blink-rs`
(HOST) INFO  flashing program (5 pages / 5.00 KiB)
(HOST) INFO  success!
────────────────────────────────────────────────────────────────────────────────
INFO  Hello, world!
└─ slstk3400a_blink_rs::__cortex_m_rt_main @ src/main.rs:21
```

Support for EFM32 Happy Gecko MCUs

---

CHANGELOG.md
probe-rs/src/bin/probe-rs/cmd/run.rs
probe-rs/src/bin/probe-rs/util/rtt.rs

This reverts parts of f77360e2 without removing the new feature. This causes some redundancy in the passed values, though. (memory_map and rtt_scan_regions contain similar information).
Closes #1748

Fix defmt decoding

---

CHANGELOG.md
probe-rs/src/bin/probe-rs/cmd.rs
probe-rs/src/bin/probe-rs/cmd/read.rs
probe-rs/src/bin/probe-rs/cmd/write.rs
probe-rs/src/bin/probe-rs/main.rs
probe-rs/src/bin/probe-rs/util/common_options.rs

- Fixes #1641
- Simple tool to read/write from target memory addresses
- Handles 8,32,64 bit words
Example (using general purpose backup registers on ATSAM4S8B)
```bash
: probe-rs read --probe 1fc9:0143 b32 0x400E1490 2 --chip ATSAM4S8B
00000000 00000000
: probe-rs write --probe 1fc9:0143 b32 0x400E1490 0xDEADBEEF 0xBEEFDEAD --chip ATSAM4S8B
: probe-rs read --probe 1fc9:0143 b32 0x400E1490 2 --chip ATSAM4S8B
deadbeef beefdead
: probe-rs read --probe 1fc9:0143 b8 0x400E1490 2 --chip ATSAM4S8B
ef be
: probe-rs read --probe 1fc9:0143 b64 0x400E1490 2 --chip ATSAM4S8B
beefdeaddeadbeef 0000000000000000
```

Add read/write probe-rs cli commands

---

CHANGELOG.md
probe-rs/src/bin/probe-rs/util/rtt.rs

This PR makes the log levels of the `defmt` logs colorful. The coloring is done by the `defmt-decoder` crate[^1].
Before: ![Screenshot from 2023-09-11 12-27-03](https://github.com/probe-rs/probe-rs/assets/37087391/22c1c5b1-a45e-4c17-b0ae-792c8f493d5c)
After: ![Screenshot from 2023-09-11 12-27-20](https://github.com/probe-rs/probe-rs/assets/37087391/fef637c2-296f-456d-83b9-2cd17a79dc09)
[^1]: Since recently the `defmt-decoder` allows to configure the output format. Also it will soon™️ be possible to style the output. There will be PRs to implement that in `probe-rs`.

Colored defmt logs

---

CHANGELOG.md
probe-rs-target/src/chip.rs
probe-rs-target/src/lib.rs
probe-rs/src/config/mod.rs
probe-rs/src/config/registry.rs
probe-rs/src/config/target.rs
probe-rs/src/probe.rs
probe-rs/src/probe/arm_jtag.rs
probe-rs/src/probe/cmsisdap/mod.rs
probe-rs/src/probe/espusbjtag/mod.rs
probe-rs/src/probe/fake_probe.rs
probe-rs/src/probe/ftdi/mod.rs
probe-rs/src/probe/jlink/mod.rs
probe-rs/src/probe/stlink/mod.rs
probe-rs/src/session.rs
probe-rs/tests/scan_chain_test.yaml
target-gen/src/commands/elf.rs
target-gen/src/generate.rs

The scan chain information structure is a direct implementation of [Scan Chain](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/sdf_pg.html#sdf_element_scanchain) from CMSIS pack's System Description File (SDF)
It aims to resolve #1682 by adding scan chain information to the target, passing scan chain information to the probe, and finally allowing the `CmsisDap` probe to use scan chain information if its provided.
Having scan chain information opens the possibly for the following (these are open ideas, not yet implemented)
* Refactoring of existing `stlink` and other probes that are already working with `ir_len`. Clean them up, use scan chain instead.
* Updating `target-gen` to parse scan chain information from the SDF if its included in a CMSIS pack
Places where I am …

Allow JTAG scan information to be encoded in targets

---

CHANGELOG.md
probe-rs/src/architecture/arm/core/armv8m.rs
probe-rs/src/architecture/arm/sequences/nxp_armv8m.rs
probe-rs/src/config/target.rs
probe-rs/targets/MIMXRT500.yaml

This is a work-in-progress branch that I'm opening just so it's visible that I'm working on this.
This isn't yet fully working: reset and halt works, but flashing isn't working because the flash algorithm is encountering a CPU exception during its execution, which I've not yet fully debugged. I intend to work on this some more soon.
This branch also has some other unrelated commits on it right now, since they were helpful in my debugging. If these still seem useful once this PR is ready for review then I'll split them into separate PRs, since they are actually independent of my work for supporting this new chip.
More to come on this later, hopefully.
It looks like this might end up having some things in common with #1612, since these two families have some similarities.

Support for NXP i.MX RT5xx series

---

CHANGELOG.md
Cargo.lock
probe-rs/Cargo.toml
probe-rs/src/bin/probe-rs/cmd/cargo_flash/diagnostics.rs
probe-rs/src/bin/probe-rs/cmd/cargo_flash/mod.rs
probe-rs/src/bin/probe-rs/cmd/download.rs
probe-rs/src/bin/probe-rs/cmd/profile.rs
probe-rs/src/bin/probe-rs/cmd/run.rs
probe-rs/src/bin/probe-rs/main.rs
probe-rs/src/bin/probe-rs/util/common_options.rs
probe-rs/src/bin/probe-rs/util/flash.rs
probe-rs/src/flashing/download.rs
probe-rs/src/flashing/loader.rs

#1758
This is very rough so far.  In trying to add UF2 support to cargo flash, it helped to bring across some stuff that was only available on probe-rs so far ie. Bin and Idf support.  Is this desirable?
I've 'cheated' with errors for now through `unwrap`.  Should I create more error types or use `anyhow`? For now I've just deleted a now unused error type.  [44d69bfdbec2d768aa388dbb3f142b3b7cb033af](https://github.com/probe-rs/probe-rs/commit/44d69bfdbec2d768aa388dbb3f142b3b7cb033af)
I've used my own crate for UF2 but I'm not married to it.  I haven't evaluated other options very well yet and my crate does not have very good support for multiple sections.

Add Bin, Idf, Uf2 support to cargo flash

---

CHANGELOG.md
RESOURCES.md
probe-rs/src/architecture/arm/core/armv6m.rs
probe-rs/src/architecture/arm/core/armv7m.rs
probe-rs/src/architecture/arm/core/armv8m.rs
probe-rs/src/architecture/arm/core/cortex_m.rs
probe-rs/src/bin/probe-rs/cmd/run.rs
probe-rs/src/core/core_status.rs
probe-rs/src/lib.rs

Adds support for Semihosting on ARMv6-M, ARMv7-M, and ARMv8-M.
The motivation for this is to allow the target application to indicate to the debugger that a) execution is complete and b) everything was successful. This is use, for example, in the [Knurling app-template](https://github.com/knurling-rs/app-template/pull/71).

Support semihosting

---

probe-rs/src/core/memory_mapped_registers.rs

The name of the constant is ADDRESS_OFFSET, not ADDRESS.
Fixes: 35e1afc0199e99337858e3fdb86dafdd4dfa12ca

Fix comment regarding the MemoryMappedRegister address constant

---

probe-rs/src/architecture/riscv/mod.rs

The resethaltreq feature is not mandatory, and not implemented on all chips. However, it's mandatory that setting the haltreq bit while in reset causes the core to be halted when coming out of reset, so we can use that functionality for reset_and_halt.

riscv: Don't use reset_catch (setresethaltreq)

---

smoke-tester/src/main.rs

Set the erase_all permission to ensure that protected devices can be tested as well.

smoke-tester: Set erase_all permission

---

target-gen/src/commands/elf.rs
target-gen/src/commands/test.rs

Don't fail with errors which don't say which path is to blame.

Improve error handling in target-gen test

---

CHANGELOG.md
Cargo.lock
Cargo.toml
probe-rs/Cargo.toml
probe-rs/src/bin/probe-rs/cmd/dap_server/server/core_data.rs
probe-rs/src/bin/probe-rs/cmd/run.rs
probe-rs/src/bin/probe-rs/util/rtt.rs

This PR adds the `--log-format` flag to `probe-rs run`. It allows to specify a custom log format for the defmt logs.
If no log format is specified a default format is chosen depending on if there is a timestamp available and if the location should be shown.
```rust
// Format options:
// 1. Custom format
// 2. Default with timestamp with location
// 3. Default with timestamp without location
// 4. Default without timestamp with location
// 5. Default without timestamp without location
let format = log_format.unwrap_or_else(|| match (show_location, has_timestamp) {
(true, true) => "{t} {L} {s}\n└─ {m} @ {F}:{l}",
(true, false) => "{L} {s}\n└─ {m} @ {F}:{l}",
(false, true) => "{t} {L} {s}",
(false, false) => "{L} {s}",
});
```
The log format is simple, a few examples can be seen in the …

Allow to customize the `defmt` log format

---

smoke-tester/src/main.rs
smoke-tester/src/tests.rs
smoke-tester/src/tests/stepping.rs

Split the tests for reading / writing tests into two parts, since it's not guaranteed that we can actually write all registers.
Also, we ensure the chip is halted before doing the *stepping* test.

test: Fix tests for ARM platforms

---

.github/workflows/release_crates.yml

Seems to be necessary for tagging the release.

Give release workflow write permission

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
.github/workflows/changelog.yml
CONTRIBUTING.md
Cargo.lock
changelog/added-fragment.md
xtask/Cargo.toml
xtask/src/main.rs

To avoid the endless conflicts in a single changelog file.
The idea is to place a file in `changelog`, in the form `added-new-fancy-stuffs.md`. The first part of the filename
should match a changelog category, the rest doesn't matter. The xtask can then be used to collect all the entries into
the changelog at release time.

Assemble changelog out of fragments

---

.cargo/config.toml
.github/actions/setup/action.yml
Cargo.toml
probe-rs/src/bin/probe-rs/cmd/cargo_embed/mod.rs
probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/request_helpers.rs
probe-rs/src/bin/probe-rs/cmd/dap_server/server/debugger.rs
probe-rs/src/bin/probe-rs/cmd/debug.rs
probe-rs/src/probe/ftdi/commands.rs
probe-rs/src/probe/ftdi/mod.rs
probe-rs/src/probe/stlink/tools.rs

Fix clippy warnings added with Rust 1.73, add some useful cargo aliases.

Fix Rust 1.73 clippy warnings

---

CHANGELOG.md
changelog/changed-simplify-rtt-get-data.md
probe-rs/src/bin/probe-rs/util/rtt.rs

This PR
- creates a utility function for each data format; this decreases the indentation and therefore makes `rustfmt` work again
- replaces `write!(...).map_or_else` with `write!(...).expect`, because writing to strings cannot fail

Simplify `RttActiveChannel::get_rtt_data`

---

.github/workflows/start-release.yml
xtask/src/main.rs

- Use a PAT when creating release to properly trigger cargo-dist workflow.
- Improve changelog check, error out when category is missing.
- Add unreleased header to changelog to play nicely together with cargo-release.

chore: Improve release flow

---

probe-rs/targets/nRF52_Series.yaml

it's an alias of main RAM connected to the ICODE bus instead of DCODE. Executing code from this address is faster.

targets/nrf52: add CODE RAM memory alias.

---

probe-rs/src/probe/cmsisdap/mod.rs
probe-rs/src/probe/espusbjtag/mod.rs
probe-rs/src/probe/ftdi/mod.rs
probe-rs/src/probe/stlink/mod.rs

* Session.rs was updated to unconditionally set scan chain information
* This would only be allowed when JTAG was the active transport
* Remove this restriction

Fix an issue where non JTAG transports would on setting scan_chain

---

changelog/fixed-lpc55s69-debug.md
probe-rs/targets/LPC55S69.yaml

There is an error when trying to connect to the second core,
which causes probe-rs to abort.
There is probably some setup required so that the second core works.
After that setup is implemented in probe-rs, the second core
could be reenabled.
This should fix #1802.

fix: Disable second core on LPC55S69

---

changelog/fixed-profile-cmd-debug-assert.md
probe-rs/src/bin/probe-rs/cmd/profile.rs
probe-rs/src/bin/probe-rs/main.rs

Rename the struct to avoid an assert.
Fixes #1808.

cli: Fix debug asssert in profile subcommand args parsing

---

Cargo.lock
changelog/fixed-openssl-dependency.md
probe-rs/Cargo.toml

The prebuilt binaries didn't work due to a dependency on openSSL, which is a different
version on Ubuntu 22.04 than on Ubuntu 20.04.

Remove dynamic dependency on openSSL

---

Cargo.lock

Fixes https://github.com/probe-rs/probe-rs/security/dependabot/12.

Update rustix version to fix dependabot warning

---

changelog/fixed-cmsis-serial.md
probe-rs/src/probe/cmsisdap/tools.rs

When connected to multiple probes with the same vid/pid it is necessary to use the serial number to distinguish them.

fix: Also use serial number to distinguish CMSIS-DAP probes

---

changelog/fixed-dbgswenable.md
probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs

This appears to be an oversight. As mentioned in the ADIv5 spec, setting DbgSwEnable to 0 "can cause software that is executing on the target to malfunction".

Set DbgSwEnable to 1 during memory access

---

changelog/fixed-os-lock.md
probe-rs/src/architecture/arm/core/armv8a_debug_regs.rs
probe-rs/src/architecture/arm/sequences/mod.rs

It is necessary for the OS Lock to be unlocked when accessing various debug registers, including EDSCR which we access later. Do so.

Unlock the OS Lock when starting an ARMv8 core

---

changelog/added-support-for-EFM32PG1B-series.md
probe-rs/targets/EFM32PG1B_Series.yaml

Generated `EFM32PG1B_Series.yaml` using the [CMSIS Pack](https://www.keil.arm.com/devices/silicon-labs-efm32pg1b200f256gm48/processors/).
Tested on a [UG154: EFM32 Pearl Gecko Starter Kit](https://www.silabs.com/development-tools/mcu/32-bit/efm32pg1-starter-kit) with the EFM32PG1B200F256GM48 controller variant, and an onboard Segger JLink probe. 
Flashing, debugging, and defmt (rtt) seem to work fine with the following VSCode launch config:
```json
{
"type": "probe-rs-debug",
"request": "launch",
"name": "probe_rs Executable launch example",
"cwd": "${workspaceFolder}",
"wireProtocol": "Swd",
"speed": 4000, 
"runtimeExecutable": "probe-rs",
"runtimeArgs": [
"dap-server",
],
"chip": "EFM32PG1B200F256GM48",
"flashingConfig": {
"flashingEnabled": true,
"haltAfterReset": false, …
```

Add support for EFM32PG1B series microcontrollers

---

changelog/added-debug-squences-for-atsam.md
probe-rs/src/architecture/arm/sequences/atsam.rs
probe-rs/src/architecture/arm/sequences/mod.rs
probe-rs/src/config/target.rs

This addresses https://github.com/probe-rs/probe-rs/issues/1854 ; the sequence that @jgust implemented for SAMD5x parts works perfectly for the smaller ATSAM parts, so I've just enabled it for those parts and done a little tidying of names/docs.

ATSAM chip erase

---

.github/workflows/release.yml
Cargo.toml
changelog/changed-static-libusb.md
probe-rs/Cargo.toml

This will allow us to specify dependencies in the Cargo.toml,
so we don't have to edit the generated workflows anymore.

Try cargo-dist 0.4 prerelease

---

changelog/fixed-lpc55s69-debug-sequence.md
changelog/fixed-lpc55s69-target-desc.md
probe-rs-target/src/chip_family.rs
probe-rs-target/src/memory.rs
probe-rs/src/architecture/arm/sequences/nxp_armv7m.rs
probe-rs/targets/LPC55S69.yaml
target-gen/src/generate.rs
target-gen/src/main.rs

- fix: Core names in LPC55S69 target description
Also update target-gen to handle memory descriptions with missing cores
better.
- fix: Region for LPC55S69 flash algorithm
- Fix debug sequence for LPC55S69
These changes should fix #1829.

Fix: Target description for LPC55S69

---

Cargo.lock
deny.toml
target-gen/Cargo.toml

Follow up to #1828, OpenSSL got used via target-gen.

fix: Also use RustTLS in target-gen

---

CHANGELOG.md
changelog/added-support-for-wch-link.md
probe-rs/src/architecture/riscv/communication_interface.rs
probe-rs/src/probe.rs
probe-rs/src/probe/cmsisdap/tools.rs
probe-rs/src/probe/wlink/commands.rs
probe-rs/src/probe/wlink/mod.rs
probe-rs/src/probe/wlink/usb_interface.rs

NOTE: This PR tries to add WCH-Link(RV mode) support. Not for CMSIS-DAP mode(ARM mode).
```console
>  cargo run -p probe-rs-cli -- list
The following devices were found:
[0]: WCH-Link (VID: 1a86, PID: 8010, Serial: 0001A0000000, WchLink)
> RUST_LOG=info cargo run -p probe-rs-cli -- info
INFO open: probe_rs::probe::wlink: WCH-Link variant: WCH-LinkE-CH32V307, firmware version: 2.7
Probing target via JTAG
INFO probe_rs::probe::wlink: attach riscvchip 0x05 Some(CH32V20x)
INFO probe_rs::probe::wlink: attach chip_type 0x20360500
No DAP interface was found on the connected probe. Thus, ARM info cannot be printed.
WARN probe_rs::probe::wlink: patch dtmcs(0x10) to be 0x00000071, read: 0x80000001
RISCV Chip:
IDCODE: 0000000001
Version:      0
Part:         0
Manufacturer: 0 (Unknown Manufacturer …
```

Add experimental WCH-Link probe(RV mode) support

---

Cargo.lock
changelog/changed-benchmark-impl.md
probe-rs/Cargo.toml
probe-rs/src/bin/probe-rs/cmd/benchmark.rs

The original benchmark implementation was a bit limited for my benchmarking purposes, so I've extended it.
This version will test different data lengths and speeds, and tries to do some basic stats to improve output.
It also supports targeting different word sizes (8/32/64bit), though only one at a time. This is not something I think is important to most people, and i know at least one target (esp32-c3) only supports 32bit reads/writes.
The whole thing definitely needs more error handling. It quits on most probe errors.
Oh, I also removed the http reporting since that isn't being used. Not bringing in reqwest should improve build times somewhat.

Benchmark rewrite

---

probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/request_helpers.rs

File name got omitted from source path by mistake.

Fix source code location in DAP server

---

CHANGELOG.md
changelog/fixed-url-format.md
target-gen/src/generate.rs

This PR fixes #1859.
The `target-gen` utility downloads the CMSIS packs correctly now.

`target-gen`: Fix incorrect URL formatting

---

README.md
changelog/fixed-dap-non-compliance.md
probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
probe-rs/src/bin/probe-rs/cmd/dap_server/mod.rs
probe-rs/src/bin/probe-rs/cmd/dap_server/server/debugger.rs
probe-rs/src/bin/probe-rs/cmd/dap_server/server/startup.rs

Minor fixes to prevent Debug Adapter Protocol workarounds (which result in DAP standard violations) which were added to probe-rs as a result of VSCode quirks from breaking other DAP clients.

DAP fixes for non-VSCode DAP clients (e.g. vimspector).
