cli/src/main.rs, coresight/src/dap_access.rs, coresight/src/lib.rs, probe/Cargo.toml, probe/daplink/src/daplink.rs, probe/src/debug_probe.rs, probe/stlink/src/stlink.rs
Use a Probe struct which contains the specific probe as a trait object, as seen in
debug_probe.rs
=> WIP: Use a wrapping struct to handle different probes

cli/src/main.rs
=> More generic commandline options (debug probe instead of ST-Link)

ocd/src/memory/romtable/mod.rs
=> Actually really fix part number detection

ocd/src/memory/romtable/mod.rs
=> Simplify RomTable handling so we get some proper data output

cargo-flash/src/main.rs, cli/src/common.rs, cli/src/debugger.rs, cli/src/info.rs, cli/src/main.rs, ocd-targets/build.rs, ocd/src/target/mod.rs
Cleanup of the CLI in general, and the interactive debug CLI in particular.
Main goal is to add better error handling and a basic help system explaining the commands.
=> General CLI cleanup

cargo-flash/src/main.rs, cli/src/debugger.rs, cli/src/main.rs, ocd/src/collection/cores/m0.rs, ocd/src/collection/mod.rs, ocd/src/coresight/access_ports/memory_ap/mod.rs, ocd/src/debug/debug.rs, ocd/src/memory/adi_v5_memory_interface.rs, ocd/src/probe/daplink/daplink.rs, ocd/src/probe/daplink/tools.rs, ocd/src/probe/flash/builder.rs, ocd/src/probe/flash/flasher.rs, ocd/src/probe/flash/loader.rs, ocd/src/probe/flash/memory.rs, ocd/src/probe/stlink/usb_interface.rs, ocd/src/session.rs, ocd/src/target/info.rs, ocd/src/target/mod.rs
Courtesy of `cargo +nightly fix -Z unstable-options --clippy`
=> A couple of clippy lint fixes

ocd/src/coresight/access_ports/memory_ap/mod.rs, ocd/src/probe/daplink/commands/mod.rs, ocd/src/probe/flash/download.rs, ocd/src/probe/flash/flasher.rs
=> Fix all cargo build/check warnings

ocd/src/debug/debug.rs, ocd/src/memory/adi_v5_memory_interface.rs, ocd/src/probe/daplink/commands/mod.rs, ocd/src/probe/daplink/commands/transfer/transfer.rs, ocd/src/probe/daplink/tools.rs, ocd/src/probe/debug_probe.rs, ocd/src/probe/flash/builder.rs, ocd/src/probe/flash/download.rs, ocd/src/probe/flash/flasher.rs, ocd/src/probe/flash/loader.rs, ocd/src/probe/flash/memory.rs, ocd/src/probe/stlink/stlink.rs, ocd/src/probe/stlink/usb_interface.rs
=> More clippy lint fixing

cargo-flash/README.md
It would be great if someone could try the nRF52832, nRF52840 and STM32F042 flash targets :)
=> Update cargo-flash readme

cargo-flash/src/main.rs
=> Cargo flash fixes

LICENSE-APACHE, LICENSE-MIT
=> Add LICENSE

cargo-flash/src/main.rs
This makes `cargo-flash` usable without passing `flash` to mimick Cargo, so `probe-rs/target/debug/cargo-flash --bin my_binary` now just works.
=> Only remove `flash` argument when it's present

README.md
Quick fix that will help folks get started!
=> Fix cli run command in the readme

probe-rs/src/memory/adi_v5_memory_interface.rs
From the specs ADI v5 C2.2.2:
> Automatic address increment is only guaranteed to operate on the 10
> least significant bits of the address that is held in the TAR.
So whenever these 10 bit overflow we need to write the TAR again.
=> Fix read/write_block32 for more than 256 words

CHANGELOG.md
Because I'm dumb and didn't test them ;)
=> Fix links in the CHANGELOG

probe-rs/src/memory/romtable/mod.rs
Also improves the warning to include more information
=> Downgrade CIDR preamble mismatch error to warning

probe-rs/src/probe/stlink/mod.rs
Helpful when getting an "UnknownError".
=> Log attaching and check_status of STLink

probe-rs/src/probe/stlink/mod.rs
A lonely curly brace is something sad :'(
=> Remove strange and lonely curly brace in comment

cargo-flash/src/main.rs, probe-rs-targets/src/lib.rs, probe-rs/src/probe/flash/builder.rs, probe-rs/src/probe/flash/memory.rs
This PR should fix the broken flashbuilder which would only ever add one page to a sector which is ofc wrong but would work for most small blinky examples.
This is also a good step towards removing convoluted pyOCD logic :)
=> Fix flash builder :)

cli/src/info.rs, probe-rs/Cargo.toml, probe-rs/examples/ram_download.rs, probe-rs/src/coresight/access_ports/memory_ap/mock.rs, probe-rs/src/coresight/ap_access.rs, probe-rs/src/coresight/memory/adi_v5_memory_interface.rs, probe-rs/src/flash/flasher.rs, probe-rs/src/probe/daplink/commands/general/info.rs, probe-rs/src/probe/daplink/commands/mod.rs, probe-rs/src/probe/daplink/commands/transfer/mod.rs, probe-rs/src/probe/daplink/mod.rs, probe-rs/src/probe/mod.rs, probe-rs/src/target/info.rs
Use the [TransferBlock](https://www.keil.com/pack/doc/CMSIS/DAP/html/group__DAP__TransferBlock.html) function for reads and writes of blocks of memory, which increases speed about by a factor of 10.
=> Use block transfer

cargo-flash/src/main.rs, cli/src/debugger.rs, probe-rs/src/cores/m0.rs, probe-rs/src/cores/m33.rs, probe-rs/src/cores/m4.rs, probe-rs/src/debug/mod.rs, probe-rs/src/probe/daplink/commands/transfer/mod.rs, probe-rs/src/session.rs, probe-rs/src/target/mod.rs
Currently, only a single hardware breakpoint is supported. This PR adds support for as many HW breakpoints as the device supports.
=> Add support for multiple breakpoints

probe-rs/targets/STM32F0 Series.yaml
=> Add stm32f0 support

probe-rs/src/debug/mod.rs
While testing the fixed back-traces for Cortex-M, I ran into a problem with missing support for debug data which requires the value of a register.
This PR adds support for that, and also removes some usage of unwrap.
=> Add support for DWARF requires-register evaluation

CHANGELOG.md, cli/src/info.rs, probe-rs/src/architecture/arm/communication_interface.rs, probe-rs/src/architecture/arm/dp/mod.rs, probe-rs/src/architecture/arm/mod.rs, probe-rs/src/probe/daplink/commands/general/connect.rs, probe-rs/src/probe/daplink/commands/general/info.rs, probe-rs/src/probe/daplink/commands/general/reset.rs, probe-rs/src/probe/daplink/commands/mod.rs, probe-rs/src/probe/daplink/commands/swj/sequence.rs, probe-rs/src/probe/daplink/mod.rs, probe-rs/src/probe/jlink/mod.rs, probe-rs/src/probe/mod.rs, probe-rs/src/probe/stlink/mod.rs
This PR adds SWD support for the JLink.
It seems to be working well with M4s and seems to have issues with some M0s.
I think we can still merge it like this and fix the issues later. What do you think?
=> Add SWD support for JLink

probe-rs/src/flash/builder.rs
The old version failed me with the STM32L071 :wink:
=> Fix page count calculation

probe-rs/src/flash/builder.rs
Revert the changes in PR #150 , they break flashing on a STM32WB55 board.
=> Revert PR #150

probe-rs/src/probe/daplink/mod.rs, probe-rs/src/probe/jlink/mod.rs, probe-rs/src/probe/mod.rs, probe-rs/src/probe/stlink/constants.rs, probe-rs/src/probe/stlink/mod.rs
Ported from https://github.com/probe-rs/probe-rs/pull/130
=> Add support for setting debug protocol speed (try 2)

CHANGELOG.md
The ST-Link fix was not mentioned in the changelog.
=> Add missing changelog entry for ST-Link fix

CHANGELOG.md, probe-rs/Cargo.toml
This PR prepares the changelog and Cargo.tomls for 0.5.2.
=> Prepare for 0.5.2

CHANGELOG.md, probe-rs-t2rust/Cargo.toml, probe-rs-t2rust/src/lib.rs, probe-rs/Cargo.toml, probe-rs/src/config/chip.rs, probe-rs/src/config/chip_family.rs, probe-rs/src/config/flash_algorithm.rs, probe-rs/src/config/flash_properties.rs, probe-rs/src/config/registry.rs, probe-rs/src/config/target.rs
This PR should greatly improve the build time in release mode, 
on my machine it now takes about 1 min 30 s, where before it
was more than 3 minutes.
To achieve this, the PR replaces all Strings and Vectors in the
auto-generated target code with `Cow` pointers, so that we can
avoid allocation where possible.
=> Improve build time

probe-rs/src/architecture/arm/communication_interface.rs, probe-rs/src/architecture/riscv/communication_interface.rs, probe-rs/src/core/mod.rs, probe-rs/src/probe/mod.rs, probe-rs/src/session.rs
This should fix the double attach issue #199.
I am not sure if this is the right way to do it. Maybe someone else has a stronger opinion on it?
Best,
Yatekii
=> Fix double attach which could prove difficult for certain probes

probe-rs/src/flashing/download.rs
This PR adds logs to the ELF loader such that the user gets informations about what sections are loaded to flash.
The loader now also properly returns an error when the ELF file is broken in some way.
=> Improve logging of ELF loading

.github/workflows/ci.yml
We're seeing 404 errors when trying to install packages. Hopefully
this improves that.
=> Update apt information before install

probe-rs/targets/HF5032x Series.yaml, probe-rs/targets/HT32F0006 Series.yaml, probe-rs/targets/HT32F0008 Series.yaml, probe-rs/targets/HT32F123xx Series.yaml, probe-rs/targets/HT32F12xx Series.yaml, probe-rs/targets/HT32F16xx Series.yaml, probe-rs/targets/HT32F17xx Series.yaml, probe-rs/targets/HT32F502xx Series.yaml, probe-rs/targets/HT32F503xx Series.yaml, probe-rs/targets/HT32F521xx Series.yaml, probe-rs/targets/HT32F522xx Series.yaml, probe-rs/targets/HT32F523xx Series.yaml, probe-rs/targets/HT32F573xx Series.yaml, probe-rs/targets/HT32F5826 Series.yaml, probe-rs/targets/HT32F590xx Series.yaml, probe-rs/targets/HT32F597xx Series.yaml, probe-rs/targets/HT32F61352 Series.yaml, probe-rs/targets/HT32F652xx Series.yaml, probe-rs/targets/HT50F32002 Series.yaml, probe-rs/targets/HT50F32003 Series.yaml
I only tested HT32F523xx chips myself, all others are untested and
should be considered a source of trouble when working with these chips.
=> Adding support for lots of Holtek chips

probe-rs/src/architecture/arm/core/m4.rs
This PR adds the ability for probe-rs to configure FPB unit revision 2 breakpoints as well. The code here works on a Cortex M7 chip in the sense that yes it does place the breakpoint and yes the chip will halt there....the communication with the GDB server and GDB is a little fucked up because of race conditions between the "my chip breaked" and GDBs "give me chip info" requests. I'll address that soon :tm:
=> FPB unit rev2 support

CHANGELOG.md, cli/Cargo.toml, probe-rs/Cargo.toml
=> Make probe-rs ready for 0.6.1

gdb-server/Cargo.toml, gdb-server/src/bin.rs, gdb-server/src/gdb_server_async.rs, gdb-server/src/reader.rs, gdb-server/src/worker.rs, gdb-server/src/writer.rs
General cleanup of the GDB server part.
=> Cleanup GDB server

.github/workflows/ci.yml
Prevents building each PR multiple times
=> Only build regular pushes to master

cli/src/debugger.rs, probe-rs/examples/ram_download.rs, probe-rs/src/architecture/arm/communication_interface.rs, probe-rs/src/config/flash_algorithm.rs, probe-rs/src/debug/mod.rs, probe-rs/src/probe/daplink/commands/mod.rs, probe-rs/src/probe/daplink/mod.rs
=> Reduce amount of unwraps

CHANGELOG.md, cli/src/debugger.rs, gdb-server/src/handlers.rs, probe-rs/examples/ram_download.rs, probe-rs/src/architecture/arm/core/m0.rs, probe-rs/src/architecture/arm/core/m33.rs, probe-rs/src/architecture/arm/core/m4.rs, probe-rs/src/architecture/riscv/mod.rs, probe-rs/src/core/mod.rs, probe-rs/src/flashing/flasher.rs, probe-rs/src/lib.rs
This fixes a bug where big flash sector erases would result in a timeout.
=> Configurable timeout

probe-rs/src/architecture/arm/core/mod.rs, probe-rs/src/core/mod.rs, probe-rs/src/session.rs
Also derives `Debug` for a bunch of other types, as required.
=> Derive `Debug` for `Session`

probe-rs/src/probe/jlink/mod.rs
If the target voltage is 0 V, a warning is generated. This can happen if the target is not powered, or if the VTref pin is not properly connected.
=> J-Link: Check target voltage before attaching

probe-rs/src/probe/stlink/mod.rs
See also: https://github.com/probe-rs/probe-rs/issues/289#issuecomment-654702327
=> Add firmware version check for STLINK-V3 probes

probe-rs/targets/STM32G4 Series.yaml
Adding  probe-rs/targets/STM32G4 Series.yaml.
=> Add support for STM32G4... targets

probe-rs/src/core/mod.rs, probe-rs/src/session.rs
=> Clear all hardware breakpoints on attach

probe-rs/src/architecture/arm/component/dwt.rs, probe-rs/src/architecture/arm/swo/mod.rs, probe-rs/src/probe/daplink/commands/general/connect.rs, probe-rs/src/probe/daplink/commands/general/disconnect.rs, probe-rs/src/probe/daplink/commands/general/info.rs, probe-rs/src/probe/daplink/commands/mod.rs, probe-rs/src/probe/daplink/commands/swd/configure.rs, probe-rs/src/probe/daplink/commands/swj/sequence.rs, probe-rs/src/probe/daplink/commands/swo.rs, probe-rs/src/probe/daplink/commands/transfer/configure.rs, probe-rs/src/probe/daplink/commands/transfer/mod.rs, probe-rs/src/probe/daplink/mod.rs, probe-rs/src/probe/daplink/tools.rs
I think the code for this is done but I want to do more testing on hardware and with the different CMSIS-DAP SWO transports before it's quite ready. The basics all seem to work great and I can get at least a couple of Mbps of SWO data through.
I don't expect any changes except small bug fixes, so this could be reviewed and I'd welcome any feedback.
=> CMSIS-DAP SWO

.github/bors.toml, .github/workflows/ci.yml, Cargo.toml, probe-rs-cli-util/Cargo.toml, probe-rs-cli-util/src/lib.rs, probe-rs-cli-util/tests/cargo_integration.rs, probe-rs-cli-util/tests/data/.gitignore, probe-rs-cli-util/tests/data/binary_cargo_config/.cargo/config, probe-rs-cli-util/tests/data/binary_cargo_config/Cargo.toml, probe-rs-cli-util/tests/data/binary_cargo_config/src/main.rs, probe-rs-cli-util/tests/data/binary_cargo_config_toml/.cargo/config.toml, probe-rs-cli-util/tests/data/binary_cargo_config_toml/Cargo.toml, probe-rs-cli-util/tests/data/binary_cargo_config_toml/src/main.rs, probe-rs-cli-util/tests/data/binary_project/Cargo.toml, probe-rs-cli-util/tests/data/binary_project/src/main.rs, probe-rs-cli-util/tests/data/library_project/Cargo.toml, probe-rs-cli-util/tests/data/library_project/src/lib.rs, probe-rs-cli-util/tests/data/library_with_example_project/Cargo.toml, probe-rs-cli-util/tests/data/library_with_example_project/examples/example.rs, probe-rs-cli-util/tests/data/library_with_example_project/src/lib.rs, probe-rs-cli-util/tests/data/multiple_binary_project/Cargo.toml, probe-rs-cli-util/tests/data/multiple_binary_project/src/bin/bin_a.rs, probe-rs-cli-util/tests/data/multiple_binary_project/src/bin/bin_b.rs, probe-rs-cli-util/tests/data/workspace_project/Cargo.toml, probe-rs-cli-util/tests/data/workspace_project/workspace_bin/Cargo.toml, probe-rs-cli-util/tests/data/workspace_project/workspace_bin/src/main.rs, probe-rs-cli-util/tests/data/workspace_project/workspace_lib/Cargo.toml, probe-rs-cli-util/tests/data/workspace_project/workspace_lib/src/lib.rs
This is an import from cargo-flash. See #347
=> Create helper library for CLI applications

probe-rs/targets/STM32WL Series.yaml
This adds 3 chips: 64k, 128k and 256k versions.
=> Add STM32WLE target

probe-rs/src/probe/daplink/tools.rs
Prior to this change I'd see probe-rs-cli info fail on my machine with
my probe as it tried to do read_languages on a hub device (which failed)
and it never got past that device.
We continue to the next device now instead to keep hunting for the
probe.
Failure in a gist I was seeing, https://gist.github.com/bfrog/4f136389f08377ccb88f3f8d9cb38675
=> Fixes read language error

probe-rs/targets/STM32L1 Series.yaml
Generated from Keil.STM32L1xx_DFP.1.2.0.pack.
Hope this helps.
=> add STM32L1 target

probe-rs/targets/nRF91 Series.yaml
=> Adding "core" value to the nRF91 Series

probe-rs/src/flashing/flasher.rs
ref #16 
I could use Default::default but I don't think this is very clear in this case or brings much benefit in terms of lines of code.
As I understand pc is just a register as the others so I put it in the struct as well.
I'm not so sure about the init param. I did a quick search but could not find a good way to describe it cause it seems to do two unrelated things but changing that is best left for someone who knows more about it, if deemed necessary.
=> closes approximately 83,333% of issue 16

probe-rs/src/architecture/riscv/communication_interface.rs, probe-rs/src/architecture/riscv/mod.rs
Some RISCV chips support an implicit ebreak instruction after
the last instruction in the program buffer. This frees up one word
of the program buffer for an additional instruction.
This improves compatibility with chips with small program buffers.
=> Add support for implict ebreak in RISCV chips

probe-rs-cli-util/src/logging.rs, probe-rs/src/probe/daplink/mod.rs
I added a new meta tag for protocol speed & Implemented Debug & Clone on the Metadata.
=> Adjust the Sentry implementation a little

gdb-server/src/handlers.rs
=> Check the core status before reading any register when GDB instructs so. If the core is not halted, return an error.

probe-rs/src/architecture/arm/communication_interface.rs, probe-rs/src/probe/daplink/mod.rs
First crack at daplink retries, largely attempting to fix samd51 speed issues #395  #433  . Need to make sure were not losing an edge case from the old process match loop.
How many retries is correct? The way its currently written, the 5 is for the entirely of the upload, not 5 per command its trying to send..
=> Daplink retry

probe-rs/examples/ram_download.rs
Use `anyhow` for better error messages in the RAM download example
=> Improved errors in ram_download example

probe-rs/src/flashing/builder.rs
=> default FlashPage value to chips erased_byte_value

.github/ISSUE_TEMPLATE/config.yml
Add a link to the newly enabled discussions
=> Add link to discussions

.github/workflows/ci.yml, README.md
Add Ubuntu 20.04 to verify installation instructions.
=> Add Ubuntu 20.04

probe-rs/src/flashing/loader.rs
Fixes #474 
Due to probe-rs-rtt vs probe-rs git versioning testing with actual hardware hard (probe-run has unrelated issues compiling).
=> Support "flashing" program data to RAM

gdb-server/src/architecture.rs, gdb-server/src/handlers.rs, gdb-server/src/worker.rs
Initial support for GDB target description,
currently only the architecture is returned.
=> Initial support for GDB target description

probe-rs/src/probe/jlink/mod.rs
Removed some comments about the format of the SWD sequence not matching
the specification. In reality, the specification is correct and it seems
it may be the JLink probe that shifts the whole SWDIO sequence by one
bit.
There is a phase shift in SWDIO which is actually covered in the
specification when the ownership of the SWDIO line changes from probe to
target or viceversa. This is documented in [1]. The target places a new
value on the SWDIO line on the rising edge of the clock signal.
In addition to the phase shift, it seems that the JLink probe samples
the SWDIO signal on the falling edge, which would explain why the whole
read sequence is shifted by one bit.
[1]: https://developer.arm.com/documentation/dui0499/j/arm-dstream-target-interface-connections/signal-descriptions/serial-wire …
=> Rework JLink SWD sequence

probe-rs/src/flashing/download.rs
This PR introduces `FormStr` for the `Format` struct to make it parseable with `structopt`.
It does just use default `BinOptions` to not make the parsing too complicated.
This can be extended later on, but should suffice for now :)
=> Make the binary file format struct parseable

probe-rs/src/flashing/download.rs, probe-rs/src/flashing/flasher.rs
I tested this in an outstanding cargo-flash PR :)
=> Make chip erasure possible throught the flash API

probe-rs/targets/SAMD21.yaml
...and rename it to match output of target-gen
Fixes #540
=> Update CMSIS pack for SAMD21

probe-rs/targets/EFR32BG12P Series.yaml, probe-rs/targets/EFR32BG13P Series.yaml, probe-rs/targets/EFR32BG14P Series.yaml, probe-rs/targets/EFR32BG1P Series.yaml, probe-rs/targets/EFR32FG23 Series.yaml, probe-rs/targets/EFR32MG13P Series.yaml, probe-rs/targets/EFR32MG14P Series.yaml, probe-rs/targets/EFR32MG1P Series.yaml, probe-rs/targets/EFR32MG21 Series.yaml, probe-rs/targets/EFR32MG22 Series.yaml
Sorry for the split PRs, this continues PR #566, adding support for SiLabs' EFR32 targets.
=> Add more EFR32 targets

gdb-server/src/architecture.rs, probe-rs-target/src/chip_family.rs, probe-rs-target/src/lib.rs, probe-rs/src/config/mod.rs, probe-rs/src/config/registry.rs, probe-rs/src/config/target.rs, probe-rs/src/core/mod.rs, probe-rs/src/lib.rs, probe-rs/src/session.rs, probe-rs/targets/GD32VF1 Series.yaml
It makes for nicer code, and helps in the multicore support I'm attempting too.
=> Move CoreType to probe-rs-target, use it in the structs.

probe-rs/src/session.rs
- [x ] The code compiles without `errors` or `warnings`.
- [ x] All tests pass and in the best case you also added new tests.
- [ x] `cargo fmt` was run.
- [ x] You add a description of your work to this PR.
- [x ] You added proper docs (in code, rustdoc and README.md) for your newly added features and code.
=> Improved doc comments for session.rs

probe-rs/targets/STM32L0 Series.yaml
=> Add EEPROM region to STM32L071KBTx

probe-rs/targets/SAME51.yaml, probe-rs/targets/SAME53.yaml, probe-rs/targets/SAME54.yaml, probe-rs/targets/SAME70.yaml
Added targets for the following Microchip MCUs:
* ATSAME51
* ATSAME53
* ATSAME54
* ATSAME70
=> SAME5x and SAME70 targets

probe-rs/targets/SAMD10.yaml
Added using info from https://github.com/Microchip-MPLAB-Harmony/dev_packs v3.9.0 - might it be better to do all the parts in that repo at once, rather than piecemeal?
=> Add Microchip SAMD10 to supported targets

README.md
=> `README`: Add installation instructions for fedora

probe-rs/src/config/target.rs, probe-rs/src/flashing/download.rs, probe-rs/src/flashing/loader.rs, probe-rs/src/flashing/mod.rs
=> Improve docs for flashing, add convenience method for FlashLoader creation

probe-rs/src/architecture/arm/core/m0.rs, probe-rs/src/architecture/arm/core/m4.rs
On some chips, we can only set a HW breakpoint in a certain range.
If setting a breakpoint is not possible, an error should be returned.
=> Check if HW breakpoint is actually possible

probe-rs/Cargo.toml, probe-rs/src/debug/mod.rs, probe-rs/src/flashing/download.rs
=> Update gimli and object dependencies

probe-rs/src/memory/mod.rs
32 bit reads have a larger maximum read size and end up more than 6
times faster.
=> Use 32 bit reads to implement read_8

CHANGELOG.md, cli/Cargo.toml, debugger/Cargo.toml, gdb-server/Cargo.toml, probe-rs-cli-util/Cargo.toml, probe-rs-target/Cargo.toml, probe-rs/Cargo.toml
Bump probe-rs versions in preparation for the v0.11.0-alpha.0 release.
=> 0.11.0-alpha.0

cli/Cargo.toml, debugger/Cargo.toml, gdb-server/Cargo.toml, probe-rs-cli-util/Cargo.toml, probe-rs-target/Cargo.toml, probe-rs/Cargo.toml
Bump probe-rs versions in preparation for the v0.11.0-alpha.3 release.
=> Release v0.11.0-alpha.3

cli/Cargo.toml, debugger/Cargo.toml, gdb-server/Cargo.toml, probe-rs-cli-util/Cargo.toml, probe-rs-target/Cargo.toml, probe-rs/Cargo.toml
Bump probe-rs versions in preparation for the v0.11.0-alpha.4 release.
=> Release v0.11.0-alpha.4

cli/Cargo.toml, debugger/Cargo.toml, gdb-server/Cargo.toml, probe-rs-cli-util/Cargo.toml, probe-rs-target/Cargo.toml, probe-rs/Cargo.toml
Bump probe-rs versions in preparation for the v0.11.0-alpha.5 release.
=> Release v0.11.0-alpha.5

CHANGELOG.md, debugger/src/debug_adapter.rs, probe-rs/Cargo.toml, probe-rs/src/debug/mod.rs, probe-rs/src/debug/variable.rs
This is a placeholder to indicate that I am working on additional data type support. Feel free to tag me if you would like to help, as this is not meant to be an exclusive placeholder ... just hoping to avoid duplicate effort.
=> Implement debug support for additional datatypes - part 1

CHANGELOG.md, cli/src/main.rs, probe-rs/src/config/target.rs, probe-rs/src/flashing/erase.rs, probe-rs/src/flashing/flasher.rs, probe-rs/src/flashing/loader.rs, probe-rs/src/flashing/mod.rs
=> flashing: add function for mass erasing. 

CHANGELOG.md, debugger/src/debug_adapter.rs, probe-rs/src/debug/mod.rs, probe-rs/src/debug/variable.rs
- Add support for static variables to debugger. 
- Various fixes and code clean-ups
=> Add: Static scope, plus other fixes

CHANGELOG.md, cli/src/common.rs, cli/src/debugger.rs, probe-rs/src/architecture/arm/ap/memory_ap/mock.rs, probe-rs/src/probe/cmsisdap/commands/general/connect.rs, probe-rs/src/probe/cmsisdap/commands/general/disconnect.rs, probe-rs/src/probe/cmsisdap/commands/general/host_status.rs, probe-rs/src/probe/cmsisdap/commands/general/info.rs, probe-rs/src/probe/cmsisdap/commands/general/reset.rs, probe-rs/src/probe/cmsisdap/commands/mod.rs, probe-rs/src/probe/cmsisdap/commands/swd/configure.rs, probe-rs/src/probe/cmsisdap/commands/swj/clock.rs, probe-rs/src/probe/cmsisdap/commands/swj/pins.rs, probe-rs/src/probe/cmsisdap/commands/swj/sequence.rs, probe-rs/src/probe/cmsisdap/commands/swo.rs, probe-rs/src/probe/cmsisdap/commands/transfer/configure.rs, probe-rs/src/probe/cmsisdap/commands/transfer/mod.rs, probe-rs/src/probe/cmsisdap/mod.rs, probe-rs/src/probe/stlink/constants.rs, probe-rs/src/probe/stlink/mod.rs, probe-rs/src/probe/stlink/tools.rs, probe-rs/src/probe/stlink/usb_interface.rs
=> Minimize usage of anyhow in cmsisdap

probe-rs/src/architecture/arm/communication_interface.rs
@Tiwalun found the issue with your PR :) 
The STLink gets angry if you write to CSW. The old stlink code had a copypaste of this code but without that write.
=> Fix stlink breaking when attaching mutliple times.

debugger/src/debugger.rs, probe-rs/src/flashing/download.rs, smoke-tester/src/tests.rs
Simplifying DownloadOptions, the lazy way ;).
=> Simplify DownloadOptions, fix #684

probe-rs/src/debug/mod.rs, probe-rs/src/probe/cmsisdap/commands/transfer/mod.rs, probe-rs/src/probe/cmsisdap/mod.rs, probe-rs/src/probe/stlink/constants.rs, smoke-tester/src/dut_definition.rs
These lints probably got added with the new Rust version.
=> Fix some clippy lints

CHANGELOG.md, cli/Cargo.toml, debugger/Cargo.toml, gdb-server/Cargo.toml, probe-rs-cli-util/Cargo.toml, probe-rs-target/Cargo.toml, probe-rs/Cargo.toml, smoke-tester/Cargo.toml
Bump probe-rs versions in preparation for the v0.11.0 release.
=> Release v0.11.0

debugger/README.md, smoke-tester/README.md
Improve debugger and smoke-tester readme files.
=> Small review fixes

probe-rs/src/architecture/arm/ap/memory_ap/mock.rs, probe-rs/src/architecture/arm/ap/memory_ap/mod.rs, probe-rs/src/architecture/arm/ap/mod.rs, probe-rs/src/architecture/arm/communication_interface.rs, probe-rs/src/architecture/arm/dp/mod.rs, probe-rs/src/architecture/arm/mod.rs, probe-rs/src/architecture/arm/traits.rs, probe-rs/src/probe.rs, probe-rs/src/probe/cmsisdap/commands/transfer/mod.rs, probe-rs/src/probe/cmsisdap/mod.rs, probe-rs/src/probe/jlink/swd.rs, probe-rs/src/probe/stlink/mod.rs
A few cleanups to the DAP traits which IMO makes much, much clearer what's going on :)
For optimal reviewer experience, it is suggested to review each commit individually. Commits messages explain the rationale for the changes.
=> DAP trait cleanup

.github/workflows/ci.yml
Trying to reproduce CI issue in cargo-flash here (see https://github.com/probe-rs/cargo-flash/pull/190)
=> Try to reproduce cargo-flash CI issue

probe-rs/src/architecture/arm/memory/mod.rs
=> Make PeripheralType public.

probe-rs/src/probe/cmsisdap/commands/transfer/mod.rs, probe-rs/src/probe/cmsisdap/mod.rs
The current code always tries to parse a u32, even if the transfer request has only writes. This causes `NotEnoughData` errors.
This was masked in CMSIS-DAP v1 probes (I think?) by the fact that the received buffer has zeros appended, so the incorrect read would still succeed. With the HS-Probe there are no zeros appended, so it fails.
example stacktrace: 
```
DEBUG probe_rs::architecture::arm::memory::adi_v5_memory_interface > Write block with total size 260 bytes to address 0x20000200
DEBUG probe_rs::architecture::arm::ap                              > Writing register TAR, value=TAR { address: 20000200 }
DEBUG probe_rs::probe::cmsisdap                                    > Adding command to batch: Write(port=AccessPort, addr=4, data=0x20000200
DEBUG …
```
=> cmsisdap: fix transfer response parsing.

probe-rs/Cargo.toml
This fix for this message https://github.com/probe-rs/probe-rs/pull/780/#issuecomment-916793443
=> Allow opt-out from vendored features

cli/src/debugger.rs, cli/src/info.rs, debugger/src/debug_adapter.rs, debugger/src/info.rs, probe-rs/examples/raw_dap_access.rs, probe-rs/src/architecture/arm/communication_interface.rs, probe-rs/src/architecture/arm/sequences/mod.rs, probe-rs/src/architecture/arm/sequences/nxp.rs, probe-rs/src/architecture/riscv/dtm.rs, probe-rs/src/architecture/riscv/sequences/esp32c3.rs, probe-rs/src/architecture/riscv/sequences/mod.rs, probe-rs/src/config/target.rs, probe-rs/src/probe/fake_probe.rs, probe-rs/src/probe/stlink/mod.rs, probe-rs/src/session.rs, rtthost/src/main.rs
#819 take two because bors got angry
=> Fix clippy lints

CHANGELOG.md, probe-rs/src/probe/ftdi/mod.rs
=> probe/ftdi: more reliable irlen detection when we have a single tap.

debugger/src/debugger.rs
In the vscode extension, the name 'wire_protocol' is used, but the
struct expected 'protocol'.
Also, the debugger always used SWD, even if no protocol was specified.
Some probes only support JTAG; so this leads to problems.
Just not specifying a protocol is a better solution, then the probe
itself can use its default protocol.
=> debugger: parse wire protocol correctly, only configure when requested

probe-rs/src/probe/jlink/mod.rs, probe-rs/src/probe/jlink/swd.rs, probe-rs/src/probe/stlink/mod.rs
=> Fix chipreset via sequences on JLink

CHANGELOG.md, debugger/src/dap_types.rs, debugger/src/debugger.rs, debugger/src/rtt.rs
*Note:* The changes in this PR is dependent on being synchronized with [probe-rs/vscode PR #21](https://github.com/probe-rs/vscode/pull/21)
*Changes*
* Convert all existing `launch.json` properties to camelCase
* Updates to CHANGELOG
=> Convert `launch.json` properties to camelCase

CHANGELOG.md, debugger/src/debug_adapter.rs, debugger/src/debugger.rs
=> Announce the flash progress on the DAP protocol via events

CHANGELOG.md, cli/Cargo.toml, debugger/Cargo.toml, gdb-server/Cargo.toml, probe-rs-cli-util/Cargo.toml, probe-rs-target/Cargo.toml, probe-rs/Cargo.toml, rtt/Cargo.toml, rtthost/Cargo.toml, target-gen/Cargo.toml
Bump probe-rs versions in preparation for the v0.12.0 release.
=> Release v0.12.0

probe-rs/src/debug/mod.rs
The display of the variables in the debugger is currently broken since the wrong PC / registers are given to the `get_stackframe_info` function.
The `pc` was not from the same frame as the `registers`, and because of this the local variables were not shown properly.
=> debugger. Fix PC when getting variable information

CHANGELOG.md, cli/src/main.rs, debugger/src/debugger.rs, debugger/src/rtt.rs, probe-rs-cli-util/Cargo.toml, probe-rs-cli-util/src/common_options.rs, rtthost/src/main.rs, target-gen/src/main.rs
=> Add a cli command to print all chips and print infos for a specific chip

probe-rs-target/src/flash_algorithm.rs, probe-rs-target/src/flash_properties.rs, target-gen/src/generate.rs, target-gen/src/main.rs
This addreses the size issue in #1005. The generated file for the H7 is still 900kb ...
I don't understand.
=> Deduplicate flash algorithms when generating target files

probe-rs/src/config/registry.rs
try_lock can fail if using probe-rs from multiple threads. Blocking
is not that bad, as the registry functions shouldn't run for long.
=> registry: use lock instead of try_lock.

gdb-server/src/writer.rs, probe-rs-cli-util/src/lib.rs, probe-rs-cli-util/src/rtt.rs, probe-rs/src/architecture/arm/memory/romtable.rs, probe-rs/src/debug/mod.rs
Automatic fixes for new clippy lints.
=> Fix new clippy lints (Rust 1.59)

CHANGELOG.md, debugger/src/debug_adapter.rs, debugger/src/debugger.rs, debugger/src/protocol.rs, probe-rs/src/debug/mod.rs, probe-rs/src/debug/variable.rs
- Add support for LocLists (attribute value of DW_AT_location)
- Improved error handling in `probe-rs/debug` ... especially
- [Updated] Decided NOT TO Add support for function parameters (DW_TAG_formal_parameters)
-  It turns out that these cause a lot of UX noise because their values go out of scope very quickly. We need to find a cleaner UX implementation (versus just adding them to locals) if we want to implement them.
=> Add support for LocLists (attribute value of DW_AT_location) and improve Variable error handling.

CHANGELOG.md, probe-rs/src/probe.rs, probe-rs/src/probe/cmsisdap/mod.rs, probe-rs/src/probe/espusbjtag/mod.rs, probe-rs/src/probe/fake_probe.rs, probe-rs/src/probe/ftdi/mod.rs, probe-rs/src/probe/jlink/mod.rs, probe-rs/src/probe/jlink/swd.rs, probe-rs/src/probe/stlink/mod.rs
=> Clarify documentation for probe speed getter (see #284)

CHANGELOG.md, probe-rs/targets/GD32F3x0_Series.yaml
Tested on my GD32F310G-START Board, which is a GD32F310G8.
Generated from `GigaDevice.GD32F3x0_DFP.3.0.0.pack`.
=> Add GD32F3x0 Series yaml

probe-rs/src/probe/cmsisdap/mod.rs
Store the protocol which is used by the probe, when the default protocol is selected.
Without this, initialisation will fail when the default protocol is selected because the protocol has to be known for the attachment process.
=> cmsisdap: Store actually used protocol when default protocol is used

debugger/src/debug_adapter/dap_adapter.rs
This fixes an error where the debugger failed to read valid memory as part of a MS DAP `Disassemble` request. 
We can't rely on the MSDAP arguments to result in a memory aligned address for us to read from, so this change forces the read pointer to be a memory aligned address.
Note: There are many places in the code where we assume 4 bytes will always result in aligned memory reads, so for now I added the following to the code as a follow-up:
`// TODO: Using 4 bytes for aligned memory reads is 32-Bit architecture specific, and needs to be addressed as part of 64-Bit implementation.`
cc: @thefaxman
=> Force memory aligned read for DAP `Disassemble` request.

CHANGELOG.md, probe-rs/targets/HC32F005-Series.yaml
Tested working: flashing, erasing, debugging.
=> Add support for Huada Semiconductor HC32F005.

debugger/src/debug_adapter/dap_adapter.rs, debugger/src/peripherals/svd_variables.rs, gdb-server/src/target/desc/data.rs, probe-rs/src/architecture/arm/communication_interface.rs, probe-rs/src/architecture/arm/core/armv7a.rs, probe-rs/src/architecture/arm/core/armv8a.rs, probe-rs/src/architecture/riscv/communication_interface.rs, probe-rs/src/probe/fake_probe.rs, probe-rs/src/probe/jlink/arm.rs, probe-rs/src/probe/stlink/mod.rs, rtt/src/channels.rs
Fix warnings reported by clippy / Rust 1.62
=> Fix clippy warnings (Rust 1.62)

CHANGELOG.md, gdb-server/Cargo.toml, gdb-server/src/target/base.rs, gdb-server/src/target/desc/mod.rs, gdb-server/src/target/mod.rs, gdb-server/src/target/thread.rs, gdb-server/src/target/utils.rs
* Update to 0.6.2 to fix a warning during connect
* Add core name to `info threads` to assist with debugging
* Move some common code to a utils module
=> Update gdbstub create

CHANGELOG.md, cli/Cargo.toml, debugger/Cargo.toml, doc/release.md, gdb-server/Cargo.toml, probe-rs-cli-util/Cargo.toml, probe-rs-target/Cargo.toml, probe-rs/Cargo.toml, rtt/Cargo.toml, rtthost/Cargo.toml, target-gen/Cargo.toml
Bump probe-rs versions in preparation for the v0.13.0 release.
=> Release v0.13.0

CHANGELOG.md, debugger/src/debugger/debug_entry.rs, debugger/src/debugger/session_data.rs, probe-rs-cli-util/src/rtt.rs
=> Debug: Read the RTT buffer in a timely way to show users available data from the target.

CHANGELOG.md, probe-rs/targets/SAMDA1.yaml
Generated yaml file from download pack and tested with ATSAMDA1G16B
=> Added support for Microchip SAMDA1

cli/src/main.rs, debugger/Cargo.toml, probe-rs-cli-util/Cargo.toml, probe-rs-cli-util/src/common_options.rs, probe-rs/Cargo.toml, probe-rs/examples/benchmark.rs, probe-rs/examples/ram_download.rs, rtthost/Cargo.toml, rtthost/src/main.rs, smoke-tester/Cargo.toml, smoke-tester/src/main.rs, target-gen/Cargo.toml, target-gen/src/main.rs
=> Update clap to 4.0

CHANGELOG.md, probe-rs/src/architecture/arm/core/armv6m.rs, probe-rs/src/architecture/arm/core/armv7a.rs, probe-rs/src/architecture/arm/core/armv7m.rs, probe-rs/src/architecture/arm/core/armv8a.rs, probe-rs/src/architecture/arm/core/armv8m.rs, probe-rs/src/architecture/arm/core/mod.rs, probe-rs/src/architecture/riscv/mod.rs, probe-rs/src/core/mod.rs, probe-rs/src/memory/mod.rs
=> Make halted core mandatory for core register access (see #476)

CHANGELOG.md, debugger/Cargo.toml, debugger/src/debug_adapter/dap_adapter.rs, debugger/src/debug_adapter/protocol.rs, debugger/src/debugger/configuration.rs, debugger/src/debugger/core_data.rs, debugger/src/debugger/debug_entry.rs, debugger/src/debugger/session_data.rs, debugger/src/main.rs, rtt/Cargo.toml, rtt/src/channel.rs, rtt/src/rtt.rs
Consistency with the changes introduced in #1294.
=> Replace log with tracing for probe-rs-debugger and rtt.

CHANGELOG.md, probe-rs/Cargo.toml, probe-rs/src/probe/ftdi/commands.rs, probe-rs/src/probe/ftdi/mod.rs
=> Replace FTDI command building with ftdi-mpsse library functions/enums

CHANGELOG.md, probe-rs/examples/ram_download.rs, probe-rs/src/architecture/arm/ap/memory_ap/mock.rs, probe-rs/src/architecture/arm/ap/mod.rs, probe-rs/src/architecture/arm/core/armv6m.rs, probe-rs/src/architecture/arm/core/armv7a.rs, probe-rs/src/architecture/arm/core/armv7m.rs, probe-rs/src/architecture/arm/core/armv8a.rs, probe-rs/src/architecture/arm/core/armv8m.rs, probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs, probe-rs/src/architecture/riscv/communication_interface.rs, probe-rs/src/architecture/riscv/mod.rs, probe-rs/src/core/mod.rs, probe-rs/src/memory/mod.rs, probe-rs/src/probe/stlink/mod.rs
=> Start standardizing memory ops

.github/workflows/ci.yml
Build docs to check for warnings.
=> Add CI check for doc warnings

cli/src/info.rs, probe-rs/examples/raw_dap_access.rs, probe-rs/src/architecture/arm/communication_interface.rs, probe-rs/src/probe/fake_probe.rs, probe-rs/src/probe/stlink/mod.rs, probe-rs/src/session.rs
=> Don't panic when initialization fails

CHANGELOG.md, probe-rs-cli-util/tests/data/library_with_example_project/Cargo.toml, probe-rs-cli-util/tests/data/multiple_binary_project/Cargo.toml
=> Rename packages with identical names

debugger/src/debug_adapter/dap_adapter.rs
A fix to respond to changes introduced in #1357
=> Fix Probe timeout error when starting a debug session.  #1357

probe-rs/src/architecture/arm/sequences/nrf52.rs
Tested working on nrf52840 rev1 (old APPROTECT) and rev3 (new APPROTECT).
I haven't been able to use the `trait Nrf` in `nrf.rs` because the nrf52 sequence has other methods implemented in the `ArmDebugSequence` impl, and the `trait Nrf` wants to provide the whole impl... Also the unlock is slightly different (needs reset and reattach), so in the end I think not sharing code is cleaner anyway.
=> nrf52: add support for unlocking APPROTECTed chips.

CHANGELOG.md, probe-rs/src/probe/cmsisdap/commands/mod.rs
Close #1423
100ms timeouts on my device.
=> cmsisdap: change read timeout from 100ms to 1000ms

CHANGELOG.md, Cargo.lock, probe-rs-target/src/flash_algorithm.rs, probe-rs/src/flashing/flash_algorithm.rs, target-gen/Cargo.toml, target-gen/src/main.rs, target-gen/src/parser.rs
Detect if the flash algorithm supports RTT, and store the RTT control block address in the target YAML if RTT is supported.
=> Detect RTT block in target-gen

Cargo.lock, cargo-embed/Cargo.toml, cargo-embed/src/main.rs, cargo-embed/src/rttui/app.rs, cargo-embed/src/rttui/channel.rs
Remove chrono dependency, so that we can get rid of the dependency on the old time crate at some point.
=> cargo-embed: Remove chrono dependency

Cargo.lock, cli/Cargo.toml, cli/src/benchmark.rs, cli/src/main.rs, debugger/Cargo.toml, debugger/src/main.rs, probe-rs-cli-util/Cargo.toml, probe-rs-cli-util/src/rtt.rs
=> Remove time 0.1.x dependency

CHANGELOG.md, probe-rs/src/probe/ftdi/mod.rs
Add support for FT4232HL FTDI probe
=> Add support for FT4232HL

CHANGELOG.md, cli/src/main.rs
Add a flag to select the log file location to probe-rs-cli.
=> probe-rs-cli: Add flag to select log file location

CHANGELOG.md, probe-rs/src/flashing/flasher.rs, probe-rs/src/flashing/loader.rs
=> probe-rs: Emit chip erase finished/failed event

renovate.json
Reduce the frequency of updates to weekly.
=> Run renovate bot weekly

.github/workflows/release.yml, .github/workflows/release_crates.yml, Cargo.toml
Would be nice to create binaries, this seems like an easy way to do it.
=> Use cargo-dist to release binaries

CHANGELOG.md, probe-rs/targets/RP2040.yaml
Also remove unimplemented chip-erase address to properly fall-back to sector erases
=> Set the flash range of RP2040 to the max supported size

.github/workflows/start-release.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, probe-rs/Cargo.toml, probe-rs/src/bin/probe-rs/cargo_embed/mod.rs, probe-rs/src/bin/probe-rs/cargo_flash/mod.rs, probe-rs/src/bin/probe-rs/util/logging.rs
See [discussion on Matrix](https://matrix.to/#/!vhKMWjizPZBgKeknOo:matrix.org/$URhzupjAuEdRluRfkRoLW2Bn412sSJxZn5DcnUmaPC8?via=matrix.org&via=chat.berline.rs&via=grusbv.com).
=> Remove Sentry.

.github/workflows/release_crates.yml
Use correct commands to call cargo-release
=> Try to fix release worflow

CHANGELOG.md, Cargo.lock, probe-rs/Cargo.toml, probe-rs/src/bin/probe-rs/cmd/attach.rs, probe-rs/src/bin/probe-rs/cmd/benchmark.rs, probe-rs/src/bin/probe-rs/cmd/cargo_flash/diagnostics.rs, probe-rs/src/bin/probe-rs/cmd/cargo_flash/mod.rs, probe-rs/src/bin/probe-rs/cmd/debug.rs, probe-rs/src/bin/probe-rs/cmd/download.rs, probe-rs/src/bin/probe-rs/cmd/dump.rs, probe-rs/src/bin/probe-rs/cmd/erase.rs, probe-rs/src/bin/probe-rs/cmd/gdb.rs, probe-rs/src/bin/probe-rs/cmd/info.rs, probe-rs/src/bin/probe-rs/cmd/itm.rs, probe-rs/src/bin/probe-rs/cmd/profile.rs, probe-rs/src/bin/probe-rs/cmd/reset.rs, probe-rs/src/bin/probe-rs/cmd/run.rs, probe-rs/src/bin/probe-rs/cmd/trace.rs, probe-rs/src/bin/probe-rs/main.rs, probe-rs/src/bin/probe-rs/util/common_options.rs, probe-rs/src/bin/probe-rs/util/flash.rs
This PR generalizes the different CLI commands and reuses code more efficiently.
Fixes #1680.
Fixes #1590.
Fixes #1695.
=> More CLI fixes

Cargo.lock, probe-rs/Cargo.toml, probe-rs/src/bin/probe-rs/cmd/cargo_embed/rttui/app.rs
ratatui is the official community-maintained
fork.
=> Replace tui with ratatui

probe-rs/targets/STM32WBA_Series.yaml
Tested working on NUCLEO-WBA52CG
=> Add STM32WBA support.

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
Can be used for local development with VSCode, but main idea is to use it together with Github codespaces for reviews.
=> Add devcontainer json

probe-rs/src/bin/probe-rs/cmd/cargo_embed/mod.rs, probe-rs/src/bin/probe-rs/util/common_options.rs
=> Clarify cargo-embed CLI

probe-rs/src/flashing/builder.rs, probe-rs/src/flashing/mod.rs
=> Make documentation for FlashLayout available

Cargo.lock, changelog/added-rtthost-version.md, rtthost/Cargo.toml, rtthost/src/main.rs
This PR adds a --version to rtthost. Otherwise, it is hard to know which probe-rs version rtthost is based on.
=> Add --version CLI argument to rtthost

CHANGELOG.md, changelog/fixed_crash_during_unwind.md, probe-rs/src/debug/unit_info.rs
=> Fix crash and misleading error while resolving the location for variable in optimized binary.

.github/workflows/start-release.yml, xtask/src/main.rs
- Try to use dedicated actions to install tools
- Run changelog generation
- Add skip-changelog lab3el
=> Fix release PR creation

.github/workflows/start-release.yml
Next try with release workflow
=> Proper reference to version, actually install semver-checks

probe-rs/src/debug/function_die.rs
Remove incorrect error tracing that slipped into PR #1783.
=> Remove  (not-an) error messages

changelog/fixed-wch-link-impl.md, probe-rs/src/probe/wlink/mod.rs, probe-rs/src/probe/wlink/usb_interface.rs
- Add code for missing probe variant
- Refine logging level
- Add additional wait for halt resume operation
- Fill unimplemented functions
- Missing default speed setting
- Typo fix
=> enhance(wlink): refine probe implementation

changelog/changed-custom-debug-sequence-logging.md, probe-rs/src/architecture/arm/sequences/atsam.rs, probe-rs/src/architecture/arm/sequences/efm32xg2.rs, probe-rs/src/architecture/arm/sequences/infineon.rs, probe-rs/src/architecture/arm/sequences/mod.rs, probe-rs/src/architecture/arm/sequences/nrf.rs, probe-rs/src/architecture/arm/sequences/nrf52.rs, probe-rs/src/architecture/arm/sequences/nrf53.rs, probe-rs/src/architecture/arm/sequences/nrf91.rs, probe-rs/src/architecture/arm/sequences/nxp_armv7m.rs, probe-rs/src/architecture/arm/sequences/nxp_armv8m.rs, probe-rs/src/architecture/arm/sequences/stm32_armv6.rs, probe-rs/src/architecture/arm/sequences/stm32_armv7.rs, probe-rs/src/architecture/arm/sequences/stm32h7.rs, probe-rs/src/architecture/riscv/sequences/esp32c3.rs, probe-rs/src/architecture/riscv/sequences/esp32c6h2.rs, probe-rs/src/architecture/riscv/sequences/mod.rs, probe-rs/src/config/target.rs
I'm not sure if there are drawbacks to implementing `Debug` for all these structs, but doing so makes nice logging easy :)
=> Quieter sequences

changelog/added-esp32c2-support.md, probe-rs/src/architecture/riscv/sequences/esp32c2.rs, probe-rs/src/architecture/riscv/sequences/esp32c2c3.rs, probe-rs/src/architecture/riscv/sequences/esp32c3.rs, probe-rs/src/architecture/riscv/sequences/mod.rs, probe-rs/src/config/target.rs, probe-rs/targets/esp32c2.yaml, probe-rs/targets/esp32h2.yaml
- Add support for ESP32-C2
- Format `esp32h2.yaml`
=> Add ESP32-C2 support

probe-rs/src/probe/espusbjtag/mod.rs
Apparently, I forgot to try my changes before submitting #1923. `bitarr!` behaves differently than `bitvec!` in that it creates 8 bits out of a u8, so the whole write process was messed up. I've replaced the state change sequences with bool arrays which are treated as single bits when passed to `extend`.
Sorry.
=> Fix espusbjtag

probe-rs/src/bin/probe-rs/cmd/dap_server/peripherals/svd_variables.rs, probe-rs/src/bin/probe-rs/cmd/dap_server/server/debugger.rs, probe-rs/src/debug/debug_info.rs, probe-rs/src/debug/unit_info.rs, probe-rs/src/debug/variable.rs, probe-rs/src/debug/variable_cache.rs
This splits the variable cache functions into different ones, so that it's a bit clearer what actually happens.
=> Split variable cache functions

changelog/fixed-attach-inconsistencies.md, probe-rs/src/probe.rs, probe-rs/src/session.rs
Originally part of #1928 but PRing separately for a proper review.
=> Fix attach inconsistencies

changelog/added-target-gen-m55-m85.md, target-gen/src/generate.rs
=> target-gen: Support Cortex-M55 and Cortex-M85

target-gen/src/algorithm_binary.rs
BSS (`PrgData (NOLOAD)`) is in a program that has `p_filesz = 0` but `p_memsz > 0`.
=> Fix finding bss

probe-rs-target/src/chip.rs, probe-rs-target/src/chip_family.rs, probe-rs-target/src/lib.rs, probe-rs/examples/xtensa.rs, probe-rs/src/architecture/xtensa/arch/instruction/format.rs, probe-rs/src/architecture/xtensa/arch/instruction/mod.rs, probe-rs/src/architecture/xtensa/arch/mod.rs, probe-rs/src/architecture/xtensa/communication_interface.rs, probe-rs/src/architecture/xtensa/mod.rs, probe-rs/src/architecture/xtensa/registers.rs, probe-rs/src/architecture/xtensa/sequences/esp32.rs, probe-rs/src/architecture/xtensa/sequences/esp32s2.rs, probe-rs/src/architecture/xtensa/sequences/esp32s3.rs, probe-rs/src/architecture/xtensa/sequences/mod.rs, probe-rs/src/architecture/xtensa/xdm.rs, probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/request_helpers.rs, probe-rs/src/bin/probe-rs/cmd/debug.rs, probe-rs/src/config/target.rs, probe-rs/src/core.rs, probe-rs/src/core/core_state.rs, probe-rs/src/flashing/download.rs, probe-rs/src/flashing/flash_algorithm.rs, probe-rs/src/flashing/flasher.rs, probe-rs/src/flashing/loader.rs, probe-rs/src/gdb_server/target/desc/data.rs, probe-rs/src/session.rs, probe-rs/targets/esp32s3.yaml, target-gen/src/generate.rs
Stripped out of #1956 because it mostly works. Changelog omitted because I think this fits under the flag of the initial implementation.
=> Xtensa: allow creating Session

probe-rs/src/architecture/xtensa/communication_interface.rs, probe-rs/src/architecture/xtensa/mod.rs
Some minor cleanup to mirror some of the ARM code.
=> Xtensa: extract some DebugCause related code

probe-rs/src/architecture/xtensa/communication_interface.rs, probe-rs/src/architecture/xtensa/xdm.rs
A 4x improvement on my laptop when flashing an ESP32-S3. The gist of it is similar to recent RISC-V patches.
=> Xtensa: Better utilise batched jtag operations

probe-rs/src/probe/ftdi/mod.rs
Besides efficiency, this also fixes ESP32 detection, which previously produced the following logs:
```
DEBUG probe_rs::probe::ftdi: tap found: 120034e5
DEBUG probe_rs::probe::ftdi: tap found: 120034e5
DEBUG probe_rs::probe::ftdi: tap 0 irlen: 5
DEBUG probe_rs::probe::ftdi: tap 1 irlen: 5
DEBUG probe_rs::probe::ftdi: tap found: 120034e5
DEBUG probe_rs::probe::ftdi: tap found: 120034e5
DEBUG probe_rs::probe::ftdi: tap 0 irlen: 5
DEBUG probe_rs::probe::ftdi: tap 1 irlen: 5
DEBUG probe_rs::probe::ftdi: Target chain params: ChainParams { irpre: 0, irpost: 0, drpre: 0, drpost: 0, irlen: 5 }
```
Notice the incorrect ChainParams that has 5 bits total for 2 taps
=> FTDI: don't scan twice

.github/workflows/release.yml
Reverts probe-rs/probe-rs#2020
=> Revert "Allow workflow dispatch for release builds"

probe-rs/src/bin/probe-rs/cmd/info.rs
Some minimal `probe-rs info` cleanup. From now on we log where we start a new detection, which just helps my eyes.
=> `info`: Extract error printing, log starting a new phase

probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs
best reviewed per commit.
- arch/arm: use multi-word code path for single-word reads. Addresses review comment https://github.com/probe-rs/probe-rs/pull/2018#discussion_r1445272182 from a previous PR.
- arch/arm: don't pass the AP number around.
=> arch/arm: some adi_v5_memory_interface simplifications.

probe-rs/src/architecture/riscv/communication_interface.rs, probe-rs/src/architecture/riscv/dtm.rs, probe-rs/src/architecture/riscv/mod.rs, probe-rs/src/architecture/xtensa/communication_interface.rs, probe-rs/src/architecture/xtensa/xdm.rs, probe-rs/src/bin/probe-rs/cmd/info.rs, probe-rs/src/session.rs
- Avoid panicking if certain batch execution errors occur
- Pretty print errors
- Avoid panicking if Xtensa register restoration fails
=> Various fixes

probe-rs/src/probe/stlink/usb_interface.rs
Regression introduced in #2086
Fixes #2100
=> stlink: use hex-encoded serial to match selectors.

probe-rs/src/architecture/arm/sequences.rs
Fixes https://github.com/probe-rs/probe-rs/pull/2092#issuecomment-1918521581
=> Exit retry loop when using JTAG

Cargo.lock, probe-rs/Cargo.toml
=> chore(deps): update ratatui to 0.26.0

probe-rs/src/debug/mod.rs, probe-rs/src/debug/unit_info.rs, probe-rs/src/debug/variable.rs, probe-rs/src/debug/variable_cache.rs
The biggest achievement is that rustfmt no longer bails on `process_tree`
=> Some more misc cleanup

changelog/fixed-increas-cmsis-dap-usb-timeout.md, probe-rs/src/probe/cmsisdap/commands/mod.rs
=> cmsis-dap: Increase USB timeout for v2 to 1s

probe-rs/src/architecture/xtensa/communication_interface.rs, probe-rs/src/architecture/xtensa/xdm.rs, probe-rs/src/core.rs, probe-rs/src/probe/common.rs
This PR should make the log viewer's output just a bit better grouped, mainly for Xtensa.
=> Instrument a few functions

probe-rs/src/probe/arm_debug_interface.rs
If this was the only offender, this PR now closes #1954
cc @t-moe
=> Remove view_bits call from u64

changelog/added-info-is.md, changelog/changed-debug-probe-info.md, probe-rs/examples/multidrop_raw.rs, probe-rs/examples/nrf53_recover.rs, probe-rs/examples/ram_download.rs, probe-rs/examples/raw_dap_access.rs, probe-rs/examples/tcp_itm.rs, probe-rs/src/lib.rs, probe-rs/src/probe.rs, probe-rs/src/probe/ftdi/mod.rs, probe-rs/src/rtt.rs, probe-rs/src/session.rs, rtthost/src/main.rs, smoke-tester/src/dut_definition.rs
=> Add shorthand to filter probe type

probe-rs/src/bin/probe-rs/util/rtt.rs
This was an unused option in the binary, which didn't really make much sense to me. Stripped out of #2249
=> Remove clap parsing option from RTT config

changelog/added-error-on-dpv3.md, changelog/added-unsupported-protocol.md, probe-rs/src/architecture/arm/communication_interface.rs, probe-rs/src/architecture/arm/dp/mod.rs, probe-rs/src/architecture/arm/sequences.rs, probe-rs/src/probe/cmsisdap/mod.rs, probe-rs/src/probe/fake_probe.rs
This PR also includes a few cosmitic changes, that IMHO facilitate reading/understanding the code.
=> Improve error reporting on unsupported protocol & start adding support for ADIv6 (through DPv3).

changelog/added-support-elf64-binary.md, probe-rs/src/flashing/download.rs
Added support ELF64 to load programs for AArch64.
=> flashing: add support ELF64 binary download

changelog/added-support-hk32f030m.md, changelog/added-target-hk32f030M-series.md, probe-rs/targets/HK32F030xMxx_Series.yaml
Add a new target, see:
https://en.hsxp-hk.com/Search.html?searchCategory=totalSite&searchKey=hk32f030m
https://www.eevblog.com/forum/microcontrollers/$0-25-hk32f030m-(cortex-m0-32mhz-16kb-2kb)/
https://github.com/IOsetting/hk32f030m-template
=> Add HK32F030M-series target

changelog/added-xtensa-semihosting.md, probe-rs/src/architecture/xtensa/mod.rs, probe-rs/src/semihosting.rs
Adds semihosting support for Xtensa arch. 
Thanks @t-moe and @MabezDev for the help!
Closes #2301
=> Add Xtensa semihosting support

probe-rs/src/semihosting.rs
=> Revert architecture match

changelog/fixed-f750-flash-algo.md, probe-rs/targets/STM32F7_Series.yaml
=> Fix F750 flashing algo flash range

Cargo.lock, probe-rs/Cargo.toml, probe-rs/src/bin/probe-rs/cmd/cargo_embed/mod.rs, probe-rs/src/bin/probe-rs/cmd/gdb.rs, probe-rs/src/gdb_server/stub.rs, probe-rs/src/gdb_server/target/base.rs, probe-rs/src/gdb_server/target/breakpoints.rs, probe-rs/src/gdb_server/target/desc/mod.rs, probe-rs/src/gdb_server/target/mod.rs, probe-rs/src/gdb_server/target/monitor.rs, probe-rs/src/gdb_server/target/resume.rs, probe-rs/src/gdb_server/target/thread.rs, probe-rs/src/rtt.rs, probe-rs/src/session.rs
=> Use `parking_lot::FairMutex`

probe-rs/src/architecture/arm/core/armv7m.rs, probe-rs/src/architecture/arm/core/armv8m.rs, probe-rs/src/probe/cmsisdap/mod.rs
No changelog included, it doesn’t seem relevant enough to me, let me know if it’s required.
=> remove redundant turbo-fishes

Cargo.lock, probe-rs/Cargo.toml
See `cargo-deny` warning inhttps://github.com/probe-rs/probe-rs/actions/runs/8544348942/job/23410164780?pr=2339
=> Update deps with RUSTSEC advisories

changelog/removed-rtt-feature.md, probe-rs/Cargo.toml, probe-rs/src/flashing/flasher.rs, probe-rs/src/flashing/progress.rs, probe-rs/src/lib.rs, target-gen/Cargo.toml
... just the feature flag, nothing else :)
=> Remove `rtt`

probe-rs/src/bin/probe-rs/cmd/run/test_run_mode.rs
=> Add `--skip-test` argument to CLI

changelog/fixed-lpc55s69-load-secure-flash.md, probe-rs/targets/LPC55S69.yaml
this change allows me to flash an application linked in the secure region of flash.
=> targets: allow flashing in secure area of LPC55S69

changelog/added-u0.md, probe-rs/targets/STM32U0_Series.yaml
Tested working on stm32u083rc.
=> Add stm32u0.

changelog/fixed-esp32-riscv-reset.md, probe-rs/src/architecture/riscv/communication_interface.rs, probe-rs/src/architecture/riscv/dtm/dtm_access.rs, probe-rs/src/architecture/riscv/dtm/jtag_dtm.rs, probe-rs/src/architecture/riscv/mod.rs, probe-rs/src/architecture/riscv/sequences.rs, probe-rs/src/architecture/xtensa/communication_interface.rs, probe-rs/src/architecture/xtensa/mod.rs, probe-rs/src/architecture/xtensa/sequences.rs, probe-rs/src/architecture/xtensa/xdm.rs, probe-rs/src/bin/probe-rs/cmd/run/mod.rs, probe-rs/src/config/sequences/esp.rs, probe-rs/src/config/sequences/esp32.rs, probe-rs/src/config/sequences/esp32c2.rs, probe-rs/src/config/sequences/esp32c3.rs, probe-rs/src/config/sequences/esp32c6.rs, probe-rs/src/config/sequences/esp32h2.rs, probe-rs/src/config/sequences/esp32s2.rs, probe-rs/src/config/sequences/esp32s3.rs, probe-rs/src/core.rs, probe-rs/src/core/core_state.rs, probe-rs/src/probe.rs, probe-rs/src/probe/arm_debug_interface.rs, probe-rs/src/probe/common.rs, probe-rs/src/probe/wlink/mod.rs, probe-rs/src/session.rs
Closes #2164
Closes #1963
Closes #2310
Closes #1964 as I believe that PR will not be necessary anymore.
Issues that may or may not be fixed:
#2317
=> RISC-V reset sequences

probe-rs/src/architecture/xtensa/communication_interface.rs, probe-rs/src/architecture/xtensa/mod.rs, probe-rs/src/architecture/xtensa/sequences.rs, probe-rs/src/config/sequences/esp.rs
This PR fixes a few regressions introduced in #2365
=> Unbreak Xtensa

probe-rs/src/architecture/riscv/mod.rs
Just resolving a 4 year old TODO, nothing to see here 👀
=> RISC-V: Cache the hw breakpoint count

changelog/added-efm32pg22-target.md, probe-rs/targets/EFM32PG22_Series.yaml
Generated with:
```
target-gen$ cargo build run --release --locked -- arm --filter GeckoPlatform_EFM32PG22
```
Resetting, flashing, and debugging on a PG22-DK2503A works at a first glance.
=> Add EFM32PG22 series

Cargo.lock, changelog/changed-update-cmsis-pack-0.7.0.md, target-gen/Cargo.toml, target-gen/src/generate.rs
Ping @Yatekii, @Tiwalun and @ithinuel.
=> Update to cmsis-pack v0.7.0

probe-rs/src/architecture/xtensa/communication_interface.rs, probe-rs/src/architecture/xtensa/sequences.rs
=> Only set intlevel on reset

probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/mod.rs, probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/rttui/app.rs, probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/rttui/channel.rs, probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/debug_rtt.rs, probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/debugger.rs, probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/session_data.rs, probe-rs-tools/src/bin/probe-rs/cmd/run/mod.rs, probe-rs-tools/src/bin/probe-rs/util/rtt.rs
=> Restore RTT channel mode if we've updated it

probe-rs/src/architecture/arm/sequences.rs, probe-rs/src/architecture/riscv/mod.rs, probe-rs/src/config/sequences/nxp_armv7m.rs, probe-rs/src/config/sequences/nxp_armv8m.rs, probe-rs/src/probe/arm_debug_interface.rs
=> Rebase of #2119 and some related cleanups

xtask/src/main.rs
Ideally I wanted the CI to comment on the PR but we currently don't grant the permissions for that to be possible.
=> Change the CI error message if CHANGELOG.md is edited

.github/workflows/changelog.yml, xtask/src/main.rs
Demo: https://github.com/probe-rs/probe-rs/pull/2505
=> Comment on PR if changelog is edited

probe-rs-tools/src/bin/probe-rs/util/common_options.rs
@teburd I hope you don't mind me doing this, but I thought I'd go through the code myself instead of asking for a bunch of small things that may annoy you unnecessarily.
=> Clean up probe selection

Cargo.lock, probe-rs-target/src/memory.rs, probe-rs-tools/Cargo.toml, probe-rs-tools/src/bin/probe-rs/cmd/cargo_flash/diagnostics.rs, probe-rs-tools/src/bin/probe-rs/cmd/chip.rs, probe-rs-tools/src/bin/probe-rs/cmd/snapshots/probe_rs__cmd__chip__single_chip_output.snap, probe-rs/src/flashing/erase.rs, probe-rs/src/flashing/flasher.rs, probe-rs/src/gdb_server/target/desc/mod.rs, probe-rs/src/rtt/channel.rs, smoke-tester/src/tests.rs
23 dependencies for the price of one!
=> Clean up Memory region related code

README.md, changelog/updated-installation-links.md
Updated installation links for shell and powershell scripts
=> Updated installation links

target-gen/src/algorithm_binary.rs, target-gen/src/commands/elf.rs, target-gen/src/commands/test.rs, target-gen/src/generate.rs, target-gen/src/main.rs, target-gen/src/parser.rs
This PR helps highlighting what target-gen needs from probe-rs.
=> target-gen: Import from probe-rs-target directly

probe-rs/src/architecture/arm/memory/romtable.rs
probe-rs info and chip identification calls this code and its output is completely irrelevant to the user in my opinion. One could argue for probe-rs info but IMHO interesting bits should be printed as part of the component tree.
=> Demote CoreSight component parsing logs

probe-rs/src/architecture/arm/core/exception_handling/armv6m.rs, probe-rs/src/architecture/arm/core/exception_handling/armv7m.rs, probe-rs/src/architecture/arm/core/exception_handling/armv8m.rs, probe-rs/src/core.rs, probe-rs/src/debug/debug_info.rs
Just some micro-cleanup, nothing particularly interesting.
=> Clean up `Core::create_state`

changelog/fixed-stm32f303vc-memory.md, probe-rs/targets/STM32F3_Series.yaml
https://github.com/probe-rs/probe-rs/issues/2496#issuecomment-2154359915
Closes #2496
=> Fix RAM size of STM32F3 chips

probe-rs/src/core.rs
https://github.com/probe-rs/probe-rs/pull/2536#discussion_r1631552787
=> Further clean up ResolvedCoreOptions

probe-rs/src/probe/espusbjtag/protocol.rs
Slight readability improvements, nothing major.
=> Clean up espusbjtag

probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/debugger.rs
First check here:
https://github.com/probe-rs/probe-rs/blob/e8739dfd552da6967a3b7cbf93c20c7e4d47d226/probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/debugger.rs#L435-L441
https://github.com/probe-rs/probe-rs/blob/e8739dfd552da6967a3b7cbf93c20c7e4d47d226/probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/configuration.rs#L57-L72
=> fix: unexpected double check of session type

changelog/added-va416xx-support.md, probe-rs/src/vendor/mod.rs, probe-rs/src/vendor/vorago/mod.rs, probe-rs/src/vendor/vorago/sequences/mod.rs, probe-rs/src/vendor/vorago/sequences/va416xx.rs, probe-rs/targets/VA416xx_Series.yaml
Fixes https://github.com/probe-rs/probe-rs/issues/2563
I tested this with `probe-rs run` as well as `cargo embed`
=> Add support for the Vorago VA416xx family of MCUs

changelog/fixed-semihosting-arm.md, probe-rs/src/architecture/arm/core/armv6m.rs, probe-rs/src/architecture/arm/core/armv7m.rs, probe-rs/src/architecture/arm/core/armv8m.rs, probe-rs/src/semihosting.rs
I've also opened https://github.com/probe-rs/probe-rs/issues/2605
Closes https://github.com/probe-rs/embedded-test/issues/34
=> Fix semihosting command caching for arm

Cargo.lock, probe-rs/Cargo.toml, probe-rs/src/rtt.rs, probe-rs/src/rtt/channel.rs
=> Do not depend on zerocopy_derive

probe-rs-target/src/flash_algorithm.rs, probe-rs-target/src/flash_properties.rs, probe-rs/src/flashing/error.rs, probe-rs/src/flashing/flash_algorithm.rs, probe-rs/src/flashing/flasher.rs, probe-rs/targets/esp32.yaml, probe-rs/targets/esp32c2.yaml, probe-rs/targets/esp32c3.yaml, probe-rs/targets/esp32c6.yaml, probe-rs/targets/esp32h2.yaml, probe-rs/targets/esp32s2.yaml, probe-rs/targets/esp32s3.yaml
=> Implement stack overflow checking during flashing

Cargo.toml, probe-rs-mi/Cargo.toml, probe-rs-mi/src/lib.rs, probe-rs-target/Cargo.toml, probe-rs-target/src/lib.rs, probe-rs-tools/Cargo.toml, probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/error.rs, probe-rs/Cargo.toml, probe-rs/src/architecture/arm/core/exception_handling/armv6m.rs, probe-rs/src/architecture/arm/core/exception_handling/armv7m.rs, probe-rs/src/architecture/arm/dp/mod.rs, probe-rs/src/architecture/riscv/communication_interface.rs, probe-rs/src/architecture/riscv/dtm/jtag_dtm.rs, probe-rs/src/debug/mod.rs, probe-rs/src/probe/stlink/constants.rs, probe-rs/src/probe/stlink/mod.rs, rtthost/Cargo.toml, smoke-tester/Cargo.toml, target-gen/Cargo.toml, target-gen/src/commands/test.rs, xtask/Cargo.toml
Extracted from #2591 to make the review process easier
=> Add global clippy lints and clean them up

probe-rs-target/src/chip_family.rs, probe-rs-target/src/lib.rs, probe-rs-target/src/memory.rs, probe-rs/src/architecture/riscv/communication_interface.rs, probe-rs/src/core/registers.rs, probe-rs/src/debug/registers.rs, probe-rs/src/flashing/flash_algorithm.rs, probe-rs/src/probe.rs, probe-rs/src/probe/cmsisdap/commands/jtag/sequence.rs, probe-rs/src/probe/cmsisdap/commands/swj/sequence.rs, probe-rs/src/probe/common.rs, probe-rs/src/probe/espusbjtag/protocol.rs, probe-rs/src/probe/ftdi/ftdaye/mod.rs, probe-rs/src/probe/jlink/mod.rs, probe-rs/src/session.rs
- Remove some inactionable todos
- Resolve some others
=> Clean up some TODOs

probe-rs/src/vendor/vorago/sequences/va416xx.rs
=> Re-try handling for VA416xx reset sequence

changelog/changed-arm-jtag-speed.md, probe-rs/src/architecture/arm/mod.rs, probe-rs/src/probe.rs, probe-rs/src/probe/arm_debug_interface.rs
I've reconnected my STM32F429 using an FT2232H and on my...
Before:
```
Running embedded-test for stm32f429zi with probe 0403:6010:FT929K9H
Finished in 37.24183s
```
After:
```
Running embedded-test for stm32f429zi with probe 0403:6010:FT929K9H
Finished in 6.872409s
```
=> Batch ARM JTAG commands

README.md
=> Update outdated example

probe-rs/src/architecture/arm/core/armv7a.rs, probe-rs/src/architecture/arm/core/cortex_m.rs, probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs, probe-rs/src/architecture/riscv/communication_interface.rs, probe-rs/src/architecture/xtensa/mod.rs, probe-rs/src/config/chip_info.rs, probe-rs/src/core/registers.rs, probe-rs/src/debug/exception_handling.rs, probe-rs/src/debug/exception_handling/armv6m_armv7m_shared.rs, probe-rs/src/debug/source_instructions.rs, probe-rs/src/debug/unit_info.rs, probe-rs/src/probe/common.rs, probe-rs/src/probe/jlink/error.rs, probe-rs/src/probe/jlink/mod.rs, probe-rs/src/probe/jlink/speed.rs, probe-rs/src/vendor/ti/sequences/cc13xx_cc26xx.rs
This fixes private item’s documentation
Follows:
- https://github.com/probe-rs/probe-rs/pull/2700
=> Fix private documentation

changelog/fixed-ApType-names.md, probe-rs/src/architecture/arm/ap/generic_ap.rs
Follows:
- https://github.com/probe-rs/probe-rs/pull/2702
=> arm: Fix ApType variant names & fix corresponding documentation

probe-rs/targets/STM32WBA_Series.yaml
Pack update + a whole lot of renames from embassy data. Data changes only affect WBA50 devices which don't seem to exist.
Closes #2612
Closes #2553
=> Update STM32WBA data

renovate.json
=> Fix json syntax error

changelog/added-erase-progress.md, probe-rs-tools/src/bin/probe-rs/cmd/erase.rs, probe-rs-tools/src/bin/probe-rs/util/flash.rs, probe-rs/src/flashing/builder.rs, probe-rs/src/flashing/erase.rs, probe-rs/src/flashing/loader.rs
A bit imprecise for devices with external flash, but it's good to see any feedback coming from `probe-rs erase`.
=> Erase progress bars

probe-rs/src/flashing/flasher.rs
This avoids a regression where we downloaded algos twice during `commit`.
=> Lazy-load flash algo

Cargo.lock, probe-rs-tools/Cargo.toml, probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/rttui/app.rs, probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/rttui/event.rs
cc #2745 let's not make our lives harder
=> Remove direct crossterm dependency

changelog/fixed-c2c3.md, probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/mod.rs, probe-rs-tools/src/bin/probe-rs/cmd/run/mod.rs, probe-rs/src/architecture/riscv/communication_interface.rs, probe-rs/src/architecture/riscv/mod.rs, probe-rs/src/vendor/espressif/mod.rs, probe-rs/src/vendor/espressif/sequences/esp32c2.rs, probe-rs/src/vendor/espressif/sequences/esp32c3.rs
It pretty much looks like they don't support reading memory while running, under some unknown circumstances. Memory read is successful, but we read only 0s.
Terrible hackery and I'm not proud of it.
=> "Fix" ESP32-C2 and ESP32-C3

probe-rs/src/architecture/riscv/communication_interface.rs, probe-rs/src/architecture/xtensa/communication_interface.rs
This PR allows delaying some writes into the next read operation.
=> Tiny risc-v speedup

probe-rs/src/config/target.rs, target-gen/src/commands/elf.rs
The idea is that if a flash algo uses a memory range that isn't in the memory map, we conjure up that memory range from thin air. This should enable us to flash option bytes, for example, for which the CMSIS-packs almost never contain a memory region. This has some consequences to our deduplication (can't merge such algos) in target-gen.
=> Attempt to make flash algos work that point at undefined memory

changelog/fixed-esp32-reset.md, probe-rs-tools/src/bin/probe-rs/cmd/run/test_run_mode.rs, probe-rs/src/architecture/xtensa/arch/mod.rs, probe-rs/src/architecture/xtensa/communication_interface.rs, probe-rs/src/architecture/xtensa/mod.rs, probe-rs/src/architecture/xtensa/sequences.rs, probe-rs/src/architecture/xtensa/xdm.rs, probe-rs/src/probe/ftdi/mod.rs, probe-rs/src/session.rs, probe-rs/src/vendor/espressif/sequences/esp.rs, probe-rs/src/vendor/espressif/sequences/esp32.rs, probe-rs/src/vendor/espressif/sequences/esp32s2.rs, probe-rs/src/vendor/espressif/sequences/esp32s3.rs
Closes #2338
Algorithms, binaries are ported from OpenOCD.
=> ESP32 Xtensa reset sequences

probe-rs/targets/GD32C1x3_Series.yaml, probe-rs/targets/HPM5300_Series.yaml, probe-rs/targets/esp32.yaml
=> Fix stack size of HPM5300 flash algo

probe-rs/src/probe/cmsisdap/commands/jtag/configure.rs, probe-rs/src/probe/cmsisdap/commands/mod.rs, probe-rs/src/probe/cmsisdap/commands/swd/configure.rs, probe-rs/src/probe/cmsisdap/commands/swj/clock.rs, probe-rs/src/probe/cmsisdap/commands/swo.rs, probe-rs/src/probe/cmsisdap/commands/transfer/configure.rs, probe-rs/src/probe/cmsisdap/commands/transfer/mod.rs, probe-rs/src/probe/cmsisdap/mod.rs
Motivation behind this was https://github.com/probe-rs/probe-rs/issues/2788 where it just says "CMSIS DAP Error Response" which is very much not actionable.
=> Clarify the CMSIS DAP error enum reason and location of error

changelog/fixed-flash-algo-crash.md, probe-rs-target/src/chip_family.rs, probe-rs-target/src/memory.rs, probe-rs/src/config/registry.rs, probe-rs/src/config/target.rs, probe-rs/src/flashing/error.rs, probe-rs/src/flashing/flash_algorithm.rs, probe-rs/src/flashing/loader.rs, probe-rs/targets/MSPM0L_Series.yaml, probe-rs/targets/STM32WBA_Series.yaml, probe-rs/targets/STM32WL_Series.yaml, smoke-tester/src/tests.rs
Fixes #2822 (in theory)
Fixes #2810
=> Fix a few flash algo validation issues, skip erasing conjured regions, fix crashes

probe-rs/src/probe/jlink/mod.rs
Should address https://github.com/probe-rs/probe-rs/pull/2732#issuecomment-2370369370
=> J-Link: Allowlist register_connection for known devices

changelog/fixed-xtensa.md, probe-rs-tools/src/bin/probe-rs/cmd/run/mod.rs, probe-rs/src/architecture/xtensa/arch/instruction/format.rs, probe-rs/src/architecture/xtensa/arch/instruction/mod.rs, probe-rs/src/architecture/xtensa/communication_interface.rs, probe-rs/src/architecture/xtensa/xdm.rs, probe-rs/src/probe/common.rs, probe-rs/src/vendor/espressif/sequences/esp32.rs, probe-rs/src/vendor/espressif/sequences/esp32s3.rs
This PR fixes a whole host of bugs that caused issues on Xtensa.
=> Fix retrying batched instructions, work around ESP32S3 external memory access issue

.github/workflows/smoketest.yml
Allow manual triggering of the smoketester workflow,
for testing purposes.
=> Allow manual triggering of smoke tester

probe-rs/src/rtt/channel.rs
This reverts https://github.com/bugadani/probe-rs/commit/204159a03d2bf5150dcef957b942468bcbbaae28
=> Fix writing to down channel

changelog/changed-c0.md, probe-rs/targets/STM32C0_Series.yaml
And patch the range for flash algorithm "stm32c0x_64" to 128KB. (Verified by flashing an image larger than 64KB to an STM32C071RBT6.)
=> Update STM32C0 from pack

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> Set the issue type when the issue forms are used

probe-rs-target/src/chip.rs, probe-rs/targets/RP2040.yaml, probe-rs/tests/scan_chain_test.yaml
Fixes an issue added with the previous PR (#2992) 🙃
=> Fix RP2040

changelog/added-s32k14-series-targets.md, probe-rs/targets/S32K14_Series.yaml
Generated from this pack: https://www.keil.arm.com/packs/s32_sdk_dfp-keil/versions/
=> Add S32K14 series targets

changelog/fixed-adiv6-semihosting.md, probe-rs/src/architecture/arm/ap_v2/memory_access_port_interface.rs
=> Fix read_8, read_16 for ap_v2

probe-rs/src/probe/espusbjtag/protocol.rs
This PR reduces the amount of data stored (from 3 bytes per command to 4 bits), by processing commands as soon as possible. This means we don't need to copy out of a buffer into the binary representation, saving a tiny bit of time.
=> Store raw bits in esp usb jtag driver

changelog/changed-rtt-print.md, probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/rttui/channel.rs, probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/debug_rtt.rs, probe-rs-tools/src/bin/probe-rs/rpc/functions/monitor.rs, probe-rs-tools/src/bin/probe-rs/util/cli.rs, probe-rs-tools/src/bin/probe-rs/util/rtt/client.rs, probe-rs-tools/src/bin/probe-rs/util/rtt/processing.rs
=> Print data from all defmt channels

probe-rs/src/architecture/arm/sequences.rs, probe-rs/src/probe.rs, probe-rs/src/probe/stlink/mod.rs, probe-rs/src/session.rs
=> Minor typos and fixes

probe-rs/src/flashing/flasher.rs
#3071 but without the hack. There's just no reason to init/uninit the flash loader when it is otherwise not used.
=> Skip flash loader when reading flash through memory interface

changelog/fixed-debugger-reflash.md, probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/debugger.rs
=> DAP: Allow reflashing other archs

changelog/fixed-deserialize-debugprobeselector.md, probe-rs/src/probe.rs
link https://github.com/probe-rs/probe-rs/issues/3201
=> fix: impl Deserialize for DebugProbeSelector

probe-rs/src/architecture/xtensa/communication_interface.rs
For some reason `fast_halted_access` in conjunction with reading from flash ends up reading garbage in the first word or so. This causes the debugger to display the RTT window with an incorrect name. This PR works around this issue.
=> Use normal halted_access for slow memory accesses

changelog/added-debugger-commands.md, probe-rs-tools/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/repl_commands.rs
=> Implement `info reg` debugger command

probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/mod.rs, probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/rttui/app.rs, probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/rttui/channel.rs, probe-rs-tools/src/bin/probe-rs/cmd/dap_server/mod.rs, probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/debug_rtt.rs, probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/debugger.rs, probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/session_data.rs, probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/startup.rs, probe-rs-tools/src/bin/probe-rs/cmd/debug.rs, probe-rs-tools/src/bin/probe-rs/cmd/erase.rs, probe-rs-tools/src/bin/probe-rs/cmd/info.rs, probe-rs-tools/src/bin/probe-rs/cmd/verify.rs, probe-rs-tools/src/bin/probe-rs/main.rs, probe-rs-tools/src/bin/probe-rs/rpc/client.rs, probe-rs-tools/src/bin/probe-rs/util/cli.rs, probe-rs-tools/src/bin/probe-rs/util/rtt/processing.rs
As part of https://github.com/probe-rs/probe-rs/pull/3249#discussion_r2058666284, I've started recoloring quite a few functions to eventually make asynchronous reactions to events possible.
As this is quite a change I'd rather run this at least by CI (if not by review) separately.
=> Asynchronifications

probe-rs-tools/src/bin/probe-rs/util/cli.rs
Fixes a regression caused by https://github.com/probe-rs/probe-rs/pull/3254
=> Add missing awaits

probe-rs/src/probe/jlink/speed.rs
Test case comes from the protocol PDF:
=> Test that we parse CMD_GET_SPEEDS correctly

changelog/added-stm-otp.md, changelog/fixed-stm.md, probe-rs/targets/STM32F2_Series.yaml, probe-rs/targets/STM32F4_Series.yaml, probe-rs/targets/STM32F7_Series.yaml, probe-rs/targets/STM32H5_Series.yaml, probe-rs/targets/STM32H7_Series.yaml, probe-rs/targets/STM32L1_Series.yaml, probe-rs/targets/STM32L4_Series.yaml, probe-rs/targets/STM32U0_Series.yaml, probe-rs/targets/STM32U5_Series.yaml, probe-rs/targets/STM32WBA_Series.yaml
Updated https://github.com/bugadani/stm-probers and ran it with the newest embassy data
=> Update STM32 data

changelog/fixed-breakpoints.md, changelog/fixed-xtensa-step-crash.md, probe-rs-debug/src/debug_step.rs, probe-rs/src/architecture/xtensa/communication_interface.rs, probe-rs/src/architecture/xtensa/mod.rs, probe-rs/src/core.rs, smoke-tester/src/tests.rs
=> Fix a bunch of breakpoint-related issues

probe-rs-tools/src/bin/probe-rs/cmd/serve.rs
- Default settings are now set to the expected value
- `handle_socket`'s Future is no longer required to be `Send`
=> Server fixes

probe-rs-debug/src/function_die.rs, probe-rs-tools/src/bin/probe-rs/cmd/benchmark.rs, probe-rs-tools/src/bin/probe-rs/cmd/dap_server/peripherals/svd_cache.rs, probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/debug_rtt.rs, probe-rs/src/probe/stlink/usb_interface.rs, rust-toolchain.toml
This version of rustc updated to LLVM 20, which gives a decent compile wall-time improvement
=> Update to rust 1.87.0

changelog/fixed-rtt-channel-modes.md, probe-rs-tools/src/bin/probe-rs/util/rtt/client.rs, probe-rs/src/rtt/channel.rs
=> Fix configuring RTT channel mode

probe-rs-debug/src/exception_handling/riscv.rs, probe-rs-debug/src/exception_handling/xtensa.rs
No behavioural changes intended, just extracting the register unwind code of Xtensa/RV
=> Tweak register unwinding a bit

.github/workflows/release_crates.yml, .github/workflows/start-release.yml, Cargo.lock, dist-workspace.toml, xtask/Cargo.toml, xtask/src/main.rs
- **Fix missing quote in release script.**
- **Include PR number and user in changelog even if the commit has been cherry-picked.**
- **Allow doing `xtask release` from point release branches.**
=> Release script fixes.

changelog/added-debug-reset.md, changelog/added-step.md, probe-rs-tools/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/repl_commands.rs, probe-rs-tools/src/bin/probe-rs/cmd/dap_server/server/core_data.rs, probe-rs/src/core.rs, probe-rs/src/error.rs, probe-rs/src/lib.rs
Chipping away at the tech debt at https://github.com/probe-rs/probe-rs/pull/3190
=> Add back the reset command to debugger REPL, add step
